### ISSUE TITLE
v46 doesn't match vulkan.h v46: duplicates some KHR enums with KHX's that are not in vulkan.h

### ISSUE THREAD

**Issue by msc-** [KhronosGroup/Vulkan-Hpp#100]
`VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHX, VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2_KHX
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHX`

do not exist in v46 vulkan.h. They are already KHR. Therefore compiles fail. Changing lines such as

```
ePhysicalDeviceProperties2KHX = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHX,
```
to
```
ePhysicalDeviceProperties2KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHR,
```
causes a different compile failure because `ePhysicalDeviceProperties2KHR` was already defined earlier in vulkan.hpp.

I had a similar problem last time I copied the "latest" vulkan.hpp from https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/vulkan/vulkan.hpp. See issue #85. I think you have a process problem that needs fixing.

Here is a diff from the downloaded file to the fixed file
```
mark:~/Projects/github/KTX (vkloadtests) $ diff ~/Downloads/vulkan.hpp ~/Molten*16.3/MoltenVK/include/vulkan/vulkan.hpp
6140,6142d6139
<     ePhysicalDeviceProperties2KHX = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHX,
<     eImageFormatProperties2KHX = VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2_KHX,
<     ePhysicalDeviceImageFormatInfo2KHX = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHX,
28601,28603d28597
<     case StructureType::ePhysicalDeviceProperties2KHX: return "PhysicalDeviceProperties2KHX";
<     case StructureType::eImageFormatProperties2KHX: return "ImageFormatProperties2KHX";
<     case StructureType::ePhysicalDeviceImageFormatInfo2KHX: return "PhysicalDeviceImageFormatInfo2KHX";
```

**Comment by asuessenbach** [comment]
The enums you're missing are part of the version-46 vulkan.h. You can find them on lines 264 to 266.
That is, the "latest" vulkan.hpp does match the v46 vulkan.h.

**Comment by msc-** [comment]
Hmmmm? The vulkan.h I am using has `#define VK_HEADER_VERSION 46` but is missing those 3 lines. I just downloaded v46 from Vulkan-Docs and ran a diff.

```
mark:~/Projects/github/KTX (vkloadtests) $ diff ~/Downloads/vulkan.h ~/Molten*16.3/MoltenVK/include/vulkan/vulkan.h
264,266d263
<     VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHX = 1000071005,
<     VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2_KHX = 1000071006,
<     VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHX = 1000071007,
```

I'll have to talk to the MoltenVK folks to find out why.
