### ISSUE TITLE
VkGeometryInstacneFlagsKHR expected in vk::AccelerationStructureInstanceKHR

### ISSUE THREAD

**Issue by XeptionE** [KhronosGroup/Vulkan-Hpp#1002]
How to reproduce:

```
vk::AccelerationStructureInstanceKHR accelerationStructureInstanceKHR;
accelerationStructureInstanceKHR.flags = vk::GeometryInstanceFlagBitsKHR::eForceOpaque;
```

This does not work, because `accelerationStructureInstanceKHR.flags` wants the C-style `VkGeometryInstanceFlagsKHR` int-value.

I am expecting the c++ style from vulkan.hpp.

**Comment by asuessenbach** [comment]
Totally agree.
Unfortunately, that `flags` member in `vk::AccelerationStructureInstanceKHR` is a bit field. And the type of a bit field can only be integral or enumeration type.
But our implementation of `flags` is a `class Flags<BitType>`, which does not fit to a bit field.
You still can use the function `vk::AccelerationStructureInstanceKHR::setFlags()`.

**Comment by XeptionE** [comment]
Ah, thx :) I did it with:

`accelerationStructureInstanceKHR.flags = vk::GeometryInstanceFlagsKHR::MaskType(geometryInstanceFlags);`
