### ISSUE TITLE
VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT not used everywhere?

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/Vulkan-Hpp#1029]
ObjectDestroy, ObjectFree, ObjectRelease, PoolFree manually default their dispatch argument. Would it be possible to make these use VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT? I'd like to use VULKAN_HPP_NO_DEFAULT_DISPATCHER, but these objects would then still take the default

**Comment by asuessenbach** [comment]
Thanks for spotting this inconsistency!
Will be fixed soon.
