### ISSUE TITLE
SamplerCreateInfo constructor sets possibly invalid default values

### ISSUE THREAD

**Issue by msc-** [KhronosGroup/Vulkan-Hpp#104]
The SamplerCreateInfo constructor sets anisotropyEnabled to false and sets maxAnistropy to 0. 1.0 seems a more reasonable value based on language in the Vulkan spec. that the value must be 1.0 when samplerAnisotropy is not enabled on the device.

The spec. is not clear on valid usage when samplerAnisotropy enabled but anisotropyEnabled is false. See https://github.com/KhronosGroup/Vulkan-Docs/issues/503.

**Comment by asuessenbach** [comment]
The Vulkan-Hpp generator uses just the file vk.xml to generate vulkan.hpp. And unforturnately, there's no wording on defaults in that file. Therefore, we just use 0 or 0-equivalents as defaults, to just have something. No matter how valid the combination of those values might be.
If we could get some source for defaults, we'd be happy to use them for vulkan.hpp.

**Comment by msc-** [comment]
A new [validusage.json](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/validation/validusage.json) file has just been added to the Vulkan registry. At present this just contains VUIDs and corresponding text for the valid usage statements. Perhaps it could be extended to include information about valid default values.

**Comment by mtavenrath** [comment]
There has been some discussion about valid default values in the past and it turns out to be best to have a factory utility library outside of Vulkan-Hpp.
