### ISSUE TITLE
Is there a reason the clang-tidy isn't run before uploading?

### ISSUE THREAD

**Issue by ezzieyguywuf** [KhronosGroup/Vulkan-Hpp#1042]
I'm curious since it seems that these are already auto-generated, it seems like it shouldn't be too challenging to add a clang-tidy step to the generation code prior to uploading to github

**Comment by asuessenbach** [comment]
What would you like to achieve with running clang-tidy on the generated headers?

**Comment by ezzieyguywuf** [comment]
🤦‍♂️ i totally meant clang-format

**Comment by asuessenbach** [comment]
Actually, the generated code _is_ formatted using clang-format... as long as clang-format is available on your machine.

**Comment by ezzieyguywuf** [comment]
When I clone the repo, there are hpp headers readily available for me to use - they've already been generated. This is the code I'm referring to

**Comment by asuessenbach** [comment]
Ok... and you want them to be formatted using clang-format?

**Comment by ezzieyguywuf** [comment]
Correct. Or at least, I'm wondering if it is feasible to do so. I'm happy to contribute a patch if you can point me in the right direction.

**Comment by asuessenbach** [comment]
Well, as said above: they _are_ formatted that way.
It's just that the formatting is not part of the CI process, but done by the generator.
