### ISSUE TITLE
Dangling pointer bug from temporary dispatch objects in debug builds

### ISSUE THREAD

**Issue by Daskie** [KhronosGroup/Vulkan-Hpp#1065]
Many functions take a dispatcher and then store it in one way or another, usually in a deleter. An example is `Device::allocateCommandBuffersUnique`, which happens to have been where I discovered this bug.

When the user does not provide their own dispatcher, a ***temporary*** `DispatchLoaderStatic` is passed in...
```c++
allocateCommandBuffersUnique( const CommandBufferAllocateInfo & allocateInfo, Dispatch const & d VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT )
```
...where `VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT` evaluates to `= ::vk::DispatchLoaderStatic()`.

Then a pointer to that temporary dispatcher is stored in a deleter like `ObjectRelease` or `PoolFree`. 
```c++
PoolFree<Device, CommandPool, Dispatch> deleter( *this, allocateInfo.commandPool, d ); // PoolFree stores a pointer to `d`
```

I imagine in many cases this goes unnoticed, as `DispatchLoaderStatic` has no state, and thus nothing to incorrectly dereference. ***Unless*** it's a debug build, in which case its parent `DispatchLoaderBase` has the `vkHeaderVersion` field.

Then later down the line, this `vkHeaderVersion` attempts to be dereferenced in these asserts:
```c++
VULKAN_HPP_ASSERT( d.getVkHeaderVersion() == VK_HEADER_VERSION );
```
But now that memory has been overwritten by something else (randomly and unpredictably, of course) and the assertion fails.

**Comment by asuessenbach** [comment]
You're absolutely right, that's a serious bug.
A fix will be available very soon!

**Comment by asuessenbach** [comment]
A fix is pending...
If you need to keep your current vulkan.hpp version, you can replace

`#    define VULKAN_HPP_DEFAULT_DISPATCHER ::VULKAN_HPP_NAMESPACE::DispatchLoaderStatic()
`

 in your local vulkan.hpp by
```
  static ::VULKAN_HPP_NAMESPACE::DispatchLoaderStatic & getDispatchLoaderStatic()
  {
    static ::VULKAN_HPP_NAMESPACE::DispatchLoaderStatic dls;
    return dls;
  }
#    define VULKAN_HPP_DEFAULT_DISPATCHER ::VULKAN_HPP_NAMESPACE::getDispatchLoaderStatic()

```
