### ISSUE TITLE
Make vulkan.hpp compatible with newer versions of vulkan.h

### ISSUE THREAD

**Issue by RippeR37** [KhronosGroup/Vulkan-Hpp#108]
Currently in code, there is static assert to check if vulkan's header file is same version as the one generator is currently configured to. This makes it impossible to use `vulkan.hpp` from `1.0.x._` with `vulkan.h` from `1.0.y._` where `x < y` (e.g. can't use `vulkan.hpp` from 1.0.46.0 with `vulkan.h` of 1.0.50.0).

Since Vulkan's API shouldn't change that much between patch-versions, maybe it would be enough to check for major and minor versions only (and maybe warn if patch version isn't the same)?

I get that having exact same version is best, but I think that if API doesn't change, there shouldn't be a reason for generated earlier headers to not work with newer Vulkan headers.

The problem I see is that when someone want to use Vulkan-Hpp in his project, he should supply both `vulkan.h` (and other Vulkan headers) and `vulkan.hpp` for them to match, since some OSes might have older packages installed which might conflict with Vulkan-Hpp version (and using user-installed might not be best, as I'm not sure if API of Vulkan-Hpp is 100% stable and backward compatibility is maintained all the time).

It's not best, but maybe worth considering? What's your opinion?

**Comment by ioquatix** [comment]
Bad idea. Just bundle `vulkan.h` and `vulkan.hpp` together. If you want to update, update them in lockstep.

**Comment by mtavenrath** [comment]
I agree with @ioquatix. While your use case should work fine in nearly all cases there might be a case where strange things happen, i.e. due to a bug in the spec and in those cases compilation will fail with error messages not explainable to some people.
