### ISSUE TITLE
ARM/X86 Compilation failure when using 32bits ArrayWrapper1D

### ISSUE THREAD

**Issue by CronnoLord** [KhronosGroup/Vulkan-Hpp#1084]
Compiler throws an error `error: use of overloaded operator '[]' is ambiguous (with operand types 'ArrayWrapper1D<float, 4>' and 'int')`
I think wrapper is missing `|| defined(__arm__) || defined(_M_ARM) || defined(__386__) || defined(___M_IX86__) || __LP32__` depending on the compiler used, when defining `operator[]` for this class

**Comment by asuessenbach** [comment]
Thanks for pointing this out!
I decided to base the decision here on VK_USE_64_BIT_PTR_DEFINES, instead.
Please re-open this issue, if it does not fit your needs.
