### ISSUE TITLE
RAII suggestion

### ISSUE THREAD

**Issue by tom-huntington** [KhronosGroup/Vulkan-Hpp#1085]
> VULKAN_HPP_RAII_ENABLE_DEFAULT_CONSTRUCTORS
>
>By default, the vk::raii wrapper classes don't support default constructors. It would be a contradiction to the raii-principle. For those who are desparate enough to ignore that restriction, you can define VULKAN_HPP_RAII_ENABLE_DEFAULT_CONSTRUCTORS. The only thing you can do with a default contructed vk::raii wrapper object is move-assigning another vk::raii wrapper object onto it. And you have to make sure that that happens before you use it.

In cppwinrt, you have constructors that take a `std::nullptr_t` to defer the construction of projection types.

Even when you have a default constructable type, you still may want to defer its construction.

With out delayed construction, the raii types are unusable as class fields, but  `VULKAN_HPP_RAII_ENABLE_DEFAULT_CONSTRUCTORS` is clearly the wrong solution.

Please add constructors that take a `std::nullptr_t` or `VK_NULL_HANDLE`.

**Comment by tom-huntington** [comment]
Also, I think it would have been good to have private constructors that used by factory methods. i.e. instead of
```
vk::raii::Fence drawFence( device, vk::FenceCreateInfo() );
```
have
```
auto drawFence = device.createFence( vk::FenceCreateInfo() );
```
So you can use auto complete for the member names, and don't have to remember exact spelling of the type names.

It would be more oop idiomatic and thus raii

**Comment by asuessenbach** [comment]
Regarding the contructors taking std::nullptr_t or VK_NULL_HANDLE:
As far as I know, the projected types in cppwinrt essentially are smart pointers to some backing object.
With vulkan, you don't have such functionality built-in, but you can use the RAII-wrappers in smart pointers like std::unique_ptr or std::shared_ptr. Then, you don't need such a constructor, or even the default constructor.

**Comment by tom-huntington** [comment]
Yes, I suppose the double indirection doesn't matter for my purposes. I found I can just do everything in the initializer list anyway.

Sorry for being demanding.

Thanks for the library!

**Comment by asuessenbach** [comment]
Thanks a lot for your input! It helped me making Vulkan-Hpp RAII better.
