### ISSUE TITLE
create*Unique functions allocate DispatchLoaderStatic on the stack, ObjectDestroy keeps referencing it after it goes out of scope

### ISSUE THREAD

**Issue by starcatter** [KhronosGroup/Vulkan-Hpp#1086]
As far as I can tell, the `VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT` define that's tacked onto create*Unique functions translates to `= vk::DispatchLoaderStatic()`, which allocates the loader on the stack. Later on the deleter `vk::ObjectDestroy` is created, which points to this dispatch loader. Most of the unique handle survives being moved around and being placed inside STL containers, but the dispatch loader is lost inside its original creation scope.

This causes header version assertions ( like `VULKAN_HPP_ASSERT( d.getVkHeaderVersion() == VK_HEADER_VERSION );`) to fail when building/running in debug mode. I'm guessing there might be worse consequences to this as well.

The workaround is to pass your own dispatch loader to each crate*Unique function, making sure it outlives the UniqueHandle.

Example:
```
#include <vulkan/vulkan.hpp>

vk::UniqueInstance getInstance() {
    vk::ApplicationInfo appInfo("App", 1, "VKR", 1, VK_API_VERSION_1_1);
    return vk::createInstanceUnique( {vk::InstanceCreateFlags(), &appInfo, 0, nullptr, 0, nullptr} );
}

void dont_touch(){
    auto instance = getInstance();
}

void stay_in_scope(){
    vk::ApplicationInfo appInfo("App", 1, "VKR", 1, VK_API_VERSION_1_1);
    auto instance =  vk::createInstanceUnique( {vk::InstanceCreateFlags(), &appInfo, 0, nullptr, 0, nullptr} );
    std::array<char, 256> arr{};
    arr.fill(0);
}

void overwrite_old_stack(){
    auto instance = getInstance();
    std::array<char, 256> arr{};
    arr.fill(0);
}

int main() {
    dont_touch(); // ok?
    stay_in_scope(); // most likely ok
    overwrite_old_stack(); // will fail in debug build
    return 0;
}
```
This consistently fails for me (on linux). I see VK_HEADER_VERSION = 191 in the sources, not sure what specific revision I'm on, file dates show 08.09.2021.

**Comment by asuessenbach** [comment]
This has already been fixed by #1066, right after the VK_HEADER_VERSION 191.
