### ISSUE TITLE
Buffer Destruction

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-Hpp#1098]
Hi, when using vk::raii::buffer and memory, I moved them into a struct for better organization. When I close my program, I get a validation message that buffer and memory has not been destroyed.
I thought the whole idea was that I could not miss the the destruction of raii object. 
I even put them in smart pointer.
Any help is appreciated.

    struct AllocatedBufferMemory
    {
        std::unique_ptr<vk::raii::Buffer>       buffer;
        std::unique_ptr<vk::raii::DeviceMemory> bufferMemory;
        vk::MemoryRequirements                  bufferMemoryRequirement;
    };

Validation message.
/**************/
    Objects: 1
        [0] 0xab64de0000000020, type: 9, name: NULL
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x1019ed1cb58, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xb991fa0000000024, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x1019ed1cb58[], VkBuffer 0xb991fa0000000024[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x1019ed1cb58, type: 3, name: NULL
        [1] 0xb991fa0000000024, type: 9, name: NULL
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x1019ed1cb58, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xab64de0000000020, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x1019ed1cb58[], VkBuffer 0xab64de0000000020[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x1019ed1cb58, type: 3, name: NULL
        [1] 0x908683000000001d, type: 8, name: NULL
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x1019ed1cb58, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xb097c90000000027, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x1019ed1cb58[], VkDeviceMemory 0xb097c90000000027[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x1019ed1cb58, type: 3, name: NULL
        [1] 0xb097c90000000027, type: 8, name: NULL
/************/

code to create buffer

    AllocatedBufferMemory MemoryAlloc::createBufferObject( const vk::DeviceSize& size, 
                                                        const vk::BufferUsageFlags& bufferUsage, 
                                                        const vk::MemoryPropertyFlags& memoryPropertyFlags, 
                                                        const vk::SharingMode& sharingMode )
    {

        AllocatedBufferMemory temp;

        vk::BufferCreateInfo bufferInfo{};
            bufferInfo.size           = size,
            bufferInfo.usage          = bufferUsage,
            bufferInfo.sharingMode    = sharingMode;

        temp.buffer =  std::make_unique<vk::raii::Buffer>( *pDevice.logicalDevice, bufferInfo );

        temp.bufferMemoryRequirement = temp.buffer->getMemoryRequirements();

        vk::MemoryAllocateInfo memoryAllocateInfo{};
            memoryAllocateInfo.allocationSize     = temp.bufferMemoryRequirement.size,
            memoryAllocateInfo.memoryTypeIndex    = determineMemoryTypeIndex( temp.bufferMemoryRequirement.memoryTypeBits, memoryPropertyFlags );
    
        temp.bufferMemory = std::make_unique<vk::raii::DeviceMemory>( *pDevice.logicalDevice, memoryAllocateInfo );

        temp.buffer->bindMemory( **temp.bufferMemory, 0 );

        return std::move( temp );

**Comment by asuessenbach** [comment]
>I thought the whole idea was that I could not miss the the destruction of raii object.

That's correct.
But the order of destruction is still important. There's no built-in automatism in the raii-objects that postpones the destruction of a device 'till all handles generated from it are destroyed. There is nothing like a `std::shared_ptr<vk::raii::Device>` as a member of `vk::raii::Buffer`.
That is, I would verify that the device is destroyed _after_ all the `AllocatedBufferMemory`s you might have created.
