### ISSUE TITLE
vk::AccelerationStructureInstanceKHR uses C enum for field "flags"

### ISSUE THREAD

**Issue by rebelroad-reinhart** [KhronosGroup/Vulkan-Hpp#1122]
Example:
![struct_field](https://user-images.githubusercontent.com/89154706/140090335-ddfca38a-b9af-4876-9f1b-9600b4da4325.png)

Expected:
members of vk::GeometryInstanceFlagBitsKHR should be assignable to flags.

**Comment by asuessenbach** [comment]
Totally agree.
But unfortunately, this special structure uses bit fields for its members, which prevents using vk::Flags.
