### ISSUE TITLE
More constexpr/literal types?

### ISSUE THREAD

**Issue by Saalvage** [KhronosGroup/Vulkan-Hpp#1123]
I'm personally a huge fan of `constexpr` and I think this (awesome!) library would quite benefit from turning most data-aggregation structs (such as `ClearDepthStencilValue`) into literal types so that they can be used in conjunction with `constexpr` elsewhere!

**Comment by asuessenbach** [comment]
What structs are you looking for here?
For example the constructors of `ClearDepthStencilValue` are already marked as `VULKAN_HPP_CONSTEXPR`.

**Comment by Saalvage** [comment]
Sorry, I was being really dumb when picking the example.

So I think there are two general cases where `constexpr` can be utilized more (at least that I came across!):
1. Union copy operations. For some reason those are implemented via `memcpy`, which is not valid in a `constexpr`. Either omitting or explicitely defaulting them should result in the same behavior while causing them to be `constexpr` compatible. (I could totally be missing something though.)
2. Basically all setters. This would allow them to be used in other `constexpr` functions. Should be fine to just add the `constexpr` specifier to all of them.

If this sounds reasonable I could try and craft up a PR.

**Comment by asuessenbach** [comment]
@Saalvage: Sounds good! Please go and craft up a PR.
I'm always happy to get the Vulkan-Hpp improved.
