### ISSUE TITLE
Unable to set vk::raii::Context dispatcher

### ISSUE THREAD

**Issue by beeryt** [KhronosGroup/Vulkan-Hpp#1134]
The `vk::raii::Context` class does not provide a constructor/method for specifying a `PFN_vkGetInstanceProcAddr`. Is this intentional? How does one go about specifying the `PFN_vkGetInstanceProcAddr` using RAII?

I would expect a constructor such as `Context(vk::raii::ContextDispatcher)` which would allow the following:

```lang-cpp
PFN_vkGetInstanceProcAddr getProcAddr = glfwGetInstanceProcAddr;
vk::raii::ContextDispatcher dispatcher{ getProcAddr };
vk::raii::Context context{ dispatcher };
auto instance = context.createInstance(/*...*/);
```

Also there is a `vk::raii::Context::getDispatcher`, but no setter?

**Comment by asuessenbach** [comment]
The vk::raii::[Context|Instance|Device]Dispatcher classes intentionally are internal classes to vk::raii::[Context|Instance|Device]. They are created and managed by those classes, therefore, there's just a getter and no setter from them.
We could add a constructor of vk::raii::Context, that gets a PFN_vkGetInstanceProcAddr as an argument.
