### ISSUE TITLE
Issue using DispatchLoaderStatic

### ISSUE THREAD

**Issue by marovira** [KhronosGroup/Vulkan-Hpp#1135]
Hello,

I've noticed the following problem in the usage of the unique handles with the default `vk::DispatchLoaderStatic`. In the declaration of `vk::Device::createCommandPoolUnique`, the `Dispatch` parameter is set to a default value, which expands to `vk::DispatchLoaderStatic()` (if we aren't using the dynamic loader). This means that the default parameter will create a new instance of the dispatcher whose lifetime is bound to that specific function. This is fine, except that when `vk::ObjectDestroy` gets created, it will then proceed to take the address of this object and store it. This is an issue because we're taking the address of a variable in the stack that will be destroyed when we exit the function. During program execution nothing happens, but once we start destroying the handles (in this example the `vk::UniqueCommandPool` handle), there will be an assert triggered because the header value held by the dispatcher of that handle is pointing at garbage values, and is therefore invalid.

Is this behaviour known? Is there something else that I should be doing?

Thanks for the help and awesome work on the wrapper!

**Comment by asuessenbach** [comment]
This is a known issue and it's been resolved with #1066.
That is, with VK_HEADER_VERSION 192 and above, you should not have that issue any more.

**Comment by marovira** [comment]
Thanks for the quick reply. I will update my version to 192. Cheers!
