### ISSUE TITLE
UB in vk::DebugUtilsMessengerCreateInfoEXT (and elsewhere)

### ISSUE THREAD

**Issue by jan-moeller** [KhronosGroup/Vulkan-Hpp#1145]
Both of these conversion functions cause undefined behavior by interpreting a pointer as a pointer to an unrelated type, then dereferencing it.:

```c++
operator VkDebugUtilsMessengerCreateInfoEXT const&() const VULKAN_HPP_NOEXCEPT
{
  return *reinterpret_cast<const VkDebugUtilsMessengerCreateInfoEXT*>( this );
}

operator VkDebugUtilsMessengerCreateInfoEXT &() VULKAN_HPP_NOEXCEPT
{
  return *reinterpret_cast<VkDebugUtilsMessengerCreateInfoEXT*>( this );
}
```

This violates the C++ aliasing rules.

This same pattern can be found all over the place (3195 occurrences of reinterpret_cast, and many of them look suspicious).

This is similar to issue #359, except that I don't believe making the type standard layout helps either. A pointer to a standard layout type can be safely interconverted to a pointer to its first member, but not to a completely unrelated type.

My gut feeling is that vk::DebugUtilsMessengerCreateInfoEXT should have a VkDebugUtilsMessengerCreateInfoEXT member, and all the data should be stored in it.

**Comment by asuessenbach** [comment]
It seems your right!
Do you have an actual case where that violation of the C++ aliasing rules is breaking at compilation or runtime?
Besides that: "simply" replacing the members of a vk::Struct by a VkStruct would not work, as accessing the member variables would fail then.
I could imagine to introduce some configuration define like VULKAN_HPP_STRICT_ALIASING that, when it's defined, would make the vk::Struct derive privately or protected from VkStruct. All member access would then needed to be done by getter and setter functions. That version would obey that aliasing rules. If it's not defined (the default!), everything would be as it is today, the aliasing rules are violated, but all (?) compilers would get you correct code.
Do you have  another idea how that issue could be resolved? Best without breaking exisiting code?

**Comment by jan-moeller** [comment]
I am not a compiler writer, but I'm pretty sure that there are cases were aliasing rules are used for optimization. One such example is [this](https://godbolt.org/z/KzWPoxWcv) where the compiler takes advantage of the fact that two parameters of different type can't alias each other, and uses that to optimize a memory read away.

There are other disadvantages of having UB in library code, in particular in headers:

- It is impossible to ever use such code in a constexpr context, since the compiler is required to reject UB at compile time. (As an aside: The C struct can be used in constexpr contexts just fine).
- If compilers implement a warning for this (I didn't check), then its the library user getting it, since this is in a header file. If they use -Werror, then compilation will even fail entirely.
- This is likely going to trip tools like [TySan](https://reviews.llvm.org/D32198).
- Static analysis tools frequently warn about reinterpret_cast.
- Even if compilers don't do some of the above things today, they might very well start doing them in their next release. Compiler updates might therefore be challenging for users of this library.

I see 3 options, each with their advantages and disadvantages. For comparison purposes, lets assume we have a type VkFoo, the wrapper type vk::foo, and 4 functions:
```c++
struct VkFoo;
namespace vk {struct foo;}

void by_value(VkFoo);
void by_ref(VkFoo&);
void by_pointer(VkFoo*);
void use_member(float f); // Wants a member of VkFoo
```
Then, with the current implementation, usage of these 4 functions is as follows ([compiler explorer](https://godbolt.org/z/9hhTz4GPb))
```c++
vk::foo f{};
by_value(f); // UB
by_ref(f);  // UB
by_pointer(&static_cast<VkFoo&>(f)); // UB
use_member(f.f);
```
### First alternative
Have vk::foo inherit VkFoo. Then the 4 functions can be used like this ([compiler explorer](https://godbolt.org/z/7nj8177Y3))
```c++
vk::foo f{};
by_value(f);
by_ref(f);
by_pointer(&f);
use_member(f.f);
```
Additional properties:
* :+1: No UB
* :+1: Usage as pointer is easier
* :+1: Can still directly access members
* :+1: Can still implement useful constructors that make sure the underlying VkFoo is properly initialized.
* :-1: Now there is no access control. After initialization, the user can arbitrarily break the object.

### Second alternative
Have vk::foo hold a VkFoo ([compiler explorer](https://godbolt.org/z/Mqd9xWb3T)).
```c++
vk::foo f{};
by_value(f);
by_ref(f);
by_pointer(&static_cast<VkFoo&>(f));
use_member(f.get_f());
```
Properties:
* :+1: No UB
* :-1: Usage as pointer is difficult.
* :-1: Need to call getter functions instead of members directly.
* :+1: Can still implement useful constructors that make sure the underlying VkFoo is properly initialized.
* :-1: There *appears* to be access control, but really the user can still arbitrarily break the object via the conversion operator.

### Third alternative
Use one of the standard-blessed alternatives for type-punning: std::memcpy or, in C++20, std::bit_cast ([compiler explorer](https://godbolt.org/z/bhETxn614)).
```c++
vk::foo f{};
by_value(f);
VkFoo c_f = f;
by_ref(c_f);
by_pointer(&c_f);
use_member(f.f);
```
Properties:
* :+1: No UB
* :-1: Usage as reference and pointer is difficult
* :+1: Can access members directly
* :+1: Can still implement useful constructors.
* :+1: There is access control.

Note that none of the options (including the status quo) produces dramatically inefficient assembly.

Personally, I would favor the first alternative. Yes, it allows the user to mess with the type member, but so does the status quo. In my mind, the major benefit of the wrappers are the constructors - you get a valid object by default. If the user goes to great lengths to then break it, that really is on them.
That option has the additional benefit that afaict all currently valid code stays valid.

**Comment by asuessenbach** [comment]
@jan-moeller Thanks a lot for your detailed analysis of different approaches to resolve this issue.
Unfortunatelly, none of them seem to work for us.
First alternative: while you have access to the struct members, those members have the type of the C-struct members, not of the C++-struct members. That's ok for standard types like int or float, but not acceptable for enum types and flags, where the improved compile time checking of the corresponding C++-types should be available.
Second alternative: As you already mentioned, accessing the members would require some getter functions. Would require substantial changes to all sources out in the wild.
Third alternative: I think, copying the complete struct on a cast operation is a no-go. Especially with nested structures.

**And as we don't have any better alternative, we simply will stay with the status quo**. If you fear to be affected by the aliasing rules, we'ld like to propose to use the -fno-strict-aliasing flag with gcc.
