### ISSUE TITLE
std::chrono::duration overloads for parameters that refer to a duration

### ISSUE THREAD

**Issue by theHamsta** [KhronosGroup/Vulkan-Hpp#1151]
Many Vulkan functions that start with vkWaitForXXX https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkWaitForFences.html or vkAquireXXX https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkAcquireNextImageKHR.html have a numeric timeout value that refers to a duration in nanoseconds. 

I don't know whether this would be in the scope of the project but it would be nice when we could provide overloads for of type `std::chrono::duration` so that one could write 

```cpp
using namespace std::literals::chrono_literals;
device.waitForFences( { *drawFence }, VK_TRUE, 1s ) )
```

I don't know whether it is possible to recognize such parameters in an automated manner.

Since including `<chrono>` adds additional compile time, this feature could be hidden behind a feature macro.

**Comment by asuessenbach** [comment]
Interesting idea!
But currently, there is no way to automatically detect, that those timeout parameters actually are meant to be nanoseconds. That is, it would need some very special handling for just those functions.
Moreover, it would require to unconditionally include `<chrono>`, and have a `using namespace std::chrono_literals;` in a header.
And, finally, it would require at least C++14.

That is, I don't see anything like that happen.
You would need to handle that on your own, by calling
`device.waitForFences( { *drawFence }, VK_TRUE, std::chrono::duration<uint64_t, std::nano>( 1s ).count() ) );`

Not that elegant, but kind of very Vulkan-like, in its explicitness.

**Comment by theHamsta** [comment]
> Moreover, it would require to unconditionally include <chrono>, and have a using namespace std::chrono_literals; in a header

This is why I suggested to have a feature guard. `using namespace std::literals::chrono_literals;` would of course be in users code
