### ISSUE TITLE
std::hash overloads for CreateInfo types

### ISSUE THREAD

**Issue by thesmallcreeper** [KhronosGroup/Vulkan-Hpp#1154]
From my understanding std::hash overloads are provided only for the handlers.
However there is no overload for CreateInfo types. Do I understand correctly?

If so, is there any work towards that? Would such pull request that add that feature will be acceptable?

Using the library for less than a week so maybe I miss something. Sorry if I missed something :) Thank you.

**Comment by thesmallcreeper** [comment]
@Wunkolo Haven't analyzed the codebase in depth but I think the rules of operator== should be applied, which as far as I know checks shallowly for equality. To give an example (from `vk::PipelineLayoutCreateInfo`):
```    
bool operator==( PipelineLayoutCreateInfo const & rhs ) const VULKAN_HPP_NOEXCEPT
    {
      return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) &&
             ( setLayoutCount == rhs.setLayoutCount ) && ( pSetLayouts == rhs.pSetLayouts ) &&
             ( pushConstantRangeCount == rhs.pushConstantRangeCount ) &&
             ( pPushConstantRanges == rhs.pPushConstantRanges );
    }
```
Indeed checking for actual equality is kinda headache. But I believe this is a discussion for another time, another issue. It is important but I think having a hash that "support" the operator== for a hash map (`std::unordered_map`) will be handy, at least for me it will.

**Comment by asuessenbach** [comment]
I think, I will introduce some define like VULKAN_HPP_HASH_COMBINE(seed, value), similar to boost::hash_combine(). With that, a "shallow" hash of structs can be generated.

**Comment by thesmallcreeper** [comment]
@asuessenbach Thank you in advance. How far you will go with it? Are you going to also add hash function generator for structs? Asking in order to know how to schedule my development :) (haha feeling like I am pressuring you)
I mean I was thinking to get my hands dirty with it today but if I can just seat and wait I will choose the later. :stuck_out_tongue_closed_eyes:

**Comment by asuessenbach** [comment]
> Are you going to also add hash function generator for structs?

Yep, that's my plan. I will skip unions and structures containing unions, for now. And I think it will be done beginning of next week.

**Comment by thesmallcreeper** [comment]
@asuessenbach Thank you, you made my day! :smile: Have a nice day too. :heart:

**Comment by Wunkolo** [comment]
@asuessenbach Thank you!

**Comment by thesmallcreeper** [comment]
@asuessenbach That was fast! Again thank you :)
