### ISSUE TITLE
Better C++ naming conventions.

### ISSUE THREAD

**Issue by ioquatix** [KhronosGroup/Vulkan-Hpp#117]
I don't know if I mentioned this before so I'm sorry if this has already come up, but:

- In C++ functions tend to use underscores between words, e.g. `push_back`. I think we should probably prefer that style of naming or at least make it an option.
- In C++, enumeration values/constants are normally upper case, and the `e` prefix is pretty ugly - it seems like the `e` prefix makes ALL constants ugly for the sake of a handful of those that start with numbers. Why not just do something like use an `_` for enumerations that start with numbers and leave the rest alone?

If it's considered too much trouble to implement these suggestions, perhaps making it at least an option when generating the header, might make sense?

**Comment by mtavenrath** [comment]
> In C++ functions tend to use underscores between words, e.g. push_back. I think we should probably prefer that style of naming or at least make it an option.
To avoid fragmentation it'd be good not introduce a second set of naming conventions in Vulkan-Hpp.

>In C++, enumeration values/constants are normally upper case, and the e prefix is pretty ugly - it seems like the e prefix makes ALL constants ugly for the sake of a handful of those that start with numbers. Why not just do something like use an _ for enumerations that start with numbers and leave the rest alone?
Starting with an _ is not desirable since ^_[A-Z] is reserved and everything starting with _ is reserved in the global namespace in C++. To avoid collisions with the compiler/libraries we decided not to let anything start with _.

We also had the discussion whether to make all enums start with e or just the numbers or even replace 1D with ONE_D. In the end we decided for consistency to avoid as much special cases as possible and add the e everywhere. It's not optimal, but it prevents at least confusions.

**Comment by ioquatix** [comment]
You've addressed one of the issues but not the other.

**Comment by ioquatix** [comment]
Oh, I see, you've quoted your own reply.

**Comment by ioquatix** [comment]
> In C++ functions tend to use underscores between words, e.g. push_back. I think we should probably prefer that style of naming or at least make it an option.

> To avoid fragmentation it'd be good not introduce a second set of naming conventions in Vulkan-Hpp.

I agree, but you've already deviated from the standard C++ conventions. I think this is really just a suggestion that you consider standard C++ function naming conventions.

> In C++, enumeration values/constants are normally upper case, and the e prefix is pretty ugly - it seems like the e prefix makes ALL constants ugly for the sake of a handful of those that start with numbers. Why not just do something like use an _ for enumerations that start with numbers and leave the rest alone?

> Starting with an _ is not desirable since ^_[A-Z] is reserved and everything starting with _ is reserved in the global namespace in C++. To avoid collisions with the compiler/libraries we decided not to let anything start with _.

Ah, yeah, good point. Perhaps there is another option?

**Comment by ioquatix** [comment]
Finally, as I suggested, perhaps just making it optional might be good. We are writing a lot of code using the current version of `vulkan.hpp` but it's naming conventions are a bit grating on existing code conventions. Obviously the value of `vulkan.hpp` outweighs the negatives, but since it's bundled with our code anyway, we wouldn't mind customising it a bit more to suit our entire code base better.
