### ISSUE TITLE
Building using MinGW x64 and Ninja

### ISSUE THREAD

**Issue by hott-henrique** [KhronosGroup/Vulkan-Hpp#1171]
Building the project for Windows using MSYS2 CMake (mingw-w64-x86_64-cmake) and Ninja (mingw-w64-x86_64-ninja), gives me this error:
ninja: error: 'glslang/OGLCompilersDLL/libOGLCompiler.a', needed by 'samples/utils/libutils.a', missing and no known rule to make it

Complete log:
$ cmake -G Ninja -D DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON -DSAMPLES_BUILD=ON -DTESTS_BUILD_WITH_LOCAL_VULKAN_HPP=ON -DTESTS_BUILD=ON -DVULKAN_HPP_RUN_GENERATOR=0N -B build
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:56 (message):
   Could not find clang-format. Generated vulkan.hpp and vulkan_raii.hpp will not be nicely formatted.

CMAKE_CXX_STANDARD = <11>
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Looking for dinput.h
-- Looking for dinput.h - found
-- Looking for xinput.h
-- Looking for xinput.h - found
-- Performing Test _GLFW_HAS_DEP
-- Performing Test _GLFW_HAS_DEP - Success
-- Performing Test _GLFW_HAS_ASLR
-- Performing Test _GLFW_HAS_ASLR - Success
-- Performing Test _GLFW_HAS_64ASLR
-- Performing Test _GLFW_HAS_64ASLR - Success
-- Using Win32 for window creation
-- No build type selected, default to Debug
-- Found PythonInterp: C:/msys64/mingw64/bin/python3.exe (found suitable version "3.9.7", minimum required is "3")
-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
-- Found Vulkan: C:/VulkanSDK/1.2.198.1/Lib/vulkan-1.lib
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP

-- Build files have been written to: C:/Users/Henrique/Documents/Vulkan-Hpp/build

$ ninja
ninja: error: 'glslang/OGLCompilersDLL/libOGLCompiler.a', needed by 'samples/utils/libutils.a', missing and no known rule to make it

**Comment by asuessenbach** [comment]
It seems, the OGLCompiler from glslang hasn't been built.
Did you clone the repository with `--recurse-submodules` to get all the submodules (including glslang)?

**Comment by hott-henrique** [comment]
> It seems, the OGLCompiler from glslang hasn't been built. Did you clone the repository with `--recurse-submodules` to get all the submodules (including glslang)?

Yes i did.

**Comment by asuessenbach** [comment]
That is, you do have that libOGLCompiler.a in glslang\OGLCompilersDLL\Debug, and it's "just" that ninja does not find it?

**Comment by hott-henrique** [comment]
Checking now, I didn't find the folder ...\OGLCompilersDLL\Debug in my directory, just after using the git clone command.

**Comment by asuessenbach** [comment]
That library is not there after cloning, but it should get build when you first build a sample in your Vulkan-Hpp folder.

One thing I just realized is wrong in our Readme: instead of 
`-D DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON`
you should use
`-DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON`

**Comment by asuessenbach** [comment]
@hott-henrique: Has this beed resolved, somehow

**Comment by ylz-at** [comment]
I tried to use ninja by changing the workflow and it fails, https://github.com/KhronosGroup/Vulkan-Hpp/runs/6997902108?check_suite_focus=true .

And I can reproduce this on my own ubuntu 20.04(VM).

1. checkout master
2. sudo apt update && sudo apt install libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev ninja-build
3. git submodule update --init --recursive
4. cmake
```cmake -B build -GNinja
-DSAMPLES_BUILD=ON
-DSAMPLES_BUILD_ONLY_DYNAMIC=ON
-DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON
-DTESTS_BUILD=ON
-DTESTS_BUILD_ONLY_DYNAMIC=ON
-DTESTS_BUILD_WITH_LOCAL_VULKAN_HPP=ON
-DVULKAN_HPP_RUN_GENERATOR=ON
-DCMAKE_CXX_COMPILER=clang++-10
-DCMAKE_C_COMPILER=clang-10
-DCMAKE_CXX_STANDARD=11
```
5. cmake --build build --config Release

**Comment by ylz-at** [comment]
@asuessenbach `cat vulkan_structs.hpp | grep PhysicalDeviceProvokingVertexPropertiesEXT` outputs,

```
  struct PhysicalDeviceProvokingVertexPropertiesEXT
    using NativeType = VkPhysicalDeviceProvokingVertexPropertiesEXT;
    static VULKAN_HPP_CONST_OR_CONSTEXPR StructureType structureType = StructureType::ePhysicalDeviceProvokingVertexPropertiesEXT;
    VULKAN_HPP_CONSTEXPR PhysicalDeviceProvokingVertexPropertiesEXT(VULKAN_HPP_NAMESPACE::Bool32 provokingVertexModePerPipeline_ = {}, VULKAN_HPP_NAMESPACE::Bool32 transformFeedbackPreservesTriangleFanProvokingVertex_ = {}, void * pNext_ = nullptr) VULKAN_HPP_NOEXCEPT
    VULKAN_HPP_CONSTEXPR PhysicalDeviceProvokingVertexPropertiesEXT( PhysicalDeviceProvokingVertexPropertiesEXT const & rhs ) VULKAN_HPP_NOEXCEPT = default;
    PhysicalDeviceProvokingVertexPropertiesEXT( VkPhysicalDeviceProvokingVertexPropertiesEXT const & rhs ) VULKAN_HPP_NOEXCEPT
      : PhysicalDeviceProvokingVertexPropertiesEXT( *reinterpret_cast<PhysicalDeviceProvokingVertexPropertiesEXT const *>( &rhs ) )
    PhysicalDeviceProvokingVertexPropertiesEXT & operator=( PhysicalDeviceProvokingVertexPropertiesEXT const & rhs ) VULKAN_HPP_NOEXCEPT = default;
    PhysicalDeviceProvokingVertexPropertiesEXT & operator=( VkPhysicalDeviceProvokingVertexPropertiesEXT const & rhs ) VULKAN_HPP_NOEXCEPT
      *this = *reinterpret_cast<VULKAN_HPP_NAMESPACE::PhysicalDeviceProvokingVertexPropertiesEXT const *>( &rhs );
    explicit operator VkPhysicalDeviceProvokingVertexPropertiesEXT const &() const VULKAN_HPP_NOEXCEPT
      return *reinterpret_cast<const VkPhysicalDeviceProvokingVertexPropertiesEXT*>( this );
    explicit operator VkPhysicalDeviceProvokingVertexPropertiesEXT &() VULKAN_HPP_NOEXCEPT
      return *reinterpret_cast<VkPhysicalDeviceProvokingVertexPropertiesEXT*>( this );
auto operator<=>( PhysicalDeviceProvokingVertexPropertiesEXT const & ) const = default;
    bool operator==( PhysicalDeviceProvokingVertexPropertiesEXT const & rhs ) const VULKAN_HPP_NOEXCEPT
    bool operator!=( PhysicalDeviceProvokingVertexPropertiesEXT const & rhs ) const VULKAN_HPP_NOEXCEPT
    VULKAN_HPP_NAMESPACE::StructureType sType = StructureType::ePhysicalDeviceProvokingVertexPropertiesEXT;
  VULKAN_HPP_STATIC_ASSERT( sizeof( VULKAN_HPP_NAMESPACE::PhysicalDeviceProvokingVertexPropertiesEXT ) == sizeof( VkPhysicalDeviceProvokingVertexPropertiesEXT ), "struct and wrapper have different size!" );
  VULKAN_HPP_STATIC_ASSERT( std::is_standard_layout<VULKAN_HPP_NAMESPACE::PhysicalDeviceProvokingVertexPropertiesEXT>::value, "struct wrapper is not a standard layout!" );
  VULKAN_HPP_STATIC_ASSERT( std::is_nothrow_move_constructible<VULKAN_HPP_NAMESPACE::PhysicalDeviceProvokingVertexPropertiesEXT>::value, "PhysicalDeviceProvokingVertexPropertiesEXT is not nothrow_move_constructible!" );
  struct CppType<StructureType, StructureType::ePhysicalDeviceProvokingVertexPropertiesEXT>
    using Type = PhysicalDeviceProvokingVertexPropertiesEXT;
```

**Comment by asuessenbach** [comment]
@ylz-at And... just to make sure... when you don't use that `-GNinja`, everything compiles fine?

**Comment by ylz-at** [comment]
@asuessenbach yes, everything is normal if I don't use ninja...I tried multiple times today.
This might be some ninja thing, I have no idea.

There are some formating errors but at least it compiles fine,
```
VulkanHppGenerator: failed to format file /home/falco/clion/Vulkan-Hpp/vulkan/vulkan_hash.hpp with error <256>
VulkanHppGenerator: Generating /home/falco/clion/Vulkan-Hpp/vulkan/vulkan_raii.hpp ...
VulkanHppGenerator: Formatting /home/falco/clion/Vulkan-Hpp/vulkan/vulkan_raii.hpp ...
YAML:4:31: error: invalid boolean
AlignConsecutiveAssignments : Consecutive
                              ^~~~~~~~~~~
Error reading /home/falco/clion/Vulkan-Hpp/.clang-format: Invalid argument
VulkanHppGenerator: failed to format file
```

**Comment by theHamsta** [comment]
@ylz-at can you try to rebase?  `'samples/utils/libutils.a'` shouldn't be built anymore with the recent MacOS CI change and just be an interface target.

**Comment by ylz-at** [comment]
Fixed this issue by adding `add_dependencies(utils build_vulkan_hpp)` and getting rid of `FILE (GLOB ...)`
But some targets didn't link to utils, which might still lead to racing in the parallel build.
