### ISSUE TITLE
Enhanced mode support for results requiring pNext

### ISSUE THREAD

**Issue by mliebenow** [KhronosGroup/Vulkan-Hpp#118]
Using the enhanced mode version of calls like PhyicalDevice::getImageFormatProperties2KHR currently is not possible when using extensions that require extending the return type using pNext.  I'm guessing that the enhanced mode wrapper is creating an intermediate return value and not properly setting pNext on the intermediate.

**Comment by asuessenbach** [comment]
Thanks for pointing to that issue!
We'll work out a solution for that .

**Comment by mtavenrath** [comment]
@mliebenow We implemented support for structure pointer chains in PR #119. Does this fit your needs?

**Comment by mtavenrath** [comment]
PR #119 has been committed. It's possible to create structure (pointer) chains now with the vk::StructureChain class and passing the desired chain to query functions through template functions.
