### ISSUE TITLE
Bitfield structures for `Flags` bit-sets...

### ISSUE THREAD

**Issue by unit-a-user** [KhronosGroup/Vulkan-Hpp#1187]
I not remembered, or not know, does had or not similar proposal... Means, getting or accessing bit by name. Also, structure align should be 4.

Such structure example... 
```cpp
    // from 2017 years... 
    struct VkBufferUsageFlags { ::VkFlags
        eTransferSrc : 1,
        eTransferDst : 1,
        eUniformTexelBuffer : 1,
        eStorageTexelBuffer : 1,
        eUniformBuffer : 1,
        eStorageBuffer : 1,
        eIndexBuffer : 1,
        eVertexBuffer : 1,
        eIndirectBuffer : 1,
        eConditionalRendering : 1,
        eShaderBindingTable : 1,
        eTransformFeedbackBuffer : 1,
        eTransformFeedbackCounterBuffer : 1,
         : 4,
        eShaderDeviceAddress : 1,
         : 1,
        eAccelerationStructureBuildInputReadOnly : 1,
        eAccelerationStructureStorage : 1;
    };
```

**Comment by asuessenbach** [comment]
What would you like to tell us with this issue?

**Comment by helixd-2k18** [comment]
I mean difference between "Flags" and "FlagBits". First is bitset, second is enum as bitmask. But would propose make "Flags" as structure, which can be got bits by name accessor.

**Comment by helixd-2k18** [comment]
> What methods do you have in mind?

```cpp
  auto bit = someflags.eTransferSrc()
  someflags.eTransferSrc(true)
```

> What would you like to resolve with such an additional type?

```cpp
  auto bitReference = someflags.eTransferSrc()
  bitReference = true;
```

**Comment by asuessenbach** [comment]
With the current implementation, you would encode your first example like
```
  auto bit = someflags & vk::BufferUsageFlagBits::eTransferSrc;
  someflags |= vk::BufferUsageFlagBits::eTransferSrc;
```
Granted, something like a "FlagBitReference" is not available, but it might be possible to add to the current approach. So, if there's some demand for it...
