### ISSUE TITLE
Would it be nice to make vk::FlagTraits throw an error when used with a Flags type?

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/Vulkan-Hpp#1192]
I had some code like this:
`VkFlags64 baseMask = vk::FlagTraits< vk::PipelineStageFlags >::allFlags;`
This compiles and at runtime results in 0.

I've now learnt i need to use `vk::PipelineStageFlagBits`. Maybe it's an idea to make it impossible to put a Flags type into FlagTraits?

**Comment by asuessenbach** [comment]
Good idea!
Will add that right now.

**Comment by MennoVink** [comment]
hehe super fast, thanks 🚀
