### ISSUE TITLE
CreateDebugUtilsMessenger sample

### ISSUE THREAD

**Issue by raitys** [KhronosGroup/Vulkan-Hpp#1197]
Hello.
`for ( uint8_t i = 0; i < pCallbackData->objectCount; i++ )
    {
      message << "\t\t"
              << "Object " << i << "\n";
    }`
uint8_t converts to char, so if i == 0, `<< i` is `<< '\0'`. It's better to use std::to_string(i) or change type.

**Comment by asuessenbach** [comment]
Thanks for reporting this issue. Will be fixed right now.
