### ISSUE TITLE
Under MSVC the debug allocation macros conflict with the methods free()...

### ISSUE THREAD

**Issue by davidbien** [KhronosGroup/Vulkan-Hpp#1200]
The debug heap macros under MSVC are, unfortunately, named the same as the normal c methods.

So, free is defined as:

`#define free(p)            _free_dbg(p, _NORMAL_BLOCK)
`
It is *really* nice to be able to use the debug heap to find memory leaks.

Luckily, there is an easy fix that I have applied locally, for each instance enclose the name free in parenthesis and this prevents looking up the preprocessor macro. i.e.:

```
  template <typename Dispatch>
  VULKAN_HPP_INLINE void Device::free( VULKAN_HPP_NAMESPACE::CommandPool           commandPool,

```
becomes:

```
  template <typename Dispatch>
  VULKAN_HPP_INLINE void (Device::free)( VULKAN_HPP_NAMESPACE::CommandPool           commandPool,

```
The other solution is to change the methods to a name that doesn't clash with the macro, i.e. vkfree() for instance.

Repro: 

```
#ifdef WIN32
#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>
#ifndef NDEBUG
    #define DBG_NEW new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )
#else
    #define DBG_NEW new
#endif
#else //!WIN32
#define DBG_NEW new
#endif //!WIN32

#define __NDEBUG_THROW
#define TRACESENABLED 0

#include <iostream>
#include <stdexcept>
#include <cstdlib>

#define GLFW_INCLUDE_VULKAN
#include <glfw3.h>
#include <vulkan/vulkan_raii.hpp>

```
Now compile anything...

**Comment by asuessenbach** [comment]
Thanks a lot for reporting this issue.
And especially for providing this nice little workaround.
Will add that right now.

**Comment by davidbien** [comment]
Wow – that was fast. Thanks. I reviewed just for completeness and it seems that the changes to the source correspond to my local changes.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
