### ISSUE TITLE
Suggestion: It would be nice if there were swap() and clear() methods on RAII objects...

### ISSUE THREAD

**Issue by davidbien** [KhronosGroup/Vulkan-Hpp#1202]
This is just a suggestion. When I write RAII objects I try to write them very similarly as have been done here. Explicitly defining all construction possibilities as "default" or "delete", etc.
You provide nice move-semantics methods but the swap() method is certainly possible on most objects and is standard on STL objects where it is possible.
Also, I find that, since I want to control my de-initialization order and also de-initialize in a method separate from the class destructor, I am declaring unique_ptr<>s of these RAII objects. In all cases that I have seen, nullptr_t initialization is provided and therefore also checked for in the destructor, making the implementation of a clear() method quite simple: It would just do what was done in the destructor, while also correctly nullifying any members, etc.

So instead of this pattern that I am using a bunch:
```
  unique_ptr< vk::raii::Instance > m_upvkiInstance;
  unique_ptr< vk::raii::DebugUtilsMessengerEXT > m_updumDebugMsgr;
  unique_ptr< vk::raii::SurfaceKHR > m_upvsSurface;
  unique_ptr< vk::raii::Device > m_upvdDevice;
...
  m_upvdDevice.reset();
  m_updumDebugMsgr.reset();
  m_upvsSurface.reset();
  m_upvkiInstance.reset();
```

I could just use:
```
  vk::raii::Instance m_vkiInstance{ nullptr };
  vk::raii::DebugUtilsMessengerEXT m_dumDebugMsgr{ nullptr };
  vk::raii::SurfaceKHR m_vsSurface{ nullptr };
  vk::raii::Device m_vdDevice{ nullptr };
...
  m_vdDevice.clear();
  m_dumDebugMsgr.clear();
  m_vsSurface.clear();
  m_vkiInstance.clear();
```
This saves implementation code a bit and as well saves memory as it allows the objects to be embedded as objects instead of pointers.

Like I said just a suggestion. I am doing the Vulkan Tutorial (and learning Vulkan at the same time) but decided, since I prefer RAII, to do it with the Vulkan-Hpp headers from the start. I really appreciate their existence. I tend to do nearly everything RAII when possible.

Also: I get that both swap() and clear() can be easily simulated with move-semantics and understand that may paradigm that is preferred in Vulkan-Hpp. swap() is kinda annoying using move-semantics:
```
  vk::raii::Instance vkiInstanceTemp( std::move( m_vkiInstance ) );
  m_vkiInstance = std::move( vkiInstanceSwap );
  vkiInstanceSwap = std::move( vkiInstanceTemp );
  // vs.:
  m_vkiInstance.swap( vkiInstanceSwap );
```
Anyway, let me know what you think. Thanks.

**Comment by davidbien** [comment]
Andreas you are a machine. Thanks. I’ll try to think of more work for you to do… lol.

**Comment by asuessenbach** [comment]
I really appreciate your suggestions. I think, they make vulkan.hpp better.
So, thanks for your input.

**Comment by davidbien** [comment]
I'm nearly done with the Vulkan Tutorial using all RAII objects from the Vulkan-Hpp. It simplifies the implementation tremendously. It is more typesafe ( I particularly like the way you made the bitwise flags into typesafe bitwise enumerations - this is cool ). It is more throwsafe. The code is much easier to read. I may publish this with tags for each chapter where things actually happen (i.e. where things actual render to the screen) so that others can benefit from seeing how the tutorial is done using RAII objects from Vulkan-Hpp.
