### ISSUE TITLE
Design Issue: CommandBuffers() = delete; prevents using CommandBuffers as a structure member...

### ISSUE THREAD

**Issue by davidbien** [KhronosGroup/Vulkan-Hpp#1203]
Move-semantics are provided but since the default constructor is deleted there is really no choice but to use a container like std::optional< CommandBuffers> or std::unique_ptr< CommandBuffers >, etc.

I'm not sure what this is saving? I guess the idea is that if a CommandBuffers object is constructed then it contains a non-empty set of command buffers?

Anyway, if this is the paradigm then that is fine but then really the move-sematics are kinda wasted.

An empty CommandBuffers object can still be produced by creating a non-empty one and then calling clear() on it...

**Comment by asuessenbach** [comment]
I see... I think, what's missing here is the constructor on nullptr_t.

**Comment by davidbien** [comment]
Same issue with vk::raii::DescriptorSets - no constructor on nullptr_t.

**Comment by davidbien** [comment]
When using DescriptorSets with a DescriptorPool it is necessary to set the vk::DescriptorPoolCreateFlagBits::eFreeDescriptorSet bit on the DescriptorPool as the DescriptorSets objects always frees the sets in its destructor. If the validation layer is activated this is pointed out to you succinctly. I'm not sure if there is a way to design DescriptorSets to allow for using it to store sets but also indicating that the DescriptorPool is going to destroy them... 
Anyway, this is a problem I ran into. For the CommandPool and CommandBuffers the same issue exists except that the CommandPool allows its constituent CommandBuffer(s) to be deallocated without a special flag on CommandPool creation.
Anyway, I was just pointing this out as part of my due diligence.

**Comment by asuessenbach** [comment]
Yes, that bit, that needs to be set here is one of the things I was not able to automatically resolve (yet).
If you (or anybody else) has a good idea on that issue, you're welcome!
