### ISSUE TITLE
Clarify which symbols are part of public API and which are implementation details

### ISSUE THREAD

**Issue by Hawk777** [KhronosGroup/Vulkan-Hpp#1205]
The README explains in general how to use Vulkan-HPP, but it doesn’t really go into details. So, to figure out e.g. individual function signatures, I’ve taken to just browsing the header file. Unfortunately, the header file has very few comments, so I’m not sure which things I discover I’m really allowed to use—which are parts of Vulkan-HPP’s public API, and which are implementation details which are only in the header file for technical reasons (i.e. because Vulkan-HPP is a header-only library so *everything* is in header files)?

For example, if I have a `Result` lying around, am I allowed to call `throwResultException` myself, or is that an implementation detail which might get renamed or deleted in a future version of Vulkan without warning?

It would be good if implementation details were either commented as such, or perhaps put into an `impl` namespace or something like that.

**Comment by Pacheco95** [comment]
Meybe put implementation details in a different namespace, e.g. `priv`

**Comment by asuessenbach** [comment]
This has been resolved with #1983 and #1984.
