### ISSUE TITLE
Structure reflection and compile times

### ISSUE THREAD

**Issue by Eearslya** [KhronosGroup/Vulkan-Hpp#1209]
PR #1166 introduced `reflect()` functions to every Vulkan struct, giving them a way to "simplify" equality checks. These look nice and neat on the surface, but I don't think they're pulling their weight. The addition of these functions has massively increased compile times for anything including `vulkan.hpp`.

Taking this simple code sample:

```cpp
#include <vulkan/vulkan.hpp>
int main() { return 0; }
```

Compiling with Visual Studio 2022 (CL version 19.30.30709) takes an average of 12.7 seconds with the current version of the headers. I modified the Hpp generator code to remove these reflection functions and return to the old comparison method, and that brought compile times down to 2.2 seconds, nearly 6 times faster.

I have not tested if there is a significant performance difference between comparing these tuples and comparing the values individually as was done before, but regardless, I think comparing structs is a relatively rare thing that is used mainly for hashing. Unless the performance difference is equally important, I don't think the extra compile time is warranted.

Is there a strong reason to keep this new method of comparison, in the face of compiler overhead that high?

**Comment by asuessenbach** [comment]
Well, it seems, that feature is a bit heavy-weight, at least for current compileres :(
I'll add a define VULKAN_HPP_USE_REFLECT, to include that feature. And as it currently is that expensive, it won't be defined by default.

**Comment by asuessenbach** [comment]
See #1210.
