### ISSUE TITLE
C++ Modules

### ISSUE THREAD

**Issue by Xottab-DUTY** [KhronosGroup/Vulkan-Hpp#121]
I'm using Visual Studio and if I enable C++ modules in project preferences, then I can't compile because Vulkan hpp uses variables with name "module" which becomes a keyword after enabling modules.

It would be nice if this will be fixed.

**Comment by mtavenrath** [comment]
I understand your concerns, but for now there is nothing we can do since the module variable name is derived from the Vulkan C-API and changing the name now would create compatibility issues. I'll bring this up in the WG to see what can be done to make Vulkan available in C++ modules.

**Comment by Xottab-DUTY** [comment]
Okay, will be waiting for it.

**Comment by Xottab-DUTY** [comment]
Any news from WG on this?

**Comment by mtavenrath** [comment]
The WG is aware of the issue and working on it. A temporary binary compatible, but very hackish, workaround is renaming the member variable to something else.

**Comment by mtavenrath** [comment]
@Xottab-DUTY  The issue has been brought up to the C++ working group: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0795r0.pdf

**Comment by charles-lunarg** [comment]
Now that C++20 is right around the corner, I believe it is worth re-checking if this will be an issue. 
From my limited understanding, in C++20 `module` is context sensitive and should only be used as a keyword in specific contexts, so it shouldn't cause a problem. 
An affirmation that this is no longer an issue with the 'official' version of C++ modules, both what the spec says and what any implementation does, would be very helpful.

**Comment by asuessenbach** [comment]
From cppreference.com:
> In addition to keywords, there are _identifiers with special meaning_, which may be used as names of objects or functions, but have special meaning in certain contexts.

And one of those _identifiers with special meaning_ is the word <module>.
So, yes, there is no interference between that module and any member variables named <module>

**Comment by Hjaltesorgenfrei** [comment]
While it should not be a problem, it does appear that MSVC (as of version 19.28.29812) has a problem with it. I had to change the field name _module_ in `PipelineShaderStageCreateInfo` for the compiler to recognise it as a field. Else it just complains that it "expected an identifier".
