### ISSUE TITLE
Resetting raii types does not destroy the vulkan objects

### ISSUE THREAD

**Issue by rudolfheszele** [KhronosGroup/Vulkan-Hpp#1218]
I am learning Vulkan and using vulkan-hpp with raii types. I noticed that the operator=() implementation on the types does not destroy the underlying vulkan handle, causing them to "leak".
To reproduce it do something like this:
`_pipeline = { std::nullptr_t{} };`
where `_pipeline` is a `vk::raii::Pipeline` object, and has a valid handle to a VkPipeline. If you have the validation layers enabled, it will complain when the device is destroyed, saying not all child resources are destroyed.
I checked the code and looks like the operator=() just exchanges the handles from the right side and does not care if the owned handles are valid or not.
I guess the solution for [this](https://github.com/KhronosGroup/Vulkan-Hpp/issues/1202) issue will help, but a raii type should clear its resources when it is being replaced.
I might be missing something, but the only way I could reset a raii, is this:
`vkDestroyPipeline(*_device, *_pipeline, nullptr);`

**Comment by asuessenbach** [comment]
You're right, https://github.com/KhronosGroup/Vulkan-Hpp/issues/1202 did resolve this issue.
That is, with the current implementation, no such leak should occur.

**Comment by rudolfheszele** [comment]
Thanks for the reply, good to know it is already fixed! :) I tried to check the solution for that ticket, but it was kind of hard to read :) I am using vullkan-hpp through the conan package of vulkan-headers. Do you know when I can expect this change to be packaged? :)

**Comment by asuessenbach** [comment]
I don't know anything about the update policy of that conan package.
But you could try to replace (all!) the vulkan headers with [https://github.com/KhronosGroup/Vulkan-Headers.](https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/v1.3.206).

**Comment by rudolfheszele** [comment]
Thanks for all the help! :)
