### ISSUE TITLE
Better unique handles to simplify updating existing code.

### ISSUE THREAD

**Issue by ioquatix** [KhronosGroup/Vulkan-Hpp#122]
The current system for unique handles is useful but cumbersome especially when migrating existing code which doesn't use them. I'm not sure how useful these ideas are but I think it would be good to have a discussion about it.

It would be good to discuss the following improvements:

- Prefer `std::unique_ptr` as base implementation.
- Type dependent allocation/initialization. Rather than `vk::DeviceDeleter`, expose `vk::Device::Deleter`.
- Use a template for the majority of deleter implementations. You know you can pass function pointers as template parameters.
- Use the type dependent lookup to automatically create the deleter appropriately rather than having to manually invoke specific methods.

Ideally, it would be possible just to change the type signature, and have everything continue to work. In order to do that, you'd need a base wrapper which could be automatically converted to a unique pointer.

```c++
vk::Device device;
vk::Unique<vk::Device> unique_device;

device = _physical_device.createDevice(device_info, alloc());
unique_device = device; // take ownership
```

or probably more reasonably:

```c++
vk::Unique<vk::Device> device = _physical_device.createDevice(device_info, alloc());
```

Otherwise, a lot of changes to the codebase are required to change `createX` to `createXUnique`.

**Comment by ioquatix** [comment]
I'm aware that the design means that the code above is not possible (that the deleter needs more information). But, I'm just giving examples, and perhaps we can discuss (a) whether this is something worth pursuing and (b) how it could be achieved.

**Comment by ioquatix** [comment]
Perhaps one option is to make a `vk::Value<T>` which contains all the information to generate either a `vk::T` or `vk::UniquePointer<T>` instance. `createX` would return `vk::Value<X>` and you could either assign this to a raw value or a handle which deletes it. The compiler would take care of the rest.

**Comment by ioquatix** [comment]
it would be pretty awesome if the semantics of `vk::Value<T>` were similar to `vk::UniquePointer`, in terms of being a container and the use of `->` vs `.`. That would ease code migration since you could move things all to `vk::Value<T>` as a first step and then to `vk::UniquePointer<T>` next, one thing at a time.

**Comment by mtavenrath** [comment]
Those are all good ideas. One thing we've to be careful about is breaking compatibility with existing applications, so all changes have to be compile-time compatible. 

> Prefer std::unique_ptr as base implementation.

That was our first approach and it failed with MSVC having problems if certain operators were overloaded in the specified element type. If you can make vk::UniquePtr derived from std::unique_ptr which runs on MSVC, GCC and CLANG and which also doesn't break compile time compatibility with existing code I'm happy to review the PR! I think the problem was related to having operator*() and operator->() in the handle.

>Use a template for the majority of deleter implementations. You know you can pass function pointers as template parameters.

That's still on the TODO-list ;-)

>Perhaps one option is to make a vk::Value<T> which contains all the information to generate either a vk::T or vk::UniquePointer<T> instance. createX would return vk::Value<X> and you could either assign this to a raw value or a handle which deletes it. The compiler would take care of the rest.

This was one of the options we've evaluated to implement this feature to make migration easier. The main reason not to implement it was that returning the compiler won't figure out how to return arrays without additional cost. The second reason is that creating a unique handle is a different operation than creating a handle and thus the operation should have a different name.

>vk::Device device;
vk::Unique<vk::Device> unique_device;
device = _physical_device.createDevice(device_info, alloc());
unique_device = device; // take ownership
I'm aware that the design of this library means that the code above is not possible (that the deleter needs more information, e.g. the allocator

Something like this is already possible. Although we couldn't use std::unique_ptr we replicated the interface, so you can write:

```
vk::Device device;
vk::UniqueDevice unique_device(nullptr, vk::DeviceDeleter(myAllocator);

device = _physical_device.createDevice(device_info, myAllocator);
unique_device.reset(device); // take ownership
```

or 

```
vk::Device device;
vk::Unique<vk::Device> unique_device();

device = _physical_device.createDevice(device_info, myAllocator);
unique_device = vk::Unique<vk::Device>(device, myAllocator);
```

>Use the type dependent lookup to automatically create the deleter appropriately rather than having to manually invoke specific methods.

That's actually a quite good idea we have to evaluate.

**Comment by ioquatix** [comment]
> Those are all good ideas. One thing we've to be careful about is breaking compatibility with existing applications, so all changes have to be compile-time compatible.

I appreciate this point, but my experience of this code, is that things have broken several times during the past 2 years which have required major refactors. I feel like breaking compatibility is worth it if it yields a significant improvement in usability, and honestly, people should be versioning the header, along with `vulkan.h` as part of their application.

**Comment by ioquatix** [comment]
I have another question. Is there actually any safe way to use the non-unique handles in the presence of exceptions?

**Comment by ioquatix** [comment]
After working on more of this code, I'm finding that while a few APIs do want to expose ownership semantics (e.g. UniqueX as an argument) many of them don't care if it's `UniqueX` or `X`. Some way of allowing an API to accept both without having to unbox `UniqueX` every time would be awesome.

**Comment by mtavenrath** [comment]
>I have another question. Is there actually any safe way to use the non-unique handles in the presence of exceptions?

Yes, catch the exceptions and clean up in the exception handler. It's easier to leak handles with this technique since you have to manually ensure that all handles get destroyed if you hit the exception handler. This is all about performance/memory footprint vs. safety and comfort.

```
vk::SomeHandle handle1;
...
vk::SomeOtherHandle handleN;

try {
  // do all your (Vulkan) stuff
} catch(...) {
  destroy(handle1);
  destroy(handle2)
};
```

**Comment by ioquatix** [comment]
I checked and it seems like at -O3 the compiler where possible completely optimises out the additional handles. It's not all cases, but at least it was interesting to see it in at least one of the cases I tried.

**Comment by ioquatix** [comment]
I noticed what I think is a bug with the API.

```c++
vk::UniqueDevice ud = ...

{
  vk::Device d = *ud;

  long_time->_pipeline = d->createGraphicsPipelineUnique(...)

  PipelineDeleter deleter(this, allocator)
}
```

The `this` pointer is invalid by the time the pipeline is destroyed.

**Comment by ioquatix** [comment]
```
  VULKAN_HPP_INLINE void PipelineDeleter::operator()( Pipeline pipeline )
  {
    m_device->destroyPipeline( pipeline, m_allocator );
  }
```

`m_device` is long gone.

**Comment by ioquatix** [comment]
```c++
class UniqueHandle {
    Type const& operator*() const
    {
      return m_value;
    }

    Type get() const
    {
      return m_value;
    }
```

Why is it not `const Type & get() const` and perhaps the equivalent non-const accessor too?

**Comment by ioquatix** [comment]
I ended up with this monster 

```c++
		vk::Device & device() {return const_cast<vk::Device &>(*_device);}
```

and no memory leaks. Not sure which one I prefer actually :D

**Comment by ioquatix** [comment]
After implementing this, some random unstructured thoughs:

- I feel like UniqueHandle instances should be the default. I know it's not the style of this library but it's not stupid either.
- The deleters are broken by design if you combine unique and plain old instances.
- The UniqueHandle has some overhead, but it's mostly removed by the compiler if you write your code a certain way.
- The overhead in Arrays might be amortised by making a UniqueArray implementation which stores the deleter once for all the items in the array.
- The actual implementation mostly just worked, and I was pretty glad about that, but there are a couple of ugly spots, `std::move`, `&&` sprinked around in places that made it compile, pass all unit tests, etc, but not entirely sure what the best practice should be - may require some documentation or perhaps just a couple of blog posts

**Comment by johannesugb** [comment]
> > Prefer std::unique_ptr as base implementation.
> 
> That was our first approach and it failed with MSVC having problems if certain operators were overloaded in the specified element type. If you can make vk::UniquePtr derived from std::unique_ptr which runs on MSVC, GCC and CLANG and which also doesn't break compile time compatibility with existing code I'm happy to review the PR! I think the problem was related to having operator*() and operator->() in the handle.

@mtavenrath uh, did you really first consider having a heap allocation for every unique handle, which is what you get by using `std::unique_ptr`? The current implementation is much better because it avoids heap allocations.

**Comment by mtavenrath** [comment]
@johannesugb There was no need for a heap allocation for unique handle. Vulkan-Hpp are actually pointers on 64-bit Vulkan, thus a custom deleter was sufficient.

**Comment by johannesugb** [comment]
I'm glad you did not not use `std::unique_ptr` in the end! :)
