### ISSUE TITLE
vk::PhysicalDevice::getMemoryProperties() does not compile

### ISSUE THREAD

**Issue by Pycorax** [KhronosGroup/Vulkan-Hpp#1228]
Tested on Visual Studio 2019 version 16.11.8 with Visual C++ 2019  (00435-60000-00000-AA218)

The following line of code:
```
vk::PhysicalDeviceMemoryProperties memProps = physicalDevice.getMemoryProperties(memReq);
```
Causes the following errors to be reported by Visual Studio:
```
>C:\VulkanSDK\1.3.204.1\Include\vulkan\vulkan_funcs.hpp(350,5): error C2039: 'getVkHeaderVersion': is not a member of 'vk::MemoryRequirements'
1>C:\VulkanSDK\1.3.204.1\Include\vulkan\vulkan_structs.hpp(44117): message : see declaration of 'vk::MemoryRequirements'
1><SolutionPathOmitted>\VulkanBuffer.cpp(39): message : see reference to function template instantiation 'vk::PhysicalDeviceMemoryProperties vk::PhysicalDevice::getMemoryProperties<vk::MemoryRequirements>(const Dispatch &) noexcept const' being compiled
1>        with
1>        [
1>            Dispatch=vk::MemoryRequirements
1>        ]
1>C:\VulkanSDK\1.3.204.1\Include\vulkan\vulkan_funcs.hpp(352,7): error C2039: 'vkGetPhysicalDeviceMemoryProperties': is not a member of 'vk::MemoryRequirements'
1>C:\VulkanSDK\1.3.204.1\Include\vulkan\vulkan_structs.hpp(44117): message : see declaration of 'vk::MemoryRequirements'
```

**Comment by asuessenbach** [comment]
Agreed, the error message is not that clear. But the error is in your code.
You're passing a variable `memReq` into the function. But the `getMemoryPropertie`s function, that returns a `vk::PhysicalDeviceMemoryProperties` only takes an (optional) `Dispatch const &` as argument. As that argument is a template, the compiler tried to use your `memReq` as a `Dispatch` object, and (correctly) tells you about some missing stuff there.

**Comment by Pycorax** [comment]
Thanks for clarifying. I'm so sorry for troubling you with my own mistake.  I appreciate the quick response.
