### ISSUE TITLE
Vulkan HPP not more compatible with Intellisense (Visual Studio 2022)

### ISSUE THREAD

**Issue by unit-a-user** [KhronosGroup/Vulkan-Hpp#1255]
I used intensive code, and got incompatibility of Intellisense and Vulkan-HPP headers. Intellisense just crashes or stuck in opening project and no more working. In small code sized project Intellisense still working, but in bigger no more works. 

- CPU: Intel Core i7 8700K (probably, too old and weak)
- OS: Windows 11 (Insiders)
- IDE: Visual Studio 2022 Community
- RAM: 32Gb (and still not enough)

**Comment by asuessenbach** [comment]
That's very unfortunate, for sure!
But are you sure, that vulkan.hpp is the culprit, here? Maybe, it's not a Vulkan-Hpp issue, but an intellisense issue?

**Comment by unit-a-user** [comment]
When used just `vulkan.h`, InteliSense works way faster.

**Comment by asuessenbach** [comment]
It's true, vulkan.hpp is way more demanding to compiler and probably intellisense as well than vulkan.h.
And it is probably to be expected, that more complex code takes longer to analyse, and finally might push intellisense to its limits.
But what do you expect to get here with that issue?
Wouldn't it be better to file an issue against intellisense? Or search the web for errors, fixes, and workarounds with intellisense?

**Comment by unit-a-user** [comment]
At the moment I don't have an exact idea why...

**Comment by johannesugb** [comment]
Experienced the same when switching to Vulkan SDK 1.3, while with Vulkan SDK 1.2 versions, everything is fine. Happened also in Visual Studio 2019 for me. 

@unit-a-user are you using Vulkan SDK 1.3 as well? Have you been able to get rid of these problems?
