### ISSUE TITLE
Why isn't pNext the last parameter of struct constructors which have it?

### ISSUE THREAD

**Issue by Karlovsky120** [KhronosGroup/Vulkan-Hpp#1259]
I was trying to create a `vk::UniqueInstance` with validation and `vk::DebugUtilsMessengerEXT` and I ended up with this:

```
vk::InstanceCreateInfo instanceCreateInfo({}, &appInfo, validationLayers, extensions);
instanceCreateInfo.pNext = &debugCreateInfo;
_instance = vk::createInstanceUnique(instanceCreateInfo);
```

However, if `pNext` was a constructor parameter, I could do the following:
```
_instance = vk::createInstanceUnique({{}, &appInfo, validationLayers, extensions, &debugCreateInfo});
```

Is there some reason why `pNext` isn't included as a parameter to all `*CreateInfo` structs that support it, defaulting to `nullptr`?

**Comment by asuessenbach** [comment]
Thanks for that good question!
Back in the days, when vulkan.hpp was started, there were very few structures that actually were specified to have some valid extension structures. Therefore, we decided to not add that parameter to the constructor's argument list.
But those days are gone. That is, I'll add pNext as an optional last parameter to the constructors, just like you suggested.
Besides that, did you have a look at the vk::StructureChain? Especially for structure chains known at compile time, that might be a good alternative.

**Comment by Karlovsky120** [comment]
I completely forgot about the structure chains, they would be a better way to do this, I agree.
Adding pNext as optional last parameter seems to be in line with the structure constructor idea, so I'm glad it's getting added.
Thanks!
