### ISSUE TITLE
Missing overload for createResultValue

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/Vulkan-Hpp#1268]
a8d47f469433a6e43e160ebbcfa9eee90b9d1c40 removed a 5 parameter version of `createResultValue`, but that version is still used by `createComputePipelineUnique`. This is causing a compilation failure. Should that use have been updated or should there still be a 5 parameter version of the function?

**Comment by asuessenbach** [comment]
Thanks for reporting this issue.
Removing that version of createResultValue was not intended. Will be added again right now.
