### ISSUE TITLE
Device::createGraphicsPipelinesUnique not working with custom allocator?

### ISSUE THREAD

**Issue by vudugun** [KhronosGroup/Vulkan-Hpp#1275]
I am trying to feed my stateless allocator to `Device::createGraphicsPipelinesUnique()`, like this:

    device.createGraphicsPipelinesUnique<vk::DispatchLoaderStatic, MyAllocator<vk::UniquePipeline>>(...)

but when I compile with VS 2019 and Clang 12 I get this error:

    no matching function for call to 'createResultValue'

Looking into `vulkan.hpp` and `vulkan_funcs.hpp` I found the create function requires a `createReturnValue()` that accepts a `std::vector<UniqueHandle<Pipeline, Dispatch>, PipelineAllocator>`, but the closest I could find only takes a `std::vector<UniqueHandle<T, D>>`.

Am I missing something?

**Comment by asuessenbach** [comment]
No, you don't miss anything, you found a bug. Will fix it right now.
