### ISSUE TITLE
Get rid of <=> operator for structs?

### ISSUE THREAD

**Issue by YaaZ** [KhronosGroup/Vulkan-Hpp#1315]
I'm not sure whether we really need a spaceship operator for structs because usually only equality test makes sense for them.
And not only I see it meaningless, explicitly defaulted spaceship operators generate warnings on Clang (there's more, I'm giving one as an example):
```
.../include/vulkan/vulkan_structs.hpp:4010:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>( AllocationCallbacks const & ) const = default;
         ^
.../include/vulkan/vulkan_structs.hpp:4030:42: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'pfnAllocation'
    PFN_vkAllocationFunction             pfnAllocation         = {};
                                         ^
```
Furthermore, old implementation `#ifndef VULKAN_HPP_HAS_SPACESHIP_OPERATOR` only provides == operator, not < and >.
That is, I propose to get rid of spaceship operator for structs and retain only equality test, if there're no objections, I can create a PR for this.

**Comment by asuessenbach** [comment]
That is, there is no default operator<=> on function pointers. Means, I would have to remove the spaceship operator for every struct that holds a function pointer (currently, that's AllocationCallbacks, DebugReportCallbackCreateInfoEXT, DebugUtilsMessengerCreateInfoEXT, and DeviceDeviceMemoryReportCreateInfoEXT).
Do you see such warnings for other structs than those four?

**Comment by YaaZ** [comment]
Yes, `ArrayWrapper2D` also doesn't have spaceship operator which causes warnings for `TransformMatrixKHR::matrix`, which in turn causes warnings for `AccelerationStructureInstanceKHR::transform` and `AccelerationStructureMatrixMotionInstanceNV::transformT0`.

**Comment by asuessenbach** [comment]
That's a bit weird, as `ArrayWrapper2D` publicly derives from `std:array`, which should have `operator<=>()` as a non-member function with C++20.

**Comment by YaaZ** [comment]
No, no warnings with `ArrrayWrapper1D`, only `ArrrayWrapper2D`, here's the full log with latest headers:
```
.../include/vulkan/vulkan_structs.hpp:2464:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>( TransformMatrixKHR const & ) const = default;
         ^
.../include/vulkan/vulkan_structs.hpp:2482:55: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'matrix'
    VULKAN_HPP_NAMESPACE::ArrayWrapper2D<float, 3, 4> matrix = {};
                                                      ^
.../include/vulkan/vulkan_structs.hpp:2593:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>( AccelerationStructureInstanceKHR const & ) const = default;
         ^
.../include/vulkan/vulkan_structs.hpp:2613:46: note: defaulted 'operator<=>' is implicitly deleted because it would invoke a deleted comparison function for member 'transform'
    VULKAN_HPP_NAMESPACE::TransformMatrixKHR transform = {};
                                             ^
.../include/vulkan/vulkan_structs.hpp:2464:10: note: explicitly defaulted function was implicitly deleted here
    auto operator<=>( TransformMatrixKHR const & ) const = default;
         ^
.../include/vulkan/vulkan_structs.hpp:2482:55: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'matrix'
    VULKAN_HPP_NAMESPACE::ArrayWrapper2D<float, 3, 4> matrix = {};
                                                      ^
.../include/vulkan/vulkan_structs.hpp:2744:10: warning: explicitly defaulted three-way comparison operator is implicitly deleted [-Wdefaulted-function-deleted]
    auto operator<=>( AccelerationStructureMatrixMotionInstanceNV const & ) const = default;
         ^
.../include/vulkan/vulkan_structs.hpp:2764:46: note: defaulted 'operator<=>' is implicitly deleted because it would invoke a deleted comparison function for member 'transformT0'
    VULKAN_HPP_NAMESPACE::TransformMatrixKHR transformT0 = {};
                                             ^
.../include/vulkan/vulkan_structs.hpp:2464:10: note: explicitly defaulted function was implicitly deleted here
    auto operator<=>( TransformMatrixKHR const & ) const = default;
         ^
.../include/vulkan/vulkan_structs.hpp:2482:55: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'matrix'
    VULKAN_HPP_NAMESPACE::ArrayWrapper2D<float, 3, 4> matrix = {};
                                                      ^
```

**Comment by asuessenbach** [comment]
I'm sorry, but I don't get that issue reproduced.
Would you mind to adjust my little repro-test on godbolt (https://godbolt.org/z/4G33KPzcn) to get that warning?

**Comment by Nahor** [comment]
> only equality test makes sense for them

Depends on the context. It may not make sense if you want to put a meaning behind a "A < B", but it makes sense if you want to just order/sort the structs (e.g. to use as keys in a std::map).

**Comment by asuessenbach** [comment]
@YaaZ That's weird again, as that should definitely get you errors on ArrayWrapper1D as well.
Nevertheless, it revealed that I check the wrong feature testing macro: I should check `( 201907 <= __cpp_lib_three_way_comparison )`, instead of `( 201711 <= __cpp_impl_three_way_comparison )`
Will fix that right now.

**Comment by YaaZ** [comment]
@asuessenbach with updated feature test it now just disables <=> on that setup, so I guess it's just not fully supported there, so I'm closing the issue. Thank you!
