### ISSUE TITLE
Enhanced mode PhysicalDevice::getProperties2<> and similar don't work with chain unlinking

### ISSUE THREAD

**Issue by Daemonae** [KhronosGroup/Vulkan-Hpp#1336]
The [addition of unlink/relink](https://github.com/KhronosGroup/Vulkan-Hpp/pull/441/commits/299734eff5a1023e82ed7a7612e5048c5eaa346b) makes it easier to suppress the inclusion of elements that are not supported or are runtime disabled. However, this support does not work for enhanced-mode variadic templace helpers like [`PhysicalDevice::getProperties2`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/42e0c54d7560326d6d0ca640521b0122abdd644c/vulkan/vulkan_handles.hpp#L11712), as they takes the template specialization and internally construct the chain, giving no opportunity for unlinking.

A discussion on gitlab I was pointed at (https://gitlab.khronos.org/vulkan/vulkan/-/issues/2442) seems to be converging on strengthening [the language](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#fundamentals-validusage-pNext) to make it a validation error to pass chain elements that are not used by an enabled extension or the driver.

It may be necessary to deprecate the current variadic template helpers to encourage propert style, but perhaps a new one could be added that accepts a `StructureChain` (without using the chain typing beyond validity) to at least preserve the more fluid style of Vulkan-Hpp.

**Comment by asuessenbach** [comment]
Maybe I don't get your proposal with "accepts a `StructureChain` (without using the chain typing beyond validity)"
Afterall, a runtime-adjusted `StructureChain<...>` isn't a modified type, but just a modified object. That is, I don't see, how you could use such a modified StructureChain as a template parameter, without passing the modified object into such a function.
But that isn't needed at all, as there already exists a flavour of that function, that takes a `vk::PhysicalDeviceProperties2 *` as an argument.
That is, with code like this, you can already get what you want:
```
vk::StructureChain<vk::PhysicalDeviceFeatures2, vk::PhysicalDeviceIDProperties, vk::PhysicalDevicePushDescriptorPropertiesKHR> chain;
// do your runtime unlink/relink here
// ...
physicalDevice.getProperties2( &chain.get<vk::PhysicalDeviceFeatures2>() );
```

**Comment by Daemonae** [comment]
Yeah, it would just enable it to be more concise and compact:
```
vk::StructureChain<vk::PhysicalDeviceFeatures2, vk::PhysicalDeviceIDProperties, vk::PhysicalDevicePushDescriptorPropertiesKHR> chain;
// do your runtime unlink/relink here
// ...
physicalDevice.getProperties2( chain );
```

Not a strong ask, as updating documentation to reflect preferred style would be more important.

**Comment by asuessenbach** [comment]
As the difference between those two function signatures/usages are that small, I probably wont add the latter.
