### ISSUE TITLE
Re-enable implicit conversions for structs

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/Vulkan-Hpp#1353]
Would it be possible to keep allowing implicit conversions for structs? When compiling on x64, handles can be implicitly converted unless you set VULKAN_HPP_TYPESAFE_CONVERSION to 0. Maybe these struct conversions should only be explicit when you set that define to 0 too?

This used to work, but was changed by https://github.com/KhronosGroup/Vulkan-Hpp/pull/1160

**Comment by asuessenbach** [comment]
... well, after thinking about it a second time: there's no connection between implicit/explicit casting of structs and VULKAN_HPP_TYPESAFE_CONVERSION. That define is purely related to casting of handles, especially with the differences between 32bit and 64bit compilation.
That is, I'll revert the struct conversion operators to implicit without restrictions.
