### ISSUE TITLE
`ArrayProxy` and co taking in `std::set`

### ISSUE THREAD

**Issue by HellsingDarge** [KhronosGroup/Vulkan-Hpp#1355]
Recently needed to pass `std::set` to constructor with `ArrayProxyNoTemporaries` as arg and found it impossible: `Converson function from 'std::set<uint32_t>' to 'ArrayProxyNoTemporaries<const uint32_t>' invokes a deleted function` (the function being `ArrayProxyNoTemporaries( V && value ) = delete;`) for both `const` and non-`const` `std::set`, although `vector` in the same place worked fine. Then tried it with `ArrayProxy` - same problem.  
Would it be possible to have `ArrayProxy` and `ArrayProxyNoTemporaries` work with `std::set`?

**Comment by asuessenbach** [comment]
Sorry, but std::set (as well as std::map) conceptually don't hold their data in an array-like fashion. Therefore, ArrayProxy and ArrayProxyNoTemporaries can't be used with that data structures.

**Comment by HellsingDarge** [comment]
A bit of a shame, I suppose resorting to temporary `set` to construct `vector` will have to do.  
I guess it's because `set` is associative instead of contigeous like `vector`? If so, could this detail be added to the README section?
