### ISSUE TITLE
Can vulkan shader(compute shader or rendering shader) created from string?

### ISSUE THREAD

**Issue by FdyCN** [KhronosGroup/Vulkan-Hpp#1364]
As mentioned above. can vulkan create shader like OpenGL or OpenCL from string？
Seemed the only way is created fromg SPIR-V and binary？

**Comment by asuessenbach** [comment]
Sure, you can use a glsl or hlsl string, for example. You just need to use some compiler to translate that to SPIR-V.
Please have a look at sample 11_InitShaders, for example, to see how it works with some glsl shaders provided as strings.

**Comment by FdyCN** [comment]
> Sure, you can use a glsl or hlsl string, for example. You just need to use some compiler to translate that to SPIR-V. Please have a look at sample 11_InitShaders, for example, to see how it works with some glsl shaders provided as strings.

@asuessenbach  Thanks for your reply，i learned the sample code, but i still had some question.

1. Is there any native support in Vulkan.hpp or generic SDK that i can use for GLSL --> SPIR-V JIT？
2. if use [glslang](https://github.com/KhronosGroup/glslang), will link 3rd-party libraries & dependencies, how large they will be? cause i muse take packet size into consideration.

**Comment by asuessenbach** [comment]
1. There's no native support in vulkan.hpp. There might by some generic SDK out there in the wild, but the code you find in the samples here should show all the needed steps from glsl to SPIR-V.
2. If you look at the release build samples here, 11_InitShaders for example is about 1.9 MB. 10_InitRenderPass just has 288 KB. (All on windows using MSVC 2019, other platforms/compilers would probably result in different sizes).

**Comment by FdyCN** [comment]
> 1. There's no native support in vulkan.hpp. There might by some generic SDK out there in the wild, but the code you find in the samples here should show all the needed steps from glsl to SPIR-V.
> 2. If you look at the release build samples here, 11_InitShaders for example is about 1.9 MB. 10_InitRenderPass just has 288 KB. (All on windows using MSVC 2019, other platforms/compilers would probably result in different sizes).

@asuessenbach thank your for your reply and test result, really helpful

after my searching for docs ,i got some useful information, post blow in case some one else has the same confusion:

1.  (Not tested yet)Vulkan SDK produced by LunarG does include the glslang lib, dissusion [refrence](https://vulkan.lunarg.com/issue/home?limit=10;q=;mine=false;org=false;khronos=false;lunarg=false;indie=false;status=new,open) 

2. (Not tested yet)its possible to use [shaderc](https://github.com/google/shaderc) from google, which is a wrapper around glslang, and shipped by NDK since r12b. LunarG Vulkan SDK ships too.

3. (tested yet)I used Vulkan SDK by LunarG on my MacOS, i got a vkInstance creationg err and fix it by [this](https://vulkan.lunarg.com/issue/view/62cfe6575df112a15deabf18)

i will go to link glslang on my MacOS demo, and give further feed back after that.
