### ISSUE TITLE
vkCreateDebugUtilsMessengerEXT problem

### ISSUE THREAD

**Issue by SetoKaiba** [KhronosGroup/Vulkan-Hpp#1378]
I tried to use the samples/utils/utils.cpp in my project. And my project can't compile.
If I removed this line, then it will compile.
Is there something that I miss?

```
LINK Pass 1: command "C:\PROGRA~1\MICROS~4\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x64\link.exe /nologo CMakeFiles\obelisk.dir\main.cpp.obj CMakeFiles\obelisk.dir\Device.cpp.obj CMakeFiles\obelisk.dir\VulkanDevice.cpp.obj CMakeFiles\obelisk.dir\Queue.cpp.obj CMakeFiles\obelisk.dir\WebGPUDevice.cpp.obj CMakeFiles\obelisk.dir\WebGPUQueue.cpp.obj CMakeFiles\obelisk.dir\utils\vk_utils.cpp.obj CMakeFiles\obelisk.dir\CommandBuffer.cpp.obj CMakeFiles\obelisk.dir\VulkanQueue.cpp.obj /out:obelisk.exe /implib:obelisk.lib /pdb:obelisk.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console C:\VulkanSDK\1.3.216.0\Lib\vulkan-1.lib C:\VulkanSDK\1.3.216.0\Lib\SDL2.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\obelisk.dir/intermediate.manifest CMakeFiles\obelisk.dir/manifest.res" failed (exit code 1120) with the following output:
vk_utils.cpp.obj : error LNK2019: unresolved external symbol vkCreateDebugUtilsMessengerEXT，referenced in function "public: enum VkResult __cdecl vk::DispatchLoaderStatic::vkCreateDebugUtilsMessengerEXT(struct VkInstance_T *,struct VkDebugUtilsMessengerCreateInfoEXT const *,struct VkAllocationCallbacks const *,struct VkDebugUtilsMessengerEXT_T * *)const " (?vkCreateDebugUtilsMessengerEXT@DispatchLoaderStatic@vk@@QEBA?AW4VkResult@@PEAUVkInstance_T@@PEBUVkDebugUtilsMessengerCreateInfoEXT@@PEBUVkAllocationCallbacks@@PEAPEAUVkDebugUtilsMessengerEXT_T@@@Z) 
```

**Comment by SetoKaiba** [comment]
I know the reason now. It defined to use VULKAN_HPP_DISPATCH_LOADER_DYNAMIC. But I want to know the reason why it doesn't work with static library.

···
target_compile_definitions(utils PUBLIC VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1)
···

**Comment by SetoKaiba** [comment]
I know the reason now. It defined to use VULKAN_HPP_DISPATCH_LOADER_DYNAMIC. But I want to know the reason why it doesn't work with static library.

```
target_compile_definitions(utils PUBLIC VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1)
```

**Comment by asuessenbach** [comment]
It doesn't work because there's nothing like a static function ::vkCreateDebugUtilsMessengerEXT available.
That's why the DispatchLoaderDynamic is used with (almost) all the samples: some functions used are not statically available.

If you really want to use the static dispatcher, you would have to provide a static version of that function, like it is done in the sample CreateDebugUtilsMessenger.

Besides that, just using utils.cpp in your own project might not be the best approach. That file really isn't designed for general usage, but just to fit the needs of the samples here. Feel free to be inspired by the functions therein, but don't expect them to be fit for commercial usage.

**Comment by SetoKaiba** [comment]
@asuessenbach So, what about making this change? If the utils project won't compile without VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1. Then the code working with static will be useless. So I make a change like this.
https://github.com/SetoKaiba/Vulkan-Hpp/commit/85a86d9574e19b0a0d264a959cc12064adb83c29

**Comment by SetoKaiba** [comment]
If VULKAN_HPP_DISPATCH_LOADER_DYNAMIC is always 1, no need to use VULKAN_HPP_DISPATCH_LOADER_DYNAMIC macro inside the utils code. So I think make a change like this would be better. If you think that it is ok, I'll make a pull request for it.

**Comment by asuessenbach** [comment]
Essentially something like that would work. But it's not only that function, that would be missing, but all the functions provided by extensions. With that, you would end up with getting almost every function dynamically to have an equivalent static function. Work, that's already done by the dynamic dispatcher.
In fact, the static dispatcher is there more or less for historic reasons only.

**Comment by SetoKaiba** [comment]
I mean it the dynamic dispatcher is the only choice for utils project to compile. A cleanup with static dispatcher code would be great.
So, for now, I still create a PR for the utils project to compile without problem without the macro.
https://github.com/KhronosGroup/Vulkan-Hpp/pull/1380

**Comment by SetoKaiba** [comment]
I see that you make a minor cleanup to remove that helper function. I'll close this issue now.

**Comment by asuessenbach** [comment]
I took the other way: simply removing that function from utils.cpp should help here too (-> #1379 )
