### ISSUE TITLE
Are we missing VK_SUBPASS_EXTERNAL / Add support for hardcoded API constants

### ISSUE THREAD

**Issue by ioquatix** [KhronosGroup/Vulkan-Hpp#138]
The function 

```
SubpassDependency& setSrcSubpass( uint32_t srcSubpass_ )
```

can receive `VK_SUBPASS_EXTERNAL` but this is not defined in `vulkan.hpp`:

https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSubpassDependency.html

Is this deliberate or is it missing?

**Comment by UPS7kYkHEPbZIucaqjje** [comment]
https://www.reddit.com/r/vulkan/comments/6u61bp/no_definition_for_vk_subpass_external_in_vulkanhpp/

**Comment by mtavenrath** [comment]
Vulkan-Hpp is missing Vulkans hardcoded constants found in the 'API Constants' enum in the Vulkan registry. We'll try to add them soon.

**Comment by asuessenbach** [comment]
We will not add those constants to the vulkan.hpp, as you don't get anything from it. You can just use the constants from vulkan.h.
