### ISSUE TITLE
Ability to disable `destroy` function overloads.

### ISSUE THREAD

**Issue by Cyphall** [KhronosGroup/Vulkan-Hpp#1383]
The issue #166 and PR #180 added overloads in the form of `X.destroy(Y)`.

These overloads make the `destroy` name confusing since it can act either as a normal method or as a destructor, depending on the arguments:
```cpp
device.destroy(commandPool); // Uses the device to destroy the command pool. Legal.
device.destroy(buffer); // Uses the device to destroy the buffer. Legal.
device.destroy(); // Uses the device to destroy ...itself?
device.destroy(image); // Uses the device to destroy the image. Crash, the device was freed.
```

Another problem is that we now have two functions to do the same thing:
`device.destroy(other_object)` and `device.destroyOtherObject(other_object)`.

With these two problems in mind, I would like to disable the `device.destroy(other_object)` form to only have `device.destroy()` as a destructor.

Could we have a define to disable these?

**Comment by asuessenbach** [comment]
I'm sorry, but I don't see a problem with having two functions (`destroy` and `destroyOtherObject`) providing the same functionality.
Having the general `destroy` might be simpler to use with template programming. The actual type to destroy is automatically detected by the argument.

**Comment by Cyphall** [comment]
My main issue is that the method name "destroy" is used both as a destructor for the underlying `VkDevice` (parameterless version) and as a standard method doing some stuff with the instance (in this case, freeing some resource handled by the device) (versions with parameters).
IMO these two behaviors are conceptually very different and should be clearly separated by their name.

**Comment by asuessenbach** [comment]
As long as there is no stronger demand for this change, I will not resolve it.
Closing it for now.
