### ISSUE TITLE
std::format usage breaks compilation with clang versions prior to 14 using C++20

### ISSUE THREAD

**Issue by bangnoise** [KhronosGroup/Vulkan-Hpp#1394]
Clang versions prior to 14 have missing support for std::format. Unfortunately they do have an effectively empty `<format>` header, so the test at lines 13 and 3006 of vulkan_to_string.hpp is satisfied, but causes a build error: No member named 'format' in namespace 'std'.

This affects the current release version of Xcode, which ships with clang 13.

Possibly a specific check for clang 14+ is required before use of std::format?

**Comment by theHamsta** [comment]
Can you test whether https://github.com/KhronosGroup/Vulkan-Hpp/pull/1396 would work?

**Comment by bangnoise** [comment]
Thanks for the quick response - the change in #1396 works.

**Comment by theHamsta** [comment]
At the moment, MSVC seems to be the only implementation with `std::format` and the feature test macro defined: https://godbolt.org/z/bsbjrvKsn (with c++20
