### ISSUE TITLE
Make good examples

### ISSUE THREAD

**Issue by root-k1d** [KhronosGroup/Vulkan-Hpp#1401]
Please make at least one example where the cube rotates, and does not appear and disappear in a second. Need to show how to work correctly not with one frame, but with a stream of frames. Show how to work with an array of fences and an array of semaphores, etc. You gave me candy and took it away in a second

**Comment by asuessenbach** [comment]
The examples in this repository are intentionally on a very fundamental level.
The things you're asking for would need some more complex framework. Such samples can be found at https://github.com/khronosGroup/Vulkan-samples, for example. Some of the samples there are also using vulkan.hpp.
