### ISSUE TITLE
FYI we added a 'stride' attribute to XML schema

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1403]
In 1.3.227 we added a 'stride' attribute for <param> tags. It raises warnings from VulkanHppGenerator but appears benign.

**Comment by asuessenbach** [comment]
In fact, that 'stride' attribute has an impact on vulkan.hpp!
As vulkan.hpp provides an "enhanced" interface on functions taking an array of data by, well, taking an array of data, not just a count and a pointer, the array of data is supposed to be packed tightly.
That is, for that flavour of those functions, I need to filter the 'stride' argument, and handle it internally. I assume, providing a stride value of 0 means, the elements are packed tightly? Or would I need to use sizeof(that_argument_type)?

**Comment by oddhack** [comment]
The registry schema document describes this - TL;DR if there is no stride attribute, the elements are assumed to be tightly packed. If there is a stride attribute, it's the name of the command parameter containing the stride. I think they might need to generalize the stride in the future to refer to other places the stride might be found, but that's for the future.
