### ISSUE TITLE
std::find getting used without including algorithm

### ISSUE THREAD

**Issue by jagoly** [KhronosGroup/Vulkan-Hpp#1405]
After updating to the latest version of vulkan-hpp, my project no longer builds because https://github.com/KhronosGroup/Vulkan-Hpp/blob/776dc7db49516b5a8b025de32a3b8550b591b21b/vulkan/vulkan.hpp#L6206 can't use std::find since algorithm hasn't been included due to me having defined VULKAN_HPP_NO_SMART_HANDLE. Either the inclusion of algorithm should be unconditional, or std::find should not be used.

**Comment by asuessenbach** [comment]
Thanks for spotting this issue.
Will be fixed asap!
