### ISSUE TITLE
`vk::raii::SwapchainKHR::getImages()` returns `std::vector<VkImage>`

### ISSUE THREAD

**Issue by jnhyatt** [KhronosGroup/Vulkan-Hpp#1412]
In the Vulkan RAII paradigm, I'd expect `vk::raii::SwapchainKHR::getImages()` to return `std::vector<vk::Image>` (Vulkan-Hpp namespaced VkImage handle type) rather than the raw `VkImage`. Indeed, when I replace my call with `(*device).getSwapchainImagesKHR(*swapchain)`, I find that this function does indeed return a `std::vector<vk::Image>`. In the sample code, this often results in `static_cast<vk::Image>( image )` being inserted wherever a swapchain is used. Is this considered a breaking change that cannot be implemented? Or is there a reason for the apparent inconsistency?

**Comment by asuessenbach** [comment]
Indeed, that's an inconsistency. Will be fixed right now.
In fact, fixing that removed some special handlings!
So thanks for spotting this issue.
