### ISSUE TITLE
vulkan validation layer tracking for memory leaks not working

### ISSUE THREAD

**Issue by jmoguill** [KhronosGroup/Vulkan-Hpp#1421]
Hi,
it seems that tracking for memory leaks doesn't work with Vulkan-Hpp?

Using vulkan configurator, I enabled "Object Lifetime" under "Validation Settings".
I tried commenting out "instance.destroy" and device.destroy in the vulkan samples in vulkan-hpp, but the validation layer doesn't report any memory leaks?

**Comment by asuessenbach** [comment]
I'm sorry, I can't repro this issue.
On what platform are you running your test? What version of the Vulkan Configurator are you using? Which Vulkan SDK version?
Which sample did you try?

**Comment by jmoguill** [comment]
Hi Andreas,
does the Vulkan validation layer report an unreleased object if you don't delete it?  Please share the log output...
I'm 99% sure this is an issue with the vulkan validation layer, not with the vulkan C++ bindings...
The d3d12 debug layer by contrast reports an error if an object is unreleased (it has a "live object" tracker).
I'm on Windows 10, 20H2, vulkan configurator version 2.5, vulkan sdk version 1.3.224.1.  
Regarding which sample: I tried with both the Sacha Willems example (hello triangle), and with one of the vulkan.hpp samples...

**Comment by asuessenbach** [comment]
After a closer look: it seems you don't get any validation messages, if you miss to destroy the instance. If you miss to destroy anything else but the instance, you should get a message.
And, you're right, that's completely independent of Vulkan-Hpp, it also happens with pure vanilla vulkan.
For example, when I don't destroy the device, I get this:
```
UNASSIGNED-ObjectTracker-ObjectLeak(ERROR / SPEC): msgNum: 699204130 - Validation Error: [ UNASSIGNED-ObjectTracker-ObjectLeak ] Object 0: handle = 0x187563b6290, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x29ad0222 | OBJ ERROR : VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT object VkDevice 0x187563b6290[] has not been destroyed.
    Objects: 1
        [0] 0x187563b6290, type: 3, name: NULL
```

**Comment by jmoguill** [comment]
Thanks, you're right, now I see the messages...

`Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x1b02e047a70, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xd5b26f0000000010, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x1b02e047a70[], VkFence 0xd5b26f0000000010[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device`
