### ISSUE TITLE
Compilation errors on MinGW with VULKAN_HPP_NO_SMART_HANDLE

### ISSUE THREAD

**Issue by GPUCode** [KhronosGroup/Vulkan-Hpp#1428]
**Is this issue appropriate for the repository?**

Vulkan-Headers exists as a publishing mechanism for headers and related material sourced from multiple other repositories. If you have a problem with that material, it should *not* be reported here, but in the appropriate repository:

- https://github.com/KhronosGroup/Vulkan-Docs - C headers, XML, validusage.json, and generation scripts
-  https://github.com/KhronosGroup/Vulkan-Hpp - C++ headers
- This repository - Repository structure, management, and build system *only*

See the repository README for more details.

**Describe the bug**
When VULKAN_HPP_NO_SMART_HANDLE is defined the algorithm header is not included which leads to compilation errors due to the usage of std::find in resultCheck

**Expected behavior**
Successful compilation with MinGW

**Screenshots**
![image](https://user-images.githubusercontent.com/47210458/196239229-935b32f0-54ed-4c8b-8781-a7b5872d398b.png)
![image](https://user-images.githubusercontent.com/47210458/196239085-b540326e-ceab-4504-895f-fd71e62c6bb6.png)

**Additional context**

**Comment by asuessenbach** [comment]
This is already resolved with release 1.3.228 (https://github.com/KhronosGroup/Vulkan-Hpp/releases/tag/v1.3.228).

**Comment by GPUCode** [comment]
Thanks for the respone, I'll update my headers in this case
