### ISSUE TITLE
vk::ExternalSemaphorePropertiesKHR lacks ctors

### ISSUE THREAD

**Issue by ddungum** [KhronosGroup/Vulkan-Hpp#143]
Generated vk::ExternalSemaphorePropertiesKHR declaration doesn't have any constructors, so its private member variable 'sType' is not properly initialized.

If such a vk::ExternalSemaphorePropertiesKHR instance is passed in to vk::PhysicalDevice::getExternalSemaphorePropertiesKHR(), it causes validation error like the following : 
> vkGetPhysicalDeviceExternalSemaphorePropertiesKHR: parameter pExternalSemaphoreProperties->sType must be VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES_KHR. The spec valid usage text states 'sType must be VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES_KHR' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkExternalSemaphorePropertiesKHR-sType-sType)

Cheers.

**Comment by mtavenrath** [comment]
Up to now Vulkan-Hpp does not create constructors for structs which are only used as return structs in Vulkan. A closer look revealed that we have to create the copy constructors and initialize sType/pNext for those structs.

I have a pending change to fix the issue. Unfortunately I ran into a minor spec issue which has to be fixed first before I can submit the change.

**Comment by mtavenrath** [comment]
The latest version of Vulkan-Hpp now creates constructors which initialize sType/pNext for readonly structs. Closing.
