### ISSUE TITLE
Pointer `len` not accepted in structs

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Hpp#1430]
In [a WIP MR](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/3997), a struct is added where a count + an array of things are returned (similar to `vkEnumeratePhysicalDevices`). However, VulkanHppGenerator does not accept the idiomatic `optional="false,true"` set on the count, and `len="pFooCount"` on the pointer. It fails with the following message:

```
member attribute <len> references a member of unexpected type <uint32_t *>
```

**Comment by asuessenbach** [comment]
@ShabbyX By the way, that MR also contains one dangerous change and one typo:
- The function `vkGetPhysicalDeviceSurfaceCapabilities2KHR` got a second successcode, `VK_INCOMPLETE`. This changes the logic behaviour of that function, as everybody would need to check for that return value as well. For vulkan.hpp, it even changes the return type for that function! Is that change really needed?
- Typo in line 18171: `extents` should be `extends`

**Comment by oddhack** [comment]
> Thanks for the feedback. I was hesitant about that too, but there doesn't seem to be a way to say "this return value can only happen with this extension", right?

We don't have any way to do that right now although I think XR might have some functionality like this I haven't backported yet. I don't think it would help the situation, though - having the return type dependent on whether or not an extension is supported sounds terrible for both Vulkan-Hpp implementers and users. OTOH, that's not exactly Vulkan's problem.

**Comment by ShabbyX** [comment]
> For vulkan.hpp, it even changes the return type for that function!

@asuessenbach can you tell me exactly how the return type changes? I see `enumerateInstanceExtensionProperties` and `PhysicalDevice::enumerateDeviceExtensionProperties` currently returns `Result`, and so does `PhysicalDevice::getSurfaceCapabilities2EXT`. What is the return type changing to? And why aren't the return types of the other enumerate functions that?

**Comment by ShabbyX** [comment]
Thanks for the explanation

> That said, the alternative would be to introduce an explicit enumerating function for each of your "enumerating structures".

Two alternatives actually; one is that, which is easy, the other is to introduce `vkGetPhysicalDeviceSurfaceCapabilities3KHR` which is annoying, but future proof

**Comment by asuessenbach** [comment]
> the other is to introduce `vkGetPhysicalDeviceSurfaceCapabilities3KHR`

When you introduce such a new function, that should accept your new "enumerating structures", the "old" `vkGetPhysicalDeviceSurfaceCapabilities2KHR` should probably not accept them.
That is, you would also need to introduce `VkSurfaceCapabilities3KHR` as an alias of `VkSurfaceCapabilities2KHR`, and likewise with all the structures extending `VkSurfaceCapabilities2KHR`, wouldn't you?
After all, that "enumerating structures" approach seems to be a bit weird. Even though it's just-another-level-of-indirection™, it seems to be new to the vulkan API.

**Comment by ShabbyX** [comment]
> you would also need to introduce VkSurfaceCapabilities3KHR

No not necessarily. I can just add a VU to `vkGetPhysicalDeviceSurfaceCapabilities2KHR` that says the pNext chain shouldn't include this new struct. `vkGetPhysicalDeviceSurfaceCapabilities3KHR` could take `VkSurfaceCapabilities2KHR`, but just not have this restriction.

**Comment by cubanismo** [comment]
I'm a bit worried about the limitations this places on the spec in general. I view this as a design flaw in the HPP wrapper. Extensions in general should be able to add return codes to existing functions, and we have in many cases. Extensions sometimes in fact introduce brand new return codes just for this purpose. It's unfortunate if that can't include success codes, or certain types of success codes, and we end up with seemingly pointless C API bloat to placate downstream wrappers.

**Comment by asuessenbach** [comment]
> I can just add a VU to vkGetPhysicalDeviceSurfaceCapabilities2KHR that says the pNext chain shouldn't include this new struct. vkGetPhysicalDeviceSurfaceCapabilities3KHR could take VkSurfaceCapabilities2KHR, but just not have this restriction.

Sounds a bit hairy... I would wonder if all downstream processes could handle such a special case.

> I view this as a design flaw in the HPP wrapper.

I view this as a design feature of the HPP wrapper. And in my experience, the vulkan API is pretty stable. I think, a change like that happened just once before with adding `VK_PIPELINE_COMPILE_REQUIRED_EXT` to the `vkCreate*Pipelines functions`.
That is, it happened before, and will happen again. All I'm asking is to be really sure, this is the way to go in this specific case. After all, adding a layer of indirection by introducing such "enumerating structures" is kind of new to the vulkan API.

**Comment by cubanismo** [comment]
> I view this as a design feature of the HPP wrapper.

Considering something that restricts extensibility a positive is an odd view to champion. Every time we've made a decision to restrict or omit flexibility in something in Vulkan, it's come back to haunt us.

**Comment by cubanismo** [comment]
This just came up yet again in the exact same extension development. It's not limited to INCOMPLETE, we have other success codes as well, in this case VK_SUBOPTIMAL_KHR, which we'd like to add to vkCreateSwapchainKHR. I'm reopening this issue, as there are others in the SI group at this point that feel it's inappropriate for HPP to constrict spec development in this way.

**Comment by chadversary** [comment]
> After all, adding a level of indirection by introducing such "enumerating structures" is kind of new to the vulkan API.

No it's not. An enumerating structure has already existed in the Vulkan API for 4 years, since v1.1.88 (Oct 2018). And Vulkan-HPP handles it incorrectly. The existing structure is `VkDrmFormatModifierPropertiesListEXT` with enumerating inout member `drmFormatModifierCount`.

Since we already have precedent for an enumerating structure, the SI group will move forward with adding the new enumerating structure, `VkSurfacePresentModeCompatibilityKHR`.

However, the issue with the new return code is a separate decision and merits more discussion.

**Comment by chadversary** [comment]
Some more background on the existing enumerating struct.

`VkDrmFormatModifierPropertiesListEXT::drmFormatModifierCount` is a `uint32_t`, not `uint32_t*`. That's why the vulkan-hpp generators did not fail when the struct was added. I chose to declare it as a non-pointer member because the struct is already an output struct, thus the extra level of pointer-indirection was unnecessary.

**Comment by asuessenbach** [comment]
> No it's not. An enumerating structure has already existed in the Vulkan API for 4 years, since v1.1.88 (Oct 2018). And Vulkan-HPP handles it incorrectly. The existing structure is VkDrmFormatModifierPropertiesListEXT with enumerating inout member drmFormatModifierCount.

Thanks for pointing that out, I was not aware of it.
Interestingly, the function where that structure is used, `vkGetPhysicalDeviceFormatProperties2`, is a void function. That is, VK_INCOMPLETE is not necessarily needed in all enumerating situations?

**Comment by chadversary** [comment]
> I think, a change like that happened just once before with adding VK_PIPELINE_COMPILE_REQUIRED_EXT to the vkCreate*Pipelines functions.

How did the hpp headers accommodate that change?

As James said, the SI group is considering adding `VK_SUBOPTIMAL_KHR` (a success code) to the list of return codes for `vkCreateSwapchainKHR`.

The SI group is still internally debating if `VK_INCOMPLETE` is desired.

**Comment by asuessenbach** [comment]
> How did the hpp headers accommodate that change?

Well, the return type of those functions just changed. It was a hiccup to all sources, but it seemed to be resolved by the users of vulkan.hpp.
But, of course, such hiccups should not happen too often!!

How did `vkGetPhysicalDeviceFormatProperties2` get away with such an enumerating struct without the need of a special success code?

**Comment by chadversary** [comment]
The SI group decided to not return `VK_INCOMPLETE` to `vkGetPhysicalDeviceSurfaceCapabilities2KHR`.  And, regarding the original issue in this issue, the problematic `uint32_t *len`, it is fixed now. We changed it to non-pointer `uint32_t len`.

However, we may still add new return codes to `vkCreateSwapchainKHR`, such as `VK_SUBOPTIMAL`.
