### ISSUE TITLE
`Flags<BitType>::operator~` does not compile

### ISSUE THREAD

**Issue by glebov-andrey** [KhronosGroup/Vulkan-Hpp#1437]
The implementation of the operator tries to XOR `BitType` with `FlagTraits::allFlags`, which since [this change](https://github.com/KhronosGroup/Vulkan-Hpp/commit/4bf02b2588f97772cd54e86248b9768dbe2a2d58) is `Flags<BitType>` instead of just `BitType`:
https://github.com/KhronosGroup/Vulkan-Hpp/blob/37b03e1210a31092129901c2b537e2db4ba1975a/snippets/Flags.hpp#L85-L88
https://github.com/KhronosGroup/Vulkan-Hpp/blob/37b03e1210a31092129901c2b537e2db4ba1975a/VulkanHppGenerator.cpp#L2131-L2137

As a result we get errors like:
```
error: invalid operands to binary expression ('const vk::Flags<vk::PipelineStageFlagBits>::MaskType' (aka 'const unsigned int') and 'const vk::PipelineStageFlags' (aka 'const Flags<vk::PipelineStageFlagBits>'))
```

The simplest fix would seem to be to add `allFlags.m_mask`.

**Comment by asuessenbach** [comment]
Thanks a lot for spotting this issue!
Will be fixed right now.
