### ISSUE TITLE
Unclear logic regarding defines

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#1441]
It seems [this condition](https://github.com/KhronosGroup/Vulkan-Hpp/blob/dcc1d9562f179f7e918ecbb63cfe5350543d8620/vulkan/vulkan.hpp#L13125) should be inverted. I tried to walk through `git blame`, `git checkout commit~` and reached the times when `vulkan/vulkan.hpp` was added to the repo (once again I see) in commit a6ad0f1e. Therefore the source of decision that led to the current state I cannot find easily.

**Comment by tomilov** [comment]
Or maybe that condition should be even removed completely? What is rationale behind it?

**Comment by tomilov** [comment]
> This condition dates back to #328! Do you think, this has been changed and need to be adjusted?

At that time that preprocessor guards [had sense](https://github.com/KhronosGroup/Vulkan-Hpp/pull/328/files#diff-4a1d477d7c7af1de6c5903aa7dbe6ffce387f9fa44a845da942be43016db6358R55360). So, yes, this need to be adjusted.
Currently it is hard to get such a conditions (i.e. values of `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC` and `VK_NO_PROTOTYPES`), that results in enabled that overloadings of `init` function.

Also I would prefer to not use `ifdef`, `ifndef` and `defined()` and others. At least it would be better to stick with single approach, not both `#if !VK_NO_PROTOTYPES` and `#if !defined(VK_NO_PROTOTYPES)`. Also it is not good practice to do:
```
#if !defined( VULKAN_HPP_DISPATCH_LOADER_DYNAMIC )
#  if defined( VK_NO_PROTOTYPES )
#    define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
```
One can configure imported library:
```
add_library("VulkanHeaders" INTERFACE)
target_include_directories(
    "VulkanHeaders"
    SYSTEM INTERFACE
        "${CMAKE_CURRENT_SOURCE_DIR}/Vulkan-Headers/include")
target_compile_definitions(
    "VulkanHeaders"
    INTERFACE
        VK_NO_PROTOTYPES
    )
```
and then rely on the fact, that `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC` is not defined, because it is external setting. But after `#include <vulkan/vulkan.hpp>` it become defined.

**Comment by asuessenbach** [comment]
You're right, that condition is outdated. Will remove it.
