### ISSUE TITLE
Conversion from C++ to C handles doesn't work in VS2017

### ISSUE THREAD

**Issue by msc-** [KhronosGroup/Vulkan-Hpp#145]
Code such as

```
vkDestroyImage(vkctx.device, vkctx.depthBuffer.image, nullptr);
```

where `vkctx.device` is a `vk::Device` and `vkctx.depthBuffer.image` is a VkImage, gets errors such as:

``` 
Error	C2664	'void vkDestroyImage(VkDevice,VkImage,const VkAllocationCallbacks *)': cannot convert argument 1 from 'vk::Device' to 'VkDevice'
````

This code compiles fine with all other compilers I have used including VS2015, clang and gcc.

I have this mixed code because I am in the process of converting the code from the C API to the `vulkan.hpp` C++ API. I thought that vulkan.hpp was supposed to provide conversions from vk:: handles to the Vk equivalents.

I'm using version 1.0.65 of the Vulkan SDK.

**Comment by Xottab-DUTY** [comment]
I don't know why it compiles in other compilers, but can't compile in VS2017, but I believe that you should use type casting
`vkDestroyImage(static_cast<VkDevice>(vkctx.device), vkctx.depthBuffer.image, nullptr);`

**Comment by msc-** [comment]
Yes, the cast fixes the compile error but
- as you ask, why does it work in other compilers?
- why doesn't vulkan.hpp provide the conversions?
    - Because it worked in earlier compilers without them?
    - Is it a deliberate omission?

**Comment by mtavenrath** [comment]
@msc Did you create a 32-bit solution when using VS 2017? On 32-bit platforms all Vulkan handles have the same integral type uint64_t and thus cannot be differentiated by the compiler. To avoid accidental conversion between a Vulkan handle and an integral type we decided to require explicit casts on those platforms. If you know what you're doing to can define VULKAN_HPP_TYPESAFE_CONVERSION on 32-bit platforms to get implicit conversions at your own risk. I recommend to use this flag only if you're developing on a 64-bit platform, but also need a 32-bit platform.

**Comment by mtavenrath** [comment]
Closing as this is most likely a configuration issue and there's no further feedback.

@msc- Please reopen in case you can reproduce the issue on a 64-bit compiler.

**Comment by msc-** [comment]
Sorry for the long delay responding.  I had to focus on other things.

Indeed this was cockpit error. I was inadvertently trying to build the 32-bit configuration. That seems to be the default, still, in vs2017 when the solution contains multiple platform support.

I will try VULKAN_HPP_TYPESAFE_CONVERSION in the 32-bit config.
