### ISSUE TITLE
VS2013 not supported - can this be worked around or fixed?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-Hpp#146]
I see from issue #126 and LVL issue https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2188 that it is known that VS2013 compatibility was broken by adding constexpr and that the decision was simply to require VS2015.

In my opinion, a better resolution would have been to fix VS2013 support.  Can VS 2013 support be restored?  It is still in common use and every other Vulkan related project we rely on such as glslang, spirv-tools, and LVL (before this change) were all working with VS 2013.

**Comment by mtavenrath** [comment]
@danginsburg We did not have any information about how widely VS2013 is used with Vulkan-Hpp and assumed that people hopefully use one of the latest two MSVC compilers.

The easy fix for VS2013 would be to add #ifdefs around the code pieces which ensure that structure pointer chains are valid and remove this feature.

A more complex fix I have in mind is replacing 

```template <typename X, typename Y> constexpr bool isStructureChainValid() { return false; }```

by a class with an enum of value 0 or 1 and do a static assert on the enum.

**Comment by danginsburg** [comment]
Unfortunately, game developers are often stuck on old versions of Visual Studio for a long time.  Rebuilding all dependencies of a project can be a major undertaking when that is required.  We still have some projects using VS 2013 for that reason.  

I'm pretty agnostic about how it's fixed, I'd just like to see VS 2013 support restored.  I think it's especially important given that vulkan.hpp is relied upon at a low level for many projects.  Thanks.

**Comment by nsubtil** [comment]
FWIW, my vote would be for whatever fix is simplest, which in this case could be #ifdef'ing out the functionality that relies on constexpr.

I do agree with @danginsburg that supporting VS2013 is useful, but I wouldn't necessarily add complexity to do so.

**Comment by mtavenrath** [comment]
@danginsburg I replaced the constexpr by an enum in a template so that Vulkan-Hpp now compiles using VS 2013. Closing.
