### ISSUE TITLE
Bad handling of type tag with name attribute, rather than name tag

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1462]
See internal MR 5593 for details but the gist is that we are trying to use an empty <type> tag of form

> \<type category="funcpointer" name="PFN_vkGetInstanceProcAddr">\</type>

to replace the explicit (re)definition introduced by the LUNARG extension in the latest spec update. Unfortunately, this causes the following error from the hpp-generate CI step:

> VulkanHppGenerator: Spec warning on line 905: unknown attribute <name>!  
> caught exception: VulkanHppGenerator: Spec error on line 905: missing required element <name>

Note that this has always been legal XML syntax, although accepting it may lead to another problem with Vulkan-Hpp, since there is then no *explicit* definition of the PFN type available - the PFN is just emitted along with the vkGetInstanceProcAddr prototype in the C headers. This is a new use case we haven't encountered before, all the other PFN types in the XML are explicit callbacks.

**Comment by oddhack** [comment]
FYI - we are in process of abandoning internal MR 5593 in preference to 5596, which introduces a new type for the PFN. So the fix in #1463, while still appropriate, isn't immediately required. Would appreciate feedback on internal MR 5596 however.

**Comment by asuessenbach** [comment]
That is, #1463 isn't needed at all? I'll close it then. It would just introduce unneeded complexity.
Besides that, I think, using an attribute for something like "name" seems to be more appropriate to me than a tag name (or an element). After all, there's supposed to be exactly one "name" per thing, and that name should probably not contain any other information. But, of course, that should be the standard, not the exception. Just my opinion.
Just replacing <PFN_vkGetInstanceProcAddr> by <PFN_vkGetInstanceProcAddrLUNARG> would seamlessly work with the generator, but would break all code that's explicitly using <PFN_vkGetInstanceProcAddr>!

**Comment by oddhack** [comment]
> That is, #1463 isn't needed at all? I'll close it then. It would just introduce unneeded complexity. Besides that, I think, using an attribute for something like "name" seems to be more appropriate to me than a tag name (or an element). After all, there's supposed to be exactly one "name" per thing, and that name should probably not contain any other information. But, of course, that should be the standard, not the exception. Just my opinion. 

It may be needed in the future, because this is part of the schema. In general we use \<name> tags because the name has to be part of the tag content in any event, and having e.g. \<type name="VkFoo">...typedef void VkFoo;\</type> is redundant and error-prone - but there are occasional cases where a tag needs a name, so it can be used as a dependency, but the name isn't needed in the tag content (usually something like external header dependencies which define types).

> Just replacing <PFN_vkGetInstanceProcAddr> by <PFN_vkGetInstanceProcAddrLUNARG> would seamlessly work with the generator, but would break all code that's explicitly using <PFN_vkGetInstanceProcAddr>!

That is in fact what we did, but I don't think it's going to break anything given the very specialized use of this extension - the extension author signed off on it.
