### ISSUE TITLE
ArrayProxy requires manual const typename after update

### ISSUE THREAD

**Issue by exuvo** [KhronosGroup/Vulkan-Hpp#1483]
I just updated from 1.3.227 to 1.3.235 and i now seem to require to specify a const typename for ArrayProxy where before it was automatic.

This used to compile for me:
```
struct TestPushConstants {
  Vector2f scale = {};
};
...

const TestPushConstants constants = { .scale = { 2.0f / renderTarget.extent.width, 2.0f / renderTarget.extent.height } };
commands.pushConstants(pipelineLayout, vk::ShaderStageFlagBits::eVertex, 0, vk::ArrayProxy(constants));
```
```
/usr/include/vulkan/vulkan_handles.hpp:3819:10: note: candidate: ‘template<class ValuesType, class Dispatch> void vk::CommandBuffer::pushConstants(vk::PipelineLayout, vk::ShaderStageFlags, uint32_t, const vk::ArrayProxy<const DataType>&, const Dispatch&) const’
/usr/include/vulkan/vulkan_handles.hpp:3819:10: note:   template argument deduction/substitution failed:
/home/exuvo/code/Aurora-C/src/ui/vulkan/shaders/TestShader.cpp:79:31: note:   types ‘const DataType’ and ‘TestPushConstants’ have incompatible cv-qualifiers
```

Now i need to add `<const TestPushConstants>` to the vk::ArrayProxy(constants) for it to compile, is this intended behavior or did i fuck something up when i updated?
```
const TestPushConstants constants = { .scale = { 2.0f / renderTarget.extent.width, 2.0f / renderTarget.extent.height } };
commands.pushConstants(pipelineLayout, vk::ShaderStageFlagBits::eVertex, 0, vk::ArrayProxy<const TestPushConstants>(constants));
```

I am using gcc 12.2.1 on arch linux.

**Comment by asuessenbach** [comment]
I'm sorry, but I can't repro the old behaviour with 1.3.227 (on MSVC at least, the platform I'm working on). It always would need the explicit template argument list.
But it should just work without explicitly using the vk::ArrayProxy at all, like this:
`commands.pushConstants(pipelineLayout, vk::ShaderStageFlagBits::eVertex, 0, constants);`
Would you please check if that works on your end as well?

**Comment by exuvo** [comment]
No that gives
```
/usr/include/vulkan/vulkan_handles.hpp:3819:10: note:   template argument deduction/substitution failed:
/home/exuvo/code/Aurora-C/src/ui/vulkan/shaders/TestShader.cpp:79:31: note:   ‘const TestPushConstants’ is not derived from ‘const vk::ArrayProxy<const DataType>’
```
Which i think is the error i got when i started a year ago and is why i used explicit vk::ArrayProxy.

Reverting to 1.3.227 my `ArrayProxy(constants)` works.
Looking at this closer the offending line seems to be the const on line 600(v235) / 577(v227) in vulkan.hpp:
`ArrayProxy( T const & value ) VULKAN_HPP_NOEXCEPT`
that const does not exist in v227 and my code compiles with v235 if i remove that const.
The commit that changed that is https://github.com/KhronosGroup/Vulkan-Hpp/commit/34725b31
It also compiles if i remove the const from `ArrayProxy<const ValuesType>` in vulkan_functs.hpp and vulkan_handles.hpp for CommandBuffer::pushConstants.
Neither allows me to use a bare `constants` though.

But it does look correct to me so i assume it is GCC that is not being smart enough here.

**Comment by asuessenbach** [comment]
Hm... Does the [PushConstants sample](https://github.com/KhronosGroup/Vulkan-Hpp/tree/main/samples/PushConstants) compile on your end?

**Comment by exuvo** [comment]
Yes i just downloaded master and built all tests with `CXX=g++ cmake -DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON -DSAMPLES_BUILD=ON -DTESTS_BUILD_WITH_LOCAL_VULKAN_HPP=ON -DTESTS_BUILD=ON -B build -G ninja` and compiled, PushConstants runs fine, a green cube shows.
I also checked out 1.3.235 and built with LOCAL_VULKAN=OFF which also worked fine.

But that sample uses `std::array<unsigned, 2> pushConstants` which uses the .data() constructor of ArrayProxy which also works in my code as i have that usage in a few places too.

**Comment by exuvo** [comment]
Sorry wrong conclusiong, the test has .pushConstants<unsigned> otherwise it errors too.

**Comment by asuessenbach** [comment]
Ah, yes! I've overlooked that you don't had the templated type specified at the command.
Great that it works now!

**Comment by exuvo** [comment]
Ah so i have been using it a bit wrong all this time then.
