### ISSUE TITLE
FYI - we will be making use of 'api' attribute in Vulkan XML, you will need a small change

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1485]
This has been part of the schema for a while, but we will start using it soon to allow combining the Vulkan and Vulkan SC XML in a single file. You will need to adapt your loading code to this new use.

The simplest way is to globally pre-filter the XML to remove all tags with explicit 'api' elements not matching the API being generated, as the Vulkan-Docs scripts already do. For this you can either use the scripts/stripAPI.py script that's provided, or do the equivalent

> import reg  
> keepAPI = 'vulkan'
> reg.stripNonmatchingAPIs(tree.getroot(), keepAPI, actuallyDelete=True)

after loading your ElementTree from the XML, where 'reg' is scripts/reg.py from the Vulkan-Docs repository. Although since you are probably doing the loading and parsing in C++, you would have to figure out the equivalent of this Python command. The essence is to recursively traverse the XML tree removing any tags with explicit non-matching 'api' attributes at the point they're encountered, prior to any other XML parsing.

Let me know if there are any questions. There isn't a specific timescale for this, but probably will appear starting sometime in February.

**Comment by asuessenbach** [comment]
I'm not really sure if I understood completely...
Could you please provide a vk.xml where that 'api' attribute is used?

**Comment by oddhack** [comment]
> I'm not really sure if I understood completely... Could you please provide a vk.xml where that 'api' attribute is used?

https://raw.githubusercontent.com/KhronosGroup/VulkanSC-Docs/sc_main/xml/vk.xml

The VKSC XML will be getting merged into the vk.xml in Vulkan-Docs in a few weeks.

**Comment by asuessenbach** [comment]
That is, everything that is marked with `api="vulkansc"` is supposed to be ignored for vulkan.hpp, right?

**Comment by dgkoch** [comment]
> That is, everything that is marked with `api="vulkansc"` is supposed to be ignored for vulkan.hpp, right?

Correct.

**Comment by asuessenbach** [comment]
@oddhack In that vk.xml file you provided, should the definition of VKSC_API_VARIANT in line 157 be
- marked with `api="vulkansc"`, or
- moved to after the definition of `VK_HEADER_VERSION`, or
- exactly as it is?

**Comment by oddhack** [comment]
> @oddhack In that vk.xml file you provided, should the definition of VKSC_API_VARIANT in line 157 be
> 
> * marked with `api="vulkansc"`, or
> * moved to after the definition of `VK_HEADER_VERSION`, or
> * exactly as it is?

It should be OK as it is. The definition is only referenced indirectly from other tags that are themselves "vulkansc" so when generating for the "vulkan" API, it should be ignored. It's possible there's some mis-tagging that we won't detect until we construct the MR to bring the SC content back into the Vulkan repo, but we will detect that at the time - the intent is that the MR not result in semantic changes when generating either a Vulkan or Vulkan SC specification & headers from the combined repository.

**Comment by asuessenbach** [comment]
@oddhack I think with relatively small changes I could adjust the VulkanHppGenerator to either generate vulkan.hpp (and related headers) or some vulkan**sc**.hpp (and related headers), controlled by a command line argument for example.
Do you think there might be some interest in that?

**Comment by oddhack** [comment]
> @oddhack I think with relatively small changes I could adjust the VulkanHppGenerator to either generate vulkan.hpp (and related headers) or some vulkan**sc**.hpp (and related headers), controlled by a command line argument for example. Do you think there might be some interest in that?

Something to ask the SC Working Group - @dgkoch?

**Comment by asuessenbach** [comment]
@dgkoch Well, adjusting the generator seems to be a bit more complex than expected (of course!).
One question I have with the vk.xml provide above (https://raw.githubusercontent.com/KhronosGroup/VulkanSC-Docs/sc_main/xml/vk.xml): the `VK_EXT_debug_report` extension has the attribute `supported="vulkan"`. Yet there are two enum children with attribute `api`, one as `"vulkan"`, the other as `"vulkansc"`.
What is that supposed to mean?

**Comment by dgkoch** [comment]
I supposed technically the vulkansc variant isn't needed, but at the same time, it shouldn't hurt either.

**Comment by asuessenbach** [comment]
Well, I think "it shouldn't hurt either" is not a good way how to handle entries in that document. It would allow to gather garbage that might be difficult to be removed at some time.
Moreover, in that specific case, neither VK_ERROR_VALIDATION_FAILED_EXT, nor VK_ERROR_VALIDATION_FAILED is ever used in that vk.xml. Getting them close to be garbage, I think.
But, after all, some downstream processors like the VulkanHppGenerator might need to handle that, somehow. Here, it means that I have to decide if `vk::Result::eErrorValidationFailedEXT` and/or `vk::Result::eErrorValidationFailed` should be generated or not. And they should be generated if and only if the corresponding defines do exist in the corresponding C-header.

**Comment by dgkoch** [comment]
Can we handle this on the internal issue (https://gitlab.khronos.org/vulkansc/vulkansc/-/issues/181) instead of this closed issue?

**Comment by asuessenbach** [comment]
Ah, sure, you're right. Will post it there as well.
