### ISSUE TITLE
Unresolved external symbol in vk:: but not in vk::raii:: for DebugUtilsMessengerEXT

### ISSUE THREAD

**Issue by Golgovskiy** [KhronosGroup/Vulkan-Hpp#1487]
```
LNK2019	unresolved external symbol vkCreateDebugUtilsMessengerEXT referenced in function "public: enum VkResult __cdecl vk::DispatchLoaderStatic::vkCreateDebugUtilsMessengerEXT(struct VkInstance_T *,struct VkDebugUtilsMessengerCreateInfoEXT const *,struct VkAllocationCallbacks const *,struct VkDebugUtilsMessengerEXT_T * *)const " (?vkCreateDebugUtilsMessengerEXT@DispatchLoaderStatic@vk@@QEBA?AW4VkResult@@PEAUVkInstance_T@@PEBUVkDebugUtilsMessengerCreateInfoEXT@@PEBUVkAllocationCallbacks@@PEAPEAUVkDebugUtilsMessengerEXT_T@@@Z)			

and

LNK2019	unresolved external symbol vkDestroyDebugUtilsMessengerEXT referenced in function "public: void __cdecl vk::DispatchLoaderStatic::vkDestroyDebugUtilsMessengerEXT(struct VkInstance_T *,struct VkDebugUtilsMessengerEXT_T *,struct VkAllocationCallbacks const *)const " (?vkDestroyDebugUtilsMessengerEXT@DispatchLoaderStatic@vk@@QEBAXPEAUVkInstance_T@@PEAUVkDebugUtilsMessengerEXT_T@@PEBUVkAllocationCallbacks@@@Z)	
```
`instance->createDebugUtilsMessengerEXT(createInfo)`
and also 
`instance->destroyDebugUtilsMessengerEXT(debugMessenger)`

If it's vk::raii:: it works, but with vk:: it gives an error.

**Comment by asuessenbach** [comment]
This is correct as long as you use the vk::DispatchLoaderStatic. If you use the vk::DispatchLoaderDynamic instead, there should not be an unresolved external.
To use the vk::DispatchLoaderDynamic by default, you would have to `#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1` and have the macro VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE exactly once in your source code to provide storage for that default dispatcher, as described in the [readme](https://github.com/KhronosGroup/Vulkan-Hpp#extensions--per-device-function-pointers).
If you really want to use the vk::DispatchLoaderStatic, you would have to resolve all extension functions on your own, as shown in the sample [CreateDebugUtilsMessenger](https://github.com/KhronosGroup/Vulkan-Hpp/tree/main/samples/CreateDebugUtilsMessenger).
