### ISSUE TITLE
Use `std::string_view` instead of `ArrayWrapper1D<char, VK_MAX_EXTENSION_NAME_SIZE>` for string-like member variables

### ISSUE THREAD

**Issue by sharadhr** [KhronosGroup/Vulkan-Hpp#1488]
I notice that many of the structs in the `vk::` namespace use `vk::ArrayWrapper1D<char, VK_MAX_EXTENSION_NAME_SIZE>` (which is a derived class of `std::array<T, N>`) for string-like members, such as `vk::LayerProperties::layerName`. 

I propose that [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view) be used instead. 

This makes it straightforward to use by API consumers, who may largely rely on the C++ standard library.

**Comment by asuessenbach** [comment]
When we have a ArrayWrapper1D, the actual memory is supposed to be in exactly that position. Just like it is with a `std::array`.
`std::string_view`, on the other hand, doesn't own the memory of the string, it just holds a pointer and a size. Therefore, we can't use that.

**Comment by sharadhr** [comment]
> doesn't own the memory of the string, it just holds a pointer and a size. Therefore, we can't use that.

Fair enough. In which case, why not simply a `std::string`? Isn't that owning? Is there some (internal) benefit to having the `std::array<char>` semantics over `std::string` semantics that I am missing? 

Secondly... could the memory not be copied from said location? As I understand it, `std::string_view` is widely considered the C++ idiomatic improvement over `char const*`[[1]](https://stackoverflow.com/questions/60015661/why-is-stdstring-view-faster-than-const-char)[[2]](https://stackoverflow.com/questions/2589949/string-literals-where-do-they-go)[[3]](https://www.sandordargo.com/blog/2022/07/13/why_to_use_string_views).

As an addition, I was also thinking about the `char const* const*` parameters in some struct constructors, which are also a bit too C-like, given this is a C++ wrapper library. Perhaps consider *overloaded* constructors to many of the structs where `char const* const*` is replaced with `std::span<std::string_view>` (requires $\mathcal{O}(n) runtime cost to extricate the pointers from each of the strings in the span), or at least `std::span<char const*> (no runtime cost).

For instance:

```C++
vk::InstanceCreateInfo(/*...*/ flags, /*...*/ pApplicationInfo, std::span<char const*> 
                       enabledLayerNames, std::span<char const*> enabledExtensionNames, pNext) 
// notice no 'count' arguments; these are derived from std::span::size()
{
    // ... other initialisers
    uint32_t enabledLayerCount{static_cast<uint32_t>(enabledLayerNames.size())}; 
    std::span<char const*> ppEnabledLayerNames{enabledLayerNames.data()}; 
    // ... 
}
````

**Comment by asuessenbach** [comment]
> why not simply a std::string

That's because the structures from the vk-namespace have to be binary identical to the corresponding C-structures. And a `std::string` is different from just some char array, as it is in those structures.

Regarding `std::span`: What benefit of `std::span` compared to the `vk::ArrayProxyNoTemporarie`s currently used in the second flavour of the struct constructors would you see? I can't see it from the sample you've provided here.

Besides that: I'm always happy about hints on how to improve Vulkan-Hpp!

**Comment by sharadhr** [comment]
> `vk::ArrayProxyNoTemporaries`

Hmm, I didn't notice that. 

From reading through its definition, it looks like it fulfils *precisely* the role performed by [`std::span`](https://en.cppreference.com/w/cpp/container/span) (one-dimensional, C++20), and [`std::mdspan`](https://en.cppreference.com/w/cpp/container/mdspan) (multi-dimensional, C++23), which are 1D and $n$-D generalisations of contiguous sequences of data. 

The advantage of `std::span` over `vk::ArrayProxyNoTemporaries` (that I can see immediately, at least) is that the former generalises the concept of 'spans' to all C++ contiguous-storage iterables, including `std::vector`, `std::array`, and even C-style arrays. To illustrate, `std::span` allows users to call the `vk::InstanceCreateInfo` constructor with something like:

```C++
auto extensionCount = 0u;
auto extensions = glfwGetRequiredExtensions(&extensionCount); 
auto extensionsVec = std::vector<char const*>{extensions, extensions + extensionCount};
auto validationLayers = std::array<char const*, 1>{"VK_LAYER_KHRONOS_validation"};
auto instanceCreateInfo = vk::InstanceCreateInfo{.enabledLayerNames = validationLayers, 
                                                 .enabledExtensions = extensionsVec};  
```

With just 2 parameters, the entire `vk::InstanceCreateInfo` struct is completely initialised; the sizes of the layer and extension names inferred from the `std::span` parameters, and the pointers to the contiguous data extricable with `std::span::data()`. As mentioned above, library consumers are free to use whatever C++ construct they want, as long as it's convertible to `std::span`.

The issue is that `std::span` is C++20-only, and not all compilers are fully compliant yet (sadly). I would think that this could be worked around (similar to `operator<=>`) by adding a feature check to define the constructor:

```C++
#ifdef __cpp_lib_span
vk::InstanceCreateInfo(/*...*/ flags, /*...*/ pApplicationInfo,  
                       std::span<char const*> enabledLayerNames, 
                       std::span<char const*> enabledExtensionNames, 
                       void* pNext) 
{
    // ... other initialisers
    uint32_t enabledLayerCount{static_cast<uint32_t>(enabledLayerNames.size())}; 
    std::span<char const*> enabledLayerNamesSpan{enabledLayerNames};
    // or: char const* const* ppEnabledLayerNames{enabledLayerNames.data()};
    // ... 
}
#endif

**Comment by asuessenbach** [comment]
Yes, adding struct-constructors taking `std::span` instead of `vk::ArrayProxyNoTemporaries` looks like a worthwhile addition.
I'll take some time to investigate.
Thanks for that idea!

**Comment by asuessenbach** [comment]
I just realized that both `vk::ArrayProxy` and `vk::ArrayProxyNoTemporaries` have a constructor that accepts any type with a `.data()` return type implicitly convertible to `T*`, and a `.size()` return type implicitly convertible to `size_t`.
That is, `std::span` can already be used wherever a `vk::ArrayProxy[NoTemporaries]` is expected. So, no need to extend anything here, I think.

**Comment by sharadhr** [comment]
I think I completely missed that constructor since I was using `VULKAN_HPP_NO_CONSTRUCTORS`; interesting.
