### ISSUE TITLE
Device::acquireNextImageKHR doesn't have an exception-throwing version

### ISSUE THREAD

**Issue by lcsondes** [KhronosGroup/Vulkan-Hpp#150]
`VK_HEADER_VERSION ==  65`

`Device::acquireNextImageKHR` comes in two variants, `Result acquireNextImageKHR(..., uint32_t*)` and `ResultValue<uint32_t> acquireNextImageKHR(...)`. Because I have exceptions turned on, I'd expect `ResultValueType<uint32_t>::type acquireNextImageKHR(...)`.

This also affects `getSwapchainCounterEXT` and `acquireNextImage2KHX`.

**Comment by mtavenrath** [comment]
This is by design. acquireNextImage has the following success codes:
```successcodes="VK_SUCCESS,VK_TIMEOUT,VK_NOT_READY,VK_SUBOPTIMAL_KHR"```

The application has to handle those, so we have to return the pair result, uint32_t.
