### ISSUE TITLE
Not handling all 'api' usage in new vk.xml schema updates

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1507]
#1496 doesn't seem to cover all the cases of 'api' usage in the XML schema updates just published in [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/releases/tag/v1.3.241) - the hpp-generate job in gitlab CI is throwing an exception

> caught exception: VulkanHppGenerator: Spec error on line 10217: command \<vkCreateDevice> already specified
98

(this is a case where there are two separate definitions of the \<command> tag).

If you think this is something that could be fixed soon, I'll hold off updating Vulkan-Headers for a few days; otherwise I'll need to push an update without the new .hpp files.

**Comment by asuessenbach** [comment]
That should be fixed by now (#1506).

**Comment by oddhack** [comment]
Thanks! Vulkan-Headers has been updated.
