### ISSUE TITLE
it would be useful for the specific Deleter objects to provide accessors for their bound elements

### ISSUE THREAD

**Issue by ericberdahl** [KhronosGroup/Vulkan-Hpp#151]
Each specific Deleter object binds the resources necessary to delete its associated element. For example, a BufferDelete binds a Device and AllocationCallbacks  necessary to delete a Buffer, and a CommandBufferDeleter binds the Device and CommandPool necessary to delete a CommandBuffer.

It would be useful for BufferDeleter to provide accessors to get the Device and AllocationCallback associated with the BufferDeleter instance, and for the CommandBufferDeleter to get the Device and CommandPool associated with the CommandBufferDeleter instance. Ditto for each specific Deleter class.

The use here is partly introspective (better debugging sanity checking in applications that use UniqueHandles) and partly taking advantage of the resource binding to eliminate additional boilerplate code. For example, if I want to write function that maps the memory inside UniqueDeviceMemory, I could conceivably use the Device bound in the UniqueHandle, which is both more efficient and less error-prone than keeping a Device paired with the UniqueDeviceMemory merely for the purpose of supporting memory mapping and unmapping.

Ditto other use cases in which Vulkan objects share common elements (e.g. Devices, CommandPools, Queues, etc).

**Comment by mtavenrath** [comment]
@ericberdahl We've reworked the UniqueHandle a little bit and added getters for the parent & allocator/pool. Please reopen the issue if you think something is missing.
