### ISSUE TITLE
Consider adding comparison to `nullptr_t` for vk::handles

### ISSUE THREAD

**Issue by swilson007** [KhronosGroup/Vulkan-Hpp#1515]
The handles in vkhpp can be set to `nullptr` through regular assignment, but there isn't support for comparing them to `nullptr`.  Example showing both regular Vulkan and vkhpp: 
```c++
void handlesAndNull() {
    VkDevice vdev;
    vdev = nullptr;
    if (vdev == nullptr) {
        // This worked!
    }

    vk::Device vkdev;
    vkdev = nullptr;
    if (vkdev == nullptr) {  // COMPILE ERROR!
        // This did not work because it didn't compile
    }

    if (vkdev) {  // Convert to bool is supported
        // This worked!
    }
}
```

While the handles do support explicit conversion to bool, from a symmetry standpoint it seems odd to be able to set a variable to `nullptr` but then not be able to immediatly compare it to that value. More importantly, attempts to use generic templates that operate on these handles as well as other values (and other non-vkhpp handles) must factor in these rules which can be challenging and unpleasant.

**Comment by asuessenbach** [comment]
Good idea!
Will add that.

**Comment by swilson007** [comment]
Great! Thanks!

**Comment by swilson007** [comment]
@asuessenbach When I made this original ticket I hadn't yet discovered the `vk::isVulkanHandleType<T>` check. Since I only have one place where I include the vk hpp headers, I went ahead and added this to my code and now I've got what I asked for. 
```c++
#include <vulkan/vulkan.hpp>

namespace VULKAN_HPP_NAMESPACE
{
template <typename T>
typename std::enable_if<vk::isVulkanHandleType<T>::value, bool>::type operator==(const T& v, nullptr_t) { return !v; }
template <typename T>
typename std::enable_if<vk::isVulkanHandleType<T>::value, bool>::type operator==(nullptr_t, const T& v) { return !v; }
template <typename T>
typename std::enable_if<vk::isVulkanHandleType<T>::value, bool>::type operator!=(const T& v, nullptr_t) { return v; }
template <typename T>
typename std::enable_if<vk::isVulkanHandleType<T>::value, bool>::type operator!=(nullptr_t, const T& v) { return v; }
} 
```

These seem to work as hoped and aren't causing any other problems, so no hurry on the feature add! I'll rip mine out in the future when needed. 

Thanks for the foresight of including the `vk::isVulkanHandleType<T>` check!

**Comment by swilson007** [comment]
For sure. Please make sure you test or validate it in some capacity though, it's been working as advertised for me, but it comes with no warrenty  :)
