### ISSUE TITLE
Does any example successfully re-implement "Debugging instance creation and destruction" with Vulkan-Hpp?

### ISSUE THREAD

**Issue by bytesandwich** [KhronosGroup/Vulkan-Hpp#1541]
Is there any example of how to implement `Debugging instance creation and destruction` from https://vulkan-tutorial.com/en/Drawing_a_triangle/Setup/Validation_layers

`samples/CreateDebugUtilsMessenger` works for me to re-implement `Message callback`.

**Comment by asuessenbach** [comment]
There is no explicit sample in this repository showing that, but it is used all over the samples here, slightly hidden in the samples utility functions `vk::su::createInstance` and `vk::su::makeInstanceCreateInfoChain`, located in `samples/utils/utils.hpp`.
For the a `vk::raii::Instance` class, the corresponding function is `vk::raii::su::createInstance` in `RAII_samples/utils/utils.hpp`

**Comment by bytesandwich** [comment]
Would you advise projects building on Vulkan-Hpp to re-use `vk::su::*`? What would you say are the tradeoffs?

**Comment by asuessenbach** [comment]
I would strongly advise to **not** re-use `vk::su::*`!
Those functions there are tailored to the very needs of the samples and may change without prior notice.
But of course, you can use them or some of them as a blueprint for your own code.

**Comment by asuessenbach** [comment]
Closing this issue, assuming it's resolved.
