### ISSUE TITLE
vulkan_raii.hpp - compilation error in ShaderEXT class

### ISSUE THREAD

**Issue by okhmanyuk-ev** [KhronosGroup/Vulkan-Hpp#1557]
class ShaderEXT does not have `m_constructorSuccessCode` field, but some functions trying to access it. It cannot be compiled.

![image](https://user-images.githubusercontent.com/3295141/230743388-e166e851-8890-438d-8d44-3a7cdc92a6d9.png)

**Comment by asuessenbach** [comment]
@okhmanyuk-ev you're right, there was an error with vulkan_raii.hpp.
It's fixed with #1550.
