### ISSUE TITLE
Proposal: Enforce implicit and explicit usage requirements with static assertions and type traits wherever possible

### ISSUE THREAD

**Issue by ethindp** [KhronosGroup/Vulkan-Hpp#1561]
I don't know if this has already been done (I can't find an issue that explicit calls this out), so I thought I'd post one in case it hasn't been done.

This idea stems from the fact that the Vulkan specification is full of tons and tons and tons of usage requirements, where the majority of them could most likely be enforced at compile time. We already have these in some cases with template instantiation and scoped enums, but do we have these with all of the others? For example, section 7.7.1, "Global Memory Barriers," has, under "usage requirements," requirements that could be shifted from validation layers to completely compile-time checks. For some requirements (e.g. Feature enablement), we may need to save some state information as a private member of, e.g., `vk::Device` or `vk::Instance`, but if we could make as many of these checks run at compile-time as is currently feasible with C++20 standard allowances, the validation layers could be reduced to checking only that which is only verifiable at run-time. It would make the Vulkan API a lot safer and harder to misuse, too, since the compiler would be looking out for you.

If this is already being worked on, awesome. I was just posting this here because I'm curious if anyone has considered this. It does look like some of it is being worked on, given the existence of vulkan_static_assert.h, but I thought I'd ask about this anyway. Maybe this idea would be too much, given the (huge) number of extensions and requirements, but it would be a great goal to work towards.

**Comment by asuessenbach** [comment]
That's an interesting idea!
Do you have some specific VUs in mind that could be checked at compile time? In section 7.7.1, for example, I don't see any.
By the way: when some state needs to be added to a class, that would probably not be checked at compile time.
And: extending the vk-classes by some data is not an option, as they have to be binary compatible with the corresponding C-types. One could add data to the vk::raii-classes, though.

**Comment by ethindp** [comment]
@asuessenbach Why do the C headers need to be binary compatible if the data we'd be working with is opaque?
Regardless, even if this only applies to the RAII portion, I invision something like this happening when you -- say -- initialize a `VkInstance`:

1. Copy features and any other properties you might need into private class members of the instance. Where a `VkDevice` is needed (or another class, such as `VkCommandBuffer`), propagate this data to those classes as well.
2. For my example provided in the OP, assume that client software calls [vkCmdPipelineBarrier2](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPipelineBarrier2.html). The valid usage requirements of this function cannot be checked at compile time (at least, not to my knowledge), but the elements of `VkDependencyInfo` can be, I think (depending on how the RAII classes do things). That is, static assertions might look like:
    * `static_assert(sType == VK_STRUCTURE_TYPE_DEPENDENCY_INFO)`
    * `static_assert(pNext == nullptr)`
    * `static_assert((memoryBarrierCount == 0 && pMemoryBarriers == nullptr) || (memoryBarrierCount > 0 && pMemoryBarriers != nullptr))`
    * If `memoryBarrierCount > 0`, then, for each memory barrier `m`:
        1. Assuming that the list of enabled features is stored in `this->enabled_features`, the static asserts might look like:
            * `static_assert(!enabled_features.GeometryShader && !(srcStageMask & VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT))` (VUID-VkMemoryBarrier2-srcStageMask-03929)
            * ETC...

I'm unsure if these requirements could fit into static asserts, and `constexpr if` might be necessary, but this is the basic idea I was thinking about. We may not be able to validate *everything* at compile-time; some checks, like thise for `vkCmdPipelineBarrier2`, require run-time checks. But I feel like the Vulkan spec has a lot of room for compile-time enforcement, which would make it far harder to accidentally mess up the API.

**Comment by asuessenbach** [comment]
> I'm unsure if these requirements could fit into static asserts

And you're right, they don't fit into static asserts. None of them evaluate to a constant and thus would need a runtime-assert.
But that would be done by the validation layer.
If you see any VU, that could really be checked at compile-time, I'd be more than happy to add that check!

Besides that:
> Why do the C headers need to be binary compatible

The vk-handles and vk-structures need to be binary compatible to the C-handles and C-structures, because at some point, each of that data needs to be passed into some C-function. And we definitely don't want to copy stuff around at that point.

**Comment by asuessenbach** [comment]
Closing this, as it seems to be finished. Please reopen if required.
