### ISSUE TITLE
Expose the dispatcher for `UniqueHandle`

### ISSUE THREAD

**Issue by NekkoDroid** [KhronosGroup/Vulkan-Hpp#1568]
Currently `UniqueHandle` require a dispatcher when they are created, so that when they are destroyed they can use that same dispatcher to destroy themselves (together with the handle owner). But unlike the handle owner this is not exposed from the deleter for the `UniqueHandle`.

It would be nice to have access to the dispatcher of a `UniqueHandle` so that you don't need to pass the same dispatcher externally around when invoking functions on that object. That would allow someone to do something like `handle->function(params..., handle.getDispatch())`.

(Theoretically it would be even better to completely omit the final dispatcher, but implementing that would probably be a completely different challenge/expense)

**Comment by NekkoDroid** [comment]
Having looked a bit more at the repo: it looks like `ObjectDestroy`, `ObjectFree` and `ObjectRelease` have a dispatch member that isn't exposed. I think I could send a patch adding them in those locations, but I want to know if those 3 files are the only place it would need to be done or if I may have missed some?

**Comment by asuessenbach** [comment]
I agree, exposing the dispatcher would be pretty simple.
But I don't see what use case you have in mind here. Could you elaborate a bit more on that? Giving some concrete example?

**Comment by NekkoDroid** [comment]
If we have an API something like roughly like this

```c++
struct Renderer
{
    vk::DispatchLoaderDynamic Dispatch;
    vk::UniqueInstance Instance;
    vk::UniqueDevice Device;
    //...

    // Doesn't have to be unique, just here it's used for dispatcher example
    vk::UniqueCommandBuffer StartBuffer();
    void EndBuffer(vk::UniqueCommandBuffer cmd);
};

// Currently if you'd pass the `cmd` to some function to do all the recording you would need to also 
// pass the `Dispatch` member from the renderer to be able to do 
// `cmd->beginRendering({}, dispatch)`.
void DoRendering(const vk::UniqueCommandBuffer& cmd, const vk::DispatchLoaderDynamic& dispatch);

// This change would allow to omit the extra dispatch parameter from the function, and simply use
// the one that was used to create the command buffer by doing
// `cmd->beginRendering({}, cmd.getDispatch())`.
void DoRendering(const vk::UniqueCommandBuffer& cmd);

int main()
{
    Renderer renderer;
    vk::UniqueCommandBuffer cmd = renderer.StartBuffer();
    
    DoRendering(cmd, renderer.Dispatch);
    //vs
    DoRendering(cmd);

    renderer.EndBuffer(std::move(cmd));
}
```

This is even more apparent when separating/abstracting other of the vulkan handles into separate classes, you'd need to in this example either pass a pointer to the dispatcher to the class (again), or every time when you want to call a function on those handles you'd need to make it go through the `Renderer` class.

**Comment by asuessenbach** [comment]
> (This all obv just applies if you aren't using the global dispatcher)

This was the important hint I had missed.
So, yes, your issue is real, and I'll merge your PR #1569.
And completely omitting the dispatcher and just always use the one from the deleter would be even better, but would be more expensive to introduce. 

Just out of curiosity: why do you need some non-default dispatcher? Would the vulkan-raii.hpp be an option for you as well?

**Comment by NekkoDroid** [comment]
I was just experimenting with some abstractions and was tempted to allow multiple devices to be created (didn't end up supporting multiple) which to my knowledge would all need their separate dispatcher, so a single global one wouldn't work.

**Comment by asuessenbach** [comment]
You can use multiple GPUs with a single default dispatcher if you skip the third init-call on it.
That is, just call
```
      static vk::DynamicLoader  dl;
      PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = dl.getProcAddress<PFN_vkGetInstanceProcAddr>( "vkGetInstanceProcAddr" );
      VULKAN_HPP_DEFAULT_DISPATCHER.init( vkGetInstanceProcAddr );
```
and
```
      // initialize function pointers for instance
      VULKAN_HPP_DEFAULT_DISPATCHER.init( instance );
```
but omit something like
```
    // function pointer specialization for device
    VULKAN_HPP_DEFAULT_DISPATCHER.init( device );
```
The instance-initalized default dispatcher runs with as many GPUs as there are available. Maybe not as fast, as each call internally requires an additional jump, but I doubt that this is measurable in any real circumstances.
