### ISSUE TITLE
Feature Request: Add assignment function that does not interact with pNext

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-Hpp#1575]
When filling a vk::StructureChain object, I may set a Features struct to be equal to a Features struct that has been filled in somewhere else (such as with a getFeatures2() call).
This can be error prone since the pNext will be overwritten with in invalid value. It would be great if we had an set() function that set all the members except the pNext member.
Thanks

**Comment by asuessenbach** [comment]
You mean, some structure member function like
`void StructureType::assign_except_pNext( StructureType const & rhs );`
This seems to be a pretty niche functionality, and the very name looks a bit clumsy. Especially with the standard assignment operator available (which of course, as you correctly state, overwrites `pNext`).
I could easily add something like that, but only if there is some more request for it.
