### ISSUE TITLE
[feature request] add asTuple to StructureChain

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#1576]
Just `static_cast<std::tuple<ChainElements...> &>(*this)` (cast to base class) in it. Currently I cannot conveniently decompose like this:
```cpp
vk::StructureChain<vk::PhysicalDeviceFeatures2, vk::PhysicalDeviceSamplerYcbcrConversionFeaturesKHR> physicalDeviceFeaturesChain;
auto& [physicalDeviceFeatures2, physicalDeviceSamplerYcbcrConversionFeatures] = physicalDeviceFeaturesChain;
```
because:
 > main.cc:11:15: error: cannot decompose class type 'StructureChain<vk::PhysicalDeviceFeatures2, vk::PhysicalDeviceSamplerYcbcrConversionFeatures>': its base classes '_Head_base<1UL, vk::PhysicalDeviceSamplerYcbcrConversionFeatures>' and '_Head_base<0UL, vk::PhysicalDeviceFeatures2>' have non-static data members

In the class definition `get` is overriden in non-compatible fasion, because of that the case `Case 2: binding a tuple-like type
` from [here](https://en.cppreference.com/w/cpp/language/structured_binding) is not working as one can expect while reading the `vk::StructureChain`'s definition.

**Comment by tomilov** [comment]
Also it is common nowadays to prefer composition to inheritance. Because of such a confusions (futile user's expectations).

**Comment by asuessenbach** [comment]
It turned out, that there needed to be some specializations of `std::tuple_element` and `std::tuple_size` for `vk::StructureChain`s to support usage of structured binding on them. So, no need for an `asTuple`-function.
