### ISSUE TITLE
Resetting aggregate of RAII types leads to out of order member destruction

### ISSUE THREAD

**Issue by thonatt** [KhronosGroup/Vulkan-Hpp#1588]
When working with high level structs that combine multiple RAII types, the member declaration order is important to be sure that Vulkan objects are destroyed using the correct order, for example with:
```
struct Window { 
    vk::raii::SurfaceKHR surface = nullptr;
    vk::raii::SwapchainKHR swapchain = nullptr;
} window;
```
However, when resetting such type, i.e. with `window = {};`, the destruction order is incorrect. The implicitely declared move assignment operator `X& operator=(X&& rhs)` calls the move assignment operator for each member using the declaration order. However, for the VulkanHpp RAII types, move assignement operators perform a `clear()`, making the destruction of the underlying Vulkan types happen during the assignment, leading to a wrong destruction order. Is that expected?

A solution from the user side is to manually define the move assignment operator of such struct to reverse the order, but it seems rather contrived.
A solution from the VulkanHpp side would be to use `std::swap` instead of `std::exchange` in the move assignment operators, postponing `clear` calls to the `rhs` destructor.

**Comment by asuessenbach** [comment]
Good catch, indeed!
Thanks a lot for that hint, will change it asap.
