### ISSUE TITLE
Compilation error: unknown type name 'StructureChainAllocator'

### ISSUE THREAD

**Issue by amaiorano** [KhronosGroup/Vulkan-Hpp#1592]
**Describe the bug**

When importing the latest Vulkan-Headers into Google repos, we are now getting compile errors like:

```
In file included from [./third_party/vulkan_headers/include/vulkan/vulkan.hpp:6794](https://cs.corp.google.com/piper///depot/google3/third_party/vulkan_headers/include/vulkan/vulkan.hpp?l=6794&ws=tap-presubmit-server/61174818&snapshot=2):
[third_party/vulkan_headers/include/vulkan/vulkan_handles.hpp:12039](https://cs.corp.google.com/piper///depot/google3/third_party/vulkan_headers/include/vulkan/vulkan_handles.hpp?l=12039&ws=tap-presubmit-server/61174818&snapshot=2):114: error: unknown type name 'StructureChainAllocator'
              typename B2                                                                                      = StructureChainAllocator,
                                                                                                                 ^
```

I think this originates from [this Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/commit/2f4ef8371aa309f91954536996582066900ef2a0) change, which resulted in [this Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers/commit/cb71b646f1389822409a281252689492a18905b9#diff-a83f956c7aeb2b6dee7ffa2f249c0d98a2cfad6e157fe8438e372a5267afaeff) change.

Is it possible that there's an issue with how `vulkan_handles.hpp` was generated? When looking for `StructureChainAllocator`, all I can find is that maybe it was supposed to be emitted by [VulkanHppGenerator here](https://github.com/KhronosGroup/Vulkan-Hpp/blob/main/VulkanHppGenerator.cpp#L2090)?

Sorry if I'm way off base, I'm just struggling to understand this new compilation error.

**Comment by asuessenbach** [comment]
Assuming this is fixed with #1591, I'll close this issue.
Feel free to re-open it if needed.
