### ISSUE TITLE
DescriptorSetLayoutBinding enhanced constructor not correct

### ISSUE THREAD

**Issue by portaloffreedom** [KhronosGroup/Vulkan-Hpp#1603]
The enhanced constructor of `vk::DescriptorSetLayoutBinding` is not correct. It has the `descriptorCount` set as the size of the `immutableSamplers_`. They are two separate things. 

(Found out following the [vulkan tutorial](https://vulkan-tutorial.com/en/Uniform_buffers/Descriptor_layout_and_buffer) but converting all vulkan calls to the vulkan-cpp equivalent) 

Currently using the archlinux package `vulkan-headers` version 1:1.3.253-1

Following is the wrong code inside `vulkan_structs.hpp`
```cpp
    DescriptorSetLayoutBinding( uint32_t                                                                                   binding_,
                                VULKAN_HPP_NAMESPACE::DescriptorType                                                       descriptorType_,
                                VULKAN_HPP_NAMESPACE::ShaderStageFlags                                                     stageFlags_,
                                VULKAN_HPP_NAMESPACE::ArrayProxyNoTemporaries<const VULKAN_HPP_NAMESPACE::Sampler> const & immutableSamplers_ )
      : binding( binding_ )
      , descriptorType( descriptorType_ )
      , descriptorCount( static_cast<uint32_t>( immutableSamplers_.size() ) )
      , stageFlags( stageFlags_ )
      , pImmutableSamplers( immutableSamplers_.data() )
    {
    }
```

**Comment by asuessenbach** [comment]
That's not exactly wrong.
According to the [spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayoutBinding.html#VUID-VkDescriptorSetLayoutBinding-descriptorType-00282):
`If descriptorType is VK_DESCRIPTOR_TYPE_SAMPLER or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, and descriptorCount is not 0 and pImmutableSamplers is not NULL, pImmutableSamplers must be a valid pointer to an array of descriptorCount valid VkSampler handles`
That is, if you have samplers to pass into this struct, it's right.
If you don't have samplers, but a non-zero amount of descriptors, you would need to use the other constructor of `DescriptorSetLayoutBinding`:
```
    VULKAN_HPP_CONSTEXPR DescriptorSetLayoutBinding( uint32_t                               binding_         = {},
                                                     VULKAN_HPP_NAMESPACE::DescriptorType   descriptorType_  = VULKAN_HPP_NAMESPACE::DescriptorType::eSampler,
                                                     uint32_t                               descriptorCount_ = {},
                                                     VULKAN_HPP_NAMESPACE::ShaderStageFlags stageFlags_      = {},
                                                     const VULKAN_HPP_NAMESPACE::Sampler *  pImmutableSamplers_ = {} ) VULKAN_HPP_NOEXCEPT
      : binding( binding_ )
      , descriptorType( descriptorType_ )
      , descriptorCount( descriptorCount_ )
      , stageFlags( stageFlags_ )
      , pImmutableSamplers( pImmutableSamplers_ )
    {
    }
```

**Comment by asuessenbach** [comment]
Assuming this is resolved. Please re-open if not.
