### ISSUE TITLE
Incomplete documentation in README

### ISSUE THREAD

**Issue by ror3d** [KhronosGroup/Vulkan-Hpp#1620]
In the readme, when it is explained how to set up the DispatchLoaderDynamic, the following snippet of code is given:

```
vk::DynamicLoader dl;
PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = dl.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
VULKAN_HPP_DEFAULT_DISPATCHER.init(vkGetInstanceProcAddr);
```

As far as I can tell, this is not entirely correct: the `vk::DynamicLoader` instance should either be marked `static`, or be stored somewhere global (using `static` is how it seems to be done in all the samples).

Otherwise, attempting to call generic functions like device.getProcAddr(...) after the scope is left will cause access violations because the vulkan library has been unloaded when the object is destroyed on leaving the scope.

**Comment by asuessenbach** [comment]
Thanks for pointing that out!
I will add some words that you need to keep the `vk::DynamicLoader` alive until after the last call to a vulkan function in your program.
