### ISSUE TITLE
RayTracingShaderGroupCreateInfoKHR should default shader indices to unused

### ISSUE THREAD

**Issue by kroppt** [KhronosGroup/Vulkan-Hpp#1653]
Currently, the constructor looks like:
```cpp
    VULKAN_HPP_CONSTEXPR RayTracingShaderGroupCreateInfoKHR(
      VULKAN_HPP_NAMESPACE::RayTracingShaderGroupTypeKHR type_                            = VULKAN_HPP_NAMESPACE::RayTracingShaderGroupTypeKHR::eGeneral,
      uint32_t                                           generalShader_                   = {},
      uint32_t                                           closestHitShader_                = {},
      uint32_t                                           anyHitShader_                    = {},
      uint32_t                                           intersectionShader_              = {},
      const void *                                       pShaderGroupCaptureReplayHandle_ = {},
      const void *                                       pNext_                           = nullptr ) VULKAN_HPP_NOEXCEPT
      : pNext( pNext_ )
      , type( type_ )
      , generalShader( generalShader_ )
      , closestHitShader( closestHitShader_ )
      , anyHitShader( anyHitShader_ )
      , intersectionShader( intersectionShader_ )
      , pShaderGroupCaptureReplayHandle( pShaderGroupCaptureReplayHandle_ )
    {
    }
```

So, the shader indices are defaulting to 0.

Per [the specification](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkRayTracingShaderGroupCreateInfoKHR.html), each of the shader values should either be set to a shader index or be set to `VK_SHADER_UNUSED_KHR`.
One of them is described thus:

> `generalShader` is the index of the ray generation, miss, or callable shader from [VkRayTracingPipelineCreateInfoKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkRayTracingPipelineCreateInfoKHR.html)::`pStages` in the group if the shader group has `type` of `VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR`, and `VK_SHADER_UNUSED_KHR` otherwise.

So, the fact that each of the shaders indices defaults to index 0 is inconvenient and invalid. You can only set the index for one of the types, and all the rest must be set to unused. If the constructor defaulted those values to unused, you would only need to set the one shader index you used.

**Comment by asuessenbach** [comment]
That seems to be reasonable.
I'll add some hardcoded default values for that structure.
Thanks a lot for this hint for improvement.

**Comment by kroppt** [comment]
> _You can only set the index for one of the types_, and all the rest must be set to unused. If the constructor defaulted those values to unused, _you would only need to set the one shader index you used_.

Looking back, I actually misspoke about the API: I said you could only ever set one index, but that's not true. You can set the index for more than one shader in some cases, e.g. if you were using a triangles hit group then you could use both closest hit and any hit shaders. However, the changes are still good.
