### ISSUE TITLE
vk::CommandPool has no member named reset

### ISSUE THREAD

**Issue by froart** [KhronosGroup/Vulkan-Hpp#1656]
Hi! I can clearly see that there is a member function "reset" in vk::CommandPool in vulkan_raii.hpp, however I get this error. Any ideas?
vulkan_tutorial.cpp:468:18: error:
 ‘class vk::CommandPool’ has no member named ‘reset’
  468 |      commandPool.reset( vk::CommandPoolResetFlags ( vk::CommandPoolResetFlagBits::eReleaseResources ) ); // clear buffers

uname -a:
Linux ubuntu 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x8
6_64 x86_64 x86_64 GNU/Linux

**Comment by asuessenbach** [comment]
It seems, you're mixing up two separate namespaces.
There is a `vk::raii::CommandPool::reset`, but no `vk::CommandPool::reset`. In the vk-namespace you would need to use `vk::Device::resetComandPool`.

**Comment by asuessenbach** [comment]
Closing, assuming it is resolved by my answer.
Please re-open in case this assumption is wrong.

**Comment by froart** [comment]
> It seems, you're mixing up two separate namespaces. There is a `vk::raii::CommandPool::reset`, but no `vk::CommandPool::reset`. In the vk-namespace you would need to use `vk::Device::resetComandPool`.

Thanks for suggestion. Seems like your point is correct, but unfortunately this would imply changing every vk:: namespace usage to vk::raii:: for every object created, because it gives me the list of such errors:
> error: no matching function for call to ‘vk::Device::freeCommandBuffers(vk::raii::CommandPool&, std::vector<vk::CommandBuffer>&)’
> 588 |   device.freeCommandBuffers( commandPool, commandBuffers ); 

...which is another story. Thanks for the answer again though.
