### ISSUE TITLE
Overload vk::device::destroy

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Hpp#166]
It would be less verbose when writing code to be able to simply call `device.destroy(XXX)` whether XXX is a descriptorSetLayout or a pipeline, instead of having to explicitly write out the type in the function name.

**Comment by mtavenrath** [comment]
It's even more useful to be able to call a 'common' destroy function when using template. This change would allow us to combine all XYZDeleter classes into two (or one with functor) which either do call destroy(...) or free(...).

The uncomfortable part is that we can't remove the destroyXYZ functions, so we have destroy(xyz) and destroyXYZ(xyz) and people might wonder where the difference is.

**Comment by jherico** [comment]
I would argue that since this is a header only library, it's easy to see that destroy(xyz) is just an alias for destroyXYZ(xyz).  Between that and generating a comment that says it's an alias for a common naming convention, I don't think there would be significant confusion.

**Comment by mtavenrath** [comment]
feature has been implemented. closing.

**Comment by FaizzJamaludin** [comment]
#1002
