### ISSUE TITLE
Provide an overloaded vk::raii::CommandBuffer::bindShadersEXT() that takes vk::raii::ShaderEXTs as a parameter

### ISSUE THREAD

**Issue by Stef-2** [KhronosGroup/Vulkan-Hpp#1660]
Just a small quality of life improvement suggestion:

Given that [Vulkan-Hpp](https://github.com/KhronosGroup/Vulkan-Hpp) provides a convenient ``vk::raii::ShaderEXTs`` class that encapsulates multiple compiled and possibly linked shader stages, it would be a further convenience to be able to pass ``vk::raii::ShaderEXTs`` directly to ``vk::raii::CommandBuffer::bindShadersEXT()``.

Right now, the user can do it themselves with a bit of custom tweaking, but it would be nice if this worked out of the box since the two seem like a perfect match for each other.

**Comment by asuessenbach** [comment]
At first, your suggestions sounds nice.
But `vk::raii:ShaderEXT`s and `vk::ShaderEXT`s are not binary identical (other than `VkShaderEXT`s and `vk::ShaderEXT`s). That is, such a function would need to do some implicit copy operation from a `vk::raii::ShaderEXTs` (or some array of `vk::raii::ShaderEXT`s) to some array of `vk::ShaderEXT`s which I would like to avoid.
Instead, I would prefer to have some explict extraction routine, like
```
template <typename RAIIType>
std::vector<typename RAIIType::WrappedType> extractWrappedTypes( std::vector<RAIIType> const & data )
{
  std::vector<typename RAIIType::WrappedType> extracted( data.size() );
  std::transform( data.begin(), data.end(), extracted.begin(), []( RAIIType const & d ) { return *d; } );
  return extracted;
}
```
This could be used like
`  commandBuffer.bindShadersEXT( stages, extractWrappedTypes( shaders ) );`

All I need to support that would be some `using WrappedType = vk::Type;` in each `class vk::raii::Type`.

What would you think about such an approach?
And would you have some better name than `WrappedType` for that type trait?

**Comment by Stef-2** [comment]
I think your suggestion sounds great, especially since it clearly informs the user that some conversion is taking place and that it might imply a slight performance overhead.

**Comment by asuessenbach** [comment]
Will add that asap.
And, do you think some version of that extraction- (or filter-)function with an UnaryPredicate is would be worth to have?
Something like
```
    template <typename RAIIType, class UnaryPredicate>
    std::vector<typename RAIIType::CppType> filterCppTypes( std::vector<RAIIType> const & raiiTypes, UnaryPredicate p)
```

**Comment by Stef-2** [comment]
I think that sounds great. I really like the explicit approach over my initial suggestion.
