### ISSUE TITLE
[Bug] "/data/data/com.termux/files/home/Vulkan-Hpp/samples/utils/shaders.cpp:19:10: fatal error: 'StandAlone/ResourceLimits.h' file not found"

### ISSUE THREAD

**Issue by AmericaPacific42** [KhronosGroup/Vulkan-Hpp#1680]
`~/Vulkan-Hpp $ cmake -DVULKAN_HPP_SAMPLES_BUILD=ON -DVULKAN_HPP_TESTS_BUILD=ON \
 -DENABLE_OPT=0 \
 -DCMAKE_CXX_STANDARD_REQUIRED=ON \
-DVULKAN_HPP_ENABLE_EXPERIMENTAL_CPP20_MODULES=ON \
 -DCMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API=aa1f7df0-828a-4fcd-9afc-2dc80491aca7 \
 -DCMAKE_CXX_STANDARD=20 && \
sed 's/-Werror/-Wno-error/g' CMakeLists.txt -i'' &&
cmake --build .
-- The CXX compiler identification is Clang 17.0.2
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--  Found clang-format version <17.0.2>.
--  Using .clang-format version 15.
CMake Warning (dev) at CMakeLists.txt:365 (target_sources):
  CMake's C++ module support is experimental.  It is meant only for
  experimentation and feedback to CMake developers.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Doxygen: /data/data/com.termux/files/usr/bin/doxygen (found version "1.9.8") found components: doxygen
-- Including X11 support
-- Found X11: /data/data/com.termux/files/usr/include
-- Looking for XOpenDisplay in /data/data/com.termux/files/usr/lib/libX11.so;/data/data/com.termux/files/usr/lib/libXext.so
-- Looking for XOpenDisplay in /data/data/com.termux/files/usr/lib/libX11.so;/data/data/com.termux/files/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found Python3: /data/data/com.termux/files/usr/bin/python3.11 (found version "3.11.6") found components: Interpreter
-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Vulkan: /data/data/com.termux/files/usr/lib/libvulkan.so (found version "1.3.267") found components: glslangValidator missing components: glslc
-- Configuring done (14.1s)
-- Generating done (0.3s)
-- Build files have been written to: /data/data/com.termux/files/home/Vulkan-Hpp
[0/1] Re-running CMake...
--  Found clang-format version <17.0.2>.
--  Using .clang-format version 15.
CMake Warning (dev) at CMakeLists.txt:365 (target_sources):
  CMake's C++ module support is experimental.  It is meant only for
  experimentation and feedback to CMake developers.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Including X11 support
-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
-- Configuring done (5.7s)
-- Generating done (0.1s)
-- Build files have been written to: /data/data/com.termux/files/home/Vulkan-Hpp
[1/1] Cleaning all built files...
Cleaning... 314 files.
[39/367] Generating HTML documentation
[44/367] Building CXX object glslang/glslang/CMakeFile...neIndependent.dir/MachineIndependent/glslang_tab.cpp.
MachineIndependent/glslang_tab.cpp:4968:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
4968 |     int yynerrs = 0;
      |         ^
1 warning generated.
[114/367] Building CXX object samples/utils/CMakeFiles/utils.dir/shaders.cpp.o
FAILED: samples/utils/CMakeFiles/utils.dir/shaders.cpp.o
/data/data/com.termux/files/usr/bin/c++ -DCLANG_FORMAT_EXECUTABLE=\"/data/data/com.termux/files/usr/bin/clang-format\" -DVK_USE_PLATFORM_XCB_KHR -DVULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1 -I/data/data/com.termux/files/home/Vulkan-Hpp -I/data/data/com.termux/files/home/Vulkan-Hpp/Vulkan-Headers/include -I/data/data/com.termux/files/home/Vulkan-Hpp/glm/glm/.. -I/data/data/com.termux/files/home/Vulkan-Hpp/glfw/include -I/data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/.. -I/data/data/com.termux/files/home/Vulkan-Hpp/include -I/data/data/com.termux/files/home/Vulkan-Hpp/glslang/SPIRV/.. -O2 -g -DNDEBUG -std=gnu++11 -Wall -Wextra -pedantic -Wno-error -Winvalid-pch -Xclang -include-pch -Xclang /data/data/com.termux/files/home/Vulkan-Hpp/samples/utils/CMakeFiles/utils.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /data/data/com.termux/files/home/Vulkan-Hpp/samples/utils/CMakeFiles/utils.dir/cmake_pch.hxx -MD -MT samples/utils/CMakeFiles/utils.dir/shaders.cpp.o -MF samples/utils/CMakeFiles/utils.dir/shaders.cpp.o.d -o samples/utils/CMakeFiles/utils.dir/shaders.cpp.o -c /data/data/com.termux/files/home/Vulkan-Hpp/samples/utils/shaders.cpp
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/samples/utils/shaders.cpp:18:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../SPIRV/GlslangToSpv.h:42:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../SPIRV/SpvTools.h:50:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/localintermediate.h:42:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/intermediate.h:56:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/../Include/Common.h:97:
/data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/../Include/PoolAlloc.h:121:12: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  121 |     static inline constexpr unsigned char guardBlockBeginVal = 0xfb;
      |            ^
/data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/../Include/PoolAlloc.h:122:12: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  122 |     static inline constexpr unsigned char guardBlockEndVal = 0xfe;
      |            ^
/data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/../Include/PoolAlloc.h:123:12: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  123 |     static inline constexpr unsigned char userDataFill = 0xcd;
      |            ^
/data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/../Include/PoolAlloc.h:128:12: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  128 |     static inline constexpr size_t guardBlockSize = 0;
      |            ^
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/samples/utils/shaders.cpp:18:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../SPIRV/GlslangToSpv.h:42:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../SPIRV/SpvTools.h:50:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/localintermediate.h:42:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/intermediate.h:57:
In file included from /data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/../Include/Types.h:47:
/data/data/com.termux/files/home/Vulkan-Hpp/glslang/glslang/../glslang/MachineIndependent/../Include/../Include/SpirvIntrinsics.h:120:10: error: no template named 'variant' in namespace 'std'
  120 |     std::variant<const TIntermConstantUnion*, const TType*> value;
      |     ~~~~~^
/data/data/com.termux/files/home/Vulkan-Hpp/samples/utils/shaders.cpp:19:10: fatal error: 'StandAlone/ResourceLimits.h' file not found
   19 | #include "StandAlone/ResourceLimits.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings and 2 errors generated.`
` `-DVULKAN_HPP_ENABLE_EXPERIMENTAL_CPP20_MODULES=ON \
-DCMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API=aa1f7df0-828a-4fcd-9afc-2dc80491aca7 \
-DCMAKE_CXX_STANDARD=20` was workaround (for variant not found); read* that <variant> requires compilation from new C++ standard versions. No go.

*https://github.com/clangd/clangd/issues/1286 https://stackoverflow.com/questions/57300495/how-to-use-c20-modules-with-cmake

**Comment by asuessenbach** [comment]
Closing this out. If you think, this is still an issue, please re-open.

**Comment by AmericaPacific42** [comment]
Still broken in latest version.
Regular BASH environment on Android Linux, setup to run as most Debian or Fedora distros run.
