### ISSUE TITLE
Some vk::raii objects are copyable conflicting with the documentation

### ISSUE THREAD

**Issue by Omasyo** [KhronosGroup/Vulkan-Hpp#1685]
I noticed that some vk::raii objects can be copied. Although the documentation explicitly states.

> Note that, as the vk::raii objects own the actual Vulkan resource, all vk::raii objects are moveable, but not copyable.

It seems to be intentional as it was brought up as an issue in #1252 and subsequently merged in #1257. I believe the documentation should be updated to reflect that only classes that hold handles with a destructor are not copyable.

**Comment by asuessenbach** [comment]
You're right, the docu should be adjusted.
Thank you for bringing this issue to our attention.
