### ISSUE TITLE
Raii version of SwapchainKHR returns C-style images

### ISSUE THREAD

**Issue by dbs4261** [KhronosGroup/Vulkan-Hpp#1691]
Very simple request: the return type of `vk::raii::SwapchainKHR::getImages()` is a `std::vector<VkImage>`. My VK_HEADER_VERSION is 204. I am new to using vulkan along with the c++ headers. I understand that as the swapchain owns the images themselves it makes sense to only return a handle and not a `vk::raii::Image`. But that should mean this function should return `std::vector<vk::Image>` instead. I am not familiar with the generation code so Id rather not dive an to create the PR myself.

**Comment by asuessenbach** [comment]
Closing this, assuming it is resolved.
