### ISSUE TITLE
Incorrect std::string and std::string_view constructors used

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#1694]
There are implicit conversion operators:
```cpp
    template <typename B = T, typename std::enable_if<std::is_same<B, char>::value, int>::type = 0>
    operator std::string() const
    {
      return std::string( this->data() );
    }

#if 17 <= VULKAN_HPP_CPP_VERSION
    template <typename B = T, typename std::enable_if<std::is_same<B, char>::value, int>::type = 0>
    operator std::string_view() const
    {
      return std::string_view( this->data() );
    }
#endif
```
but there is constructor
```cpp
VULKAN_HPP_CONSTEXPR ArrayWrapper1D( std::array<T, N> const & data ) VULKAN_HPP_NOEXCEPT : std::array<T, N>( data ) {}
```
In the wild it can be used against non-zero-terminated sequence of `char`s (the sequence even contain zeros for some reasons). Therefore constructors of `std::string` and `std::string_view`, that expects zero-terminated strings may fail indeterministically in real applications.
"Range" versions of constructors like 6 from [here](https://en.cppreference.com/w/cpp/string/basic_string/basic_string) or sized like 4 from there should be used instead. For `std::string_view` it is better to use sized version ([link](https://en.cppreference.com/w/cpp/string/basic_string_view/basic_string_view)), due to range version is not available until C++20.

**Comment by asuessenbach** [comment]
Great catch!
Thanks for reporting this potential issue. Will fix it asap.
