### ISSUE TITLE
VkDisplayKHR does not have proper destructor

### ISSUE THREAD

**Issue by Agrael1** [KhronosGroup/Vulkan-Hpp#1695]
Whilst I was making type traits for VkUtils I noticed that VkDisplayKHR does't get destroyed in Vulkan Hpp, however vk.xml shows that there is a `vkReleaseDisplayEXT` function for that.

Please fix.

**Comment by Agrael1** [comment]
Seems like there is no UniqueHandleTraits for that. I thought, that it was present, but I can't seem to find any UniqueDisplayKHR. So the issue may be closed.

**Comment by asuessenbach** [comment]
You're right, there's no UniqueDisplayKHR. And that's an error!
Thanks for spotting that.
The resolution is on its way (#1697). Would you mind to verify the correctness of the SharedHandles?

**Comment by Agrael1** [comment]
Yes, shared handles are correct
