### ISSUE TITLE
Add ability to custom override assert

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-Hpp#170]
The header calls assert() in a few places, more if you define VULKAN_HPP_NO_EXCEPTIONS. Unfortunately the system assert is quite fatal and it doesn't give the application a chance to try and recover from those errors or report them in a more friendly way.

It'd be nice to add the ability to optionally override the assert macro with some code like:

```cpp
#if !defined(VULKAN_HPP_ASSERT)
# define VULKAN_HPP_ASSERT assert
#endif
```

That way the macro can be overridden externally if desired to point to some other assert macro/function/etc. It's not possible to do this at the moment since the header has `#include <cassert>` which may then `#undef assert` before defining its own macro.

**Comment by mtavenrath** [comment]
You can now define VULKAN_HPP_ASSERT to your custom assert function or override assert. For the latter case you've to add ```#define VULKAN_HPP_ASSERT assert``` to prevent vulkan.hpp including cassert.
