### ISSUE TITLE
Tests won't compile with clang, `std::string_literals` are only available since C++14

### ISSUE THREAD

**Issue by kiroma** [KhronosGroup/Vulkan-Hpp#1702]
Test [ArrayWrapper](https://github.com/KhronosGroup/Vulkan-Hpp/blob/main/tests/ArrayWrapper/ArrayWrapper.cpp#L270) fails to compile with a pedantic compiler due to the standard being defaulted to C++11
```
Vulkan-Hpp/tests/ArrayWrapper/ArrayWrapper.cpp:27:22: error: expected namespace name
   27 | using namespace std::string_literals;
      |                 ~~~~~^
```

**Comment by asuessenbach** [comment]
You're right. Will fix it asap.
Thanks for reporting this issue!
