### ISSUE TITLE
Missing items from c++20 module

### ISSUE THREAD

**Issue by HildarTheDorf** [KhronosGroup/Vulkan-Hpp#1706]
Writing a hello triangle using the .cppm, all very snazzy and compile times are much improved (if only clangd/intellisense worked).

Couple of things I've found missing so far, mainly related to macros.

Can the cppm define storage vk::defaultDispatchLoaderDynamic? Having to manually write out the definition of VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE is bug prone due to a lack of access to macros for things like dllimport/dllexport. Defining storage in the module should be fine with regards to the ODR, unlike defining it in a header.

Could the .cppm export constexpr variables containing extension names? (i.e. aliases for VK_KHR_SWAPCHAIN_EXTENSION_NAME and the like), as again we don't have access to macros.

**Comment by theHamsta** [comment]
This might be similar to https://github.com/KhronosGroup/Vulkan-Hpp/pull/1651. We have seen that some functionally of Vulkan-Hpp still relies on macros. As a mitigation, we have out-factored such macros to a dedicated header `"vulkan/vulkan_hpp_macros.hpp"`. We have considered putting `"vulkan/vulkan_hpp_macros.hpp"` into the module (in fact it was there before), but this would lead to the problem that we don't know in which `.DLL`s/`.so` the compiled `.cppm` will end up which could cause multiple instances of the `VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE` singleton. Our current approach is to recommend to create a single file in your project to define the dynamic storage (that still uses a header).

```
#include "vulkan/vulkan_hpp_macros.hpp"
import vulkan_hpp;

#if VULKAN_HPP_DISPATCH_LOADER_DYNAMIC
#else
#error "I expect VULKAN_HPP_DISPATCH_LOADER_DYNAMIC to be defined"
#endif

VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE
```
We're open for suggestions for better approaches that would not require any headers. There are also some macros from `vulkan.h` that are still have no equivalent in vulkan.cppm (btw. we found that with clang `import vulkan_hpp;` is faster than `#include vulkan.h`

**Comment by sharadhr** [comment]
> if only clangd/intellisense worked

If you're using VS Code, perhaps that's why. Visual Studio or CLion are pretty good with C++20 modules now, and Visual Studio with ReSharper C++ is what I've been using to develop `vulkan.cppm`. 

> Can the cppm define storage `vk::defaultDispatchLoaderDynamic`

I was under the impression this was first mentioned in #1649, subsequently fixed in #1651, and released to the public in header version [1.3.264](https://github.com/KhronosGroup/Vulkan-Headers/blob/fff6d143cc4dccb5959db63c85c7b01406e0d333/include/vulkan/vulkan.cppm#L29). Is there something additional you need?

> Could the `.cppm` export `constexpr` variables containing extension names?

Good idea. In fact, I think *all* macros defined in `vulkan.h` ought to be consumed and re-exported as constexpr variables in `vulkan.cppm`.

@asuessenbach, I'd be happy to work on the latter proposal.

**Comment by asuessenbach** [comment]
> @asuessenbach, I'd be happy to work on the latter proposal.

Would be great, yes!

**Comment by HildarTheDorf** [comment]
>I was under the impression this was first mentioned in https://github.com/KhronosGroup/Vulkan-Hpp/issues/1649, subsequently fixed in https://github.com/KhronosGroup/Vulkan-Hpp/pull/1651, and released to the public in header version [1.3.264](https://github.com/KhronosGroup/Vulkan-Headers/blob/fff6d143cc4dccb5959db63c85c7b01406e0d333/include/vulkan/vulkan.cppm#L29). Is there something additional you need?

This patch allows me as a conspumer to enable the dynamic dispatch loader as long as I place VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE in a .cpp file. I was thinking the .cppm file could contain the instance of VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE, but as @theHamsta mentioned this probably breaks when consuming the module from multiple shared objects.

However I have found another bug, currently it is impossible to include vulkan_hpp_macros.hpp inside a module.

For example, I tried to create a vulkan_hpp_dispatch module that only contained VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE. This failed to compile as DispatchLoaderDynamic is now defined in both vulkan_hpp (the module provided by this repo) and vulkan_hpp_dispatch (module I authored). If I want my application to be structred using modules, that means I can't use vulkan_hpp_macros.hpp.

**Comment by sharadhr** [comment]
@asuessenbach, before I post my PR, I'd like to ask for some naming suggestions. 

Every extension name macro is of the form `VK_<VENDOR>_<EXTNAME>_EXTENSION_NAME`. For instance, `VK_KHR_SWAPCHAIN_EXTENSION_NAME` (as the first post suggests). 

I would like to perform the following transformation:

`VK_<VENDOR>_<EXTENSION_STRING>_EXTENSION_NAME` → `<ExtensionString>_<VENDOR>ExtName`. 

So, `VK_KHR_SWAPCHAIN_EXTENSION_NAME` would become `SwapchainKHRExtName`. 

Sounds OK? Cheers :)

**Comment by asuessenbach** [comment]
@sharadhr I would transform `EXTENSION_NAME` just to the camel-case version of it: `ExtensionName`. No abbreviation or shortcut there.
What I'm not sure about is the position of the `<VENDOR>`. As the original define starts with that (after the VK_, of course), I would tend to also start the transformed name with it. That is `VK_KHR_SWAPCHAIN_EXTENSION_NAME` -> `vk::KHRSwapchainExtensionName`.
I think, that would be as close as possible to the original name.

**Comment by sharadhr** [comment]
@asuessenbach, 

Thanks; that sounds better. By the way, every extension also has a `SPEC_VERSION` macro. I'm not entirely sure what this is for, but would it be useful to `constexpr`-ify this, too? So, `constexpr auto vk::KHRSwapchainSpecVersion = VK_KHR_SWAPCHAIN_SPEC_VERSION;`?

**Comment by asuessenbach** [comment]
I don't know either what those values might be used for. But who knows?
That is: as it's probably very easy to `constexpr`-ify them as well, I would go for it.
