### ISSUE TITLE
On using defined() in preprocessor directives

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#1714]
It seems it is wrong to use `defined()` in macro to test whether a feature should be enabled or not. It is common approach to just write `#if VK_NO_PROTOTYPES` or `#if !VK_NO_PROTOTYPES`. It works fine for undefined macros and works as expected if one want to generate `config.h` from `config.h.in` and get `#define VK_NO_PROTOTYPES 0` as a result. In the case `#if defined( VK_NO_PROTOTYPES )` is wrong test.

**Comment by asuessenbach** [comment]
I think, I don't get what you're asking for...
Even in vulkan_core.h the check is `#ifndef VK_NO_PROTOTYPES`.
Where exactly do you see the "common approach to just write `#if VK_NO_PROTOTYPES`"? What `config.h` are you talking about?

**Comment by tomilov** [comment]
I mean [this](https://cmake.org/cmake/help/latest/command/configure_file.html) functionality. Small and widely used codegen.
```
Even in vulkan_core.h the check is #ifndef VK_NO_PROTOTYPES.
```
this is not an argument. They cannot be ground truth for sure. One cannot use `-DVK_NO_PROTOTYPES=0` as boolean flag with that code. But semantics of `VK_NO_PROTOTYPES` is exactly "boolean flag".

**Comment by tomilov** [comment]
okay, this is opinion-based
