### ISSUE TITLE
vulkan_hpp_macros.hpp uses feature-test macros without including headers that contain them

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1715]
vulkan_hpp_macros.hpp uses feature-test macros, but it doesn't include headers supplying them:

https://github.com/KhronosGroup/Vulkan-Hpp/blob/26664a38a4e8a38feb9d834987a8160e2db5702a/vulkan/vulkan_hpp_macros.hpp#L73-L79

as such some macros may not be set even if a feature is present.

All feature-test macros are defined in `<version>` header (avaiable since c++20).
Also according to [C++ reference](https://en.cppreference.com/w/cpp/header/version): "Prior to C++20, including [`<ciso646>`](https://en.cppreference.com/w/cpp/header/ciso646) is sometimes used for this purpose." But note that `<ciso646>` was removed from c++20.

As such just adding
```c++
#if 20 <= VULKAN_HPP_CPP_VERSION
#  include <version>
#else
#  include <ciso646>
#endif
```
should do the trick. Also one thing to note is that `__has_include` is in standard since c++17 so that could be used instead.

**Comment by asuessenbach** [comment]
Thanks for that hint!
Will add that asap.
