### ISSUE TITLE
A recent change to ArrayWrapper1D may have broken string comparison in some cases

### ISSUE THREAD

**Issue by JoseGRuiz** [KhronosGroup/Vulkan-Hpp#1718]
I believe this change was in pr #1698. Basically the way the cast used to work is using [this constructor](https://en.cppreference.com/w/cpp/string/basic_string/basic_string#:~:text=constexpr%20basic_string(%20const%20CharT*%20s%2C%0A%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20const%20Allocator%26%20alloc%20%3D%20Allocator()%20)%3B) which copied the char array up to the first null character. But it was changed in response to issue #1708 which is a reasonable issue to disambiguate a constructor call. However, some things such as `ExtensionProperties` which has a member `extensionName` of type `ArrayWrapper1D<char, 256>`, when cast to a string gives a strange result which is likely not intended. That is for example, take "VK_KHR_swapchain" when cast using the new constructor creates the string "VK_KHR_swapchain\0\0\0\0... repeated until string length of 256". This breaks some string comparisons when comparing to the macro **VK_KHR_SWAPCHAIN_EXTENSION_NAME**, which is supposed to be the best way to ensure proper naming of extensions. 

Some string comparisons should still work for example casting to a c-string and using strcmp should still take into account the null character as being the end of the string. However some code that is all over the vulkan-tutorial repo `requiredExtensions.erase(extension.extensionName);` is now broken because it is internally using c++ string comparison methods. Telling users to always explicitly cast their strings how they want could be one way to fix this. Or maybe redefining the type of extensionName and other similar ArrayWrapper1D char arrays to use the c++ string class might work.  I'm not quite sure how to fix this issue or if it is considered an issue at all but I feel it is worth bringing it up and seeing what you want to do with it.

**Comment by zoddicus** [comment]
This change in behaviour is causing breakages/inability of downstream projects to ingest updates, because it breaks how checking for extensions should work as described.

**Comment by amaiorano** [comment]
To add to @zoddicus's comment, [this change](https://github.com/KhronosGroup/Vulkan-Hpp/commit/bab0e249f25a94f282a481e5cae828e1846b75c9) has broken projects at Google. This fix is not a good one. If an ArrayWrapper1D is supposed to represent a "stringy" std::array, but can be constructed from a non-null-terminated array of char, then the implicit string/string_view operators should take this into account:
1. If the array buffer is null-terminated, return a std::string/string_view with the pointer + strlen(pointer)
2. If the array bufer is not null-terminated, return a std::string/string_view with the pointer + N

**Comment by asuessenbach** [comment]
@JoseGRuiz, @zoddicus, @amaiorano
Please sorry for all those inconveniences! Would you mind to verify that #1725 fixes this issue?

**Comment by JoseGRuiz** [comment]
@asuessenbach  it solves my issue. Tested it on my project and it solves the issue and seems to give no further issues. I also looked at the proposed changes and they look good to me.
