### ISSUE TITLE
Feature request: Dispatcher bound to vk::Device

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1719]
Passing dispatcher to each and every function can be quite tedious.

Would it be possible to add a handle dispatcher pair so that `HD( handle, dispatcher ).func(...)` was equivalent to `handle.func(..., dispatcher)`?

**Comment by asuessenbach** [comment]
You only need to pass the dispatcher to every function, if you don't use the default dispatcher (set via `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC` and `VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE`, see https://github.com/KhronosGroup/Vulkan-Hpp#extensions--per-device-function-pointers).
Besides that, you might have a look at the vk::raii classes, that hold their dispatcher or a link to it.

**Comment by qbojj** [comment]
What I was trying to accomplish was to use per-device fn pointers while having ABI compatibility between Vulkan-Hpp versions.

Basically because Dispatchers are not ABI compatible I cannot use vk::raii::* variants and even vk::Unique* variants are a no-go.
