### ISSUE TITLE
Add feature macro to allow implicit cast of UniqueHandle to hpp handles

### ISSUE THREAD

**Issue by GPUCode** [KhronosGroup/Vulkan-Hpp#1731]
UniqueHandles are a great way of ensuring automatic resource destruction and cleaner code. However the constant need to run .get() or operator* to retrieve the underlying handle for CreateInfo structures or vulkan calls makes them more cumbersome to use than normal handles. I feel that trying to mimic the std::unique_ptr API here doesn't make much sense, considering that handles are most often used in such a manner compared to e.g running member functions with operator->. So I feel it would be useful to add new feature macro, for example VULKAN_HPP_SMART_HANDLE_IMPLICIT_CAST, that will define an implicit convertion operator to the underlying handle

**Comment by Pacheco95** [comment]
They could create a constructor like this at https://github.com/KhronosGroup/Vulkan-Hpp/blob/846ac99ceeb4e4ec671668b1914c45bf60a150ab/vulkan/vulkan.hpp#L871

```
// vulkan.hpp:837
template <typename Type, typename Dispatch>
class UniqueHandleTraits;

template <typename Type, typename Dispatch>
class UniqueHandle : public UniqueHandleTraits<Type, Dispatch>::deleter
{
 private:
  using Deleter = typename UniqueHandleTraits<Type, Dispatch>::deleter;

 public:
#if defined(VULKAN_HPP_SMART_HANDLE_IMPLICIT_CAST)
  UniqueHandle(Type t) : Deleter(), m_value(t) {}
#endif

  // ...

 private:
  Type m_value;
};
```

**Comment by Pacheco95** [comment]
If the maintainers agree I can make a PR

**Comment by GPUCode** [comment]
There is already such constructor. And this isn't the same as an implicit convertion operator anyway. https://github.com/KhronosGroup/Vulkan-Hpp/blob/846ac99ceeb4e4ec671668b1914c45bf60a150ab/vulkan/vulkan.hpp#L886

**Comment by Pacheco95** [comment]
But this is an explicit constructor

**Comment by asuessenbach** [comment]
Thanks for your request.
I think, this feature is worth to have, so (as stated in #1771), I added the implicit cast to the UniqueHandles and the SharedHandles, controlled by the opt-in define `VULKAN_HPP_SMART_HANDLE_IMPLICIT_CAST`.'
The vk::raii::Handles get the implicit cast unconditionally.
