### ISSUE TITLE
How to properly use vk::UniqueSwapchainKHR?

### ISSUE THREAD

**Issue by Pacheco95** [KhronosGroup/Vulkan-Hpp#1732]
I'm trying to convert my `vk::SwapchainKHR` to `vk::UniqueSwapchainKHR`, but when I try to get the swapchain images with

```c++
vk::UniqueDevice::getSwapchainImagesKHR()
```

it returns `std::vector<vk::Image>` instead of `std::vector<vk::UniqueImage>` and there is no `vk::UniqueDevice::getUniqueSwapchainImagesKHR` method.

Also tried this:

```c++
vk::UniqueDevice m_device;
std::vector<vk::UniqueImage> m_swapChainImages;
vk::UniqueSwapchainKHR m_swapChain;
// ...
m_swapChainImages.clear();

for (const auto& item : m_device->getSwapchainImagesKHR(*m_swapChain)) {
  m_swapChainImages.emplace_back(item);
}
```

But at the cleanup function the validation layer logged this:

```
/usr/include/vulkan/vulkan.hpp:5814: void vk::ObjectDestroy<OwnerType, Dispatch>::destroy(T) [with T = vk::Image; OwnerType = vk::Device; Dispatch = vk::DispatchLoaderStatic]: Assertion `m_owner && m_dispatch' failed.
```

**Comment by asuessenbach** [comment]
The "problem" with the swapchain images is, that they're owned by the system, not by user code.
But the `vk::UniqueHandle`s own their handle and destroy it on destruction.
That is, you should not assign a swapchain image to a `vk::UniqueImage`. Only your own images could be managed by a `vk::UniqueImage`.
By the way, the same holds for `vk::raii::Image`.

**Comment by theHamsta** [comment]
Assuming the question was answered by https://github.com/KhronosGroup/Vulkan-Hpp/issues/1732#issuecomment-1813974209. Feel free to re-open if something remains unclear.
