### ISSUE TITLE
Improvements to documentation

### ISSUE THREAD

**Issue by Pacheco95** [KhronosGroup/Vulkan-Hpp#1733]
First of all, thank you guys for making vulkan possible and to actively maintain the codebase.

I did the [Khronos Vulkan Tutorial](https://docs.vulkan.org/tutorial/latest/00_Introduction.html) using the C functions and decided to move to Vulkan HPP. Reading the documentation I saw two ways of doing this.

1. Using the Unique versions of handles like [`UniqueInstance`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/846ac99ceeb4e4ec671668b1914c45bf60a150ab/vulkan/vulkan_handles.hpp#L1869)
2. Using the RAII namespace

The problem with the RAII approach is that all samples are a bunch of code inside a main function.
It would be great if more realistic examples were provided. Maybe using a single class with members is would be fine. This would help a lot understanding how to properly use `vk::raii::Context`

Another thing that is obscure is those functions with a `2` suffix like this one https://github.com/KhronosGroup/Vulkan-Hpp/blob/846ac99ceeb4e4ec671668b1914c45bf60a150ab/vulkan/vulkan_handles.hpp#L4779

I saw some examples using the Unique handles and all of them deletes resources using explicit destroy functions like `device->destroySomething()` but there are automatic template specializations so you can just use `device->destroy()` and `device->free()` for everything. Why is this not pointed in samples?

Template especializations:
https://github.com/KhronosGroup/Vulkan-Hpp/blob/846ac99ceeb4e4ec671668b1914c45bf60a150ab/vulkan/vulkan_funcs.hpp#L1418

Explicit destroy functions:
https://github.com/KhronosGroup/Vulkan-Hpp/blob/846ac99ceeb4e4ec671668b1914c45bf60a150ab/samples/15_DrawCube/15_DrawCube.cpp#L152

**Comment by asuessenbach** [comment]
> Reading the documentation I saw two ways of doing this.

To be complete, there is a third way to us Vulkan-Hpp: using the "plain" handles from the vk-namespace (like `vk::Instance`,...).
That way, you would need to manage the lifetime of the handles on your own, but get all the other improvements of Vulkan-Hpp over the pure C interface. All the samples in https://github.com/asuessenbach/Vulkan-Hpp/tree/main/samples are using that approach.

> It would be great if more realistic examples were provided.

Totally agree!

> Another thing that is obscure is those functions with a 2 suffix like this one

I don't get your question here. Those are just Vulkan-Hpp-versions of the underlying C-functions (here: `vkCmdBeginRenderPass2`).

> Why is this not pointed in samples?

The `destroySomething()` and `destroy( Something )` functions are completely equivalent. There's no specific reason why the one should be preferred over the other (besides, maybe, using meta-programming the simple `destroy( Something )` function would probably be easier to use). Just use what better fits to your style.

**Comment by Pacheco95** [comment]
> To be complete, there is a third way to us Vulkan-Hpp: using the "plain" handles from the vk-namespace (like vk::Instance,...).

Yes, you're right. I was not clear. Those 2 options are for automatic resource management.

> I don't get your question here. Those are just Vulkan-Hpp-versions of the underlying C-functions (here: 

vkCmdBeginRenderPass2).
I didn't notice thos functions in the C library. I have no idea of their meaning.

**Comment by asuessenbach** [comment]
> I have no idea of their meaning.

Usually, when some improved version of a function is introduced, its name just gets a trailing '2'.
In this specific case, the new function takes (besides the other arguments) a `SubpassBeginInfo`, instead of just `SubpassContents`. That allows for extending the functionality of this function without changing its signature by chaining other (specifically allowed) structures with that `SubpassBeginInfo`.

**Comment by Pacheco95** [comment]
Adding a complement to my suggestions. I missed some guidance of automated testing with Vulkan. Actually I never thought about testing in game engines. I have no idea how it should be done. I'm interested about this subject. If you have any material, please send the links.

**Comment by Pacheco95** [comment]
I have created an implementation for the tutorial using the Vulkan-Hpp binding, and I'll share it here.
If you think it is worth mentioning in the docs as an example, feel free to add a link to it.

I tried to make it very flexible and all dependencies are managed by CMake.

https://github.com/Pacheco95/khronos-vulkan-tutorial-cpp
