### ISSUE TITLE
Need all info for Vulkan-hpp in what is equivalent to C

### ISSUE THREAD

**Issue by threedslider** [KhronosGroup/Vulkan-Hpp#1735]
Hi,

I am new to learn for Vulkan-hpp and I love it, thank you for that ! :) But I am losing some info in C++ in what is equivalent to C, for example : 

```
vk::DispatchLoaderDynamic dldi{ nullptr };

dldi = vk::DispatchLoaderDynamic(instance, vkGetInstanceProcAddr);
```
vkGetInstanceProcAddr return an assert of error :/ How to resolve this issue, please ?

I need to get a tool as search for finding all stuffs in documentation in what is equivalent to C++ from C, any there has this feature ?

Thanks and best regard.

**Comment by theHamsta** [comment]
Hi, 

`vk::DispatchLoadDynamic` doesn't have a direct equivalent in the C API. Effectively it is just a struct with function pointers. If you're looking for something similar in pure C, you can use https://github.com/zeux/volk or https://github.com/KhronosGroup/Vulkan-Utility-Libraries/blob/main/include/vulkan/utility/vk_dispatch_table.h which you can fill using `vkGetInstanceProcAddr`.

`vkGetInstanceProcAddr` can be confusing. Where are you getting `vkGetInstanceProcAddr` from? Are you linking against `libvulkan.so.1`/`vulkan.lib` or do you use dynamic loading? If using dynamic loading it might help to define `VK_NO_PROTOTYPES` since you need to get all function pointers through `vkGetInstanceProcAddr`/`vkGetDeviceProcAddr` and `vkGetInstanceProcAddr` from libvulkan.so.1. Please also have a look onto the behavior of https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetInstanceProcAddr.html for different input argument combinations.

> I need to get a tool as search for finding all stuffs in documentation in what is equivalent to C++ from C, any there has this feature ?

Can't you use the goto-definition feature of your IDE to see which C functions the C++ functions are using?

**Comment by threedslider** [comment]
Hi theHamsta,

I was following tutorial about for Vulkan in C++, the guy make this as I have posted above in example and the link is here : [https://youtu.be/Bsd9BtOoiNw?si=vFNp8uHHiJkwvnp3&t=625](url)

Do you know how to make it right for working with vkGetInstaceProcAddr ? Or You know if I can get equivalent to C in C++, I mean vkGetInstanceProcAddr to something with vk::function ... ? 

Thank you and I am working on Windows.

**Comment by theHamsta** [comment]
Vulkan gives you different choices on how you load your function pointer

Here is the definition of `vkGetInstanceProcAddr` https://github.com/KhronosGroup/Vulkan-Headers/blob/374f9fd97520f6dd1b80745de09208d878ab4a52/include/vulkan/vulkan_core.h#L4174-L4176.  As you can see it is defined as a function pointer. So it might be initially a `nullptr`. When you link against `vulkan.lib`/`vulkan.dll`, then the DLL should set this function pointer so you can use it. Assuming you use CMake...
```cmake
find_package(Vulkan REQUIRED)
# define your executable ...
target_link_library(foo_executable PUBLIC Vulkan::Vulkan)
```
You might also choose to dynamically load Vulkan.dll
```cmake
find_package(Vulkan REQUIRED)
# define your executable ...
target_link_library(foo_executable PRIVATE Vulkan::Headers)
# optional, you might choose to hide the definition of `vkGetInstanceProcAddr`
target_compile_definitions(foo_executable PRIVATE -DVK_NO_PROTOTYPES=1)
```
and then in your code
```c++
vk::DispatchLoaderDynamic dldi{ nullptr };
auto lib = LoadLibraryA("vulkan.dll"); // full path or library in %PATH% or current/application directory
auto myGetInstanceProcAddr = (PFN_vkGetInstanceProcAddr) GetProcAddress(lib, "vkGetInstanceProcAddr");
dldi = vk::DispatchLoaderDynamic(instance, myGetInstanceProcAddr);

// FreeLibrary when program shuts down
```

I would argue that the easiest way to use Vulkan-Hpp ist to use `VULKAN_HPP_DEFAULT_DISPATCHER` and follow the instructions in the README. Then, you don't need to explicitly deal with `dldi`

https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#extensions--per-device-function-pointers

> To use the vk::DispatchLoaderDynamic as the default dispatcher (means: you don't need to explicitly add it to every function call), you need to #define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1, and have the macro VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE exactly once in your source code to provide storage for that default dispatcher. Then you can use it by the macro VULKAN_HPP_DEFAULT_DISPATCHER, as is shown in the code snippets below.

**Comment by theHamsta** [comment]
Attached a minimal project that uses `VULKAN_HPP_DEFAULT_DISPATCHER`. It is made to test the feature with C++20 modules (requires CMake 3.28 release candidate). But you can refactor the code to use `#include <vulkan/vulkan.hpp` instead of `import vulkan_hpp;`

[dynamic_storage_modules_test.zip](https://github.com/KhronosGroup/Vulkan-Hpp/files/13423864/dynamic_storage_modules_test.zip)

**Comment by threedslider** [comment]
Hi theHamsta,

Thank you for your info 👍 
Ok I try this file that you provided me but I get error like : 
```
CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22631.
Configuring done (0.1s)
CMake Error at CMakeLists.txt:23 (target_sources):
  Cannot find source file:

    C:/VulkanSDK/1.3.243.0/Include/vulkan/vulkan.cppm


Generating done (0.1s)
```
I change to vulkan.hpp but another error saying problem of module...

**Comment by theHamsta** [comment]
> Hi theHamsta,
> 
> Thank you for your info 👍 Ok I try this file that you provided me but I get error like :
> 
> ```
> CMake Warning (dev) at CMakeLists.txt:1 (project):
>   cmake_minimum_required() should be called prior to this top-level project()
>   call.  Please see the cmake-commands(7) manual for usage documentation of
>   both commands.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22631.
> Configuring done (0.1s)
> CMake Error at CMakeLists.txt:23 (target_sources):
>   Cannot find source file:
> 
>     C:/VulkanSDK/1.3.243.0/Include/vulkan/vulkan.cppm
> 
> 
> Generating done (0.1s)
> ```
> 
> I change to vulkan.hpp but another error saying problem of module...

The newest release of Vulkan-Hpp is 1.3.270. Older versions don't have the C++20 module.

Would changing the CMakeLists.txt to
```
project(my-vulkan-module)

cmake_minimum_required( VERSION 3.20 )

if (MSVC)
    # warning level 4
    add_compile_options(/W4)
else()
    # additional warnings
    add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package( Vulkan REQUIRED )

add_executable(my-vulkan-module
    main.cpp
    myloader.cpp)
target_link_libraries(my-vulkan-module
    PRIVATE Vulkan::Vulkan)
target_compile_definitions(my-vulkan-module PRIVATE
    VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1)

set_target_properties(my-vulkan-module PROPERTIES
    CXX_STANDARD 20
    CXX_EXTENSIONS OFF
    )
```
work. Of course replaceing `import` with `#inlcude <vulkan/vulkan.hpp>`

**Comment by threedslider** [comment]
Oh well I have updated the new version 1.3.268 and still not working, sorry I don't know how to fix that...
My link from my source code that I was following in Youtube tutorial is here : [Vulkan-test](https://drive.google.com/drive/folders/1-OqrPmWX52jhsLjAAdRwwi-0fiYb6pm0?usp=sharing) it is a zip file and it contains all source codes maybe you can look at this and how to fix that this function vkGetInstanceProcAddr.

**Comment by theHamsta** [comment]
Your code works just fine for me with two changes:
- don't use ` vk::DispatchLoaderDynamic dldi{ nullptr };` in engine.h. This will trigger an assertion. Use the default constructor (no arguments) or use `std::optional` to indicate that the dispatcher is not yet initialized.
```
	// setting dldi {null} will trigger the following, assert just use the default contructor
	//│    14742     void init( PFN_vkGetInstanceProcAddr getInstanceProcAddr ) VULKAN_HPP_NOEXCEPT                                                                                        │
	//│    14743     {                                                                                                                                                                     │
	//│  > 14744       VULKAN_HPP_ASSERT( getInstanceProcAddr );                                                                                                                           │
```
- add `extensions.emplace_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);` to your instance extension. The debug messenger will try to use [vkCreateDebugUtilsMessengerEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateDebugUtilsMessengerEXT.html) which is a part of this instance extension https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_debug_utils.html

You can use Git to see which changes I did. In the end the engine told me:
```
Goodbye see you !
```
[vulkan_test_gipa.zip](https://github.com/KhronosGroup/Vulkan-Hpp/files/13445098/vulkan_test_gipa.zip)

**Comment by threedslider** [comment]
Ok thank you a lot for your help, I understand more from your change and it works well ! 👍 

Yes I am closing now, you are the best  ;)

**Comment by theHamsta** [comment]
> Ok thank you a lot for your help, I understand more from your change and it works well ! 👍
> 
> Yes I am closing now, you are the best ;)

Is it also working for you?
