### ISSUE TITLE
Trouble on running application compiled with GCC 11.4.0

### ISSUE THREAD

**Issue by Pacheco95** [KhronosGroup/Vulkan-Hpp#1736]
Hey guys. This is propably not a problem with Vulkan itself, but I think you can help me with this.
This code below compiles without errors or warnings in both CLang 17 and GCC 11.4.0, but running the GCC binary results in strange behaviors while in CLang everything works as expected.

If I change `const auto& viewport` to `const auto viewport` it works.
Do you have any idea why const reference to temporary variable works in CLang but GCC don't?

```c++
#include <iostream>
#include <vulkan/vulkan.hpp>

void printViewPorts(const vk::ArrayProxy<vk::Viewport>& viewports) {
  for (const auto& viewport : viewports) {
    std::cout << "x: " << viewport.x << std::endl
              << "y: " << viewport.y << std::endl
              << "width: " << viewport.width << std::endl
              << "height: " << viewport.height << std::endl
              << "minDepth: " << viewport.minDepth << std::endl
              << "maxDepth: " << viewport.maxDepth << std::endl;
  }
}

int main() {
  const auto& viewport =
      vk::Viewport()
          .setX(0.0f)
          .setY(0.0f)
          .setWidth(800)
          .setHeight(600)
          .setMinDepth(0.0f)
          .setMaxDepth(1.0f);

  printViewPorts(viewport);

  return 0;
}
```

CLang output:

```
x: 0
y: 0
width: 800
height: 600
minDepth: 0
maxDepth: 1
```

GCC output:

```
x: 1.4013e-45
y: 0
width: 7.53808e+28
height: 4.59149e-41
minDepth: 0
maxDepth: 1
```

**Comment by theHamsta** [comment]
I can reproduce (with g++11 and g++13). Maybe there is some UB in `vk::ArrayProxy` that GCC interprets in a different way. Interestingly the output is the same when using `-O0` to disable all optimizations.

**Comment by theHamsta** [comment]
It's interesting what GCC actually does for `const auto& viewport` (Ghidra decompilation). It seems to use this constructor  https://github.com/KhronosGroup/Vulkan-Hpp/blob/1620b8b0bf9daacae6394e682b2db5946230a175/vulkan/vulkan.hpp#L279-L283
```c++

undefined8 main(void)

{
  long in_FS_OFFSET;
  ArrayProxy<> local_38 [16];
  undefined4 local_28;
  undefined4 local_24;
  float local_20;
  float local_1c;
  undefined4 local_18;
  undefined4 local_14;
  long local_10;
  
  local_10 = *(long *)(in_FS_OFFSET + 0x28);
  local_28 = 0;
  local_24 = 0;
  local_20 = 800.0;
  local_1c = 600.0;
  local_18 = 0;
  local_14 = 0x3f800000;
  vk::ArrayProxy<>::ArrayProxy(local_38,(Viewport *)&local_28);
  printViewPorts((ArrayProxy *)local_38);
  if (local_10 != *(long *)(in_FS_OFFSET + 0x28)) {
                    /* WARNING: Subroutine does not return */
    __stack_chk_fail();
  }
  return 0;
}
```
while with `const auto viewport`
```

undefined8 main(void)

{
  Viewport *pVVar1;
  long in_FS_OFFSET;
  Viewport local_28 [24];
  long local_10;
  
  local_10 = *(long *)(in_FS_OFFSET + 0x28);
  vk::Viewport::Viewport(local_28,0.0,0.0,0.0,0.0,0.0,0.0);
  pVVar1 = (Viewport *)vk::Viewport::setX(local_28,0.0);
  pVVar1 = (Viewport *)vk::Viewport::setY(pVVar1,0.0);
  pVVar1 = (Viewport *)vk::Viewport::setWidth(pVVar1,800.0);
  pVVar1 = (Viewport *)vk::Viewport::setHeight(pVVar1,600.0);
  pVVar1 = (Viewport *)vk::Viewport::setMinDepth(pVVar1,0.0);
  pVVar1 = (Viewport *)vk::Viewport::setMaxDepth(pVVar1,1.0);
  vk::ArrayProxy<>::ArrayProxy((ArrayProxy<> *)local_28,pVVar1);
  printViewPorts((ArrayProxy *)local_28);
  if (local_10 != *(long *)(in_FS_OFFSET + 0x28)) {
                    /* WARNING: Subroutine does not return */
    __stack_chk_fail();
  }
  return 0;
}
```

**Comment by Pacheco95** [comment]
> So viewport in main would refer to a valid object. The RHS of the assignment is only valid for this one statement. So you're not allowed to take a reference to it.

That's what I read on my researchs, my curiosity here is that CLang compiles it to a perfectly working binary, but GCC don't.
And even enabling compiler warnings `-Wall -Wextra -Wpedantic` the compiler does not complain about this.

**Comment by Pacheco95** [comment]
> Maybe there is some UB in vk::ArrayProxy that GCC interprets in a different way

What do you mean about "UB"?

**Comment by theHamsta** [comment]
> > Maybe there is some UB in vk::ArrayProxy that GCC interprets in a different way
> 
> What do you mean about "UB"?

Undefined behavior. For instance when using a referencing a object out of it's lifetime. Compiler will then just do random, "undefined" things. The life time of an object defined as a variable is to the end of the scope. The lifetime of a temporary R-value (like any expression on the right-hand side of an expression is for this statement.

Closing this. Feel free to reopen when you think something is wrong with the library.
