### ISSUE TITLE
Question about DEFAULT_DYNAMIC_LOADER

### ISSUE THREAD

**Issue by swhoro** [KhronosGroup/Vulkan-Hpp#1737]
I notice in example, there is a code like this: https://github.com/KhronosGroup/Vulkan-Hpp/blob/64539664151311b63485a42277db7ffaba1c0c63/tests/DispatchLoaderDynamic/DispatchLoaderDynamic.cpp#L33C5-L33C42

But if I don't pass in any arguments inmy code, the compiler gets an error:
![image](https://github.com/KhronosGroup/Vulkan-Hpp/assets/34229589/c4d06ffc-b36b-4cae-8c65-8e6b651591fc)

**Comment by theHamsta** [comment]
Can you try this minimal project https://github.com/KhronosGroup/Vulkan-Hpp/issues/1735#issuecomment-1820483892 with CMake 3.28 prerelease (or refactor to not use c++20 modules)?

The macros are defined here https://github.com/KhronosGroup/Vulkan-Headers/blob/374f9fd97520f6dd1b80745de09208d878ab4a52/include/vulkan/vulkan_hpp_macros.hpp#L234-L258

Have you defined `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1` for your whole project? Have you included `vulkan/vulkan.hpp` in the file where you use `VULKAN_HPP_DEFAULT_DISPATCHER`?

https://github.com/KhronosGroup/Vulkan-Hpp/blob/1620b8b0bf9daacae6394e682b2db5946230a175/README.md#L546-L549

**Comment by swhoro** [comment]
> Can you try this minimal project https://github.com/KhronosGroup/Vulkan-Hpp/issues/1735#issuecomment-1820483892 with CMake 3.28 prerelease (or refactor to not use c++20 modules)?
> 
> The macros are defined here https://github.com/KhronosGroup/Vulkan-Headers/blob/374f9fd97520f6dd1b80745de09208d878ab4a52/include/vulkan/vulkan_hpp_macros.hpp#L234-L258
> 
> Have you defined `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1` for your whole project? Have you included `vulkan/vulkan.hpp` in the file where you use `VULKAN_HPP_DEFAULT_DISPATCHER` (not only vulkan_hpp_macros.hpp)?
> 
> https://github.com/KhronosGroup/Vulkan-Hpp/blob/1620b8b0bf9daacae6394e682b2db5946230a175/README.md#L546-L549

1. I cannot compile this project. It reports like this:
![{C34CBA7D-5657-4ed1-B521-4C83A9BE6487}(1).png](https://github.com/KhronosGroup/Vulkan-Hpp/assets/34229589/96197995-65d0-4c75-94ca-caf6a328389b)

2. Yes, I am sure I have defined `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC` with `add_definitions` in cmakelists and included vulkan.cpp

**Comment by swhoro** [comment]
It was my fault. I use an old version of vulkan.
After upgrading, it works fine.
