### ISSUE TITLE
Wasted Memory in Structs?

### ISSUE THREAD

**Issue by Neev-Kataria** [KhronosGroup/Vulkan-Hpp#1738]
I used pvs studio on my vulkan project and it showed hundreds of structs with member variables not sorted in decreasing order of their size and wasting a lot of memory due to padding. Is it intentional, if so why?
![Screenshot 2023-11-27 211055](https://github.com/KhronosGroup/Vulkan-Hpp/assets/63790933/b41c279a-03c5-41c1-acb3-d0b4fc1c51dc)

**Comment by theHamsta** [comment]
Thank you for raising this issue vulkan_core.h is part of the C headers that are generated according to the Vulkan Spec XML https://github.com/KhronosGroup/Vulkan-Docs/. Most struct of vulkan.hpp are generated to be ABI compatible to the C counterparts. So it's not possible for us to change the layout.

The layout of the structs will change automatically when upstream changes the spec XML. But they probably won't do this step to maintain ABI breakage. Feel free to raise your issue at https://github.com/KhronosGroup/Vulkan-Docs/. If you think that struct layout could be improved for structs/classes specific to vulkan.hpp please raise an issue specific to that structs. At the moment, we the order of the members are mainly determined to optimize for readability/API conventions

Structs by the Vulkan specs are usually not kept on the heap. So there should not be any waste of RAM or worse cache locality here when keeping large arrays or dicts of those structs. The main cost of larger structs on the stack to be passed as function arguments would be additional instructions to fill the padding (additional `push` or decrements of the stack pointer). Have you compared disassembly whether reordering would generate substantially better instructions?
