### ISSUE TITLE
Something changed recently in Vulkan-Hpp that's breaking vulkan spec CI

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1760]
Starting about 13-14 hours ago, all the hpp-compile stages in internal gitlab vulkan CI are failing. I re-ran a previously successful hpp-generate / hpp-compile stage (https://gitlab.khronos.org/vulkan/vulkan/-/pipelines/60077) as a test, and it failed as well. Presumably the recent commit caused this.

**Comment by asuessenbach** [comment]
#1762 Resolved this issue.
