### ISSUE TITLE
Repeated depends= in require tags should be allowed

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1764]
E.g. https://gitlab.khronos.org/vulkan/vulkan/-/jobs/513529 is failing in the hpp-generate stage with

> caught exception: VulkanHppGenerator: Spec error on line 23909: required extension <VK_KHR_push_descriptor> already listed

but there's nothing wrong with this usage - the require tags are sometimes used as a logical grouping mechanism so it's plausible someone would wish to have the same dependency on two require tags. Perhaps you could coalesce them if this is a limitation of the generator tool?

**Comment by asuessenbach** [comment]
Ok, I can easily downgrade that error into a warning.
But I think, it would keep the xml file in a better (human-)readable state if something like that would not be allowed.
