### ISSUE TITLE
minwindef.h and vulkan.hpp compilation errors on windows 11, MSVC, c++20 and vulkan 1.3.275

### ISSUE THREAD

**Issue by roberttenche** [KhronosGroup/Vulkan-Hpp#1775]
When including "Windows.h" before "vulkan/vulkan.hpp" I get these following errors:
![image](https://github.com/KhronosGroup/Vulkan-Hpp/assets/76185318/29d15bfa-760b-4154-a1d8-a3142e83c50e)

The error comes from this std::min where min gets overwritten by minwindef.h
![image](https://github.com/KhronosGroup/Vulkan-Hpp/assets/76185318/e5ddf006-4de8-4591-9a28-d87730396ca2)
![image](https://github.com/KhronosGroup/Vulkan-Hpp/assets/76185318/e3231cec-75fb-464b-85ca-e2c3ec3d3736)

A a solution would be to add parenthesis surrounding std::min (reference https://stackoverflow.com/questions/22744262/cant-call-stdmax-because-minwindef-h-defines-max)
![image](https://github.com/KhronosGroup/Vulkan-Hpp/assets/76185318/4aea68c6-41ba-4dd2-bc35-0e948809b613)

I hope I'm not duplicating this issue, from what I searched it was not mentioned before.
As mentioned in the stackoverflow link, NOMINMAX can also be defined by me to fix it, but I think this would be a nice fix if it doesn't break anything else.

**Comment by sharadhr** [comment]
> NOMINMAX can also be defined by me to fix it

I believe this is the better fix. 

`Windows.h` is a pretty bad citizen when it comes to macro pollution, and things like `NOMINMAX` and `WIN32_LEAN_AND_MEAN` are almost required to have a decent experience.

**Comment by asuessenbach** [comment]
I agree with @sharadhr: defining NOMINMAX is the better approach.
I'd consider adding parenthesis around each std::min and std::max be a bad move, though, as that would require work in potentially every file you're using.

**Comment by roberttenche** [comment]
sure, makes more sense this way actually
thanks for the advice 👍
