### ISSUE TITLE
build failure with null-terminated static array members

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1777]
In internal MR https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6448 I'm seeing CI failure in the hpp-generate stage. I'm not sure, but this is probably because the point of the MR is to allow 'len' attributes to be used and well-defined WRT struct members that are arrays of static size, including 'len="null-terminated"' for static arrays containing strings (as quite a few do). We'd like to get this merged within a week or two, so if you're able to resolve this, that would help.

**Comment by asuessenbach** [comment]
That's a great addition!
That 'len' attribute allows some nice little improvements for Vulkan-Hpp.
Thanks for introducing it.

**Comment by oddhack** [comment]
This does now pass the hpp-generate stage, but there are a lot of errors in the hpp-compile stage - can you look at that as well (same MR as linked above)?

**Comment by asuessenbach** [comment]
Resolved those errors as well with #1781, #1782, and #1782
