### ISSUE TITLE
Vulkan-hpp for extensions

### ISSUE THREAD

**Issue by billgan1024** [KhronosGroup/Vulkan-Hpp#1785]
Are there plans to create  a c++ port for extensions, e.g. VK_KHR_win32_surface?

**Comment by asuessenbach** [comment]
@billgan1024 I think, I don't get your question. All extensions are already part of Vulkan-Hpp.

**Comment by theHamsta** [comment]
Platform extensions like VK_KHR_win32_surface are guarded with the same macros as they are in vulkan.h (`VK_USE_PLATFORM_....`) in case you don't see them enabled by default.

**Comment by asuessenbach** [comment]
I assume, this issue can be closed, then.
