### ISSUE TITLE
bad implementation of getFaultInfoEXT in vk::Device and vk::raii::Device 

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1786]
The `vkGetDeviceFaultInfoEXT` is a enumerate-like function.

It should be called twice (query size + query data), but it is called like a normal non-enumerate function.

**Comment by asuessenbach** [comment]
Indeed, documentation says, you're right!
Unfortunately, that expected behaviour can not be identified through vk.xml, the ground truth for Vulkan-Hpp. I'll see, if I can add some exceptional handling for that function.
