### ISSUE TITLE
Line rendering example

### ISSUE THREAD

**Issue by lobneroO** [KhronosGroup/Vulkan-Hpp#1794]
Is there an example for line rendering somewhere? I couldn't find any sample code so far, but rendering lines would be helpful in contexts like ray tracer debugging or graph creation.

I have found the documentation regarding some of the necessary objects, but it is not clear to me yet, how to set this up. E.g. the [rasterization](https://registry.khronos.org/VulkanSC/specs/1.0-extensions/man/html/VkPipelineRasterizationLineStateCreateInfoEXT.html) for lines needs to be set up as `pNext` pointer of a pipeline rasterization, but does that require the pipeline rasterization to be set up in a specific way?

**Comment by lobneroO** [comment]
I am trying to render a line(/vector) in 3D space. Not a wireframe, i.e. not lines of triangles, but of two points. In my case, I just want to debug rays in a ray tracer and visualizing a few may be a great help. It's obviously not as trivial as just connecting the start and end of every ray, but to get anything going at all, I need to render a line between to points in 3D space and have a depth test enabled.

**Comment by asuessenbach** [comment]
Would `vk::PrimitiveTopology::eLineList` in the `vk::PipelineInputAssemblyStateCreateInfo` (or `vk::CommandBuffer::setPrimitiveTopology()` when corresponding dynamic state is set) and `vk::PipelineRasterizationStateCreateInfo::lineWidth` (or `vk::CommandBuffer::setLineWidth()` when the corresponding dynamic state is set) do what you need?

**Comment by lobneroO** [comment]
I can't say if that is a solution to my problem right now, I'll have to implement it to check. 
So far I had been trying to implement a solution including a new pipeline with the Rasterizaer containing a `VkPipelineRasterizationLineStateCreateInfoEXT` but I am not at a point of rendering this new pipeline yet. Though if your suggestion suffices, I'm not sure why (/what for) I should use the `VkPipelineRasterizationLineStateCreateInfoEXT` . What would it do that your suggestion does not?

**Comment by lobneroO** [comment]
Sorry for the delay. Finally got round to work on it and get the first results. The suggested solution works, and I do get a line on screen. I still think, it'd be neat to have an example (e.g. draw a histogram or something like that).
Either way, thank you for the help!

**Comment by asuessenbach** [comment]
Maybe you could file an issue requesting for such a sample on https://github.com/KhronosGroup/Vulkan-Samples.
