### ISSUE TITLE
cast of  const void* to void* in  vk::StructureChain::assign

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1797]
vk::StructureChain::assign is implemented as:
```
T &    lhs   = get<T, Which>();
void * pNext = lhs.pNext;
lhs          = rhs;
lhs.pNext    = pNext;
return *this;
```

but `lhs.pNext` may be `const void*`.
Note that `lhs.pNext` may also be `void*`, so I would suggest using `auto`.

**Comment by asuessenbach** [comment]
Thanks for spotting this issue!
Will be fixed right now.
