### ISSUE TITLE
VULKAN_HPP_TYPESAFE_CONVERSION cannot be set to 0 to disable implicit conversions

### ISSUE THREAD

**Issue by d235j** [KhronosGroup/Vulkan-Hpp#1801]
The manual currently states the following at https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#cc-interop-for-handles:

> On 64-bit platforms this define is set to 1 by default and can be set to 0 to disable implicit conversions.

The headers use
`#if defined(VULKAN_HPP_TYPESAFE_CONVERSION)`,

which will return true regardless of what VULKAN_HPP_TYPESAFE_CONVERSION is set to as long as it's defined. Defining an identifier as 0 does not undefine it.

This needs to be changed to

`#if (VULKAN_HPP_TYPESAFE_CONVERSION == 1)`. 

Similarly, the code that defines it if undefined needs to be changed.

I can prepare a PR if desired.

**Comment by asuessenbach** [comment]
You're right, docu and code don't fit together.
And we think, changing the code accordingly would be the right move. Would be great, if you could prepare a PR on it.
