### ISSUE TITLE
Macros in minwindef.h prevent compilation of vulkan-hpp if using VK_USE_PLATFORM_WIN32_KHR 

### ISSUE THREAD

**Issue by tlegoc** [KhronosGroup/Vulkan-Hpp#1804]
Hi,
As the title says, I have problems compiling my project on windows if I use VK_USE_PLATFORM_WIN32_KHR.
Precisely, when I include vulkan.hpp and use this define, there's a min macro that gets defined and prevents the usage of std::min.
I tried searching, and found #600 that could be related but it was solved so I guess this isn't what I was looking for.

My code is very basic, I use SDL2+Vulkanhpp, and VK_USE_PLATFORM_WIN32_KHR is only defined in one cpp file so I can use `vk::PhysicalDevice::getWin32PresentationSupportKHR`. 

I use VS2022 and MSVC with cmake, and the LunarG SDK 1.3.275 which comes with vulkan-hpp. Note that this error wasn't triggered on SDK version 1.3.268.

Thanks a lot.

**Comment by asuessenbach** [comment]
It's #1775, that this issue popped up the last time :(
The resolution on this issue is: define NOMINMAX before including minwindef.h.

**Comment by tlegoc** [comment]
Amazing it fixed it. Thanks a lot !
