### ISSUE TITLE
Compiler error for VULKAN_HPP_HAS_SPACESHIP_OPERATOR

### ISSUE THREAD

**Issue by BehroozRezvani** [KhronosGroup/Vulkan-Hpp#1812]
This might be a user error but I am building the Vulkan-Headers inside my project with MSVC and getting an error that "'return': cannot convert from 'std::partial_ordering' to 'std::strong_ordering'".

Is this something about MSVC or is it an actual error?

"[build] \vendor\Vulkan-Headers\include\vulkan/vulkan_structs.hpp(77532): error C2440: 'return': cannot convert from 'std::partial_ordering' to 'std::strong_ordering'"

**Comment by asuessenbach** [comment]
This has been fixed with #1808.
