### ISSUE TITLE
Support multiple XML <formats> tags

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1813]
Internal MR 3789 is doing this, which is allowed by the RNC schema, but the registry schema document states that only one is allowed and this results in a "required element <formats> is supposed to be listed exactly once, but is listed 2" error.

This is being used as a grouping mechanism, but note that 3789 also updates the format traversal code in the Python scripts to only operate on <format> tags whose corresponding format name enum is required by the targets being built. This is to provide mechanical documentation of ASTC 3D formats that are not currently used by Vulkan itself, but are present in a disabled extension for use by KTX.

**Comment by asuessenbach** [comment]
Resolved with #1814.
