### ISSUE TITLE
How to enable khronos_validation.validate_gpu_based and khronos_validation.printf_to_stdout using vk::LayerSettingEXT

### ISSUE THREAD

**Issue by vojtadavid** [KhronosGroup/Vulkan-Hpp#1818]
How VkLayerSettingEXT should look like to enable khronos_validation.validate_gpu_based and khronos_validation.printf_to_stdout, because there is no VK_LAYER_SETTING_TYPE\_\*\_EXT for enums.

I am referring to https://vulkan.lunarg.com/doc/sdk/1.3.275.0/linux/layer_configuration.html
and https://vulkan.lunarg.com/doc/view/1.3.250.1/linux/khronos_validation_layer.html

I tried with no luck

```
const char* layer_name = "VK_LAYER_KHRONOS_validation";
const char* gpu_based = "GPU_BASED_DEBUG_PRINTF";
VkBool32 enable_stdout = true;
const vk::LayerSettingEXT settings[]
{
    {layer_name, "validate_gpu_based", vk::LayerSettingTypeEXT::eString, 1, &gpu_based},
    {layer_name, "printf_to_stdout", vk::LayerSettingTypeEXT::eBool32, 1, &enable_stdout},
};
vk::LayerSettingsCreateInfoEXT layer_settings_create_info{static_cast<uint32_t>(std::size(settings)),settings,nullptr};
```

**Comment by asuessenbach** [comment]
I would write it slightly different:
```
    const char *                     layer_name    = "VK_LAYER_KHRONOS_validation";
    const char *                     gpu_based     = "GPU_BASED_DEBUG_PRINTF";
    bool                             enable_stdout = true;
    std::vector<vk::LayerSettingEXT> settings{
      { layer_name, "validate_gpu_based", vk::LayerSettingTypeEXT::eString, 1, &gpu_based },
      { layer_name, "printf_to_stdout", vk::LayerSettingTypeEXT::eBool32, 1, &enable_stdout },
    };
    vk::LayerSettingsCreateInfoEXT layer_settings_create_info{ settings };
```
But I don't get your question. Do you get compiler/linker errors? Or do you not get the expected functionality from the validation layer?

**Comment by vojtadavid** [comment]
I want to enable debugPrintfEXT from vulkan shaders and redirect that output to stdout. Here is code that demonstrates that [(https://gist.github.com/vojtadavid/3f90d8a65bbf2081139dda8d80ec78c4).](https://gist.github.com/vojtadavid/3f90d8a65bbf2081139dda8d80ec78c4) But when I run the code there is no output from shader. In order to see any output from shaders I must use vulkan configurator to override vulkan layers and enable Debug printf  and redirect printf messages to stdout. I just don't want to it like that. I want to set those two settings programmatically.

In this overview of khronos validation layer and its options https://vulkan.lunarg.com/doc/view/1.3.250.1/linux/khronos_validation_layer.html **khronos_validation.validate_gpu_based** has type ENUM but there is no vk::LayerSettingTypeEXT::eEnum

**Comment by asuessenbach** [comment]
Maybe you just need to also enable extension `VK_EXT_LAYER_SETTINGS_EXTENSION_NAME`, to use the layer settings.
Besides that, you could use `vk::ValidationFeaturesEXT`, instead, with `vk::ValidationFeatureEnableEXT::eDebugPrintf` (and enabling `VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME`).

**Comment by asuessenbach** [comment]
Assuming, this is resolved.
