### ISSUE TITLE
code completion in XML files became very slow

### ISSUE THREAD

**Issue by prinss** [KhronosGroup/Vulkan-Hpp#1820]
When I upgraded android studio, code completion in XML files became very slow

**Comment by prinss** [comment]
Is there a great god to guide how to solve it ?      I tried everything I could think of, including adding more memory and changing the studio Settings

**Comment by asuessenbach** [comment]
I'm not sure what you're asking for here. Is it one specific XML file used in this repo, or is it with any XML file (with similar size)?
Maybe, you should ask for help in some android studio forum?

**Comment by asuessenbach** [comment]
Assuming this is resolved.
