### ISSUE TITLE
Do you use the feature number= XML attribute?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#1825]
@asuessenbach I'm thinking about replacing the \<feature number="1.x"> attribute in the XML with an explicit \<feature depends="dependency expression"> attribute instead, as people are using the 'number' to infer information it isn't intended to provide(*). Do you make any use of the 'number' attribute in Vulkan-Hpp?

(*) Literally all we intended it for was to established a fixed order in which feature tags are emitted by our generator scripts. The specific numeric value is irrelevant to this.

**Comment by asuessenbach** [comment]
@oddhack I don't know anything about the using of that 'number' in Ash.
But in Vulkan-Hpp it's just used in a check if it fits to the 'name' of the feature. Would be easy to remove.

**Comment by oddhack** [comment]
Thanks! Sorry, cut & paste error putting the same question in both repos. Fixed now.
