### ISSUE TITLE
PR 1829 causes build failures on 32-bit builds

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-Hpp#1833]
#1829 causes build failures on 32-bit builds.

On 32-bit builds VkDebugUtilsMessengerEXT and other non-dispatchable handle types map to unsigned long long.

This causes a compile error because there are repeated templates of CppType<unsigned long long, VK_NULL_HANDLE>

Example:
```
In file included from ./third_party/vulkan_headers/include/vulkan/vulkan.hpp:8684:
third_party/vulkan_headers/include/vulkan/vulkan_handles.hpp:2577:10: error: redefinition of 'CppType<unsigned long long, 0>'
 struct CppType<VkDebugReportCallbackEXT, VK_NULL_HANDLE>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/vulkan_headers/include/vulkan/vulkan_handles.hpp:2481:10: note: previous definition is here
 struct CppType<VkSurfaceKHR, VK_NULL_HANDLE>
        ^
third_party/vulkan_headers/include/vulkan/vulkan_handles.hpp:2667:10: error: redefinition of 'CppType<unsigned long long, 0>'
 struct CppType<VkDebugUtilsMessengerEXT, VK_NULL_HANDLE>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dneto0** [comment]
This bug might also depend on the Android NDK toolchain, and compiling to armeabi-v7a

**Comment by mikes-lunarg** [comment]
I'm also seeing it on Win32 https://github.com/KhronosGroup/Vulkan-Tools/actions/runs/8397499700/job/23000903779?pr=975

**Comment by asuessenbach** [comment]
Great catch!
Will guard that with `VK_USE_64_BIT_PTR_DEFINES`.
