### ISSUE TITLE
getSurfaceSupportKHR function dont have vk::raii::SurfaceKHR as an argument

### ISSUE THREAD

**Issue by ashwith2427** [KhronosGroup/Vulkan-Hpp#1835]
There is no function in vulkan_raii.hpp that takes vk::raii::SurfaceKHR as an argument there is only a single function getSurfaceSupportKHR that takes vk::SurfaceKHR as an argument

```
VULKAN_HPP_NODISCARD VULKAN_HPP_NAMESPACE::Bool32 getSurfaceSupportKHR(uint32_t queueFamilyIndex, VULKAN_HPP_NAMESPACE::SurfaceKHR surface) const;
```

**Comment by asuessenbach** [comment]
I think, I don't get what you're asking for.

There are a couple of member functions in `vk::raii::PhysicalDevice`, that take a `vk::SurfaceKHR` as argument.
That's in line with all the other functions of `vk::raii::Handle`s, that take (often as part of structures) `vk::Handle`s as arguments.
You can easily get the `vk::Handle` of a `vk::raii::Handle` by using the `operator*()` (`vk::SurfaceKHR = *raiiSurfaceKHR;`) or just by (implicitly) casting (`bool supports = physicalDevice.getSurfaceSupportKHR( graphicsQueueFamilyIndex, raiiSurface );`).

**Comment by asuessenbach** [comment]
Closing this, assuming it has been resolved.
