### ISSUE TITLE
throwResultException in public API

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-Hpp#1837]
I found throwResultException() function very useful. Could it possibly be considered to be part of the public Vulkan-HPP API? It used to be in vk namespace but it was moved to vk::detail namespace some time ago, e.g. it was made a part of internal implementation.

Typical use case:

	vk::Result r = presentationQueue.presentKHR(&presentInfo);
	if(r != vk::Result::eSuccess) {
		if(r == vk::Result::eErrorOutOfDateKHR || r==vk::Result::eSuboptimalKHR) { [... recreate swapchain here ....] }
		else  vk::throwResultException(r, VULKAN_HPP_NAMESPACE_STRING"::Queue::presentKHR");
	}

Sometimes, we do not want Vulkan-HPP just to throw on error, like in the case above. We may prefer to get vk::Result, handle the most typical cases, like eErrorOutOfDateKHR and eSuboptimalKHR, and handle the rest of errors (eErrorDeviceLost, and whatever may be returned) by calling throwResultException().

Alternative approaches I considered: Generating my own switch of throws or my own throwResultException seems not so nice compared to having it covered already in Vulkan-HPP API. Using vk::resultCheck() instead seems a little misleading on this place. It does not express the real intention that is not to check result but to throw vk exception. The resultCheck() has also overhead of one additional if.

**Comment by asuessenbach** [comment]
Maybe you want to do something like
try
{
}

**Comment by asuessenbach** [comment]
> Could it possibly be considered to be part of the public Vulkan-HPP API?

Let us think about it. But I'm not sure.
Maybe, 'til then, you could do something like that:
```
    try
    {
      result = presentQueue.presentKHR( presentInfoKHR );
      switch ( result )
      {
        case vk::Result::eSuccess: break;
        case vk::Result::eSuboptimalKHR: std::cout << "vk::Queue::presentKHR returned vk::Result::eSuboptimalKHR !\n"; break;
        default: assert( false );  // an unexpected result is returned !
      }
    }
    catch (vk::OutOfDateKHRError)
    {
      std::cout << "vk::Queue::presentKHR returned vk::Result::eErrorOutOfDateKHR!\n";
    }
```

**Comment by pc-john** [comment]
Concerning your suggestion, I am trying to avoid throw for regular events (like OutOfDateKHRError) for high throw overhead. It is from far not like single if. So, if I am going to show error dialog, I really do not take care about throw overhead and the overhead of throw propagation. But for OutOfDateError, it is a kind of standard situation and not the exceptional one. I would prefer to handle it through standard if. I follow the rule no exceptional situation => no exceptions. I do not know if it makes a sense to you, but I would prefer to stick with if for OutOfDateKHRError. Among others, I also like that the code I presented is much shorter (and maybe more readable) than when using exceptions, but it might depend on preference.

Surely, the decision is on you. Take your time for consideration. I am sticking with old headers in the meantime.

**Comment by asuessenbach** [comment]
Well, I think, that `throwResultException` really is some implementation detail.
Even though it seems to be very unlikely that it will change anytime soon, it might. And it could change without further notice.
That is, I'd like to keep it in the `vk::detail` namespace.
But I think, there's no problem to use it just like that: call `vk::detail::throwResultException()`. Makes clear that you're using some implementation detail and you're responsible to keep it valid.
And regarding the `vk::resultCheck()`: That will probably moved into `vk::detail` as well.

**Comment by pc-john** [comment]
I am probably the only person asking such thing at the moment. I felt it like API functionality that helps writing Vulkan code.

Anyway, thanks for consideration.

**Comment by maxime-modulopi** [comment]
@asuessenbach We also used `vk::resultCheck` in our code, notably for VMA functions which also return a `VkResult` but are not encapsulated by Vulkan-HPP.
It was really useful as a one-liner that smoothly translates error codes into corresponding Vulkan-HPP exceptions (+ it was also automatically kept up-to-date with future `VkResult` values).
