### ISSUE TITLE
Provide move constructor and move assignment to vk::handles

### ISSUE THREAD

**Issue by caiovpsilveira** [KhronosGroup/Vulkan-Hpp#1851]
Would it be possible to provide move constructors and move assignment to vk::handles such as vk::Instance, vk::Device, etc?

They already have a default constructor that sets their value to VK_NULL_HANDLE, m_handle = {};

I think it would be good to add with implementation of 
std::swap(handle, rhs.handle)

this way we could define move operations on classes containing these as default, and only worry about cleaning them in the destructor.

**Comment by asuessenbach** [comment]
That might be a good addition to the vk::handles... but they're already nothrow_move_constructible, as checked by a static_assertion in vulkan_static_assertions.hpp.

**Comment by caiovpsilveira** [comment]
Or this is intended to be handled this way? Should vk::Handles be treated like regular pointers?

**Comment by asuessenbach** [comment]
> Should vk::Handles be treated like regular pointers?

Yes, vk::Handles don't own anything. Otherwise, they would not be copyable.
If you want to manage ownership, you need to do it on your own or use something like vk::UniqueHandle, vk::SharedHandle, or vk::raii::Handle.
