### ISSUE TITLE
device.resetFence returning vk::Result even with exceptions enabled

### ISSUE THREAD

**Issue by caiovpsilveira** [KhronosGroup/Vulkan-Hpp#1854]
Hi,

Im using VulkanHPP with exceptions enabled and I noticed that device.resetFences is returning a vk::Result

From the vulkan specification for vkResetFences:

On success, this command returns
        VK_SUCCESS
On failure, this command returns
        VK_ERROR_OUT_OF_DEVICE_MEMORY

So, should't this be void? It's also marked as [[nodiscard]]

**Comment by caiovpsilveira** [comment]
It's also marked as noexcept.

But the device.resetFences(ArrayProxy<const vk::Fence>) is void, with exceptions

**Comment by asuessenbach** [comment]
You might have noticed, that there are two overloads of Device::resetFences:
```
    template <typename Dispatch = VULKAN_HPP_DEFAULT_DISPATCHER_TYPE>
    VULKAN_HPP_NODISCARD Result resetFences( uint32_t                            fenceCount,
                                             const VULKAN_HPP_NAMESPACE::Fence * pFences,
                                             Dispatch const & d                  VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT ) const VULKAN_HPP_NOEXCEPT;
#ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE
    template <typename Dispatch = VULKAN_HPP_DEFAULT_DISPATCHER_TYPE>
    typename ResultValueType<void>::type resetFences( VULKAN_HPP_NAMESPACE::ArrayProxy<const VULKAN_HPP_NAMESPACE::Fence> const & fences,
                                                      Dispatch const & d VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT ) const;
#endif /* VULKAN_HPP_DISABLE_ENHANCED_MODE */
```

The first one is more or less a one-to-one mapping of the wrapped C-function `vkResetFences`. I just calls that function and returns the result.
The second one is the "enhanced" version, that takes an `ArrayProxy` of fences and throws (if `VULKAN_HPP_NO_EXCEPTIONS` is not defined) on an error code.

So, do you still have a question on this?

**Comment by caiovpsilveira** [comment]
So I have to use the enhanced mode to enable exceptions, and for this I have to use the array proxy.

This will enable the enhanced mode: `device.resetFences({1, &fence})`;
But this won't: `device.resetFences(1, &fence);`

I see. I thought that vulkan.hpp exceptions were independent of the ArrayProxy. Thanks for the clarificantion.

Also there is a missing close par in the README:

VULKAN_HPP_DISABLE_ENHANCED_MODE
...
If this is not defined, you additionally get:
    enhanced versions of the commands (consuming vk::ArrayProxy<>,   <- here

**Comment by asuessenbach** [comment]
> This will enable the enhanced mode: `device.resetFences({1, &fence});`

And as the ArrayProxy also have a single-element constructor, you could as well write
`device.resetFences( fence );`

**Comment by asuessenbach** [comment]
> Also there is a missing close par in the README:

I can't find this... would you mind to file a pull request resolving that?

**Comment by caiovpsilveira** [comment]
Well, I tried, but I'm not that familiar with git. it's on line 873 col 66.

**Comment by asuessenbach** [comment]
> it's on line 873 col 66.

Ah, yes! Finally found it.
Thanks for reporting this little issue, will be fixed.
