### ISSUE TITLE
VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL and vulkan.cppm don't mix

### ISSUE THREAD

**Issue by oracleoftroy** [KhronosGroup/Vulkan-Hpp#1855]
Everywhere else where `VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL` is checked, it is checked against the value it expands to, e.g.:

```
#if VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL
...
#endif
```

See for example how the DynamicLoader class itself is protected:

https://github.com/KhronosGroup/Vulkan-Hpp/blob/1de6e89eb29bdb019eed2733fa7ed9fa72da08fa/vulkan/vulkan.hpp#L16677-L16679

This is because the value is forced to be defined to 1 if it isn't already set:
https://github.com/KhronosGroup/Vulkan-Hpp/blob/1de6e89eb29bdb019eed2733fa7ed9fa72da08fa/vulkan/vulkan_hpp_macros.hpp#L74-L76

However, the modules currently check whether it is defined at all:

https://github.com/KhronosGroup/Vulkan-Hpp/blob/1de6e89eb29bdb019eed2733fa7ed9fa72da08fa/vulkan/vulkan.cppm#L4678
https://github.com/KhronosGroup/Vulkan-Hpp/blob/1de6e89eb29bdb019eed2733fa7ed9fa72da08fa/vulkan/vulkansc.cppm#L1706

The immediate issue is that this should check the value, not whether it is defined.

The meta issue is that the whole "enable" system of vulkan hpp seems really weird. I shouldn't have to define `ENABLE_X=0` to disable feature X at all, the lack of a define should be enough. If it is default on, then provide a `DISABLE_X` macro. It really isn't surprising that this bug slipped through with the really unintuitive way these ENABLE macros are set up.

My ultimate goal is that I want to use vk::raii::Context with my own getInstanceProcAddr pointer since I already have it. It seems a bit weird to me that the constructor doesn't always exist, but I can see a train of thought that might justify that decision.

**Comment by sharadhr** [comment]
> The meta issue is that the whole "enable" system of vulkan hpp seems really weird. I shouldn't have to define ENABLE_X=0 to disable feature X at all, the lack of a define should be enough. If it is default on, then provide a DISABLE_X macro. It really isn't surprising that this bug slipped through with the really unintuitive way these ENABLE macros are set up.

Good point. I've been meaning to work though all these defines and first document them, and then clean them up. We've already made some effort in cleaning up the macros (https://github.com/KhronosGroup/Vulkan-Hpp/pull/1651), but like you said, it could be better. 

That being said, the immediate issue may be straightforwardly resolved; I can submit a merge request for this real quick.

**Comment by oracleoftroy** [comment]
That commit looks good to me.

Not sure it's a problem, but I noticed it didn't update vulkansc.cppm. It looks like that uses the same code generator with a different option. Not sure if that's something you should do as part of this or if regenerating the source is something that happens at a release tooling level, but I figured I'd mention it just in case.

Thanks for your work!
