### ISSUE TITLE
How to create device on heap with vk::raii with NO_EXCEPTIONS enabled?

### ISSUE THREAD

**Issue by orion160** [KhronosGroup/Vulkan-Hpp#1862]
In the docs it gives this example wich uses the method to create a device
```cpp
// create a vk::raii::Device, given a vk::raii::PhysicalDevice physicalDevice and a vk::DeviceCreateInfo deviceCreateInfo
// when VULKAN_HPP_NO_EXCEPTIONS is defined and your using at least C++23
auto deviceExpected = physicalDevice.createDevice( deviceCreateInfo );
if ( deviceExpected.has_value() )
{
	device = std::move( *deviceExpected );
}
```

Is possible to allocate it on an pointer/smart?

As constructor is not exposed?

**Comment by asuessenbach** [comment]
As there's no constructor for the vk::raii objects when `VULKAN_HPP_NO_EXCEPTIONS` is defined, you can't allocate them on a smart pointer.
And the constructors are not exposed in that case, because they would need to throw an exception on error.

**Comment by orion160** [comment]
Though it can be move constructed
