### ISSUE TITLE
vk::su::createInstance() in Utils.cpp needs parameter for flags to support VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME

### ISSUE THREAD

**Issue by genkiyooka** [KhronosGroup/Vulkan-Hpp#1872]
I understand this applies on any platform wrapping a native API with Vulkan, in my case MoltenVK.

It is possible to pass VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME to vk::su::createInstance() however the flags value of vk::InstanceCreateFlagBits::eEnumeratePortabilityKHR must also be set in vk::InstanceCreateInfo struct which is created in makeInstanceCreateInfoChain (Utils.cpp).

**Comment by asuessenbach** [comment]
I think, you're asking to extend the functionality for `vk::su::createInstance`, right?
First, I want to restate, that the functions from the `vk::su` namespace (`su` here means "sample utilities"!) are not meant to be used in production code. They are made to just support the needs of the (very simple!) samples here.
But as this extension is that simple, I'll add it.
