### ISSUE TITLE
compilation error when including vulkan_enums.hpp by itself

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1881]
`vulkan_enums.hpp` does not include any headers, but uses defines such as `VULKAN_HPP_CONST_OR_CONSTEXPR` and many more. Furthermore it uses `std::underlying_type` without including `<type_traits>`.

Is this header just not intended to be included by itself?

**Comment by sharadhr** [comment]
> Is this header just not intended to be included by itself?

No, it is not; the interface to Vulkan-Hpp is one of `#include <vulkan.hpp>` or `import vulkan_hpp;`. The separation of headers is for all intents and purposes an implementation detail.

**Comment by qbojj** [comment]
ok
