### ISSUE TITLE
Allow destructuring of ResultValue with std::tie

### ISSUE THREAD

**Issue by HildarTheDorf** [KhronosGroup/Vulkan-Hpp#1882]
Currently it is possible to do the following as `ResultValue<T>` provides a cast operator to `std::tuple<vk:Result, T>`:
`const auto [acquireResult, imageIndex] = _device->acquireNextImageKHR(...);`.

I would like to be able to do this: `std::tie(std::ignore, _imageIndex) = _device->acquireNextImageKHR(...);`[^1] however it currently fails to compile.

As a work around I either have to `static_cast` the ResultValue to `std::tuple`, or write a helper function that does such. Would it be possible to alter `vk::ResultValue` to allow this implicitly?

[^1]: Note that the actual usefulness of ignoring the result of vkAcquireNextImageKHR is beyond the scope of this issue.

**Comment by sharadhr** [comment]
Ah, how nice would it be if C++ had built-in ignores like Rust or C#, then we could just write `auto const& [_, imageIndex] = ...`?

In the mean time, this sounds like a reasonable request, I'll work on it.

**Comment by qbojj** [comment]
@sharadhr This is already in C++26 https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2169r4.pdf

**Comment by cutieskye** [comment]
`std::tie(result, backBufferIndex) = swapchainData.swapchain.acquireNextImage(...)` is an actual snippet from my C++20 sample...

**Comment by asuessenbach** [comment]
> Would it be possible to alter `vk::ResultValue` to allow this implicitly?

Yes, that would be possible.
But I doubt, it would be useful to have such a capability. Simplifying to ignore (part of) a `vk::ResultValue` is probably not the right move.
