### ISSUE TITLE
ObjectDeleter for Device and DeviceMemory not working

### ISSUE THREAD

**Issue by gartenriese2** [KhronosGroup/Vulkan-Hpp#189]
I think Device and DeviceMemory are using the wrong ObjectDeleter. 

Since Device destroys itself, it should be `template <> class UniqueHandleTraits<Device> {public: using deleter = ObjectDeleter<NoParent>; };` I think.

DeviceMemory must be freed instead of destroyed, so there needs to be another ObjectDeleter that uses free, like the PoolDeleter. What I did was add the following template specialization to ObjectDeleter:

`template <>
      void destroy(DeviceMemory t)
      {
        m_owner.free(t, m_allocator);
      }`

However I think it would be better to add a new ObjectDeleter (or maybe MemoryDeleter?).

If these issues are non-existant and I'm just using the wrapper wrong, then sorry, and I would like to know how to use it instead.

**Comment by asuessenbach** [comment]
Thanks for reporting those issues. They'll be fixed soon.

**Comment by YukinoHayakawa** [comment]
The deleter for Device still not seems to work. It passes a reference of PhysicalDevice to ObjectDestroy<NoParent>, which does not accept it.

**Comment by jeremyong** [comment]
I'm also seeing this in the latest 1.1.70.1 release. Was this resolved or is it pending release?

**Comment by mtavenrath** [comment]
Closing. The issue will be picked up by the next Vulkan SDK.
