### ISSUE TITLE
How to load function ptrs for enhanced mode

### ISSUE THREAD

**Issue by Findus79** [KhronosGroup/Vulkan-Hpp#19]
This is more like a C++ question:

When not using DISABLE_ENHANCED mode, there are methods like vk::Instance::createDebugReportCallbackEXT using vkCreateDebugReportCallbackEXT. This fails on my system with an unresolved external symbol for vkCreateDebugReportCallbackEXT.

How do I load the extension (VK_EXT_debug_report is supported on my system) so I can still use the enhanced mode?

**Comment by oceantume** [comment]
Sadly, the library from LunarG's SDK doesn't export symbols for extensions other than wsi and swapchain, so you will need to use instance's getProcAddress to dynamically link to the extension's functions. Vulkan-Hpp only wraps around the vulkan C headers and doesn't offer a type safe equivalent of the PFN_* functions, meaning you have to either use the c header directly and cast arguments from c++ wrappers to c definitions.

**Comment by Findus79** [comment]
Thanks for the heads up :)
