### ISSUE TITLE
ArrayProxy with designated initializers

### ISSUE THREAD

**Issue by barcharcraz** [KhronosGroup/Vulkan-Hpp#1909]
It seems like it should be possible for vulkan-hpp to generate structure types that look approximately like:

```c++
struct WhateverInfo {
  ...
   union {
     struct {
        uint32_t whateverThingsCount;
        whateverThing* pWhateverThings;
     };
     ArrayProxyNoTemporaries<whateverThing> whateverThings;
   };
};
```

or even just an option to generate ArrayProxy data members instead of the count and pointer members.

Is there interest in this?

Note: this relies on the commonly implemented extension where reading non-active union members is allowed. This isn't that relevant because you're using this extension across translation units (one of which is likely C), and vulkan-hpp is already fudging things in this area.

Edit: actually, reading the non-active union member is defined behavior, ArrayProxy and the anonymous struct have a common-initial-sequence. And casting this to the "normal" definition and reading from it is also (probably?) defined behavior because the two types should be layout-compatible (although the rules for layout compatibility between a struct and a union like this don't seem that well specified).

**Comment by asuessenbach** [comment]
That might indeed be a good idea.

But there are a couple of structs, where the `count` is used for multiple `things` pointers. In those structures, one such union would be surprising (why just that available via a union, not the other?). And multiple unions would not be identical to the corresponding C-struct any more.
That is, there would be structs with such unions and structs (here: with multiple pointers per count member) without, which again might be surprising.
Therefore, I think, I will not add that.

Nevertheless, thank you very much for your idea!
