### ISSUE TITLE
[c++20 module] getDispatchLoaderStatic is not available

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1927]
When using c++20 module without `VK_NO_PROTOTYPES`, `getDispatchLoaderStatic` is not exported, but it is required to be visible if someone wants to use it outside vulkan-hpp

**Comment by qbojj** [comment]
e.g the [VulkanMemoryAllocator-Hpp](https://github.com/YaaZ/VulkanMemoryAllocator-Hpp) project uses it to pull functions for use in VMA (https://github.com/YaaZ/VulkanMemoryAllocator-Hpp/blob/8335d9d6ff3574c89e6cf363ec1d279179f9b957/include/vk_mem_alloc.hpp#L130-L134)

**Comment by asuessenbach** [comment]
@qbojj Would you please verify that #2008 resolves your issue?
Thanks a lot!

**Comment by qbojj** [comment]
Will close after merge
