### ISSUE TITLE
[c++20 module] functions from vk::detail:: pulled into vk::

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Hpp#1928]
`vulkan.cppm` uses `namespace vk { ... using vk::detail::{createResultValue, ignore, resultCheck} ... }`, so those symbols are present in the `vk::` namespace instead of the original `vk::detail::`

**Comment by asuessenbach** [comment]
@sharadhr, could you please have a look on this issue?

**Comment by sharadhr** [comment]
Ideally these symbols shouldn't be exported at all, since they're in a `detail` namespace. It's pretty trivial to remove them, but it's worth testing that the module still works as expected without exporting these synbols.
