### ISSUE TITLE
Confusing deprecation of extensions

### ISSUE THREAD

**Issue by n0F4x** [KhronosGroup/Vulkan-Hpp#1935]
The _vulkan.hpp_ defines its own version of instance/device extension names. However, many of these are (I think wrongly) marked as deprecated due to being promoted to core.

A simple example is the following code snippet:
```cpp
VULKAN_HPP_DEPRECATED( "The VK_EXT_descriptor_indexing extension has been promoted to core in version 1.2." )
VULKAN_HPP_CONSTEXPR_INLINE auto EXTDescriptorIndexingExtensionName = VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME;
 ```

The compiler gives a warning in case someone wants to use these.
This is counter-productive when somebody wants to target lower Vulkan versions but finds out that an extension has been promoted in a newer version of Vulkan.

**Comment by asuessenbach** [comment]
You're right, extension that are promoted to a vulkan version are not meant to be deprecated. You might still use them, as you said, when you target a lower vulkan version.
Those deprecation attributes will be removed.
