### ISSUE TITLE
<vulkan/vulkan_hash.hpp> included in vulkan.cppm but std::hash specializations are not exported.

### ISSUE THREAD

**Issue by stripe2933** [KhronosGroup/Vulkan-Hpp#1943]
Looks like Clang can use them, but MSVC can't. Is it intended behavior?

**Comment by sharadhr** [comment]
I suppose we need to explicitly `export` the template specialisations. I haven't quite tested them; if you've got a minimum example that'd be great.

**Comment by asuessenbach** [comment]
@sharadhr If you're looking for some usage of the vk-hash functions, please have a look at the Hash test (`Vulkan-Hpp\tests\Hash\Hash.cpp`).

**Comment by asuessenbach** [comment]
@sharadhr Are you working on resolving this issue? Or could you give me some hint how I could do that?

**Comment by sharadhr** [comment]
I've been looking at it but I am not certain how to proceed. What I've done is write the following in `CppStdModule.cpp` (essentially copied the contents of `Hash.cpp` but replaced the `#include` lines with `import`), and try to compile it (assuming all CMake options are set correctly).

[CppStdModule.cpp.txt](https://github.com/user-attachments/files/17242407/CppStdModule.cpp.txt)

I then see, with `cl.exe`:
```
  C:\PROGRA~1\MIB055~1\2022\ENTERP~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe  /nologo /TP -DCLANG_FORMAT_EXECUTABLE=\"R:/Vulkan-Hpp/clang-format.exe\" -DNOMINMAX -DVK_USE_PLATFORM_WIN32_KHR -DVULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1 -DVULKAN_HPP_ENABLE_STD_MODULE -IR:\Vulkan-Hpp -IR:\Vulkan-Hpp\Vulkan-Headers\include -IR:\Vulkan-Hpp\glm -external:IR:\Vulkan-Hpp\vcpkg\installed\x64-windows\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob1 /DNDEBUG -std:c++latest -MD -Zi /W4 /WX /showIncludes @tests\CppStdModule\CMakeFiles\CppStdModule.dir\CppStdModule.cpp.obj.modmap /Fotests\CppStdModule\CMakeFiles\CppStdModule.dir\CppStdModule.cpp.obj /Fdtests\CppStdModule\CMakeFiles\CppStdModule.dir\ /FS -c R:\Vulkan-Hpp\tests\CppStdModule\CppStdModule.cpp
R:\Vulkan-Hpp\tests\CppStdModule\CppStdModule.cpp(41): error C2512: 'std::hash<vk::Instance>': no appropriate default constructor available
  R:\Vulkan-Hpp\tests\CppStdModule\CppStdModule.cpp(41): note: Invalid aggregate initialization
R:\Vulkan-Hpp\tests\CppStdModule\CppStdModule.cpp(52): error C2512: 'std::hash<vk::FormatFeatureFlags>': no appropriate default constructor available
  R:\Vulkan-Hpp\tests\CppStdModule\CppStdModule.cpp(52): note: Invalid aggregate initialization
  ninja: build stopped: subcommand failed.
```

**Comment by sharadhr** [comment]
@asuessenbach were you able to try my MWE?

**Comment by sharadhr** [comment]
I seem to have found a solution, based on [this mailing list thread](https://lists.isocpp.org/std-proposals/2021/06/2672.php), which says:

> MSVC implements an extension where writing "export template<...>" on a specialization (or putting the specialization in an export namespace/scope) will implicitly export the primary template and specializations from the current module, and multiple modules can contribute to specializations. It makes the snippets above work as one would expect.MSVC implements an extension where writing "expor template<...>" on a specialization (or putting the specialization in an export namespace/scope) will implicitly export the primary template and specializations from the current module, and multiple modules can contribute to specializations. It makes the snippets above work as one would expect.

So, I propose that in `vulkan.cppm`, we have something like:

```cpp
export namespace std
{
  template <>
  struct hash<VULKAN_HPP_NAMESPACE::Instance>;

  template <typename BitType>
  struct hash<VULKAN_HPP_NAMESPACE::Flags<BitType>>;

  template <>
  struct hash<VULKAN_HPP_NAMESPACE::AabbPositionsKHR>;

  template <>
  struct hash<VULKAN_HPP_NAMESPACE::AccelerationStructureBuildSizesInfoKHR>;

  template <>
  struct hash<VULKAN_HPP_NAMESPACE::AccelerationStructureBuildSizesInfoKHR>;

  template <>
  struct hash<VULKAN_HPP_NAMESPACE::ApplicationInfo>;

  template <>
  struct hash<VULKAN_HPP_NAMESPACE::InstanceCreateInfo>;
}
```

This makes my snippet compile correctly. I don't think we need to guard for compilers/platforms—the thread concludes by saying that such exports of template specialisations are legal on other compilers too.

**Comment by asuessenbach** [comment]
@sharadhr That's a great finding!
Thanks a lot for your investigations again.

Would you like to add that to the generator, or should I?

**Comment by sharadhr** [comment]
Would you be able to add it in? I could help with testing once it's ready!

**Comment by asuessenbach** [comment]
> I could help with testing once it's ready!

@sharadhr Thanks a lo for your help! Would be great if you could have a look at #1994, then.
