### ISSUE TITLE
Unable to create VkSurfaceKHR when following raii examples with cmake and vcpkg

### ISSUE THREAD

**Issue by jeffwhunter** [KhronosGroup/Vulkan-Hpp#1957]
Hey all!

I'm trying to follow the [Vulkan-Hpp::raii samples](https://github.com/KhronosGroup/Vulkan-Hpp/tree/main/RAII_Samples) with a cmake project that handles dependencies through vcpkg. Samples 1 through 4 work fine, but sample 5, creating a swapchain, blows up after failing to create a VkSurfaceKHR with glfwCreateWindowSurface, warning of missing VK_HKR_win32_surface. The context of the terminating code is:

```
// This warns 'glfw: (65542) Win32: Vulkan instance missing VK_KHR_win32_surface extension'
auto result{glfwCreateWindowSurface(static_cast<VkInstance>(*instance), window.handle, nullptr, &_surface)};
//_surface = 0x0000000000000000 <NULL>

vk::raii::SurfaceKHR surface(instance, _surface);
//surface = {m_instance={m_instance=0x000001c5c0830080 {...} } m_surface={m_surfaceKHR=0x0000000000000000 <NULL> } ...}

//terminates here
uint32_t presentQueueFamilyIndex = physicalDevice.getSurfaceSupportKHR(graphicsQueueFamilyIndex, surface)
    ? graphicsQueueFamilyIndex
    : checked_cast<uint32_t>(queueFamilyProperties.size());

std::println(std::cerr, "not printed");
```

I've rigged up a minimal example [here](https://github.com/jeffwhunter/minimumVulkanError). Any hints as to what I might be doing wrong? Or better build systems and package manager combos for vulkan/glfw than cmake/vcpkg?

**Comment by sharadhr** [comment]
The warning should be fairly illuminating. 

The list of extensions you're passing to the instance constructor doesn't have `VK_KHR_WIN32_SURFACE_EXTENSION_NAME` in it. That name is only defined if `VK_USE_PLATFORM_WIN32_KHR` is defined before it. Additionally I notice you've used `getInstanceExtensions()` function from the sample as-is, which only adds that extension to the list if  the latter macro, i.e. `VK_USE_PLATFORM_WIN32_KHR` is present, which you have not defined anywhere in your project nor in your CMake file. I suggest the following in your `CMakeLists.txt` line 38:

```diff
- target_compile_definitions(main PRIVATE NOMINMAX=1)
+ target_compile_definitions(main PRIVATE NOMINMAX=1 VK_USE_PLATFORM_WIN32_KHR)
```

Re-configure, re-compile, and your program runs correctly.

**Comment by jeffwhunter** [comment]
Well look at that! Thanks so much!
