### ISSUE TITLE
vk::StructureChain reporting invalid chain

### ISSUE THREAD

**Issue by M2-TE** [KhronosGroup/Vulkan-Hpp#1972]
There are some device features I would like to enable via the vk::PhysicalDevice[...]Features structs like this:
```
vk::StructureChain<
    vk::PhysicalDeviceMaintenance5FeaturesKHR,
    vk::PhysicalDeviceMemoryPriorityFeaturesEXT,
    vk::PhysicalDevicePageableDeviceLocalMemoryFeaturesEXT> chain;
```
but this fails as the StructureChainValidation<...>::valid evaluates to false:
```
vulkan.hpp:613:98: error: static assertion failed: The structure chain is not valid!
  613 |       static_assert( StructureChainValidation<sizeof...( ChainElements ) - 1, ChainElements...>::valid, "The structure chain is not valid!" );
```
Am I misunderstanding something more fundamental or is this erroneous behavior? There are no complaints from validation layers or otherwise, if chained normally via pNext.

**Comment by asuessenbach** [comment]
All those structs are supposed to extend `vk::PhysicalDeviceFeatures2`.
That is, you should start your chain with that struct:
```
vk::StructureChain<
    vk::PhysicalDeviceFeatures2
    vk::PhysicalDeviceMaintenance5FeaturesKHR,
    vk::PhysicalDeviceMemoryPriorityFeaturesEXT,
    vk::PhysicalDevicePageableDeviceLocalMemoryFeaturesEXT> chain;
```

**Comment by M2-TE** [comment]
Ah damn.. that makes sense. Sorry for taking up your time and thanks!
