### ISSUE TITLE
How to use Vulkan-HPP ?

### ISSUE THREAD

**Issue by bioorg** [KhronosGroup/Vulkan-Hpp#1977]
Hello,
I succeeded in building two Microsoft Windows executable files from here

VideoHppGenerator.exe
VulkanHppGenerator.exe

But I don’t know how to use them and for what I can do

So could you please introduce to me

how to use Vulkan-HPP and what I can do using this

Should I include and link this Vulkan-HPP here in my own Vulkan Project ?

And what are VideoHppGenerator.exe and VulkanHppGenerator.exe ?

**Comment by asuessenbach** [comment]
As the readme states:
`The goal of the Vulkan-Hpp is to provide header only C++ bindings for the Vulkan C API to improve the developers Vulkan experience without introducing CPU runtime cost. It adds features like type safety for enums and bitfields, STL container support, exceptions and simple enumerations.`

That is, you usually don't use the actual Generator executables, but just the generated headers in your project. Note, that those headers need to be in sync with the VulkanSDK you have installed. And also note, that the VulkanSDK already contains the headers generated with the programs from this repository.

That is, unless you have some very specific needs, you don't need to actually use this repository.

**Comment by bioorg** [comment]
Hello, thank you for your prompt answers
I understand now and you can close this issue
Have a nice day
