### ISSUE TITLE
vk::raii::getQueryPoolResults is not available

### ISSUE THREAD

**Issue by eriand01** [KhronosGroup/Vulkan-Hpp#1979]
getQueryPoolResults should be used in order to fetch runtime timestamps for the vk device. 

However, this method is not available through the vk::raii namespace for C++17 as one gets "method does not exist" error when trying to call it. 

As a work around for now it is manually wrapped using MVK_CALL, which is not ideal.

**Comment by asuessenbach** [comment]
You might have missed `vk::raii::QueryPool::getResults`?

**Comment by asuessenbach** [comment]
Assuming, this issue is resolved...

**Comment by eriand01** [comment]
Hi! I did not have the time to look into this issue until now. Thanks for the quick response! Is QueryPool::getResults in any documentation? All I can find regarding results retrieval is https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetQueryPoolResults.html
