### ISSUE TITLE
Abstraction of Khronos XML to bindings code

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Hpp#199]
With OpenXR on the horizon, and apparently following the same model as Vulkan in terms of exposing the API in a machine readable XML format, it might be useful to try to abstract some of this repository so that it can be re-used with the OpenXR API once it's available.

**Comment by oddhack** [comment]
@jherico there's now the https://github.com/KhronosGroup/OpenXR-Hpp repo. I don't think they use this framework but they do provide C++ headers - maybe this issue should be closed?
