### ISSUE TITLE
vulkan_to_string.hpp should be exported with `vulkan_hpp`

### ISSUE THREAD

**Issue by n0F4x** [KhronosGroup/Vulkan-Hpp#1998]
_vulkan_to_string.hpp_ and its contents are not exported through `vulkan_hpp` as of now.
Moreover, this header includes _vulkan_enums.hpp_, which requires _vulkan.hpp_ to be pre-included.

**Comment by asuessenbach** [comment]
You're right, `vulkan_to_string.hpp` need to include `vulkan.hpp`.
And the functions there will be exported through `vulkan_hpp` as well.

**Comment by n0F4x** [comment]
I think #2017 should resolve this.
Having to include _vulkan.hpp_ for the `to_string` can cause problems if you also import `vulkan_hpp`.

**Comment by asuessenbach** [comment]
> I think https://github.com/KhronosGroup/Vulkan-Hpp/pull/2017 should resolve this.

Ok, closing this then.
