### ISSUE TITLE
Compiler errors without VULKAN_HPP_TYPESAFE_CONVERSION

### ISSUE THREAD

**Issue by lenny-lunarg** [KhronosGroup/Vulkan-Hpp#20]
When I try to compile a Win32 program, using Visual Studio 2013, I get 37 compiler errors in vulkan.hpp, each complaining that there is no == operator for the given types. The errors look like:

1>c:\vulkansdk\1.0.21.2.ccvb.1300\include\vulkan\vulkan.hpp(2598): error C2678: binary '==' : no operator found which takes a left-hand operand of type 'const vk::Buffer' (or there is no acceptable conversion)
1>          could be 'built-in C++ operator==(VkBuffer, VkBuffer)'
1>          or       'built-in C++ operator==(VkBuffer, bool)'
1>          or       'built-in C++ operator==(bool, VkBuffer)'
1>          or       'built-in C++ operator==(bool, bool)'
1>          while trying to match the argument list '(const vk::Buffer, const vk::Buffer)'

It looks like what's happening is that each error occurs in an overloaded equality operator, but the member variables to not have overloaded equality operators. Everything compiles just fine with VULKAN_HPP_TYPESAFE_CONVERSION because the compiler uses equality from the C Vulkan structs (i.e. VkBuffer instead of vk::Buffer), but when implicit conversion isn't allowed, that conversion must be explicit (and it's still implicit).

To fix the compiler errors, you would need to either explicitly convert the C++ objects to their C counterparts, or overload the equality operator for the C++ objects. Obviously, you can work around this issue by simply defining VULKAN_HPP_TYPESAFE_CONVERSION, but since the header simply refuses to compile without it (which is default for 32-bit), this is something that should probably get fixed.

**Comment by jherico** [comment]
Didn't we just go through this on #14

**Comment by lenny-lunarg** [comment]
So does this mean that you think this is proper behavior? It seems to me that if its crashing for 32-bit, this shouldn't be the default behavior. In that issue, it sounded like he just switched to a 64-bit build. But sometimes you need to build for 32-bit. Admittedly, this isn't anything that can't be worked around, but it seems like bad default behavior.
