### ISSUE TITLE
Expose VK_HEADER_VERSION in vulkan_hpp_macros.hpp?

### ISSUE THREAD

**Issue by stripe2933** [KhronosGroup/Vulkan-Hpp#2019]
Is there a way to get the Vulkan header version (e.g. `296` for Vulkan SDK 1.3.296) without including `vulkan_core.h`? I think exposing `VK_HEADER_VERSION` in `vulkan_hpp_macros.hpp` is good for module user.

**Comment by asuessenbach** [comment]
That value is exposed as a `constexpr` value `vk::HeaderVersion` in `vulkan.hpp`, and also exported by `vulkan.cppm`.

**Comment by asuessenbach** [comment]
Assuming, this is answered...
