### ISSUE TITLE
Vulkan-hpp fails with 1.1.72 version of vk.xml

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Hpp#205]
Some new extensions in this registry file are (incorrectly?) using aliased extension names in the 'structextends' tag.  For instance, specifying
 ```
structextends="VkPhysicalDeviceFeatures2KHR,VkDeviceCreateInfo"
```
instead of 
```
structextends="VkPhysicalDeviceFeatures2,VkDeviceCreateInfo"
```

will generate an assert.

**Comment by asuessenbach** [comment]
This was fixed within the vk.xml with later versions.
Closing.
