### ISSUE TITLE
Compilation error with clang-5.0.1 and LunarG SDK 1.1.70.1 on x86

### ISSUE THREAD

**Issue by MuAlphaOmegaEpsilon** [KhronosGroup/Vulkan-Hpp#208]
I don't know if this has been fixed yet, I saw a similar but non-identical issue already solved however.
GCC 7.3.0 gives me no errors with this, but Clang does!
Here it is the Clang output log whenever I include the vulkan.hpp:

/usr/include/vulkan/vulkan.hpp:35431:29: **error:** no matching constructor for initialization of 'ObjectDestroy<vk::NoParent>'
    ObjectDestroy<NoParent> deleter( *this, allocator );
                            ^        ~~~~~~~~~~~~~~~~
![screenshot_20180413_121330](https://user-images.githubusercontent.com/26225010/38729808-77f1467c-3f14-11e8-99bb-e1cb34710225.png)

/usr/include/vulkan/vulkan.hpp:1014:5: note: candidate constructor not viable: allows at most single argument 'allocator',
      but 2 arguments were provided
    ObjectDestroy( Optional<const AllocationCallbacks> allocator = nullptr )
    ^
/usr/include/vulkan/vulkan.hpp:1011:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1
      argument, but 2 were provided
  class ObjectDestroy<NoParent>
        ^
/usr/include/vulkan/vulkan.hpp:1011:9: note: candidate constructor (the implicit move constructor) not viable: requires 1
      argument, but 2 were provided
1 error generated.

**Comment by jherico** [comment]
I've been seeing this as well trying to build my Vulkan examples with the latest android NDK.  I don't use the smart handles, so I was able to work around it by defining `VULKAN_HPP_NO_SMART_HANDLE`

**Comment by MuAlphaOmegaEpsilon** [comment]
Thanks jherico, the workaround seems to be working! 
Apart from this, I find frustrating the fact of being unable to compile without disabling features, whether or not I'll be using them.
Clang seems to be struggling to find the correct templated function when I'm not disabling the use of smart handles.

**Comment by mtavenrath** [comment]
@MuAlphaOmegaEpsilon The shipped Vulkan headers for Vulkan 1.1.70 are knowed to be broken. Can you copy over the 1.1.72 headers from Vulkan-Hpp to your SDK and check if you still see the issue?

I tested the headers with a clang 5.0 compiler and they compile fine:
`clang-5.0 -I Vulkan-Docs/include/ --std=c++11 vulkan/vulkan.hpp`

**Comment by MuAlphaOmegaEpsilon** [comment]
@mtavenrath Ok, I wasn't sure if this issues could eventually be fixed in .72, I'll try as soon as possible and keep you informed.
Thanks for now!

**Comment by MuAlphaOmegaEpsilon** [comment]
Problem solved after installing LunarG SDK 1.1.73.0.
