### ISSUE TITLE
Easier conversion between Extent2D & Extent3D would be useful

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Hpp#209]
a constructor for Extent3D with the signature `explicit Extent3D(const Extent2D& size, uint32_t depth)` would be useful to have

**Comment by Wunkolo** [comment]
Not sure if there is a neat and procedural way to do this in the current generator without having to add edge-case code like some `name == "Extent3D"` check on constructor generation.
If something like that does happen I would hope that it would be put behind an opt-in `VULKAN_HPP_EXTRA` or `VULKAN_HPP_UTIL` type of preprocessor flag to enable it or some `VulkanHppGenerator --extra` flag during header generation.

**Comment by asuessenbach** [comment]
Resolved with pull-request #213.
