### ISSUE TITLE
Custom "vulkan.h" generation?

### ISSUE THREAD

**Issue by elviras9t** [KhronosGroup/Vulkan-Hpp#219]
flextGL and volk already have custom headers with Vulkan API support (i.e. meta loaders). I want to suggest generation another header, instead of "vulkan.h" or "vulkan/vulkan.h" (if fully) make possible to choice another header (for example, "vulkan/flextVk.h" or "vulkan/volk.h").

**Comment by asuessenbach** [comment]
Do you want to have something like that inside vulkan.hpp:

#if !defined(VULKAN_HPP_INCLUDE_VULKAN_H)
# define VULKAN_HPP_INCLUDE_VULKAN_H "vulkan/vulkan.h"
#endif
#include VULKAN_HPP_INCLUDE_VULKAN_H

**Comment by mtavenrath** [comment]
@elviras9t @genpfault @Behemyth
Given that vulkan.hpp now has a metaloader, is this still a requirement?`

**Comment by genpfault** [comment]
I can' remember why this impacted me any more, so do as you will :)

**Comment by Behemyth** [comment]
My needs have since been resolved. Thanks for reaching out.
