### ISSUE TITLE
Program gets stuck on vk::DispatchLoaderStatic::vkCreateGraphicsPipelines on the newest NVIDIA drivers

### ISSUE THREAD

**Issue by GrumpyLion** [KhronosGroup/Vulkan-Hpp#224]
I have both an older version of the nvidia drivers (988.13) and the newest one. On the old version there aren't any problems but on the new one the driver randomly gets stuckt at vk::DispatchLoaderStatic::vkCreateGraphicsPipelines. The complete program is stuck and nothing changes. When I pause on visual studio the last entry in the call stack is the problem function. If I use the C api everything works on both drivers.

**Comment by asuessenbach** [comment]
Could you provide a simple reproducer for that problem?

**Comment by GrumpyLion** [comment]
Sorry for the inconvenience I forgot to close this problem. The Problem has something to do with my implementation and not the vulkan hpp version. So there is no need for a fix on the vulkan hpp side.
