### ISSUE TITLE
MSVC warnings on to_string inlining

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-Hpp#226]
Compiling a project that uses vulkan-hpp with /W4 on VS 2015 yields warnings like the following:

`warning C4714: function 'std::string vk::to_string(vk::Result)' marked as __forceinline not inlined`

It seems to me like there's not much to be gained from inlining to_string, so maybe we can just drop the __forceinline attribute on those functions?

**Comment by mtavenrath** [comment]
We are going to remove __forceinline on functions returning in a string. There're potentially more functions which will encounter this issue which have yet to be identified.
