### ISSUE TITLE
Missing return in createResultValue

### ISSUE THREAD

**Issue by Solree** [KhronosGroup/Vulkan-Hpp#230]
By the looks of it in vulkan.hpp there is return missing in `createResultValue( Result result, char const * message )` if exceptions are enabled.

**Comment by asuessenbach** [comment]
Actually, it's not missing.
That function returns `ResultValueType<void>::type`, which maps to `void` in that case. So no return statement needed.

**Comment by Solree** [comment]
You're right, excuse me for my lack of observation.
