### ISSUE TITLE
Separate graphics and present queues in 05_InitSwapchain?

### ISSUE THREAD

**Issue by genpfault** [KhronosGroup/Vulkan-Hpp#235]
Does `05_InitSwapchain.cpp` need a two-`DeviceQueueCreateInfo` call to `createDeviceUnique()` if there are separate graphics and present queue families?

**Comment by asuessenbach** [comment]
Yes, if there is no single queue family supporting both graphics and present, you could try to create a device with two separate queue families by providing two `DeviceQueueCreateInfo`s.
