### ISSUE TITLE
Statefull allocators?

### ISSUE THREAD

**Issue by red1939** [KhronosGroup/Vulkan-Hpp#237]
Currently, every function returning an array, returns `std::vector<T, Alloc>` where `Alloc` can be given as template argument. This assumes two things:

* allocator can be default constructed,
* we cannot pass our own pre-allocated block of memory to it.

Would it be that hard to allow (in those several cases) user to pass an allocator via a parameter?

Currently I have to "override" `new` and `delete` operators and I would rather see it more explicitly customizable for any lowish-level C/C++ library.

**Comment by mtavenrath** [comment]
We've determined the required changes to allow passing an allocator object without breaking existing code . It shouldn't be too hard, so we're going to implement this feature soon.
