### ISSUE TITLE
Dynamic loader inherently broken when using Unique instances?

### ISSUE THREAD

**Issue by red1939** [KhronosGroup/Vulkan-Hpp#241]
After passing through an instance of my `vk::DispatchLoaderDynamic` through all the calls I found one nasty issue when doing that. *I assume this scenario is applicable to all cases, thus a wider problem.*

Let's say I create everyone's favorite extension via `createDebugReportCallbackEXTUnique()` and as a last parameter I pass dynamic `Loader`. As it should be, when `vkCreateDebugReportCallbackEXT()` is called, it's done on the `Loader`. However **deleter** that's passed to `Unique` is ultimately going to call `destroy(obj, allocator)` on the `Instance`. As the `Loader` is not passed to this call, it will use the default `vk::DispatchLoaderStatic` thus causing linker errors.

As there is no concept of a handle to a `Loader` (like in the case of `vk::Instance`), we can't cheaply copy it into the `Unique`. Easiest solution would be probably to stick with pointer to `Loader`. This, however, causes another issue that if we just take a pointer to the `Dispatch const& d` parameter we might just as well end up with a dangling pointer to temporary created `DispatchLoaderStatic`.

I immediately see two possible solutions (hopefully not the only ones out there).

Split every `Unique` generating call into two overloaded versions - one without `d` parameter that would create a `Unique` like it is now; second with `d` parameter but passed as a pointer. This way callers have a clear indication that they will be sharing lifetime of `Loader` with `Unique`. Also, a specialized version of `Unique` would need to be created to store the additional pointer, that would be dereferenced when calling `destroy`.

Another option is to just have one form with pointer to `d`, but this would penalize users who have static `Loader` and don't need indirection via a pointer and increasing the size of `Unique`.

Both of these solutions would be an ABI break (first one less so), thus some attention is needed here.

P.S. Could someone explain why we need static and dynamic `Loader`? I mean when and how would one use a static `Loader`? Wherever I go I see people dynamically `getProc`ing themselves so why in case of non exported calls by Khronos/Vulkan (instance/device creation and wis) don't we just require that a dynamic dispatch needs to be provided?

**Comment by pierremoreau** [comment]
The initial issue (missing symbols at link time) has already been reported as #212. It was decided in #236 to change the ABI as no better solution was found and `Unique*` objects could no longer be used with `master` (see #233).

**Comment by red1939** [comment]
@pierremoreau Thanks for pointing the existing bugs. It seems you have reached the same conclusions as I did :). I am not sure whether we should keep `d` parameter as `Dispatch const&` as we are quietly lying about lifetime (taking a pointer to it) expectations. I think `Dispatch const*` would be better here.
