### ISSUE TITLE
vk::Device::acquireNextImageKHR returns ResultValue<uint32_t> instead of ResultValueType<uint32_t>

### ISSUE THREAD

**Issue by mujjingun** [KhronosGroup/Vulkan-Hpp#245]

**Comment by asuessenbach** [comment]
vk::Device::acquireNextImageKHR returns ResultValue<uint32_t>, and that's correct.

There is more than one success code on that function, therefore, the caller might need to know what the actual result is (besides the acquired imageIndex). No matter if exceptions are enabled or not.

Only functions that have just one success code can return a ResultValueType<T>::type.
When exceptions are enabled, that type is just the template parameter T, as you don't need to know any details on the error code at all. It would have been an exception, if it was something else but that success code.
When exceptions are disabled, that type is a ResultValue<T>, telling you everything you need to handle any error.

**Comment by mujjingun** [comment]
Ah, thanks for explaining.
