### ISSUE TITLE
Problem with UniqueHandle move assignment operator and swap

### ISSUE THREAD

**Issue by thd-v** [KhronosGroup/Vulkan-Hpp#246]
The following code does not compile when trying to move a UniqueHandle
```
vk::ApplicationInfo appInfo("VulkanTest", 1, "vulkan.hpp", VK_API_VERSION_1_1);
vk::InstanceCreateInfo instanceCreateInfo({}, &appInfo);
vk::UniqueInstance instance1 = vk::createInstanceUnique(instanceCreateInfo);

/* This works (calling the move constructor)
vk::UniqueInstance instance2 = std::move(instance1);
*/

/* This fails to compile (calling the move assignment operator)
vk::UniqueInstance instance2;
instance2 = std::move(instance1);
*/

/* This fails to compile (calling swap)
vk::UniqueInstance instance2;
instance2.swap(instance1);
*/
```

The error is:
```
Error	C2280	'vk::ObjectDestroy<vk::NoParent,Dispatch> &vk::ObjectDestroy<vk::NoParent,Dispatch>::operator =(const vk::ObjectDestroy<vk::NoParent,Dispatch> &)': attempting to reference a deleted function	VulkanTest	c:\vulkansdk\1.1.82.1\include\vulkan\vulkan.hpp	409	

```

**Comment by dokipen3d** [comment]
I think this is fixed in the master version of hpp. the one that ships with the lunarg sdk is tiny bit old now. i found out the same as you a few weeks ago but tested the latest and it works.

**Comment by SilverPhoenix99** [comment]
@dokipen3d I've tried your solution and it's working, so thanks for pointing that out.

I might be worth mentioning that one should use the [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers) repo instead of this one, otherwise it's likely to give a `"Wrong VK_HEADER_VERSION!"` error (like it happened to me).

**Comment by asuessenbach** [comment]
Closing this issue, as it's fixed in current versions of vulkan.hpp.
