### ISSUE TITLE
Build fails on gitlab !2810 (maybe due to "provisional" attribute but probably not)

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#248]
I'm seeing a build error in hpp-generate for our gitlab MR !2810 as follows:

```
$ ./VulkanHppGenerator
Loading vk.xml from /tmp/Vulkan-Hpp/Vulkan-Docs/xml/vk.xml
Writing vulkan.hpp to /tmp/Vulkan-Hpp/vulkan/vulkan.hpp
warning: Unknown attribute provisional in line 9612!
VulkanHppGenerator: /tmp/Vulkan-Hpp/VulkanHppGenerator.cpp:2910: void VulkanHppGenerator::sortDependencies(): Assertion `std::find_if(sortedDependencies.begin(), sortedDependencies.end(), [&dit](DependencyData const& dd) { return(dd.name == *dit); }) != sortedDependencies.end()' failed.
/bin/bash: line 79:  3986 Aborted                 (core dumped) ./VulkanHppGenerator
```

This is a bunch of vendor extensions queued up for the next public release, and the error probably isn't actually related to the "provisional" warning, but to the new extension XML - but that's as far as I've traced it. I'll be releasing the next update probably 9/20, so there's some time to fix this internally first.

**Comment by asuessenbach** [comment]
This was fixed with #249.
