### ISSUE TITLE
Support for VK_KHR_mir_surface should be removed

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-Hpp#259]
See also https://github.com/KhronosGroup/Vulkan-Docs/issues/814

**Comment by jherico** [comment]
The vulkan.hpp header is derived from the docs, so no explicit action is required.  When the extension is removed from the spec, it will automatically vanish from the header.

**Comment by mtavenrath** [comment]
jherico is correct. We're generating the header based on the spec and a vulkan.hpp header is only compatible to the vulkan.h header with the same version. If something vanishes in vulkan.h it'll also vanish in vulkan.hpp.
