### ISSUE TITLE
Missing Queue::submit() overload with single SubmitInfo parameter

### ISSUE THREAD

**Issue by yzsolt** [KhronosGroup/Vulkan-Hpp#260]
There are single value overloads for most Vulkan functions taking an array as parameter by default (e.g. Device::createGraphicsPipeline[s]), but Queue::submit is missing such an overload. It would be nice if it could have one too.
(Probably there are more functions like this, I haven't checked thoroughly.)

**Comment by asuessenbach** [comment]
There are such overloads for functions returning either an array of stuff or a single piece of stuff.
But there's no need for such an overload for functions that just take an array of stuff to work on, as they get an ArrayProxy of stuff, and there's a single element constructor of the ArrayProxy, allowing you to just throw in a single piece of stuff into such a function, like so:
`  m_graphicsQueue->submit(vkhlf::SubmitInfo{ { m_framebufferSwapchain->getPresentSemaphore() },{ vk::PipelineStageFlagBits::eColorAttachmentOutput }, commandBuffer, m_renderCompleteSemaphore });
`

**Comment by yzsolt** [comment]
I don't fully understand your reasoning. I can throw a single value into CreateGraphicsPipelines too, yet there's a single value version of it. The only difference is (correct me if I'm wrong) that Queue::submit() doesn't return an array of values, but why should that matter?
I see that generating such overloads can get tricky with functions taking multiple ArrayProxies, but maybe those could be exceptions.

**Comment by asuessenbach** [comment]
When you throw a single value into createGraphicsPipelines, you still get a std::vector<Pipelines> back. With just one element, in that case.
That is, the reason why we introduced the singular version of some functions is the return value, not the input value(s).
For functions not returning anything (like submit), there would be no difference between a singular version and the "standard" version with an ArrayProxy of one element.

**Comment by yzsolt** [comment]
Ah, clear, I missed the difference between the return values, thanks for the explanation. Closing the issue now, I can live with creating dummy arrays for single values.

**Comment by asuessenbach** [comment]
@yzsolt : Just to make it clear, there's no need to create "dummy arrays for single values". Functions consuming ArrayProxys can directly take single values.
