### ISSUE TITLE
Optionally support (designated) aggregate initialization for structs.

### ISSUE THREAD

**Issue by ekpyron** [KhronosGroup/Vulkan-Hpp#261]
It would be really great if structs could be initialized with designated initializers (C++20), e.g:
```
auto createInfo = vk::PipelineTessellationStateCreateInfo {
   .patchControlPoints = 4
};
```

Currently, this is prevented by:
  - The fact that structs define custom constructors.
  - The fact that most structs have a private ``StructureType`` member.
  - Default initialization is performed in the constructor instead of using default member initializers.

A possible solution for all these issues might be the following construction:
**EDIT: note that this original suggestion was *not* a good idea, since the resulting struct will not be guaranteed to have the correct memory layout.**
```
template<StructureType s>
struct StructureBase {
private:
  StructureType sType = s;
};

struct PipelineInputAssemblyStateCreateInfo
: StructureBase<StructureType::ePipelineInputAssemblyStateCreateInfo>
  {
    // no constructors
    ... // setters, operators as before
    // no private sType member
    // all fields use default member initializers
    const void* pNext = nullptr;
    PipelineInputAssemblyStateCreateFlags flags = PipelineInputAssemblyStateCreateFlags();
    PrimitiveTopology topology = PrimitiveTopology::ePointList;
    Bool32 primitiveRestartEnable = 0;
  };
```

To achieve backwards compatibility constructors could still be defined, unless disabled by an explicit ``#define``. An alternative to inheriting from a ``StructureBase`` template type would be another ``#define`` that changes the ``sType`` members from ``private`` to ``public``.

Any thoughts?

**Comment by ekpyron** [comment]
I experimented with this in https://github.com/ekpyron/Vulkan-Hpp/tree/designatedInitialization and hit some issues - that version will *only* be good for designated aggregate initialization, but will break regular construction due to the now public ``sType`` member. Moving to a templated base class in fact *doesn't* solve this problem (there's still an additional aggregate field for the public base class as of C++17).
I'm not yet sure whether there is a better solution that retains more backwards compatibility.

**Comment by W4RH4WK** [comment]
It seems like this feature request got even more compiled with the introduction of the `layout` namespace (see #360).

Now the actual data members are located in a *base class*, rather than the actual struct handled by the user. So far, it doesn't seem like designated initializers allow you to initialize inherited members.

**Comment by ekpyron** [comment]
@W4RH4WK I haven't looked into this in a while and I haven't checked what the C++ standard actually says about this, but the following compiles both with gcc and clang (using ``-std=c++17`` or ``-std=c++2a``):
```
#include <iostream>

class A {
public:
    int type = 42;
    int a;
    int b;
};

class B : public A {
private:
    using A::type;
};

int main() {

    B b { { .a = 23, .b = 84 } };
    std::cout << b.a << std::endl << b.b << std::endl;

}
```

Funnily this will also allow ``B b { { .type = 1, .a = 23, .b = 84 } }``, though, and ``B b { 1, 2 }`` will initialize ``type`` and ``a`` instead of ``a`` and ``b``...

In any case it might still be viable to consider this at least optionally - the main obstacles are still the same: explicitly defined constructors prevent designated initialization, but removing them will result in *only* designated initialization to work as intended (only now with an additional set of brackets).

**Comment by ekpyron** [comment]
So generally I still think it'd be nice to have a preprocessor flag to put vulkan-hpp in "aggregate mode", which, when enabled, removes all constructors and uses direct member initialization for default values instead (the latter could be done either way without any harm anyways).

**Comment by W4RH4WK** [comment]
You are right, inheritance is not an issue *if* the derived class does not add any data members. So +1 for an *aggregate mode* preprocessor switch.

**Comment by asuessenbach** [comment]
Unfortunately, there's one important fact that prevents us from supporting aggregate initialization:
- The fact that structs define custom constructors.
Even if we would remove the member-wise constructor in favor of the aggregate initalization, we would need to keep the copy constructor from the underlying vulkan structure.
If there's a way to keep that copy construction functionality, I'ld be more than happy to introduce aggregate initialization. But 'til then, we have to live with what we have.

**Comment by ekpyron** [comment]
Actually, when I opened this issue and forked there were to custom constructors from underlying vulkan structures... and I actually don't think they are a good idea - you do take care that the memory layout is identical, so why would I want to copy-construct instead of ``reinterpret_cast``?

**Comment by ekpyron** [comment]
I still think designated initializers are sufficiently nice for the big vulkan structs to warrant some more thought on this...

**Comment by ekpyron** [comment]
What's your argument for the copy-construction functionality :-)? It's always wasteful, isn't it? Wouldn't a generic cast function that auto-deduces the correct vulkan-hpp struct type be much better?

**Comment by W4RH4WK** [comment]
> Even if we would remove the member-wise constructor in favor of the aggregate initalization, we would need to keep the copy constructor from the underlying vulkan structure.

I assume these constructors have been added to improve interoperability between the C and C++ types as they are the counter part to the conversion operators. However, from this point of view, it seems like a language limitation that adding *from conversion operators* to a type disables designated initializer functionality (as they are constructors).

> Wouldn't a generic cast function that auto-deduces the correct vulkan-hpp struct type be much better?

I don't know about *much better* but certainly an alternative that should be considered to make this work. We could still keep all of this behind a compiler define until we are sure it can replace what's currently in place.

Personally I'd trade in these constructors to get designated initializers. I imagine something like `vk::from()` to hide the `reinterpret_cast`.

**Comment by ekpyron** [comment]
Well, with "much better" I meant that a cast doesn't need to copy, whereas an implicit constructor always has to.
The pity is that designated initialization only works for aggregates and C++ is rather strict about what's an aggregate, which makes life a bit hard for this...

**Comment by asuessenbach** [comment]
If we don't change anything in vulkan.hpp regarding (designated) aggregate initialization, still something like this is accepted:`
  vk::GeometryTrianglesNV geometryTriangles0{ { .vertexCount = 1, .vertexStride = 42 } };`

**Comment by W4RH4WK** [comment]
> Could that be considered as "close enough" for this issue?

I'd say so, yes. Looking at my `createInstance` call, it's already an improvement to chaining setters together:

```c++
const vk::ApplicationInfo appInfo = {{
    .pApplicationName = APP_NAME,
    .applicationVersion = VK_MAKE_VERSION(APP_VERSION_MAJOR, APP_VERSION_MINOR, APP_VERSION_PATCH),
    .pEngineName = RAYGUN_NAME,
    .engineVersion = VK_MAKE_VERSION(RAYGUN_VERSION_MAJOR, RAYGUN_VERSION_MINOR, RAYGUN_VERSION_PATCH),
    .apiVersion = VK_API_VERSION_1_2,
}};

instance = vk::createInstanceUnique({{
    .pApplicationInfo = &VkApplicationInfo(appInfo),
    .enabledLayerCount = (uint32_t)layers.size(),
    .ppEnabledLayerNames = layers.data(),
    .enabledExtensionCount = (uint32_t)extensions.size(),
    .ppEnabledExtensionNames = extensions.data(),
}});
```

**Comment by ekpyron** [comment]
Interesting! This only works, because vulkan-hpp has started to define constructors from the underlying C-structs, right? So what actually happens is that it will deduce the type of the inner brackets as the underlying C-struct, so the inner brackets end up as a temporary vulkan struct from which the C++ constructor will then copy into the C++ struct...

I'd still argue that this is generally the wrong direction to take... as far as I'm concerned those constructors shouldn't exist in the first place, since they are wasteful in contrast to casting (i.e. they will needlessly copy).

I'd guess that using this construction to "simulate" designated initialization via the C-structs *might* end up the same as "proper" designated initialization after optimization - but I wouldn't be sure and in general this still seems less than ideal to me...

**Comment by W4RH4WK** [comment]
Looking at other places, it seems this technique is a bit limited. Need to look more into this to really say whether it's close enough.

The main issue I see is that it requires you to mix C and C++ types, invoking the conversion operators along the way which adds noise. I already had to this in my previous example to convert from `vk::ApplicationInfo*` to `VkApplicationInfo*`.

While I'd deem this acceptable, it looks more dire with enums:

```c++
const vk::ImageMemoryBarrier barr = {{
    .dstAccessMask = VkAccessFlags(vk::AccessFlagBits::eTransferWrite),
    .newLayout = VkImageLayout(vk::ImageLayout::eTransferDstOptimal),
    .image = resultImage,
    .subresourceRange = gpu::defaultImageSubresourceRange(),
}};
```

The more I think about and play with it, the more I lean towards @ekpyron point of view.

**Comment by W4RH4WK** [comment]
Side note: applying this technique on the fly is currently a bit hard. Using Visual Studio, I don't get auto-completion for field names with just writing `{{` and compiler error messages are a bit cryptic. Leaving of the `VkAccessFlags` conversion in the previous example yields the following error message:

    error C2440: 'initializing': cannot convert from 'initializer list' to 'vk::ImageMemoryBarrier'

While this is, of course, correct, it's not as helpful as it should be.

**Comment by W4RH4WK** [comment]
@asuessenbach thank you for adding these changes, this seems like a step in the right direction.

Let me just highlight that converting from Vulkan C type to the corresponding Vulkan C++ type can now be done via the assignment operator. Just in case anyone was wondering.

```c++
ApplicationInfo & operator=( VkApplicationInfo const & rhs ) VULKAN_HPP_NOEXCEPT
{
  *this = *reinterpret_cast<VULKAN_HPP_NAMESPACE::ApplicationInfo const *>( &rhs );
  return *this;
}
```
