### ISSUE TITLE
"enumeratePhysicalDevices" doesn't seem to handle all errors.

### ISSUE THREAD

**Issue by Gaspard--** [KhronosGroup/Vulkan-Hpp#265]
Hello,

The assertion
```cpp
    VULKAN_HPP_ASSERT( physicalDeviceCount <= physicalDevices.size() );
```
fails on some (probably badly configured) systems because `physicalDeviceCount` wasn't written.

After reading the specification, I believe this should fixed in vulkan.hpp:

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkEnumeratePhysicalDevices.html states that `vkEnumeratePhysicalDevices` may fail with errors.
One can (probably) reasonably assume the implementation won't allocate memory, but for the case of `VK_ERROR_INITIALIZATION_FAILED` the language of the specification doesn't seem to prohibit that from occuring when querying the device count.

I believe a simple fix would be to bail out early if retrieving the physical device count fails. I'm too unfamiliar with the project to propose the change myself.

**Comment by asuessenbach** [comment]
You're absolutely right!
I'll fix that soon.

**Comment by Gaspard--** [comment]
I'm closing this because I believe it's done, good job!
