### ISSUE TITLE
DispatchLoaderDynamic doesn't allow user provided vkGet*ProcAddr

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/Vulkan-Hpp#268]
#120 was resolved with the inclusion of dynamic dispatchers, but the solution doesn't provide an overload to use user provided pointers for the `vkGet*ProcAddr` pair, it uses the external ones instead.

I need this in particular to drop static linkage to the Vulkan loader.

**Comment by asuessenbach** [comment]
Could you provide some (pseudo-)code on what you want to do? I don't get you issue here.

**Comment by asuessenbach** [comment]
Resolved with PR #284.

**Comment by ReinUsesLisp** [comment]
Thanks!
