### ISSUE TITLE
Building Vulkan-Hpp with Vulkan-Docs (85184f3) fails because of "ExternalMemoryHandleTypeFlagBitsNV"

### ISSUE THREAD

**Issue by FirefoxMetzger** [KhronosGroup/Vulkan-Hpp#27]
Due to current version missmatch of the `vulkan.hpp` and the latest `vulkan.h` I decided to rebuild it myself. Compilation of the `VulkanHppGenerator.exe` (im on Win10 VS2015) works fine, but executing it throws this message:

    Loading vk.xml from D:\Repos - Kopie\Vulkan-Hpp\Vulkan-Docs\src\spec\vk.xml
    Writing vulkan.hpp to D:\Repos - Kopie\Vulkan-Hpp\vulkan\vulkan.hpp
    caught exception: spec error: enums name="ExternalMemoryHandleTypeFlagBitsNV" 
    is missing the type attribute

Older versions work just fine. I already ran the integrity tests for the `vk.xml` and successfully compiled the `vulkan.h` generated from it. Any clue on where to start the bug hunt?

**Comment by karl-lunarg** [comment]
Maybe related to #25?

**Comment by sl1pkn07** [comment]
maybe no, the same issue. "fixed" with @mtavenrath tip in https://github.com/KhronosGroup/Vulkan-Hpp/issues/25#issuecomment-243061709 and wait to next update with this implemented

**Comment by FirefoxMetzger** [comment]
yep, this can be resolved in the same manner. Thank you :)

**Comment by mtavenrath** [comment]
It's the same issue. I've improved the error reporting due to #25. The temporary workaround until the next spec update is described here: https://github.com/KhronosGroup/Vulkan-Hpp/issues/25#issuecomment-243061709
