### ISSUE TITLE
Incorrect generation of extension protect macro

### ISSUE THREAD

**Issue by cdotstout** [KhronosGroup/Vulkan-Hpp#271]
In VulkanHppGenerator::readExtensionsExtension(tinyxml2::XMLElement const* element):

If a 'protect' attribute is found: use that as the macro.  In recent vk.xml, 'protect' is not set for any extension; its set on the 'platform' entries.

If no 'protect' is found but 'platform' is found: generate a macro from VK_USE_PLATFORM_ + 'platform' + 'author'

Expected: for the 2nd case when 'platform' is found, use the 'protect' attribute for that platform.

**Comment by asuessenbach** [comment]
Thanks for detecting this issue. Will be resolved with PR #276.
