### ISSUE TITLE
VK_ERROR_OUT_OF_DATE_KHR handling

### ISSUE THREAD

**Issue by roever** [KhronosGroup/Vulkan-Hpp#274]
Hi,

when the swapchain becomes invalid due to window resize, acquiring or presenting an image will result in returncode VK_ERROR_OUT_OF_DATE_KHR

As far as I know there is no way to detect this problem before getting this returncode. At least glfw doesn't deliver the window resize event before the swapchain becomes invalid.

All examples I could find use the C api and handle the out of date error. But the C++ api  has made the unfortunate choice of throwing an exception. This is suboptimal, because now I get an exception in a path that is not really an exception. 

Is this intentional?
Is the exception the supposed way to handle this situation?
Have I overlooked something?
I would prefere to include the VK_ERROR_OUT_OF_DATE_KHR returncode in the possible return-values for acquireNextImageKHR and presentKHR, any thoughts on that?

**Comment by asuessenbach** [comment]
For those functions VK_ERROR_OUT_OF_DATE_KHR are spec'ed as an error code, not as a success code. Therefore, our vk functions can only handle it as an error. And an error in this context means, it's has to throw an exception. There's no way around it.
If you want to have that changed, you would have to ask for changing the spec, which I think is very unlikely to happen.

**Comment by roever** [comment]
ok.. I understand. Not perfect but understandable, just wanted to make sure I didn't overlook something, will close the issue

**Comment by mtavenrath** [comment]
Also, it is still possible to call the version of the function which does not generate exceptions. In Vulkan-Hpp exceptions are a choice, not a must.

**Comment by BartSiwek** [comment]
This issue is still very much relevant.
In case exceptions are used VK_ERROR_OUT_OF_DATE_KHR will cause an exception to be thrown.
In case when exceptions are turned off the return values are asserted for and VK_ERROR_OUT_OF_DATE_KHR will cause the assert to fail.
This leaves the following options (assuming exceptions are already off):
- Don’t use Vulkan-Hpp for swapchain management
- Turn off Vulkan-Hpp asserts via VULKAN_HPP_ASSERT (or related macros)
- Build code with asserts enabled

None of these options are particularly good because they either hinder debugging or bypass Vulkan-Hpp.

**Comment by roever** [comment]
After tinkering with this problem for a while I actually found a very nice solution for my program (which uses exceptions)
The problem was that on window resizes the swapchain got outdated before the windowing library (glfw) pushed the window resize event. And then a new redraw starts while the swapchain is no longer usable.
Then I catch the exception outside of the whole draw routine. If the swap chain is out of date no screen update is done at all.
Glfw will eventuelly inform about window resizes, which will get handled at that moment. When that happens the swapchain is recreated. All draws inbetween simply don't happen.
This resulted in clean code and seems to work.
