### ISSUE TITLE
Use FindVulkan for the samples

### ISSUE THREAD

**Issue by Robert42** [KhronosGroup/Vulkan-Hpp#301]
In current cmake versions, there is a vulkan findinf script Working on multiple platforms:

https://cmake.org/cmake/help/v3.7/module/FindVulkan.html

This allows to

- Replace [`include_directories("$ENV{VK_SDK_PATH}/include")`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/samples/CMakeLists.txt#L33) with 

        find_package(Vulkan REQUIRED)
        include_directories("${Vulkan_INCLUDE_DIRS}")
- Replace all those highly platform specific [`target_link_libraries(01_InitInstance "$ENV{VULKAN_SDK}/Lib/vulkan-1.lib")`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/samples/01_InitInstance/CMakeLists.txt#L35) with

        target_link_libraries(01_InitInstance "${Vulkan_LIBRARIES}")

This changes would make it easier to  add Linux Support. See #302

**Comment by asuessenbach** [comment]
Resolved with PR #308.
