### ISSUE TITLE
Remove platformspecific code from the samples

### ISSUE THREAD

**Issue by Robert42** [KhronosGroup/Vulkan-Hpp#302]
I know, that the samples officially are not supported on linux, but there is some highly platform specific code making it more unlikely, that someone will contribute to add support for other paltforms to the samples

- [`#include "..\utils\utils.hpp"`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/samples/02_EnumerateDevices/02_EnumerateDevices.cpp#L18) can be replaced with

        #include "../utils/utils.hpp"
- [`int main(int /*argc*/, char * /*argv[]*/)`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/samples/02_EnumerateDevices/02_EnumerateDevices.cpp#L25) Can be replaced with

       int main(int /*argc*/, char** /*argv*/)

After solving #301 and #302, the compiler will guide a linux developer directly to the relevant spots

**Comment by asuessenbach** [comment]
Resolved with PR #307.
