### ISSUE TITLE
gitlab build issue with MR 3082

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#316]
We have a pending MR in internal gitlab which is breaking the hpp-generate CI stage - see internal Vulkan MR 3082 / CI job 44561. I believe the problem is happening because we introduced multiple (3) aliases of a single structure / function. This will hold up updating the Vulkan-Headers repo after the MR is accepted and published, so this is to give you an early heads-up that it's coming, probably on Monday.

**Comment by asuessenbach** [comment]
This has already been fixed with PR #305.
Retrying the build on https://gitlab.khronos.org/vulkan/vulkan/pipelines/9337 passed both hpp-generate and hpp-compile.

**Comment by oddhack** [comment]
Cool, thanks!
