### ISSUE TITLE
[Buffer/Image]MemoryBarrier structs QueueFamilyIndices fields default value form 0 to VK_QUEUE_FAMILY_IGNORED

### ISSUE THREAD

**Issue by gssgh** [KhronosGroup/Vulkan-Hpp#321]
Currently [Buffer/Image]MemoryBarrier structs QueueFamilyIndices fields default to 0. It would be nice to have it set to VK_QUEUE_FAMILY_IGNORE  (defined as ~(0U) in vulkan_core.h) such that if no family ownership transfer is necessary  the fields can be ignored.

**Comment by mtavenrath** [comment]
The Vulkan WG discussed the topic default values for structs and decided that the core spec will not get any non-zero defaults.  Vulkan-Hpp stays as close as possible to the C interface of Vulkan and thus won't introduce defaults which differ from 0.
