### ISSUE TITLE
Create debug callback is used without checking extention availability

### ISSUE THREAD

**Issue by xXSeraphimXx** [KhronosGroup/Vulkan-Hpp#33]
I'm not sure whether this is only a problem for me, but last time I used Vulkan-Hpp and tried to create a Debug Callback, I got a linker error(The library didn't know the function? Even if the function for creation is at runtime available!). If I'm missing anything, I'm very sorry, just trying to understand and help :) !

**Comment by mtavenrath** [comment]
Vulkan-Hpp relies on the application/loader to provide the function pointers for vulkan & vulkan extensions. You've to fetch the function pointers for extensions in your application and implement the corresponding delegation functions for the extension.

This issue is coming up from time to time and I'm wondering if it'll make sense to enhance the loader so that it supports all functions defined in vulkan.h for the given platform.

**Comment by ioquatix** [comment]
I agree that this approach makes sense. I also have the same problem, I don't even see how it's possible that should work, it should definitely be calling _instance.getProcAddr rather than having it globally defined.

**Comment by ioquatix** [comment]
Here is what I did to fix this:

```diff
diff --git a/source/Vulkanraum/vulkan.hpp b/source/Vulkanraum/vulkan.hpp
index bd10602..a95bfb9 100644
--- a/source/Vulkanraum/vulkan.hpp
+++ b/source/Vulkanraum/vulkan.hpp
@@ -20823,12 +20823,16 @@ namespace vk
 
     Result createDebugReportCallbackEXT( const DebugReportCallbackCreateInfoEXT* pCreateInfo, const AllocationCallbacks* pAllocator, DebugReportCallbackEXT* pCallback ) const
     {
+      PFN_vkCreateDebugReportCallbackEXT vkCreateDebugReportCallbackEXT = (PFN_vkCreateDebugReportCallbackEXT)this->getProcAddr("vkCreateDebugReportCallbackEXT");
+      
       return static_cast<Result>( vkCreateDebugReportCallbackEXT( m_instance, reinterpret_cast<const VkDebugReportCallbackCreateInfoEXT*>( pCreateInfo ), reinterpret_cast<const VkAllocationCallbacks*>( pAllocator ), reinterpret_cast<VkDebugReportCallbackEXT*>( pCallback ) ) );
     }
 
 #ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE
     ResultValueType<DebugReportCallbackEXT>::type createDebugReportCallbackEXT( const DebugReportCallbackCreateInfoEXT & createInfo, Optional<const AllocationCallbacks> allocator = nullptr ) const
     {
+      PFN_vkCreateDebugReportCallbackEXT vkCreateDebugReportCallbackEXT = (PFN_vkCreateDebugReportCallbackEXT)this->getProcAddr("vkCreateDebugReportCallbackEXT");
+      
       DebugReportCallbackEXT callback;
       Result result = static_cast<Result>( vkCreateDebugReportCallbackEXT( m_instance, reinterpret_cast<const VkDebugReportCallbackCreateInfoEXT*>( &createInfo ), reinterpret_cast<const VkAllocationCallbacks*>( static_cast<const AllocationCallbacks*>( allocator)), reinterpret_cast<VkDebugReportCallbackEXT*>( &callback ) ) );
       return createResultValue( result, callback, "vk::Instance::createDebugReportCallbackEXT" );
@@ -20845,12 +20849,16 @@ namespace vk
 
     void destroyDebugReportCallbackEXT( DebugReportCallbackEXT callback, const AllocationCallbacks* pAllocator ) const
     {
+      PFN_vkDestroyDebugReportCallbackEXT vkDestroyDebugReportCallbackEXT = (PFN_vkDestroyDebugReportCallbackEXT)this->getProcAddr("vkDestroyDebugReportCallbackEXT");
+      
       vkDestroyDebugReportCallbackEXT( m_instance, static_cast<VkDebugReportCallbackEXT>( callback ), reinterpret_cast<const VkAllocationCallbacks*>( pAllocator ) );
     }
 
 #ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE
     void destroyDebugReportCallbackEXT( DebugReportCallbackEXT callback, Optional<const AllocationCallbacks> allocator = nullptr ) const
     {
+      PFN_vkDestroyDebugReportCallbackEXT vkDestroyDebugReportCallbackEXT = (PFN_vkDestroyDebugReportCallbackEXT)this->getProcAddr("vkDestroyDebugReportCallbackEXT");
+      
       vkDestroyDebugReportCallbackEXT( m_instance, static_cast<VkDebugReportCallbackEXT>( callback ), reinterpret_cast<const VkAllocationCallbacks*>( static_cast<const AllocationCallbacks*>( allocator)) );
     }
 #endif /*VULKAN_HPP_DISABLE_ENHANCED_MODE*/
```

**Comment by ioquatix** [comment]
Just to add to this, I know this isn't a general efficient solution since every time you call the method it's doing a lookup. Perhaps this functionality does not belong in the core Vulkan-Hpp if it can't be guaranteed. Because, it seems like to me, it should be cached, but that would change the size of the Device instance.

**Comment by mtavenrath** [comment]
vulkan.h by default declares all the functions, so we decided to implement an extension loader which implements the functions which can be found here: https://github.com/KhronosGroup/Vulkan-Docs/tree/1.0/src/ext_loader

To generate the ext-loader with your own extensions you can call gen_vk.py from here: https://github.com/KhronosGroup/Vulkan-Docs/tree/1.0/src/spec

For each to exclude add --removeExtension to the command line.
