### ISSUE TITLE
#335 makes it hard to create Vulkan-Headers updates

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#339]
In #335, it looks like the cmake rules changed to use a Vulkan-Headers submodule instead of Vulkan-Docs. This caused two issues with trying to update Vulkan-Headers for the 1.1.111 spec update. First, when I cloned the Vulkan-Hpp repo locally, I got an empty Vulkan-Headers directory, which is causing the error "VkGenerate: failed to load file /home/tree/git/Vulkan-Hpp/Vulkan-Headers/registry/vk.xml . Error code: 3" from VulkanHppGenerator, and there aren't any build instructions that say how to pull the submodule (in fairness, there weren't when using Vulkan-Docs, either - I just removed the entire Vulkan-Docs directory and symlinked to my local up-to-date repo).

Second, and more problematic, is that I'm trying to update Vulkan-Headers with the new Vulkan-Hpp. I can't do that if Vulkan-Hpp is pulling its content from Vulkan-Headers, at least without a two-stage process in which I first update the XML, scripts and C headers; pull Vulkan-Hpp and update the Vulkan-Headers submodule; and then update vulkan.hpp in Vulkan-Headers in an additional step. This seems like annoying extra effort involving multiple round trips to github, which I'd rather avoid since I'm doing this every time I push a spec update.

Can we restore, or offer as a documented alternative, making Vulkan-Hpp build out of Vulkan-Docs again? I don't think I can move forward with the headers update until this circular dependency situation is addressed, and that's what would be the easiest way for me.

**Comment by mtavenrath** [comment]
@oddhack For your case there's no need to use the 'default' vk.xml specified in the project file which currently resides in Vulkan-Headers. You can pass whatever vk.xml you want as argument to the generator. In your case pass the path to your Vulkan-Docs vk.xml to the generator and it'll use it.

**Comment by oddhack** [comment]
@mtavenrath do you mean like

> (cd build && ./VulkanHppGenerator some-path/vk.xml)

?

**Comment by mtavenrath** [comment]
Yes

**Comment by oddhack** [comment]
Thanks, Vulkan-Headers is updated now.
