### ISSUE TITLE
GCC 9.1.1 warnings

### ISSUE THREAD

**Issue by jeremy-lunarg** [KhronosGroup/Vulkan-Hpp#342]
GCC 9.1.1 generates many warnings of the form:

`vulkan.hpp:48313:61:` warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct vk::XcbSurfaceCreateInfoKHR’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
48313 |       memcpy( this, &rhs, sizeof( XcbSurfaceCreateInfoKHR ) );`

**Comment by JanHellwig** [comment]
GCC 8.3.0 is affected by this as well.
