### ISSUE TITLE
Cannot generate vulkan.hpp using 1.0.28 spec

### ISSUE THREAD

**Issue by lenny-lunarg** [KhronosGroup/Vulkan-Hpp#35]
The vulkan 1.0.28 spec changed the notiation used to refer to members of structs when they're referenced as an array length. Previously, the spec would notate this like `pAllocateInfo->descriptorSetCount`, but in 1.0.28 this is notated as `pAllocateInfo::descriptorSetCount`. As a result, when trying to generate vulkan.hpp with the 1.0.28 version of vk.xml, I get an assertion error. My guess is that you'll want to make this project handle both notations so that it works both before and after 1.0.28.

**Comment by sl1pkn07** [comment]
```
Loading vk.xml from /tmp/makepkg/vulkan-git/src/Vulkan-Docs/src/spec/vk.xml
Writing vulkan.hpp to /tmp/makepkg/vulkan-git/src/Vulkan-Hpp/vulkan/vulkan.hpp
caught exception: basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 32)
```

this is the same error? (with 1.0.29 vk.xml)

**Comment by peterazmanov** [comment]
Encountered the same issue (described by @lenny-lunarg) with latest spec 1.0.29. I checked pull request #37 from @mtavenrath. It seems that it fixes the issue.

**Comment by sl1pkn07** [comment]
yep. fiixed for me

greetings

**Comment by mtavenrath** [comment]
Issue is fixed, closing.
