### ISSUE TITLE
Possible undefined behavior when type punning wrapper class to native struct using reinterpret_cast

### ISSUE THREAD

**Issue by ph3rin** [KhronosGroup/Vulkan-Hpp#359]
I am aware that many wrapper classes have their pointers `reinterpret_cast`ed into native structs in function calls. However this according to the c++ standard is undefined behavior. See: [Type Aliasing](https://en.cppreference.com/w/cpp/language/reinterpret_cast#Type_aliasing) .

See [my question](https://stackoverflow.com/q/56985831/9171697) on StackOverflow.

-------

Essentially:

```c++
/* Using the LunarG Sdk version 1.1.108.0 */

//definition of vk::InstanceCreateInfo
struct InstanceCreateInfo
{
    /*  member function omitted  */
private:
  StructureType sType = StructureType::eInstanceCreateInfo;
public:
  const void* pNext = nullptr;
  InstanceCreateFlags flags;
  const ApplicationInfo* pApplicationInfo;
  uint32_t enabledLayerCount;
  const char* const* ppEnabledLayerNames;
  uint32_t enabledExtensionCount;
  const char* const* ppEnabledExtensionNames;
};

//definition of VkInstanceCreateInfo
typedef struct VkInstanceCreateInfo {
    VkStructureType             sType;
    const void*                 pNext;
    VkInstanceCreateFlags       flags;
    const VkApplicationInfo*    pApplicationInfo;
    uint32_t                    enabledLayerCount;
    const char* const*          ppEnabledLayerNames;
    uint32_t                    enabledExtensionCount;
    const char* const*          ppEnabledExtensionNames;
} VkInstanceCreateInfo;

//And the usage where reinterpret_cast takes place
template<typename Dispatch>
VULKAN_HPP_INLINE ResultValueType<Instance>::type createInstance( const InstanceCreateInfo &createInfo, Optional<const AllocationCallbacks> allocator, Dispatch const &d )
{
  Instance instance;
  Result result = static_cast<Result>( d.vkCreateInstance( reinterpret_cast<const VkInstanceCreateInfo*>( &createInfo ), reinterpret_cast<const VkAllocationCallbacks*>( static_cast<const AllocationCallbacks*>( allocator ) ), reinterpret_cast<VkInstance*>( &instance ) ) );
  return createResultValue( result, instance, VULKAN_HPP_NAMESPACE_STRING"::createInstance" );
}
```

Here we are casting `vk::InstanceCreateInfo*` to `const VkInsanceCreateInfo*`. Those are not the same type (more accurately, the pointers don't point to the same type).  `vk::InstanceCreateInfo` is not even a standard layout type (because of mixed access specifiers).

Maybe inheritance should be used instead?

**Comment by mtavenrath** [comment]
You're correct with your assumption. The C++11 rules would require us to make all members public to use the standard layout which would result in the sType being public.

As possible workaround to keep the private feature we would have to define all classes with private fields in standard layout with all fields public, derive from this those classes and put private fields in a private section with a using statement. We're going to evaluate if there is any other pitfall in this solution.

**Comment by mtavenrath** [comment]
@ph3rin We've changed the header to ensure that the standard layout type is always used. Do you see any remaining issue? 

Fixed. Closing.
