### ISSUE TITLE
Undefined `Vkvk` namespace appears in `vulkan.hpp`

### ISSUE THREAD

**Issue by shannon-lunarg** [KhronosGroup/Vulkan-Hpp#368]
The current version of `vulkan.hpp` erroneously utilizes the `Vkvk` namespace which is not defined. Three instances of `Vkvk` occur in the file (lines 22897, 22898, and 42440). My best guess as to where this rogue "vk" originates is "`(beginsWith(member.type.type, "Vk") ? "Vk" : "")`" of line 4240 of `VulkanHppGenerator.cpp`.

**Comment by asuessenbach** [comment]
Thanks for spotting this issue!
