### ISSUE TITLE
About UniqueHandle for DebugUtilsMessengerEXT

### ISSUE THREAD

**Issue by BlurringShadow** [KhronosGroup/Vulkan-Hpp#372]
It seems that if the I use UniqueDebugUtilsMessengerEXT type will get a link error, as reported in [https://stackoverflow.com/questions/55233129/vulkan-hpp-unique-handles-for-extensions?r=SearchResults](url). So I substitute it.
```C++
using unique_debug_utils_messenger_ext = UniqueHandle<DebugUtilsMessengerEXT, DispatchLoaderDynamic>;
...
UniqueInstance instance_{nullptr};
UniqueDevice device_;
unique_debug_utils_messenger_ext debug_messenger_;
DebugUtilsMessengerCreateInfoEXT debug_messenger_create_info;
DispatchLoaderDynamic dispatch_loader_dynamic_;
...
dispatch_loader_dynamic_ = {*instance_, *device_};
debug_messenger_ = instance_->createDebugUtilsMessengerEXTUnique(
			debug_messenger_create_info,
			nullptr,
			dispatch_loader_dynamic_);
```
So that I could continue using the smart pointer feature. Same as the UniqueDebugReportCallbackEXT type. I wonder if there is a better way to solve it.
Thanks for reading my issue.

**Comment by asuessenbach** [comment]
Your approach is absolutely correct. It works with every extension without explicitly getting their function pointers. But you have to introduce your own UniqueHandleTypes, based on the DispatchLoader you're using.
The other valid way is described in that stackoverflow post, and also used in samples/utils/utils.cpp. The downside of that approach is, that you have to explicitly get all the function pointers and provide some wrapper functions for them. But now you can simply use the "standard" vk::UniqueHandleTypes.

**Comment by BlurringShadow** [comment]
Thanks a lot.
