### ISSUE TITLE
This screws up the usage of Volk for me.

### ISSUE THREAD

**Issue by Carandiru0** [KhronosGroup/Vulkan-Hpp#378]
This screws up the usage of Volk for me. 
I have simply exposed the DispatchLoaderStatic by removing the new #ifdefs that surrounded it. And deleted the NeedsExplicitDispatchLoader typedef to get it working again
Using latest version of Volk and have predefined VK_NO_PROTOTYPES

DispatchLoaderStatic, in this case, maps to the functions defined in Volk nicely, I do not link with the vulkan.lib static library.

. This regression should be reverted or make the changes as stated above.

Attached changed vulkan.hpp that has me compiling again. Thanks.

[vulkan.zip](https://github.com/KhronosGroup/Vulkan-Hpp/files/3591290/vulkan.zip)

_Originally posted by @Carandiru0 in https://github.com/KhronosGroup/Vulkan-Hpp/pull/328#issuecomment-529531386_

**Comment by res2k** [comment]
I took a look at what Volk does:
1. `#define`s `VK_NO_PROTOTYPES`
2. Includes `vulkan.h`
3. Defines it's own Vulkan "functions" (pointers actually)

So the simplest solution is to `#undef`ine `VK_NO_PROTOTYPES` after Volk made it's own function definitions. Arguably, that would also be a more consistent state of affairs - there _are_ prototype-compatible definitions available, but currently the macro says there aren't.

Anyway, such an `#undef VK_NO_PROTOTYPES` could either happen in Volk itself (you'd need to file a PR there) or in your own code (after including `volk.h`, before `vulkan.hpp`).

**Comment by asuessenbach** [comment]
@Carandiru0 Does the comment from @res2k resolve your issue?

**Comment by Carandiru0** [comment]
#defines VK_NO_PROTOTYPES
was previously used to prevent including the runtime
To use volk, you have to include volk.h instead of vulkan/vulkan.h; this is necessary to use function definitions from volk. If some files in your application include vulkan/vulkan.h and don't include volk.h, this can result in symbol conflicts; consider defining VK_NO_PROTOTYPES when compiling code that uses Vulkan to make sure this doesn't happen.

So I would have to say undefining it is not ideal. It could defeat the purpose of using Volk in the first place. Nonetheless, the issue is that Volk worked great with vulkan-hpp before this change. I can work around it no problem as described above, however I posted this issue not myself but to make you aware of this regression, and so other's who are using Volk can be aware of it.

**Comment by res2k** [comment]
> So I would have to say undefining it is not ideal. It could defeat the purpose of using Volk in the first place. Nonetheless, the issue is that Volk worked great with vulkan-hpp before this change. I can work around it no problem as described above, however I posted this issue not for myself, but to make you aware of this regression, and so other's who are using Volk can be aware of it.

_Some_ way to avoid the definition of `DispatchLoaderStatic` is required, as sometimes, there are really no definitions for Vulkan functions; see PR #328 for an example.
So the only other way would be to require a separate preprocessor macro, e.g. `VULKAN_HPP_NO_DISPATCH_LOADER_STATIC`, to disable `DispatchLoaderStatic`.

**Comment by mtavenrath** [comment]
If VK_NO_PROTOTYPES is defined we honor the spec that there are no prototypes defined and thus we cannot define the DispatchLoaderStatic. As @res2k states, the correct workaround is undefining VK_NO_PROTOTYPES after including volk.

@Carandiru0 We have added a full transparent loader support which makes the use of volk unnecessary in combination with Vulkan-Hpp. For a full example how to use the feature check out

https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/tests/DispatchLoaderDynamic/DispatchLoaderDynamic.cpp

The short summary is either ```#define VK_NO_PROTOTYPES``` or ```#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1``` and add ```VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE;``` to any compilation unit. This will replace the use of the static dispatcher by the dynamic dispatcher. Afterwards follow the test on how to initialize the function pointers.

**Comment by Carandiru0** [comment]
Thanks guys!
