### ISSUE TITLE
Add conversion operator vulkan handle->uint_64

### ISSUE THREAD

**Issue by Karlovsky120** [KhronosGroup/Vulkan-Hpp#399]
I'm trying to name a `vk::Buffer` using `vk::Device::setDebugUtilsObjectNameEXT(...);`
It requires a structure that has an `objectHandle` as one of its members, which expects an `uint_64` type value.

Passing a `vk::Buffer` object directly causes a no suitable conversion error.
A somewhat ugly 

```
vk::Buffer buffer;
uint64_t = (uint64_t)VkBuffer(buffer);
// or (uint64_t)(VkBuffer)buffer;
```

does work.

Adding something along the lines of

```
VULKAN_HPP_TYPESAFE_EXPLICIT uint64_t operator uint64_t() const
{
    return (uint64_t)m_buffer;
}
```

to vk::Buffer makes the following code correct:

```
vk::Buffer buffer;
uint64_t = buffer;
```

This can, of course, be applied to every other Vulkan handle.

If there is no reason against doing this, I'd be happy to create a pull request.

**Comment by pierremoreau** [comment]
That would be nice!

I have been using the following macro:
```
#define DEFINE_OBJECT_HELPERS( obj )                                           \
	[[maybe_unused]] inline Vk##obj castToCType( vk::obj const object ) {  \
		return static_cast<Vk##obj>( object );                         \
	}
```
and applying it to all known Vulkan object types, to then use `static_cast<uint64_t>(castToCType(buffer));` for the same reason.

**Comment by asuessenbach** [comment]
To allow something like 
```
vk::Buffer buffer;
uint64_t b = buffer;
```
that conversion operator would need to be implicit. And I'd consider an implicit converion to an uint64_t too dangerous. The compiler gets too much freedom to make something you would not expect.
And I don't see much value in an explict conversion as well.

**Comment by Karlovsky120** [comment]
Yeah, I wondered if that would be a problem. You're right.
