### ISSUE TITLE
Make DescriptorSetLayoutBinding constructors constexpr

### ISSUE THREAD

**Issue by cos-public** [KhronosGroup/Vulkan-Hpp#401]
Make DescriptorSetLayoutBinding constructors constexpr, because I don't see a reason why not. And actually it is handy to declare simple bindings at compile-time.

**Comment by asuessenbach** [comment]
There already is a constexpr constructor of DescriptorSetLayoutBinding (and other structs as well). What are you missing?

**Comment by cos-public** [comment]
It's not, as far as I can see: https://raw.githubusercontent.com/KhronosGroup/Vulkan-Headers/ba091ba6a947f79623b28fe8bfccdce1ab9fa467/include/vulkan/vulkan.hpp line 27060:
```
    DescriptorSetLayoutBinding( uint32_t binding_ = 0,
                                vk::DescriptorType descriptorType_ = vk::DescriptorType::eSampler,
                                uint32_t descriptorCount_ = 0,
                                vk::ShaderStageFlags stageFlags_ = vk::ShaderStageFlags(),
                                const vk::Sampler* pImmutableSamplers_ = nullptr )
      : binding( binding_ )
      , descriptorType( descriptorType_ )
      , descriptorCount( descriptorCount_ )
      , stageFlags( stageFlags_ )
      , pImmutableSamplers( pImmutableSamplers_ )
    {}
```

as well as PushConstantRange constructor (line 52636)
VULKAN_HPP_CONSTEXPR macro is missing in both cases.

**Comment by asuessenbach** [comment]
As of now, the new version in [https://github.com/KhronosGroup/Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers) has the constrexpr constructors.

**Comment by cos-public** [comment]
Yes, that's great. The KhronosGroup/Vulkan-Hpp repo is referring to the previous version of Vulkan-Headers. I'm a bit confused about interlinking of these repos, but anyway, that's fixed, and I'll wait for the next SDK release with these improvements.
