### ISSUE TITLE
cmake compilation fails

### ISSUE THREAD

**Issue by dov** [KhronosGroup/Vulkan-Hpp#402]
Trying to build Vulkan-hpp (in order to generate the examples) fails on my Fedora 30 system. Here are the steps I did from the top dir

```
git clean -xfd
git reset --hard
mkdir build
cd build
cmake ..
```

This fails as follows:
```
CMake Error at CMakeLists.txt:69 (add_executable):
  Cannot find source file:

    tinyxml2/tinyxml2.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:69 (add_executable):
  No SOURCES given to target: VulkanHppGenerator


-- Build files have been written to: /space/pub-repos/Vulkan-Hpp/build

```

**Comment by dov** [comment]
The issue is most easily solved just by copying ```tinyxml2.cpp``` and `tinyxml2.h` into the ```./tinyxml2``` directory. You probably just forgot to add these files to git.

**Comment by asuessenbach** [comment]
tinyxml2 (as well as glm, glslang, glfw, and Vulkan-Headers) are added to this repo as submodules. You should just update them.

**Comment by dov** [comment]
Thanks. I missed initially missed that. Closing.
