### ISSUE TITLE
CMake build is broken for samples and tests

### ISSUE THREAD

**Issue by dov** [KhronosGroup/Vulkan-Hpp#403]
There are several issues with the cmake build for the samples and the tests:

1. The README.md file should describe how to build them, or perhaps add a INSTALL.md file describing the needed git and ccmake commands.
2. There is a CMake reference to the function `error` that doesn't exist. The proper cmake way of doing a fatal error is `message(FATAL_ERROR "barfing")`.
3. (The utils library should be expanded to support glfw and not only HWND windows. But that is a separate issue).

**Comment by asuessenbach** [comment]
Thanks for your feedback!
Bullet point 2 is fixed with PR #404. The others will probably take a little longer.

**Comment by asuessenbach** [comment]
There is some description on building samples and tests in the readme.md for a while now. And, as you mentioned, expanding the utils library is a separate issue.
So, closing out this issue as fixed.
