### ISSUE TITLE
Allow custom throwResultException

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/Vulkan-Hpp#406]
`throwResultException` is a relatively large `switch` case of throwing code that's being marked with `__attribute__((always_inline))` in clang and gcc. This will repeat the same code in all `vulkan.hpp` callers that return an error code in C (most Vulkan functions).

I'd like to be able to define a custom `throwResultException` that does not get inlined in all callers without losing the exception based API.

**Comment by asuessenbach** [comment]
You're right, `throwResultException` being inlined isn't really needed, as it's only called in case of error anyways. So perf shouldn't matter here.
That is, I don't think it's worth to have a custom version, just removing the VULKAN_HPP_INLINE should do the job.
Do you agree?

**Comment by ReinUsesLisp** [comment]
While we are at it, it might also be beneficial to mark this function as `[[noreturn]]`.
