### ISSUE TITLE
How does new Flags work ?

### ISSUE THREAD

**Issue by HelloWorldlsla** [KhronosGroup/Vulkan-Hpp#413]
I don't understand how I can use flags with this API to know if a queue supports graphics.
I found a solution but I think that this solution is not the best one :
```
VkQueueFamilyProperties &oldProperties = properties;
if (oldProperties.queueFlags & VK_QUEUE_GRAPHICS_BIT) {
```
Any answer will be appreciated.

And I think we should also put the answer in the README file, maybe other people didn't understand that.

**Comment by HelloWorldlsla** [comment]
But why don't add some useful functions in QueueFamilyProperties ?

**Comment by asuessenbach** [comment]
You can check it like this:
`if (properties.queueFlags & vk::QueueFlagBits::eGraphics)`
And we don't add any functions or new member variables that are not part of the vulkan spec.
