### ISSUE TITLE
Depend on "windows.h" on win32 breaks mingw usage

### ISSUE THREAD

**Issue by wumo** [KhronosGroup/Vulkan-Hpp#425]
Currently the vulkan.hpp uses "HMODULE" and "LoadLibrary" on win32 platform
```
//vulkan.hpp
...
#elif defined(_WIN32)
      m_library = LoadLibrary( "vulkan-1.dll" );
#else
...
#elif defined(_WIN32)
    HMODULE m_library;
#else
...
```
This makes the user have to include <windows.h> when include <vulkan/vulkan.hpp>.
Please modify the macro to include <windows.h> on win32 platform.

**Comment by Warpten** [comment]
`vulkan.h` already pulls `windows.h` though?

**Comment by wumo** [comment]
@Warpten  I see. It is the problem that `vulkan.h` requires `VK_USE_PLATFORM_WIN32_KHR` to be defined so that `windows.h` will be included. I didn't use `VK_USE_PLATFORM_WIN32_KHR` because I used `glfw`.

**Comment by wumo** [comment]
`glfw` doesn't require `VK_USE_PLATFORM_WIN32_KHR `. In this case, `windows.h` should be included only when the platform is win32.

**Comment by BlurringShadow** [comment]
`/*
#if !defined(VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL)
# define VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL  1
#endif
*/

#if VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL
  class DynamicLoader
`
And I currently comment the macro to avoid error.

**Comment by wumo** [comment]
@BlurringShadow  Unfortunately, I also use   VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL to enable “volk” like loading.

**Comment by YaaZ** [comment]
+1, I am getting `error C3646: 'm_library': unknown override specifier` error on line `HMODULE m_library;` using MSVC

**Comment by mtavenrath** [comment]
By default VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL  is set to 1. If the tool is not required set the define VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL to 0 in your build configuration or before including vulkan.hpp.

**Comment by mtavenrath** [comment]
@wumo Is there a problem adding a #if defined(WIN32) to include <window.h> before including vulkan.h. To prevent a build failure I'm wondering if it'd be better to not set VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL if windows.h hasn't been included before.

**Comment by wumo** [comment]
@mtavenrath  Currently, I use:
```c++
#ifdef _WIN32
  #ifndef NOMINMAX
    #define NOMINMAX
  #endif
  #include <windows.h>
#endif
#include <vulkan/vulkan.hpp>
```
And everything is fine.

As for `VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL `, that's right to not include `windows.h` if dynamic loader is not needed.

**Comment by mtavenrath** [comment]
windows.h is now included by vulkan.hpp iff the dynamoc loader tool is requested through the define. If someone doesn't want to include windows.h he has to add define VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL 0 before including vulkan.hpp. This should handle all use cases.
