### ISSUE TITLE
Almost all operator= lead to memory corruption

### ISSUE THREAD

**Issue by spfuetzner** [KhronosGroup/Vulkan-Hpp#435]
For example:
`    vk::MemoryRequirements2 & operator=( vk::MemoryRequirements2 const & rhs ) VULKAN_HPP_NOEXCEPT
    {
      memcpy( &pNext, &rhs.pNext, sizeof( vk::MemoryRequirements2 ) - sizeof( vk::StructureType ) );
      return *this;
    }
`
On my computer (Windows MSVC x64), sizeof( vk::StructureType) is 4, but &pNext is aligned to 8. So memcpy copies 4 more bytes and overwrites 4 bytes that do not belong to the structure.
This may be part of an "optimization" which in my opinion is completely unnecessary and dangerous (UB). Also every reinterpret_cast I saw in the header is technically UB. It is better to have correct code that can be optimized by the compiler than UB, where the compiler does the wrong thing. This is also true for this (serious) bug.

**Comment by mtavenrath** [comment]
operator= is not supposed to overwrite sType which is the reason for this memcpy.

offsetof(struct, pNext) should be used instead of sizeof(vk::StructureType).
