### ISSUE TITLE
operator== is ambiguous for FlagBits types

### ISSUE THREAD

**Issue by spfuetzner** [KhronosGroup/Vulkan-Hpp#436]
The following code does not build because the compiler (MSVC14, VisualStudio 2015) thinks, the operator== is abiguous with other *FlagBits types in vulkan.hpp.

`#include <vulkan/vulkan.hpp>`
`int main()`
`{`
`    vk::SampleCountFlagBits f1, f2;`
`    f1 == f2;`
`}`

The error message is rather long and begins with:
`1>c:\_code\private-test\test.cpp(7): error C2593: 'operator ==' is ambiguous`
`1>  c:\program files (x86)\windows kits\8.1\include\shared\guiddef.h(192): note: could be 'bool operator ==(const GUID &,const GUID &)'`
`1>  l:\vc14\vulkansdk\1.1.126.0\include\vulkan\vulkan.hpp(6310): note: or       'bool vk::operator ==(vk::AccessFlagBits,vk::AccessFlagBits) noexcept' [found using argument-dependent lookup]`
`1>  l:\vc14\vulkansdk\1.1.126.0\include\vulkan\vulkan.hpp(6417): note: or       'bool vk::operator ==(vk::AttachmentDescriptionFlagBits,vk::AttachmentDescriptionFlagBits) noexcept' [found using argument-dependent lookup]`

**Comment by mtavenrath** [comment]
It turns out that we the default operator== ist constexpr, so there's no need to introduce a custom one which confused msc140.
