### ISSUE TITLE
VK_EXT_headless_surface extension is not available in 1.1.126

### ISSUE THREAD

**Issue by QuantumDeveloper** [KhronosGroup/Vulkan-Hpp#438]
I am trying to use mentioned extension, but its not reported as available and when I try to call it, API reports that 'vkCreateHeadlessSurfaceEXT' entry point not found in vulkan-1.dll

Can you say what I am missing here? Doe this extension really works or I need to do something else to activate it?

**Comment by asuessenbach** [comment]
VK_EXT_headless_surface is an instance extension, and you can get a list of available extensions using vk::enumerateInstanceExtensionProperties().
If that extension is not available, you're not allowed to use it and you should definitely not try to call any extension specific functions or use any extension specific structures.

**Comment by QuantumDeveloper** [comment]
OK, but why this extension could be not available? Does it suppose to be available to windows? Which conditions make this extension to be present in the extension list?

**Comment by asuessenbach** [comment]
I think, this slack channel is a better fit for questions like that: https://app.slack.com/client/TDMDFS87M/CDTJ9BELF
