### ISSUE TITLE
Cannot use Unicode character set (Visual Studio, Win32)

### ISSUE THREAD

**Issue by W4RH4WK** [KhronosGroup/Vulkan-Hpp#444]
Using Vulkan SDK `1.1.126.0`, compilation fails with the following error message, when the character set option of the Visual Studio project is set to Unicode.

```
vulkan.hpp(73814,1): error C2664: 'HMODULE LoadLibraryW(LPCWSTR)': cannot convert argument 1 from 'const char [13]' to 'LPCWSTR'
vulkan.hpp(73814,32): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

This is the offending line: `m_library = LoadLibrary( "vulkan-1.dll" );`

**Comment by asuessenbach** [comment]
This was resolved with #422.
