### ISSUE TITLE
VULKAN_HPP_NAMESPACE is not used across vulkan.hpp

### ISSUE THREAD

**Issue by andreykulik** [KhronosGroup/Vulkan-Hpp#447]
Tried to change default namespace from vk to a different one using VULKAN_HPP_NAMESPACE.
Unfrotunatelly 75% of the code in vulkan.hpp still uses hardcoded vk:: all over, thus it renders VULKAN_HPP_NAMESPACE setting useless.

**Comment by asuessenbach** [comment]
Good catch! Will fix it.
