### ISSUE TITLE
CLion Compilation Fails on Windows 10

### ISSUE THREAD

**Issue by ROTARTSI82** [KhronosGroup/Vulkan-Hpp#453]
Hello! I've been trying to port an application that I've been writing on Mac over to windows, and I'm using CMake. However, the compile is failing with the error:

```
C:\VulkanSDK\1.1.126.0\Include\vulkan/vulkan.hpp(74354): error C2664: 'PFN_vkVoidFunction (VkInstance,const char *)': cannot convert argument 1 from 'vk::Instance' to 'VkInstance'
C:\VulkanSDK\1.1.126.0\Include\vulkan/vulkan.hpp(74354): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```
repeating over and over again (The line number goes from 74354 to 74505 at which point make just gives up because we exceeded 100 errors)

I'm compiling with `/std:c++17`.

This compiles just fine on mac. (Of course, I've changed the CMakeLists.txt to link to the correct libraries and include dirs)

I'm using CLion's built in CMake on Windows 10 64-bit, and I'm building using:
`C:\Program Files\JetBrains\CLion 2019.3.1\bin\cmake\win\bin\cmake.exe" --build C:\Users\PATH\TO\MY\PROJECT\BUILD\DIR --target all`

**Comment by asuessenbach** [comment]
Is that a 32 bit build?
If so, have you tried to explicitly define VULKAN_HPP_TYPESAFE_CONVERSION?

**Comment by asuessenbach** [comment]
@ROTARTSI82 has this issue been resolved?
Assuming it is, so closing it. You can easily re-open if it's still valid.
