### ISSUE TITLE
PhysicalDeviceMemoryProperties operator== error?  0 items shouldn't need to compare memory no?

### ISSUE THREAD

**Issue by Keith-Albright-Bose** [KhronosGroup/Vulkan-Hpp#456]
I have unit tests around objects I'm using that wrap vulkan.hpp objects.
One of my tests was failing .
I tracked it down to operator== for the PhysicalDeviceMemoryProperties.
Looking at the code it compares the count of types but then proceeds to compare the full size of memory not the count.  The result seems to be uninitialized memory is compared.  Vulkan.hpp doesn't consistently initialize things in spite of the assumed promise to initialize things.  I can work around but wanted to point this out.  e.g. I would use memoryTypeCount in place of VK_MAX_MEMORY_TYPES and memoryHeapCount in place of VK_MAX_MEMORY_HEAPS such that 0 would do a 0 sized compare or only the valid number of items are compared.

bool operator==( PhysicalDeviceMemoryProperties const& rhs ) const VULKAN_HPP_NOEXCEPT
    {
      return ( memoryTypeCount == rhs.memoryTypeCount )
          && ( memcmp( memoryTypes, rhs.memoryTypes, VK_MAX_MEMORY_TYPES * sizeof( vk::MemoryType ) ) == 0 )
          && ( memoryHeapCount == rhs.memoryHeapCount )
          && ( memcmp( memoryHeaps, rhs.memoryHeaps, VK_MAX_MEMORY_HEAPS * sizeof( vk::MemoryHeap ) ) == 0 );
    }

**Comment by mtavenrath** [comment]
This is indeed an interesting observation.
Seeing the structure as container with a ptr + count it makes sense to compare only count items. Seeing the structure from a plain Vulkan C view one would have to compare the complete array.

I'm  currently trending towards handling the 'special cases' for array with a count the with the proposal.
