### ISSUE TITLE
PhysicalDeviceProperties and many other structs now default constructs uninitialized in 126

### ISSUE THREAD

**Issue by Keith-Albright-Bose** [KhronosGroup/Vulkan-Hpp#457]
I ran into another case of my unit test failing that newly constructed objects were not the same.

PhysicalDeviceProperties has an empty default constructor.  This overrides the default constructor which results in uninitialized memory when the assumption is it is default initialized.
So a client using PhysicalDeviceProperties props{}; in a class might expect default initialization except in this case the specified empty default constructor leaves all members uninitialized.

Having 
PhysicalDeviceProperties() = default;
would yield the expected behavior.

See: https://en.cppreference.com/w/cpp/language/value_initialization

**Comment by Keith-Albright-Bose** [comment]
Ok this is a general regression from 108.  108 didn't specify constructors so they were implicitly defaulted which meant using in a class with empty brace initializer properly set all members to 0.  Now it's all bust meaning I have to now initialize what should have been initialized to avoid failing tests.  I'm seeing same with most every vulkan.hpp struct member of my object class.  

 PhysicalDeviceMemoryProperties() VULKAN_HPP_NOEXCEPT
    {}
Is NOT the same thing as the default constructor.

108 did not have this.

**Comment by asuessenbach** [comment]
That issue has already been adressed with #455.
@Keith-Albright-Bose: Would you mind running your unit tests with the corresponding vulkan.hpp?

**Comment by mtavenrath** [comment]
Closing since the issue has been addressed with #455.

@Keith-Albright-Bose Feel free to reopen the issue with more details if something is not yet correct.
