### ISSUE TITLE
Use of GSL (Guideline Support Library) for ArrayProxy ?

### ISSUE THREAD

**Issue by vlj** [KhronosGroup/Vulkan-Hpp#46]
Hi,
GSL is a library that provides some types aimed at type safety and improved ownership semantics. It has a gsl::span<> type which is a non owning view over contigus collection of object in memory like std::array, std::vector, or raw pointer. I think it does the same things as ArrayProxy does plus it's intended to be understood by static analysis Tools and it hides pointer arithmetics with the help of subspan() functions :
https://github.com/Microsoft/GSL
Given that GSL is a semi standard in C++ (the gsl::string_view class made it to C++17 drafts) it would be nice to have some overloads accepting gsl::span instead of ArrayProxy (maybe guarded behind an ifdef).

Regards,
Vincent

**Comment by mtavenrath** [comment]
Hi,
this is an interesting suggestion. The 'best' solution would be a typedef which chooses either gsl::span or ArrayProxy is they're fully compatible. Did you check if gsl::span and the ArrayProxy are compatible with respect to construction?

**Comment by mtavenrath** [comment]
We're not going to implement features which do require 3rdparty libraries. Closing.
