### ISSUE TITLE
GLFW is there but no Linux samples available

### ISSUE THREAD

**Issue by filipwasil** [KhronosGroup/Vulkan-Hpp#463]
Hello,

Is there specific reason why Linux build is "Unhandled platform" ? Seems like an easy thing to do. GLFW is already there.

**Comment by mtavenrath** [comment]
The only reason for missing Linux samples is the lack of time. PRs which add glfw samples are welcome.

**Comment by mocabe** [comment]
Please check out my PR (#491) and see if it works on your machines :)
