### ISSUE TITLE
signature for getAccelerationStructureHandleNV appears incorrect

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Hpp#469]
The current signature for enhanced operation is

```
template<typename T, typename Dispatch>
  VULKAN_HPP_INLINE ResultValueType<void>::type 
  Device::getAccelerationStructureHandleNV( 
    vk::AccelerationStructureNV accelerationStructure, 
    ArrayProxy<T> data, 
    Dispatch const &d 
) const;
```

However, it appears that the correct signature should be 

```
template<typename T, typename Dispatch>
  VULKAN_HPP_INLINE ResultValueType<T>::type 
  Device::getAccelerationStructureHandleNV( 
    vk::AccelerationStructureNV accelerationStructure,
    Dispatch const &d 
) const;
```

The problem appears to be that the parser is seeing the raw signature of 

```
VkResult vkGetAccelerationStructureHandleNV( 
  VkDevice device, 
  VkAccelerationStructureNV accelerationStructure, 
  size_t dataSize, 
  void* pData 
)
```

and assuming that the `dataSize` / `pData` denotes an input array of untyped values.  However, because the type of `pData` is `void*` and not `const void*` the process should realize that this is an output variable, not an input variable and favor returning a `T` or `vector<T>` over accepting an `ArrayProxy` input.

**Comment by asuessenbach** [comment]
Interesting idea!
Unfortunately, there are two more functions following the same API pattern (size_t dataSize; void * pData;) but completely different logic:
For vkGetAccelerationStructureHandleNV, dataSize has to be at least 8.
For vkGetRayTracingShaderGroupHandlesNV, dataSize to be at least VkPhysicalDeviceRayTracingPropertiesNV::shaderGroupHandleSize * groupCount.
For vkGetQueryPoolResults, dataSize has to be at least queryCount * stride; that is, some of the memory might be kept unaltered by that function.
After all, none of that logic is visible through the specifying vk.xml, so I doubt we could find some general logic to improve that API. Means: we could just introduce a special case for just that function.
Special-casing single functions has already been done, sure, but I don't like that idea either.
On the other hand, having some function like
```ResultValueType<uint64_t> Device::getAccelerationStructureHandleNV(vk::AccelerationStructureNV accelerationStructure, Dispatch const & d) const```
 is really tempting.
