### ISSUE TITLE
Any API documentation or cheat sheet for vulkan.hpp?

### ISSUE THREAD

**Issue by adamcavendish** [KhronosGroup/Vulkan-Hpp#47]
I wonder whether there're any API documentation or cheat sheet for vulkan.hpp? It might be easier to reference to or search from.

**Comment by jherico** [comment]
There's this:  https://www.khronos.org/files/vulkan10-reference-guide.pdf

Translating from the reference guide (which refers to the C bindings) to the C++ version is pretty easy

**Comment by adamcavendish** [comment]
Thx. I thought you might have some generated docs for reference... I think I got to grep the headers for some info~

**Comment by mtavenrath** [comment]
@adamcavendish What kind of information are you missing? 

The README explains the 'differences' between the C and the C++ API. Using the original cheatsheet jherico mentioned you should be good to go.

Assuming there would be a cheatsheet, would it be enough to show only the transformed C++ functions which support arrays and references?

**Comment by adamcavendish** [comment]
@mtavenrath  Just some tiny info, like is some type assignable or comparable etc., and vk::Extent2D does not support initializer_list etc. Grepping would be fine.

**Comment by jherico** [comment]
An initializer list is arbitrary length.  `Extent2D` requires exactly two arguments.  You can declare `vk::Extent2D foo { 1, 2 };` or for that matter, pass `{ 1, 2}` into any function that expects an `Extent2D` and it will implicitly create one.  Why would you want initializer lists?

**Comment by adamcavendish** [comment]
@jherico Ah, I just made an example to specify what I was grepping in the morning, not for asking a feature or sort of that. I just used `vk::Extent2D foo(1, 2)`. Anyway, thx for the answer.

**Comment by Tachi107** [comment]
Same here. The best doc I found about Vulkan.hpp is [this pdf](https://www.khronos.org/assets/uploads/developers/library/2017-vulkan-devu-vancouver/006-VulkanC++Bindings.pdf) (or [this](https://www.khronos.org/assets/uploads/developers/library/2016-vulkan-devu-seoul/4-Vulkan-HPP.pdf)) that I believe if from some kind of talk about the hpp itself. 
I think that we need a complete doc about Vulkan.hpp that we could use instead of the one used to describe the C bindings; that could be expecially useful to starters who are already struggling undestranding Vulkan's concepts.

**Comment by pc-john** [comment]
Nothing against cheatsheet or complete doc, if somebody creates it or contributes it.
In my opinion, Vulkan.hpp is so close to C API that intelli sense of IDE is usually enough. In more complicated cases, some IDEs usually allow one click jump to C++ vulkan.hpp declaration and short look explains any API doubts. Wherever C++ API is more complicated, I suggest to read https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/README.md first and than discuss what is missing. Other suggestions?
