### ISSUE TITLE
`CommandBuffer::bindVertexBuffers` generates wanrings on MSVC 2019

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Hpp#470]
The enhanced mode version of `CommandBuffer::bindVertexBuffers` is labeled `VULKAN_HPP_NOEXCEPT`, but it explicitly checks that the incoming array proxies for vertex buffers and array offsets are the same size and if they aren't it throws an exception in contravention of the `VULKAN_HPP_NOEXCEPT` annotation.  

This generates a warning, and in turn is causing my port of the Vulkan-Samples repository to the C++ bindings to fail unless I turn off the "warnings as errors" option that defaults to on.

**Comment by asuessenbach** [comment]
This has already been resolved with PR #416.

**Comment by mtavenrath** [comment]
resolved, closing.
