### ISSUE TITLE
vk::ErrorOutOfDateKHR terminates program as a result of being thrown.

### ISSUE THREAD

**Issue by isaboll1** [KhronosGroup/Vulkan-Hpp#479]
Given that now in Vulkan Hpp, Vulkan errors now throw a std::runtime_error, errors can cause applications to terminate as a result of capturing them. For a good portion of errors, this behavior handles common errors which cannot be readily handled, however for the case of the error "VK_ERROR_OUT_OF_DATE_KHR ", this leads into behavior that I believe conflicts with advice given within the spec.

In the specification, when an application captures this error, the application "must query the new surface properties and recreate their swapchain if they wish to continue presenting to the surface". The fact that this error is thrown in Vulkan-Hpp and terminated under default behavior conflicts with the ability to do this. Previous versions of Vulkan-Hpp didn't create such a circumstance. The fact that it does this now messes with code for resizing swapchains for example, as on Linux using some Mesa drivers, the act of resizing can give that error result.

**Comment by asuessenbach** [comment]
Well, throwing an error (if not VULKAN_HPP_NOEXCEPT is defined) is in vulkan.hpp for quite some time now.
The standard approach for handling that would be a try/catch around that error provoking function. Is there a reason that prevents that in your case?
If you need to, you can define VULKAN_HPP_NOEXCEPT before including vulkan.hpp and handle all errors on your own.

**Comment by isaboll1** [comment]
I have tried to try/catch the code giving the error, and that works if i catch the error around queue.presentKHR. The try/catch clause doesn't seem to catch any error surrounding device.acquireNextImageKHR, which is before any code within my rendering loop. past versions of vulkan hpp i've found this wasn't much of an issue, and under regular c code this isn't an issue as well.

VULKAN_HPP_NOEXCEPT would require writing certain parts of the code differently, given the requirement to perform error handling manually. this applies to rendering commands as well. It's very weird considering that past versions of Vulkan Hpp captured the error in such a way where i cold process it in a vkResult without needing to use VULKAN_HPP_NOEXCEPT, allowing me to handle that particular case. either way, resizing seems to work correctly now when using the exception over the present.

**Comment by asuessenbach** [comment]
> It's very weird considering that past versions of Vulkan Hpp captured the error in such a way where i could process it in a vk::Result
Could you please tell us what version you used before?

**Comment by isaboll1** [comment]
I believe the version was in SDK version 1.1.126. however going back to that version I found that i ran into the same issue. perhaps the root cause wasn't the version i am using, but instead the driver as i did recently change to a different MESA driver. I apologize for the disruption
