### ISSUE TITLE
Newbie question: vulkan/vulkan.hpp not found?

### ISSUE THREAD

**Issue by kershnerd** [KhronosGroup/Vulkan-Hpp#487]
I am on a MAC and using `clion` IDE.

When I clone this repo and all submodules, I am able to load the CMakeLists.txt project and compile and run with no trouble.

But when I load the CMakeLists.txt project in the samples/01_InitInstance folder, I get the following error when compiling:

```/Users/jeff/projects/personal/Vulkan-Hpp/samples/01_InitInstance/01_InitInstance.cpp:18:10: fatal error: 'vulkan/vulkan.hpp' file not found```

I see the vulkan/vulkan.hpp from the root directory.  How do the sample projects find this file?

**Comment by mtavenrath** [comment]
By default the samples & tests use the Vulkan SDK. There are two cmake options which have to be anbled to use the local version of vulkan.hpp
SAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP
TESTS_BUILD_WITH_LOCAL_VULKAN_HPP

**Comment by asuessenbach** [comment]
Assuming this is resolved.
