### ISSUE TITLE
Misleading function name description

### ISSUE THREAD

**Issue by Wasabichicken** [KhronosGroup/Vulkan-Hpp#49]
Hi,

The README states:

> All functions, enums and structs have the Vk prefix removed. `vkCreateImage` can be accessed as `vk::CreateImage`

Some functions do not follow this naming convention with respect to leading uppercase letters, e.g. `vk::enumerateInstanceLayerProperties()` or `vk::enumerateInstanceExtensionProperties()` (there may be others). Either they should be re-named to follow the naming convention, or the README should be clarified.

**Comment by xXSeraphimXx** [comment]
I do not thing it's meant to be written with upper letters. So far as I know the convention is to start method names with lower case letters and not uppercase. Uppercase conventions is only used in C# I thought.

**Comment by Wasabichicken** [comment]
I agree, the correct fix here is probably to adjust the README, i.e. "vkCreateImage can be accessed as vk::createImage".
