### ISSUE TITLE
Generator Asserts with 1.0.35 version of vk.xml

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Hpp#51]
Tried Windows and Linux -- debug builds assert as follows while release builds hang.

C:\dev\xgl\Vulkan-Hpp\build\Debug>.\VulkanHppGenerator.exe .\vk.xml
Loading vk.xml from c:\[blah]\vk.xml
Writing vulkan.hpp to C:\blah\Vulkan-Hpp\vulkan\vulkan.hpp
Assertion failed: stit != vkData.structs.end() && stit->second.protect.empty(), file C:\dev\xgl\Vulkan-Hpp\VulkanHppGenerator.cpp, line 1205

**Comment by mtavenrath** [comment]
Fixed with pull request #54

**Comment by mark-lunarg** [comment]
Thanks a bunch, Markus!
