### ISSUE TITLE
Multiple parser failures when disabling extensions in vk.xml

### ISSUE THREAD

**Issue by wheybags** [KhronosGroup/Vulkan-Hpp#531]
I'm trying to use the generator with most extensions disabled (by setting supported="disabled" in vk.xml), as I want to generate only the extensions I actually intend to use.
The parser seems to not handle this very well, with multiple unrelated errors cropping up when I do.
For example, if you disable VK_KHR_draw_indirect_count, it errors trying to remove the vkCmdDrawIndirectCountAMD command, because the command is just an alias, and this is not handled for commands (I guess because none of the current default disabled extensions use disabled commands).

From what I can tell the generator does a bunch of "linting" on the vk.xml file, some of which only kicks in when an extension is disabled. A lot of this linting is either correctly failing, or erroring out due to missing functionality in the parser, like the issue with VK_KHR_draw_indirect_count described above. Apart from the use case of wanting a vulkan.hpp without extensions, it might be a good idea to get this working just to make sure the data in vk.xml is all correct, and that the parser will continue to work following any future deprecations.

**Comment by asuessenbach** [comment]
You're right, the extensions disabled handling is not complete. I've improved that a bit with #533, but can't test lots of disabled-configurations of the vk.xml.
Would be great if you could tell me on which other extensions, the generator errors out when you disable them. (After #533 is merged, of course).
