### ISSUE TITLE
Consider to return std::string_view from vk::to_string

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#534]
`vk::to_string` deal with string literals internally. Dynamic memory management (despite of SSO) introduced by `std::string` looks redundant. It clearly possible to return just `const char *` or C++-ish `std::string_view`, which both can be easily converted to `std::string` if necessary on user code side.
BTW [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view/basic_string_view) is C++17 feature.

**Comment by Wunkolo** [comment]
This would be good for a lot of the `vk::to_string` functions, but not the bit-flag ones where the string is _generated_ like `{ FLAG0 | FLAG1 | FLAG3 }` and you can't just provide a `const char *` or `std::string_view` since it is dynamically created as an `std::string`.
It would be good if there was a way to have the non-generated `to_string` functions return a `std::string_view` to their constant string literals and the generated ones can continue to return an `std::string`.

**Comment by tomilov** [comment]
I would prefer to format string for bit flags by myself. For me it would be better if imaginary `vk::to_vector` would return container of individual `*FlagBits` from `*Flags`, then I can apply `vk::to_string(*Flags value)` to them or use in different logic.
It possible to invent some kind of forward iterators on bitmask (container of individual bits) using `(x - 1) & x` trick to detect lowest set bit. Though it would not be the good practice.

**Comment by asuessenbach** [comment]
For what reasons would you want to have a std::string_view out of the vk::to_string functions?
We think, they're just for debugging purposes, where performance is not the most important argument.
Besides that, there is no implicit converstion from std::string_view to std::string. That is, if we would change those functions to return a std::string_view, everyone who assigns that to a std::string would have to modify their code.
And regarding the vector of FlagBits: what would you gain with that?

**Comment by tomilov** [comment]
It maybe antipattern but I use strings for the following predicate:
```
inline bool isSrgbFormat(vk::Format format)
{
    std::string f = vk::to_string(format);
    std::string_view suffix = "Srgb";
    assert(std::size(f) >= std::size(suffix));
    return std::equal(std::crbegin(suffix), std::crend(suffix), std::crbegin(f));
}
```
> Besides that, there is no implicit conversion from std::string_view to std::string. That is, if we would change those functions to return a std::string_view, everyone who assigns that to a std::string would have to modify their code.
This is the stopper.
```
for (auto bit : FlagBits) std::cout << vk::to_string(bit) <<  ' ';
```
