### ISSUE TITLE
XML warnings building 1.2.134 headers

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#535]
I got these warnings building headers from the latest spec update. They didn't seem to compromise the header so I went ahead and updated the repo, but it would be great to not encounter them in the future as none of them are useful.

```
Loading vk.xml from ../Vulkan-Docs/xml/vk.xml
Writing vulkan.hpp to /home/tree/git/Vulkan-Hpp/vulkan/vulkan.hpp
Spec warning on line 160 unknown attribute <requires>!
```

Line 160 is a valid XML dependency and this attribute is used elsewhere in this section, so not sure why it would even complain.

```
Spec warning on line 5209 enum <VkSemaphoreCreateFlagBits> is not listed as enum in the types section!
Spec warning on line 5209 enum <VkSemaphoreCreateFlagBits> is not listed as an requires for any bitmask in the types section!
```

This must be a new warning? I don't recall seeing it before. Suggest suppressing it, at least in the case when it is an empty enumerated type - this is here intentionally as a placeholder for future extensions.

```
Spec warning on line 9201 unknown attribute <specialuse>!
```

This is a recently added attribute which I suspect can be ignored by Vulkan-Hpp. It just tags certain extensions as being intended for certain restricted use cases.

**Comment by asuessenbach** [comment]
The warnings on line 160 and on the attribute <specialuse> are resolved with the #536.
The warnings on VkSemaphoreCreateFlagBits are new, and could easily be resolved withing the vk.xml:
1. on line 242 in vk.xml:
        <type                                             category="bitmask">typedef <type>VkFlags</type> <name>VkSemaphoreCreateFlags</name>;</type>
VkSemaphoreCreateFlagBits should be listed here are as "requires",
2. lines 396 - 606 in vk.xml:
VkSemaphoreCreateFlagBits should be listed here are as category="enum"
Would that be an option? Could remove some special handling in the hpp generator.
