### ISSUE TITLE
Perfectly trivially copyable types are not trivially copyable

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/Vulkan-Hpp#546]
I'm on commit `74556a1` from `Vulkan-Headers`.

Recent headers started adding a defined constructor for trivial Vulkan types:
```cpp
  struct DescriptorImageInfo
  {
    VULKAN_HPP_CONSTEXPR DescriptorImageInfo( DescriptorImageInfo const& rhs ) VULKAN_HPP_NOEXCEPT
      : sampler( rhs.sampler )
      , imageView( rhs.imageView )
      , imageLayout( rhs.imageLayout )
    {}
```
This immediately makes the type non-trivially copyable, making it impossible to put on unions and making its `std::memcpy` calls undefined behaviour (something that is done in a copy assignment method from the same class).

These constructors don't have to be defined, C++ takes care of them when no destructor is defined, as it can be seen [here](https://godbolt.org/z/-3mUMp).

**Comment by asuessenbach** [comment]
Actually, it's not only the copy constructor that prevails using such a struct as a member in a union. It's also the non-trivial default constructor
```
    VULKAN_HPP_CONSTEXPR DescriptorImageInfo( VULKAN_HPP_NAMESPACE::Sampler sampler_ = {},
                                              VULKAN_HPP_NAMESPACE::ImageView imageView_ = {},
                                              VULKAN_HPP_NAMESPACE::ImageLayout imageLayout_ = VULKAN_HPP_NAMESPACE::ImageLayout::eUndefined ) VULKAN_HPP_NOEXCEPT
      : sampler( sampler_ )
      , imageView( imageView_ )
      , imageLayout( imageLayout_ )
    {}
```
As an alternative, and if you're allowed to use C++17 features, I would recommend to use std::variant, instead.

**Comment by ReinUsesLisp** [comment]
My problem is with the copy constructor. As it can be seen [here](https://godbolt.org/z/atJFJ6), copy constructors break union compatibility. Having a non-trivial default constructor is not a problem for unions, it's possible to specify what union you want to initialize:
```cpp
struct Foo {
    Foo() : foo{} {}

    union {
        DescriptorImageInfo foo;
        OtherDescriptor bar;
    };
};
```

Older Vulkan-Hpp releases didn't ship with a non-trivial copy constructor, hence why it worked.

**Comment by tomilov** [comment]
> It's also the non-trivial default constructor
You can achieve the same behaviour using in-class default member initializers and leave a class aggregate. I think using list initialization everywhere is future of C++.
