### ISSUE TITLE
How to query for empty flag?

### ISSUE THREAD

**Issue by Chrjstoph** [KhronosGroup/Vulkan-Hpp#55]
imageMemoryBarrier.srcAccessMask == 0

Hi, how can I check for this?
I guess thats where the bool operator kicks in:
if(imageMemoryBarrier.srcAccessMask)

But how to pass 0 Flag, e.g. DependencyFlag 0
Like this i guess: {}

But how do I get the flagmask of for example vk::ShaderStageFlagBits?

**Comment by mtavenrath** [comment]
I'l update the documentation

Test if no bit is set ( mask == 0):
If (!imageMemoryBarrier.srcAccessMask) {}

Test if any bit is set:
if (imageMemoryBarrier.srcAccessMask)

Pass Zero flag:
{} (as documented in README.md)

>But how do I get the flagmask of for example vk::ShaderStageFlagBits?
What do you mean with getting the flagMask?

**Comment by mtavenrath** [comment]
Closing since it's not an issue.
