### ISSUE TITLE
vulkan.hpp: createComputePipelineUnique calls undefined createResultValue

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/Vulkan-Hpp#559]
In vulkan.hpp (using Vulkan-Headers 136), `createComputePipelineUnique` calls an undefined version of `createResultValue`:
```
return createResultValue<Pipeline,Dispatch>( result, pipeline, VULKAN_HPP_NAMESPACE_STRING"::Device::createComputePipelineUnique", { Result::eSuccess, Result::ePipelineCompileRequiredEXT }, deleter );
```

`createResultValue` has 5 overloads. The two that take 4 parameters each have either the list of success values or the deleter as the last argument. Should there be a version that takes 5 parameters or should one of the other overloads be used instead (minus one of the last parameters)?

**Comment by asuessenbach** [comment]
Yes, that's a bug in vulkan.hpp. And it's fixed with PR #554.

**Comment by alan-baker** [comment]
Is it expected that Vulkan-Headers will get the fix with it's next release?

**Comment by asuessenbach** [comment]
Yep, that's expected.
