### ISSUE TITLE
Feedback required: Accept nullptr_t for constructor, operator == and operator != to support 0 as input

### ISSUE THREAD

**Issue by mtavenrath** [KhronosGroup/Vulkan-Hpp#56]
It's possible to make the flags class look even more like native flags by adding a new constructor which accepts a nullptr_t whic has a result would accept 0 as only integer. This way one could write

```
SomeFlag flag = 0.
```

In addition to this we could introduce operator == and operator != with nullptr_t to allow comparisons with 0. This change has one side effect can be considered harmless or harmfull. In addition to 0 Vulkan-Hpp would also accept nullptr as input for the constructor and the == and != operators. 

Would this feature be a gain or loss?

**Comment by ioquatix** [comment]
What is the reason for this? Why not just SomeFlag flag; - it should be zero initialized by default IMHO.

**Comment by mtavenrath** [comment]
@ioquatix  Conversion between C-code and passing no flags to functions

```barStruct.barFlags = 0;``` instead of ```barStruct.barFlags = {}```
and 
```fooFunction(..., 0, ...)``` instead of ```fooFunction(..., {}, ...);```

**Comment by ioquatix** [comment]
Ah, it's an interesting idea.
