### ISSUE TITLE
I have add leethomason/tinyxml2 but now I can't make install

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Hpp#575]
Hello,

I am go more far by import https://github.com/leethomason/tinyxml2 instead your tinyxml but I happening :

![VulkanHppErrorHappeningWhenMake](https://user-images.githubusercontent.com/30596513/79898544-b2f30880-840b-11ea-973e-49c0157929c5.jpg)

Thank you in advance to help myself build Vulkan Hpp,

Regards.

azaretdodo.

**Comment by asuessenbach** [comment]
Hi azaretdodo,
could you please tell us the very first error that's happening with your setup? Showing the last few lines doesn't help that much.

**Comment by Azaretdodo** [comment]
Hello,


I type by the hand for you because on my linux system I can't copy past,

The Following error :

''' make[2]: *** [CMakeFiles/VulkanHppGenerator.dir/build.make:83/ CMakeFiles/VulkanHppGenerator.dir/VulkanHppGenerator.cpp.o] Error 1
make[1]: *** [CMakesFiles/Makefile2:96: CMakesFiles/VulkanHppGenerator.dir/all] Error 2
make: *** [Makefile:104: all] Error 22 '''

Thank you in advance to help myslef compile your GitHub by cmake,

Regards.


azaretdodo.
________________________________
De : Andreas Süßenbach <notifications@github.com>
Envoyé : mercredi 22 avril 2020 08:22
À : KhronosGroup/Vulkan-Hpp <Vulkan-Hpp@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-Hpp] I have add leethomason/tinyxml2 but now I can't make install (#575)


Hi azaretdodo,
could you please tell us the very first error that's happening with your setup? Showing the last few lines doesn't help that much.

**Comment by asuessenbach** [comment]
Sorry, azaretdodo, but that doesn't tell anything.
You would have to add the actual error messages, not just the lines that tell you that an error occured.

**Comment by Azaretdodo** [comment]
I won't type all the bash that will take too much time...
________________________________
De : Andreas Süßenbach <notifications@github.com>
Envoyé : mercredi 22 avril 2020 12:36
À : KhronosGroup/Vulkan-Hpp <Vulkan-Hpp@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-Hpp] I have add leethomason/tinyxml2 but now I can't make install (#575)


Sorry, azaretdodo, but that doesn't tell anything.
You would have to add the actual error messages, not just the lines that tell you that an error occured.

**Comment by asuessenbach** [comment]
That is, we can't help you with that kind of information you're providing.
Would you mind closing this issue, then?

**Comment by Azaretdodo** [comment]
You can close by yourself

This laster time I have install yours github by packager downloader installer of programs

But they installs older version instead yours github...

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________
