### ISSUE TITLE
Cannot instantiate createRayTracingPipelineKHRUnique

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#577]
Please, check the following code:
```
vk::Device{}.createRayTracingPipelineKHRUnique(vk::PipelineCache{}, vk::RayTracingPipelineCreateInfoKHR{});
```
**`VULKAN_HPP_NO_SMART_HANDLE`**, **`VULKAN_HPP_DISABLE_ENHANCED_MODE`** are not defined.

**`VK_ENABLE_BETA_EXTENSIONS`**, `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC`,  `VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL` are defined.

On MSVC 2017 it get an error:
```
C:\VulkanSDK\1.2.135.0\Include\vulkan/vulkan.hpp(74665): error C2440: 'return': cannot convert from 'vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>' to 'vk::ResultValue<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>>'
C:\VulkanSDK\1.2.135.0\Include\vulkan/vulkan.hpp(74665): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Anatoly\Documents\Projects\toyrenderer\renderer.cpp(78): note: see reference to function template instantiation 'vk::ResultValue<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>> vk::Device::createRayTracingPipelineKHRUnique<vk::DispatchLoaderDynamic>(vk::PipelineCache,const vk::RayTracingPipelineCreateInfoKHR &,vk::Optional<const vk::AllocationCallbacks>,const Dispatch &) const' being compiled
        with
        [
            Dispatch=vk::DispatchLoaderDynamic
        ]
C:\VulkanSDK\1.2.135.0\Include\vulkan/vulkan.hpp(8848): note: see reference to class template instantiation 'vk::Flags<vk::AccessFlagBits>' being compiled
```

**Comment by asuessenbach** [comment]
This is most likely a header version mismatch.
From VK_HEADER_VERSION 135 to 136, the C++-API did change for a couple of functions, while the C-API did not change. There, only the logic did change!
Previously, some C-Functions supported just VK_SUCCESS as an success code. Other possible return codes were supposed to be errors.
We translated those calls to just return what the C-function would create, as all the error codes where mapped to exceptions.
With VK_HEADER_VERSION 136, some C-Functions now support more than just VK_SUCCESS as success codes. Therefore, we needed to change the C++-API to returning  a pair of values: the success code and the actual stuff created.
But, unless you've defined VULKAN_HPP_DISABLE_IMPLICIT_RESULT_VALUE_CAST, you don't _need_ to handle that explicitly, as there are implicit conversions from ResultValue<T> to T available.
That is, old code should not _need_ any changes. But, of couse, you should consider to handle that explicitly to make sure you don't miss any changes in behaviour.

**Comment by asuessenbach** [comment]
Yes it is.
The reason for that is, that for those functions more than just VK_SUCCESS is allowed to represent a success. And that information has to be carried back to the caller.

**Comment by tomilov** [comment]
@asuessenbach Has this problem been resolved?

**Comment by asuessenbach** [comment]
As said above, it seems to be a header version mismatch.
Have you replaced or modified vulkan.hpp somehow?
Could you provide the code of the function at line 74665 of the vulkan.hpp you're using? If at all, I would have expected to see the error message referring line 74649, which holds the return statement of createRayTracingPipelineKHRUnique() in the 1.2.135 SDK header.

**Comment by tomilov** [comment]
https://gist.github.com/tomilov/7f5b4d26e187345ccc740bab02f5ae4d

**Comment by asuessenbach** [comment]
That is, you changed the return type of `Device::createRayTracingPipelineKHRUnique` from `ResultValue<UniqueHandle<Pipeline,Dispatch>>` to `ResultValueType<UniqueHandle<Pipeline,Dispatch>>::type`, but did not adjust the function body accordingly.
My advice (if you want/need to stay with the version 135 headers): don't change the interface of that function, but extent the ResultValue capabilities as introduced with #554. Look for VULKAN_HPP_DISABLE_IMPLICIT_RESULT_VALUE_CAST in that change.

**Comment by tomilov** [comment]
I use version of headers that provided by (roughly speaking) OS. https://github.com/KhronosGroup/Vulkan-Hpp/pull/554 fixes that bug?

**Comment by asuessenbach** [comment]
Yes, exactly.
