### ISSUE TITLE
vkGetBufferDeviceAddress/EXT/KHR confusion with VULKAN_HPP_DEFAULT_DISPATCHER

### ISSUE THREAD

**Issue by FelixFifi** [KhronosGroup/Vulkan-Hpp#588]
I'm using the VULKAN_HPP_DEFAULT_DISPATCHER to load extension functions.
Later, I want to use 
    device.getBufferAddress(...);
My problem is, that the dispatcher is only able to retrieve the `vkGetBufferDeviceAddressKHR` function and not `vkGetBufferDeviceAddress` which is called in all `device.getBufferAddress/KHR/EXT(...)` functions.

Is this an issue with the NVIDIA drivers? As the documentation states, that [these functions should be equivalent](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_physical_storage_buffer_access).

    const std::vector<const char *> deviceExtensions = {
        VK_KHR_SWAPCHAIN_EXTENSION_NAME,
        VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME
    };

    const std::vector<const char *> instanceExtensions = {
        VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME
    };
    void initVulkan() {
        setupDispatchLoader();
        createInstance();

        VULKAN_HPP_DEFAULT_DISPATCHER.init(instance);

        createSurface();
        pickPhysicalDevice();
        createLogicalDevice();

        VULKAN_HPP_DEFAULT_DISPATCHER.init(device);

        std::cout << "vkGetBufferDeviceAddress " << VULKAN_HPP_DEFAULT_DISPATCHER.vkGetBufferDeviceAddress << std::endl;
        // prints 0
        std::cout << "vkGetBufferDeviceAddressEXT " << VULKAN_HPP_DEFAULT_DISPATCHER.vkGetBufferDeviceAddressEXT << std::endl;
        // prints 0
        std::cout << "vkGetBufferDeviceAddressKHR " << VULKAN_HPP_DEFAULT_DISPATCHER.vkGetBufferDeviceAddressKHR << std::endl;
        // prints 1

        // device.getBufferAddressKHR(...); would SegFault because vkGetBufferDeviceAddress=NULL
    }

    void setupDispatchLoader() const {
        PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr =
                dl.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
        VULKAN_HPP_DEFAULT_DISPATCHER.init(vkGetInstanceProcAddr);
    }

Here are the relevant *vulkan.hpp* sections:
Function address retrieval:

      vkGetBufferDeviceAddress = PFN_vkGetBufferDeviceAddress( vkGetDeviceProcAddr( device, "vkGetBufferDeviceAddress" ) );
      vkGetBufferDeviceAddressEXT = PFN_vkGetBufferDeviceAddressEXT( vkGetDeviceProcAddr( device, "vkGetBufferDeviceAddressEXT" ) );
      vkGetBufferDeviceAddressKHR = PFN_vkGetBufferDeviceAddressKHR( vkGetDeviceProcAddr( device, "vkGetBufferDeviceAddressKHR" ) );

And the function call:

    template<typename Dispatch>
    VULKAN_HPP_INLINE DeviceAddress Device::getBufferAddressKHR( const VULKAN_HPP_NAMESPACE::BufferDeviceAddressInfo* pInfo, Dispatch const &d) const VULKAN_HPP_NOEXCEPT
    {
      return static_cast<DeviceAddress>( d.vkGetBufferDeviceAddress( m_device, reinterpret_cast<const VkBufferDeviceAddressInfo*>( pInfo ) ) );
    }

OS: Ubuntu 19.10
Vulkan SDK: `vulkan-sdk/bionic,bionic,now 1.2.135.0~rc1-1lunarg18.04.1.1 all`
NVIDIA beta driver: linux 440.66.11

**Comment by asuessenbach** [comment]
This has been fixed with #553.
