### ISSUE TITLE
clang-format breaks Hpp build

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#591]
When I update headers for Vulkan-Headers, I've been getting the message

> VulkanHppGenerator: could not find clang-format. The generated vulkan.hpp will not be formatted accordingly.

This was mildly annoying so I finally got around to installing clang-format. Unfortunately, now I get:

> YAML:13:33: error: invalid boolean  
> AllowShortBlocksOnASingleLine : Empty  
>                                ^~~~~  
> Error reading /home/tree/git/Vulkan-Hpp/.clang-format: Invalid argument  
> VulkanHppGenerator: formatting vulkan.hpp using clang-format...VulkanHppGenerator: failed to format file ../Vulkan-Docs/xml/vk.xml with error <256>  

If it's going to hard fail when I install clang-format, it shouldn't be warning that I don't have it, IMO.

**Comment by oddhack** [comment]
(clang-format 1:7.0-47 packaged for Debian 10, BTW).

**Comment by asuessenbach** [comment]
Totally agree. I should check the version of a found clang-format as well.
For now, would you mind to update your clang-format version? I'm using`clang-format version 10.0.0`. Don't know how that translates to the version string you provided.

**Comment by oddhack** [comment]
I am stuck on what's packaged for Debian unless I want to build it myself, which I don't. N.b. I don't think making it work is required - I've been building Vulkan-Headers without it since I started. I just removed the package and am back where I was before.

**Comment by oddhack** [comment]
AFAICT what Debian provides is clang-format 7.0 (.47?) - if that's too old to work then maybe the cmake setup could figure that out and bypass it?

https://debian.pkgs.org/10/debian-main-amd64/clang-format_7.0-47_amd64.deb.html

**Comment by asuessenbach** [comment]
That's exactly what I'm going to do...
Just a little request: could you please provide the output on your setup of the following command:
`clang-format --version`

**Comment by oddhack** [comment]
clang-format version 7.0.1-8 (tags/RELEASE_701/final)

**Comment by asuessenbach** [comment]
Thanks a lot!
