### ISSUE TITLE
getBufferMemoryRequirements2 is ambiguous

### ISSUE THREAD

**Issue by CaffeinePwrdAl** [KhronosGroup/Vulkan-Hpp#598]
Hi all,

I'm having trouble with getBufferMemoryRequirements2 it seems that the compiler finds that both the use of use of vk::MemoryRequirements2 directly or wrapped in a structure chain is ambiguous.

Here are the constructions I'm trying:

```
    vk::BufferMemoryRequirementsInfo2 bmri{ buffer };
    vk::MemoryRequirements2 memoryReq;
    memoryReq = d.getBufferMemoryRequirements2(bmri);
```

Or alternatively using a structure chain to wrap the requirements

```
    vk::StructureChain<vk::MemoryRequirements2> memoryReq;
    memoryReq = d.getBufferMemoryRequirements2(buffer);
```

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

```
/home/alex/dev/mine/VulkanTests/vkcm/vkcm_memory.cpp: In function ‘vk::DeviceMemory vkcm::Memory::allocate_buffer_memory(vk::PhysicalDevice, vk::Device, vk::Buffer, const MemoryPropertyFlags&)’:
/home/alex/dev/mine/VulkanTests/vkcm/vkcm_memory.cpp:80:53: error: call of overloaded ‘getBufferMemoryRequirements2(vk::Buffer&)’ is ambiguous
    memoryReq = d.getBufferMemoryRequirements2(buffer);
                                                     ^
In file included from /home/alex/dev/mine/VulkanTests/vkcm/vkcm.h:41:0,
                 from /home/alex/dev/mine/VulkanTests/vkcm/vkcm_memory.cpp:19:
/usr/local/include/vulkan/vulkan.hpp:37588:41: note: candidate: vk::MemoryRequirements2 vk::Device::getBufferMemoryRequirements2(const vk::BufferMemoryRequirementsInfo2&, const Dispatch&) const [with Dispatch = vk::DispatchLoaderStatic]
   VULKAN_HPP_INLINE MemoryRequirements2 Device::getBufferMemoryRequirements2( const BufferMemoryRequirementsInfo2 & info, Dispatch const &d ) const
                                         ^~~~~~
/usr/local/include/vulkan/vulkan.hpp:37595:42: note: candidate: vk::StructureChain<T ...> vk::Device::getBufferMemoryRequirements2(const vk::BufferMemoryRequirementsInfo2&, const Dispatch&) const [with T = {}; Dispatch = vk::DispatchLoad
erStatic]
   VULKAN_HPP_INLINE StructureChain<T...> Device::getBufferMemoryRequirements2( const BufferMemoryRequirementsInfo2 & info, Dispatch const &d ) const
                                          ^~~~~~
```

**Comment by asuessenbach** [comment]
Those functions differ in the returned type. And one is a function, the other a function template.
That is, using this construct should correctly differentiate those two:

`auto memoryReq = d.getBufferMemoryRequirements2<vk::MemoryRequirements2>(buffer);`

**Comment by CaffeinePwrdAl** [comment]
Thanks, I thought the return type would have been explicit in the second version, and the issue in the first was that vk::MemoryRequirements2 could be converted to either, but I missed that it is actually ambiguous still without specifying the return type via the template parameter.

Just tried out your suggestion and I still get the same issue:

```
/home/alex/dev/mine/VulkanTests/vkcm/vkcm_memory.cpp: In function ‘vk::DeviceMemory vkcm::Memory::allocate_buffer_memory(vk::PhysicalDevice, vk::Device, vk::Buffer, const MemoryPropertyFlags&)’:
/home/alex/dev/mine/VulkanTests/vkcm/vkcm_memory.cpp:104:102: error: call of overloaded ‘getBufferMemoryRequirements2(vk::Buffer&)’ is ambiguous
    vk::MemoryRequirements2 memoryReq = d.getBufferMemoryRequirements2<vk::MemoryRequirements2>(buffer);
                                                                                                      ^
In file included from /home/alex/dev/mine/VulkanTests/vkcm/vkcm.h:41:0,
                 from /home/alex/dev/mine/VulkanTests/vkcm/vkcm_memory.cpp:19:
/usr/local/include/vulkan/vulkan.hpp:37588:41: note: candidate: vk::MemoryRequirements2 vk::Device::getBufferMemoryRequirements2(const vk::BufferMemoryRequirementsInfo2&, const Dispatch&) const [with Dispatch = vk::MemoryRequirements2]
   VULKAN_HPP_INLINE MemoryRequirements2 Device::getBufferMemoryRequirements2( const BufferMemoryRequirementsInfo2 & info, Dispatch const &d ) const
                                         ^~~~~~
/usr/local/include/vulkan/vulkan.hpp:37595:42: note: candidate: vk::StructureChain<T ...> vk::Device::getBufferMemoryRequirements2(const vk::BufferMemoryRequirementsInfo2&, const Dispatch&) const [with T = {vk::MemoryRequirements2}; Dispatch = vk::DispatchLoaderStatic]
   VULKAN_HPP_INLINE StructureChain<T...> Device::getBufferMemoryRequirements2( const BufferMemoryRequirementsInfo2 & info, Dispatch const &d ) const
                                          ^~~~~~
```
The overload seems to be 'too greedy' to ever specify just the single type name. I tried various other formulations to try and ensure the template was specified without any doubt in which version was taken.

If you specify just MemoryRequirements2, then it seems it can always be either itself, or a StructureChain -> thus always ambiguous.

If you specify a valid >1 element chain, i.e. `<vk::MemoryRequirements2, vk::MemoryDedicatedRequirements>` then it works because it can then only match the StructureChain verison. I suppose if you're not using a chain then use 'verison 1' of the memory requirements API, but I was hoping to just code one path using the newer API/

I also tried with <vk::MemoryRequirements2, vk::DispatchLoaderStatic> just to see if that happened to force a match against the non-structure chain version, but again it just tries to make a structure chain out of those two types which then fails the static checks for a valid chain.

Am I missing something? - I'll openly admit I'm primarily a C programmer so I wouldn't be surprised!

**Comment by asuessenbach** [comment]
`vk::MemoryRequirements2 memoryReq = d.getBufferMemoryRequirements2<vk::MemoryRequirements2>(buffer);`
This is not correct. That function returns a `vk::StructureChain<vk::MemoryRequirements2>`, not a `vk::MemoryRequirements2`.

**Comment by CaffeinePwrdAl** [comment]
Sorry, I'd tried both with and without auto, same error.

**Comment by asuessenbach** [comment]
And you're right!
Both functions here are template function. The one is templated just by the dispatcher, the other by an arbitrary number of structures, minimum 2, and the dispatcher.
That is, if you provide no or just one template argument, the compiler will either not be able to disambiguate those two functions, or just tries to use the first version.
So, your conclusion is right: 
> if you're not using a chain then use 'verison 1' of the memory requirements API

**Comment by CaffeinePwrdAl** [comment]
There is a small chink, I was needing to use those API's because of passing an extension chain *in* with the image info, but do not need the chain on output:

```
// Yes I should change these now to a vk::StructureChain
vk::ImagePlaneMemoryRequirementsInfo plane;
vk::ImageMemoryRequirementsInfo2 imri{ image };
imri.pNext = &plane;

vk::MemoryRequirements2 memoryReq0;

plane.planeAspect = vk::ImageAspectFlagBits::ePlane0;
memoryReq0 = d.getImageMemoryRequirements2(imri);
```

Adding the dedicated memory structure to the return chain is ok for now to get me by, but I think this is a general issue with this paradigm, not sure I know how to solve it I'm afraid. Happy to try things out though.

**Comment by asuessenbach** [comment]
I think, I don't get your issue here. Could you please elaborate a bit more on that?

**Comment by asuessenbach** [comment]
Getting no more information, I'm closing this issue.
