### ISSUE TITLE
acquireNextImageKHR and presentKHR should not throw an exception in case of vk::Result::eErrorOutOfDateKHR

### ISSUE THREAD

**Issue by lcq2** [KhronosGroup/Vulkan-Hpp#599]
Hello everyone,
I believe there's something wrong with current implementation of Vulkan Enhanced mode using C++ exception handling. As far as I understand, the code for vulkan.hpp is automatically generated, and this may explain the reason.

I think that mentioned functions, `acquireNextImageKHR` and `presentKHR` should NOT raise an exception if the return value is VK_ERROR_OUT_OF_DATE_KHR . Even though the enum member is called "error", this is not a fatal error and can be recovered by successfully recreating the swap chain and everything else connected to it (also explained by the Vulkan Tutorial).

The problem can be seen here in Vulkan.hpp, for `acquireNextImageHKR`:
```c++
#ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE
  template<typename Dispatch>
  VULKAN_HPP_INLINE ResultValue<uint32_t> Device::acquireNextImageKHR( VULKAN_HPP_NAMESPACE::SwapchainKHR swapchain, uint64_t timeout, VULKAN_HPP_NAMESPACE::Semaphore semaphore, VULKAN_HPP_NAMESPACE::Fence fence, Dispatch const &d ) const
  {
    uint32_t imageIndex;
    Result result = static_cast<Result>( d.vkAcquireNextImageKHR( m_device, static_cast<VkSwapchainKHR>( swapchain ), timeout, static_cast<VkSemaphore>( semaphore ), static_cast<VkFence>( fence ), &imageIndex ) );
    return createResultValue( result, imageIndex, VULKAN_HPP_NAMESPACE_STRING"::Device::acquireNextImageKHR", { Result::eSuccess, Result::eTimeout, Result::eNotReady, Result::eSuboptimalKHR } );
  }
#endif /*VULKAN_HPP_DISABLE_ENHANCED_MODE*/
```
and here for `presentKHR`:
```c++
#ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE
  template<typename Dispatch>
  VULKAN_HPP_INLINE Result Queue::presentKHR( const PresentInfoKHR & presentInfo, Dispatch const &d ) const
  {
    Result result = static_cast<Result>( d.vkQueuePresentKHR( m_queue, reinterpret_cast<const VkPresentInfoKHR*>( &presentInfo ) ) );
    return createResultValue( result, VULKAN_HPP_NAMESPACE_STRING"::Queue::presentKHR", { Result::eSuccess, Result::eSuboptimalKHR } );
  }
#endif /*VULKAN_HPP_DISABLE_ENHANCED_MODE*/
```
of course the issue can be somehow solved by wrapping `acquireNextImageKHR` and `presentKHR` into their own try/except blocks, but I'd like to avoid this, because typically those two functions are called inside some kind of loop, where I'd like to avoid using try/except.

I can always go back to the C api for these two specific functions, it's not the end of the world, but I'd like to keep it somehow coherent.

Of course I can change the structure of the code to catch that specific exception and restart the rendering loop from outside of it, that's not a problem, given that I need to recreate the swap chain anyway. I was simply wondering if there's a reason why that specific error code is considered "exception worthy", allow me this term.

Thanks!

**Comment by asuessenbach** [comment]
As you said, vulkan.hpp is generated. The source is an xml file that specifies "everything".
In that file, VK_ERROR_OUT_OF_DATE_KHR is specified to be an error result for those functions, not a success.
And for vulkan.hpp we simply turn each and every error result into an exception.

**Comment by lcq2** [comment]
Thanks, any chance that VK_ERROR_OUT_OF_DATE_KHR can be promoted to a "success" value, like Result::eNotRead or Result::eSuboptimalKHR? I think it's in the same category, even though technically is an error.

**Comment by asuessenbach** [comment]
Maybe you could ask here [https://github.com/KhronosGroup/Vulkan-Docs](). At least there should be enough people to guide you to the right place for such a query.

**Comment by CRISPYricePC** [comment]
For anyone who found this issue looking for a solution. Add the following functions:

```cpp
/**
 * @brief vk::raii::SwapchainKHR::acquireNextImageKHR without exceptions
 */
std::pair<vk::Result, uint32_t> SwapchainNextImageWrapper(const vk::raii::SwapchainKHR &swapchain,
                                                          uint64_t timeout, vk::Semaphore semaphore,
                                                          vk::Fence fence) {
  uint32_t image_index;
  vk::Result result = static_cast<vk::Result>(swapchain.getDispatcher()->vkAcquireNextImageKHR(
      static_cast<VkDevice>(swapchain.getDevice()), static_cast<VkSwapchainKHR>(*swapchain),
      timeout, static_cast<VkSemaphore>(semaphore), static_cast<VkFence>(fence), &image_index));
  return std::make_pair(result, image_index);
}

/**
 * @brief vk::raii::Queue::presentKHR without exceptions
 */
vk::Result QueuePresentWrapper(const vk::raii::Queue &queue,
                               const vk::PresentInfoKHR &present_info) {
  return static_cast<vk::Result>(queue.getDispatcher()->vkQueuePresentKHR(
      static_cast<VkQueue>(*queue), reinterpret_cast<const VkPresentInfoKHR *>(&present_info)));
}
```

Note: My project uses `vk::raii`. You'll likely have to adjust the typenames and dereference operators to get it to work with plain `vulkan_hpp`
