### ISSUE TITLE
Access violation when using ArrayProxy on x64 Release build (VS2019) 

### ISSUE THREAD

**Issue by msizov** [KhronosGroup/Vulkan-Hpp#602]
https://github.com/msizov/VulkanHpp-issue

**Comment by msizov** [comment]
I've attached a minimal reproducing example, at the end of file two variants for calling deviceQueue.submit are presented:

This one fails:
    ArrayProxy<const SubmitInfo> submitInfo = { { 0, nullptr, nullptr, 1, &cb } };
    deviceQueue.submit(submitInfo, {});

But when using ordinary array, everything works fine:
    SubmitInfo submitInfo = { 0, nullptr, nullptr, 1, &cb };
    deviceQueue.submit(1, &submitInfo, {}); // Works

I use Vulkan SDK 1.2.135 on Windows (1903) x64, with Radeon RX590

**Comment by asuessenbach** [comment]
Note, that an ArrayProxy doesn't own the memory!
That is
```
ArrayProxy submitInfo = { { 0, nullptr, nullptr, 1, &cb } };
deviceQueue.submit(submitInfo, {});
```
does not work as submitInfo would hold a pointer to a temporarily constructed SubmitInfo, which is invalid right after that line of code.
What would work instead:
`deviceQueue.submit( { { 0, nullptr, nullptr, 1, &cb } }, {});`

**Comment by msizov** [comment]
Thanks for pointing that out, I tried to use
>deviceQueue.submit( { { 0, nullptr, nullptr, 1, &cb } }, {});

but now it gives me `eErrorOutOfHostMemory` while other variant with regular array still works fine

**Comment by asuessenbach** [comment]
I'm sorry, but I can't repro you issue.
I've modified your example accordingly, and it runs fine, both in debug and in release mode.

**Comment by asuessenbach** [comment]
Getting no more information, closing this.
