### ISSUE TITLE
a lot of yours subdirectory are empty

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Hpp#603]
Hello,

a lot of yours subdirectory are empty : 

![IWillGrowInVulkanHppGithubSubdirectory](https://user-images.githubusercontent.com/30596513/81493070-82312100-929d-11ea-9359-ff17ad44fa44.jpg)

I will grow it then I will load them by the cmakelist file at the cmake dot dot command line :) 

Regards.

Azaretdodo.

**Comment by tomilov** [comment]
You must read about `git submodules` first. Or google commands `git pull --recurse-submodules
`, `git submodules update --init --recursive` etc.

**Comment by Azaretdodo** [comment]
Thank you but I have finish to add subdirectory without this,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by tomilov** [comment]
Please take a break (for a couple of years) and spent time to go deeper in development skills. 97% of your questions will disappear.
