### ISSUE TITLE
I have edited the cmakelist for bring glm, glfw and glslang

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Hpp#604]
Hello,

I have add thoses lines of code :

![GlfwAddedPrintScreen1](https://user-images.githubusercontent.com/30596513/81496043-f88d4d80-92b4-11ea-8d6e-5fb3e9041da1.jpg)

![GlfwAdded2](https://user-images.githubusercontent.com/30596513/81496068-26729200-92b5-11ea-8366-c650b256ddd3.jpg)

![GlslangAdded1](https://user-images.githubusercontent.com/30596513/81496109-69346a00-92b5-11ea-9eef-a24fd1a3bffd.jpg)

![GlslangAdded2](https://user-images.githubusercontent.com/30596513/81496127-8d904680-92b5-11ea-84a4-cd8915dfa31f.jpg)

![GlslangAdded3](https://user-images.githubusercontent.com/30596513/81496170-f24ba100-92b5-11ea-9058-b2feb0ac3b55.jpg)

This area exit ever I have add some lines : 

![AeraEdited](https://user-images.githubusercontent.com/30596513/81496203-245d0300-92b6-11ea-840b-3351d9363994.jpg)

The next lines were keep !

How do you feel my works ?

Have a nice Week-end from France,

Regards.

Azaretdodo.

**Comment by tomilov** [comment]
> How do you feel my works ?

It useless in current form. I can't even copy and paste your editions. It is common to make _pull requests_. You can google what does it mean.

**Comment by tomilov** [comment]
Seems you are spammer. Please stop your annoying activity on Github.
