### ISSUE TITLE
Wrong extension dependency

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#610]
I came across an odd behavior recently where I had put VkStencilFaceFlagBits as an explicit dependency in the \<extension> block for VK_EXT_metal_surface, as well as VK_VERSION_1_0, via \<type name="VkStencilFaceFlagBits"/>. The C headers were fine, but Vulkan-Hpp generated a header where it wrapped the StencilFaceFlagBits  enum class in #ifdef VK_USE_PLATFORM_METAL_EXT, resulting in compilation failure.

While I'll grant that this was a slightly unusual thing to do, there's nothing wrong with it in the sense of it being allowed by the schema and semantically meaningful. Suggest taking a look at whatever dependency tracking you are doing to make sure that something defined in the core as well as a protected extension, will not be protected in the same way as the extension-specific interfaces.

N.b. the way the C headers deal with this when creating the vulkan_metal header is to traverse dependencies for all versions as well as the specific extension, but suppress everything generated prior to the extension itself. So StencilFaceFlagBits lands in vulkan_core.h as desired.

This isn't actually holding anything up at this point, but suggest taking a look as you have time, in case it crops up in the future and is harder to remove. You can refer to recent commits in internal MR 3845 for details.

**Comment by asuessenbach** [comment]
Thanks for this hint. I'll adjust the generator asap.
But, just out of curiosity: what's the semantic meaning of such a situation? Why should I list an entity in an extension that's already part of the core?
And, is it also allowed and semantically meaningful to list an entity in more than one extension?

**Comment by oddhack** [comment]
It is both allowed and meaningful, although unusual. For example, VkPhysicalDeviceIDPropertiesKHR is required by each of
VK_KHR_external_memory_capabilities, VK_KHR_external_semaphore_capabilities,
and VK_KHR_external_fence_capabilities; and VkDeviceGroupPresentModeFlagsKHR
is required by VK_VERSION_1_1 when VK_KHR_swapchain is also enabled, and by
VK_KHR_device_group when VK_KHR_surface is also enabled.

That said, this specific case was a typo while adding all the directly required interfaces, so that the upcoming extension/version dependency tagging while work properly.
