### ISSUE TITLE
Ambiguous Conversion From ResultValue

### ISSUE THREAD

**Issue by GiantBlargg** [KhronosGroup/Vulkan-Hpp#616]
#590 seems to have broken assignment from a `ResultValue`

For example
```c++
vk::Pipeline graphicsPipeline = device.createGraphicsPipeline(nullptr, pipelineInfo);
```
when compiled with clang 10.0.0 produces an error:
```
error: use of overloaded operator '=' is ambiguous (with operand types 'vk::Pipeline' and 'ResultValue<vk::Pipeline>')
                 graphicsPipeline = device.createGraphicsPipeline(nullptr, pipelineInfo);
                 ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan.hpp:15428:9: note: candidate function (the implicit copy assignment operator)
   class Pipeline
         ^
/usr/include/vulkan/vulkan.hpp:15428:9: note: candidate function (the implicit move assignment operator)
```
This breaks existing code, including the sample code provided in this repo (but it's broken for other reasons anyway)

**Comment by mocabe** [comment]
Looks like forgot adding ref-qualifier to existing conversion operator, and test is only checking rvalue conversoin :(
I'll make PR for fix

**Comment by ROTARTSI82** [comment]
Hello, it appears that this exact bug has been re-introduced. Generating vulkan.hpp from this repo (commit d58b93d8e5e3597edc61504c77d1a9e22dc1d2ff), I get this error when compiling my code:
```
../src/vk_pipeline.cpp:130:18: error: use of overloaded operator '=' is ambiguous (with operand types 'vk::Pipeline' and 'ResultValue<vk::Pipeline>')
        pipeline = device.createGraphicsPipeline(cache, createInfo);
        ~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/vulkan/vulkan.hpp:25375:9: note: candidate function (the implicit copy assignment operator)
  class Pipeline
        ^
/usr/local/include/vulkan/vulkan.hpp:25375:9: note: candidate function (the implicit move assignment operator)
1 error generated.
```
I'm using Ubuntu 20.04.2 and vulkan SDK 1.2.162.1

**Comment by mocabe** [comment]
@ROTARTSI82 Implicit conversion from `ResultValue` is deprecated. If you want to ignore possible result value (`vk::Result::ePipelineCompileRequiredEXT` here), you should add `.value` to take result explicitly.
