### ISSUE TITLE
Request for string interface in the Extension / Layer names

### ISSUE THREAD

**Issue by amadlover** [KhronosGroup/Vulkan-Hpp#621]
Hello

Is it possible to have a std::string interface for the layer / extension names for instance and device creation. Instead of the current char[256] for the enumerated Extension/Layers names and a const char* const* pointer for the InstanceCreateInfo.

would make it more C++ like (I guess)

e.g.
1. Get available extensions vk::enumerateInstanceExtensions
2. Filter the required extensions to a std::vector<std::string>
3. pass this vector to the InstanceCreateInfo.

or I am missing something very obvious.

Thank you,
Nihal Kenkre.

**Comment by asuessenbach** [comment]
This essentially is the same issue as #216.
And for the very same reason, we probably won't add such a functionality.
I think, I have to extend the Readme to mention that.

**Comment by amadlover** [comment]
Thank you for clearing it up!.

Cheers.
