### ISSUE TITLE
char to ArrayWrapper1D breaks app compilation

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Hpp#622]
Sometime between 1.2.135 and 1.2.141 some declarations in PhysicalDeviceProperties were changed from straightforward arrays:

```c++
    char deviceName[VK_MAX_PHYSICAL_DEVICE_NAME_SIZE] = {};
    uint8_t pipelineCacheUUID[VK_UUID_SIZE] = {};
 ```

to use a template

```c++
    VULKAN_HPP_NAMESPACE::ArrayWrapper1D<char, VK_MAX_PHYSICAL_DEVICE_NAME_SIZE> deviceName = {};
    VULKAN_HPP_NAMESPACE::ArrayWrapper1D<uint8_t, VK_UUID_SIZE> pipelineCacheUUID = {};
```

As a result my app which passes `deviceName` to a function parameter of type `std::string` no longer compiles:

```
VulkanAppSDL.cpp:1290:26: No viable conversion from 'vk::ArrayWrapper1D<char, 256>' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
```

Did you intend to break apps? If so, how should I modify my app so it will work with this and previous versions of the SDK? If not, please fix a.s.a.p.

**Comment by mocabe** [comment]
Have you tried `deviceName.data()`?

**Comment by MarkCallow** [comment]
Even had I known that ArrayWrapper1D had a data() method it would not meet my need to work with both older versions of vulkan.hpp and this one. This is because I cannot mandate the Vulkan SDK my users choose to use when compiling the software. For now I have solved this by casting to char*.

In any case, the key point is that the change broke app compilation.

**Comment by mtavenrath** [comment]
>Did you intend to break apps? If so, how should I modify my app so it will work with this and previous versions of the SDK? If not, please fix a.s.a.p.'
No. The goal is not to break source code compatibility if possible.

At a first glance it looks like the issue can be solved by adding an implicit conversion to std::string in a partially specialized template ArrayWrapper1D<char>.

**Comment by mocabe** [comment]
>  an implicit conversion to std::string 

Well, that can fix `std::string` conversion, but cannot fix other classes like `std::string_view` (and that adds extra heap allocation).
It looks there's no general fix for this, except for going back to C-style arrays (but this removes ability to use `std::array` like interface, which might cause issues existed before #550).

**Comment by asuessenbach** [comment]
> At a first glance it looks like the issue can be solved by adding an implicit conversion to std::string in a partially specialized template ArrayWrapper1D.

As Markus mentions, this is probably the right way to go.

> Well, that can fix std::string conversion, but cannot fix other classes like std::string_view (and that adds extra heap allocation).

**Comment by mocabe** [comment]
@asuessenbach I think these are most commonly used ones. The change could affect any custom string classes similar to `std::string`, so adding comments on `ArrayWrapper1D` might help too.

**Comment by MarkCallow** [comment]
I just updated to a version of vulkan.hpp with the cast operator. I had to explicitly make the cast otherwise with clang on macOS I get

```
error: call to member function 'compare' is ambiguous
            if (!wantedExtensions[i].name.compare(deviceExtensions[j].extensionName)) {
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

Here is the declaration of `wantedExtensions`.

```
struct extension {
        std::string name;
        ext_need need;
    };
    std::vector<extension> wantedExtensions;
```

After adding an explicit cast, as follows, it compiles with clang but I still get the "ambiguous" error with gcc on Ubuntu Focal.

```
if (!wantedExtensions[i].name.compare(static_cast<std::string>(deviceExtensions[j].extensionName))) {
```

gcc says

```
../tests/loadtests/appfwSDL/VulkanAppSDL/VulkanAppSDL.cpp:718:109: error: call of overloaded ‘basic_string(vk::ArrayWrapper1D<char, 256>&)’ is ambiguous
  718 |             if (!wantedExtensions[i].name.compare(static_cast<std::string>(deviceExtensions[j].extensionName))) {
      |                                                                                                             ^
In file included from /usr/include/c++/9/string:55,
                 from /usr/include/c++/9/bits/locale_classes.h:40,
                 from /usr/include/c++/9/bits/ios_base.h:41,
                 from /usr/include/c++/9/iomanip:40,
                 from ../tests/loadtests/appfwSDL/VulkanAppSDL/VulkanAppSDL.cpp:30:

/usr/include/c++/9/bits/basic_string.h:552:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’

  552 |       basic_string(basic_string&& __str) noexcept
      |       ^~~~~~~~~~~~
/usr/include/c++/9/bits/basic_string.h:525:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  525 |       basic_string(const _CharT* __s, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
/usr/include/c++/9/bits/basic_string.h:448:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  448 |       basic_string(const basic_string& __str)
      |       ^~~~~~~~~~~~
```

**Comment by asuessenbach** [comment]
@MarkCallow could you please check what you get when using the data() function of the ArrayWrapper1D, that is:
`if (!wantedExtensions[i].name.compare(deviceExtensions[j].extensionName.data()))`
