### ISSUE TITLE
Alternative to standard VK_NULL_HANDLE

### ISSUE THREAD

**Issue by lromor** [KhronosGroup/Vulkan-Hpp#643]
Hi, 
in `createGraphicsPipelineUnique()` how can I avoid passing a PipelineCache?
In C vulkan it's possible to pass VK_NULL_HANDLE. What's the alternative here?

**Comment by Wunkolo** [comment]
Sounds like this could be the introduction of something like `vk::nullhandle_t` similar to `nullptr_t` to specially handle null-cases.

**Comment by asuessenbach** [comment]
You could either use nullptr or {} for the PipelineCache. In either case, that is mapped to VK_NULL_HANDLE for the C-API call.

**Comment by lromor** [comment]
So a default initialized PipelineCache maps to a VK_NULL_HANDLE call? I think I was having a complaint about using nullptr in the function call from the compiler.

**Comment by asuessenbach** [comment]
Could you please provide the error message, and what compiler are you using?

**Comment by lromor** [comment]
My fault. I was using NULL.
