### ISSUE TITLE
Spaceship operators cause a huge regression in compile times

### ISSUE THREAD

**Issue by vblanco20-1** [KhronosGroup/Vulkan-Hpp#656]
I am experimenting with vulkan and some of the Cpp 20 features. I saw vulkan.hpp header taking 6.5 seconds to include (by /d1reportTime timings. When investigating it, i found that the reason it regressed so hard was due to operator<=> instantiations.

To experiment, i compared it when commenting out the code that does the #define to enable spaceship operators, to see what the difference is.
The test i did takes 4.5 seconds more time to compile with operator spaceship.

Example output from Visual studio 2019 d1reportTime.
```
2>	Top 100 (top-level only):
2>		vk::PhysicalDeviceToolPropertiesEXT::operator <=>: 0.588307s
2>		vk::PerformanceCounterDescriptionKHR::operator <=>: 0.423359s
2>		vk::PipelineExecutableInternalRepresentationKHR::operator <=>: 0.324760s
2>		vk::PhysicalDeviceVulkan12Properties::operator <=>: 0.313279s
2>		vk::PipelineExecutablePropertiesKHR::operator <=>: 0.280069s
```
Up to 0.6 seconds to parse a single operator <=> function definition.

Operator <=> is not worth the cost, given that the vulkan.hpp generator already implements normal comparator operations, so i deleted it in my project.

**Comment by asuessenbach** [comment]
Nice little flag, indeed!
But I can't repro such a dramatic increase in compile time. Here's what I get with one of the test projects:
```
1>	Top 100 (top-level only):
1>		vk::PhysicalDeviceLimits::operator <=>: 0.015580s
1>		main: 0.007985s
1>		vk::PipelineViewportShadingRateImageStateCreateInfoNV::setShadingRatePalettes: 0.007718s
1>		vk::to_string: 0.006828s
1>		vk::PhysicalDeviceFeatures::operator <=>: 0.005577s
1>		vk::PhysicalDeviceVulkan12Properties::operator <=>: 0.005448s
1>		vk::PhysicalDeviceVulkan12Features::operator <=>: 0.004873s
```
@vblanco20-1: Would you mind providing a VS solution/project showing that slowdown for additional investigations? What VS version are you using?

**Comment by vblanco20-1** [comment]
[VkHppIssue.zip](https://github.com/KhronosGroup/Vulkan-Hpp/files/4907463/VkHppIssue.zip)

The .zip contains a micro-project with cmake that enables C++20 and the "/Bt" flag, that shows compile times (not as verbose as /d1reporttime. Tested with 64 bit build

On this project, the issue does happen. SDK version 1.2.135.0. Visual studio version is "16.7.0 Preview 2.0".

**Comment by asuessenbach** [comment]
It seems, this is a Visual Studio issue, then.
I didn't try 16.7.0 Preview 2.0, but a couple of other versions and C++ Language Standard settings, and it got slower on newer standards. But more in the range of up to 20%, not a factor of 2-4.
That is, I can't see anything I can do about that issue.
