### ISSUE TITLE
Deleter classes taking pointer to parent not working

### ISSUE THREAD

**Issue by spfuetzner** [KhronosGroup/Vulkan-Hpp#66]
The following code doesn't work (it crashes):
```
vk::UniqueFence createSubmitFence(vk::Device dev)
{
	auto const create_info {vk::FenceCreateInfo {}
		.setFlags(vk::FenceCreateFlagBits::eSignaled)};
	return dev.createFenceUnique(create_info);
}
```
The problem is the temporary handle "dev" getting destroyed when the function returns. The Deleters should store the handle directly and not a pointer to it.

**Comment by spfuetzner** [comment]
This is a serious issue! No comments?
I think pointers were chosen because the Deleters have to be defined before the parent classes (Instance or Device). It can be solved by only declaring creation functions in the parent class definition and define them out-of-class after the Deleters (which themselves can now be defined after the parent class definition).

**Comment by asuessenbach** [comment]
You're absolutely right. This is a serious error and will be fixed in the next couple of days.
Thanks a lot for pointing to that issue!

**Comment by mtavenrath** [comment]
@spfuetzner Fixed with latest commit. Closing.
