### ISSUE TITLE
Compilation error due to lack of <compare> header on Clang 10

### ISSUE THREAD

**Issue by technoir42** [KhronosGroup/Vulkan-Hpp#684]
I installed Ubuntu 20.04 and Clang 10 in WSL2.
```
$ clang++ --version
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
When compiling with `--std=c++2a` and including `vulkan.hpp` from  Vulkan Headers v1.2.148 I get the following error:
```
external/vulkan_headers/include/vulkan/vulkan.hpp:88:11: fatal error: 'compare' file not found
# include <compare>
          ^~~~~~~~~
```

**Comment by asuessenbach** [comment]
Could you please look for __cpp_impl_three_way_comparison? What's the value of that macro in your environment?

**Comment by technoir42** [comment]
```
__cpp_impl_three_way_comparison=201907
__cplusplus=202002
```

**Comment by asuessenbach** [comment]
Well, I think, then it's an issue with that clang version, or your installation.
With __cplusplus=202002, one should assume that <compare> is there.

**Comment by technoir42** [comment]
Nothing is wrong with my installation. I just installed the default version of Clang on Ubuntu 20.04.
```
sudo apt install clang
```

> With __cplusplus=202002, one should assume that is there.
This doesn't sound right since support for C++20 is incomplete in Clang 10.
