### ISSUE TITLE
Changed order of template arguments of Device::createGraphicsPipelinesUnique()

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-Hpp#701]
The latest git contains swapped template arguments for Device::createGraphicsPipelinesUnique():

    template<typename Dispatch = ..., typename Allocator  = ...>
    VULKAN_HPP_NODISCARD ResultValue<...> createGraphicsPipelinesUnique( pipelineCache, createInfos, allocator = nullptr, Dispatch const &d = VULKAN_HPP_DEFAULT_DISPATCHER ) const;

and

    template<typename Dispatch = ..., typename Allocator  = ..., typename B = Allocator, typename std::enable_if<std::is_same<typename B::value_type, UniqueHandle<Pipeline, Dispatch>>::value, int>::type = 0>
    VULKAN_HPP_NODISCARD ResultValue<...> createGraphicsPipelinesUnique( pipelineCache, createInfos, allocator, Allocator const& vectorAllocator, Dispatch const &d ) const;

When looking to latest Vulkan SDK release 1.2.141.2 and older release 1.2.131.2, the order of template arguments was different:

    template<typename Allocator = std::allocator<UniquePipeline>, typename Dispatch = VULKAN_HPP_DEFAULT_DISPATCHER_TYPE>

It breaks the code that explicitly specifies template parameters.

**Comment by pc-john** [comment]
I see the same problem still at least on Device::createComputePipelinesUnique() (in two overloads) and Device::allocateCommandBuffersUnique() (in two overloads).

**Comment by asuessenbach** [comment]
Yep, your absolutely right.
We thought a lot about keeping the order of template arguments, but did not find any solution.
The change in order was needed due to fixing the default for the `Allocator` template parameter: using `std::allocator<UniquePipeline>` was wrong, it needs to be `std::allocator<UniqueHandle<Pipeline, Dispatch>>>`.

**Comment by pc-john** [comment]
I see. That is the really serious reason. Thanks for the explanation.
