### ISSUE TITLE
an extension not able to be use by yours github

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Hpp#702]
Hello,

I am hapening this error when I want to build your GitHub :

```
'''cmake .. && make -j 6 && make -j 6 install
-- Configuring done
CMake Error at CMakeLists.txt:175 (add_executable):
  Cannot find source file:

    /home/dorianrosse/Vulkan-Hpp/glslang/SPIRV/SpvBuilder.cppp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:175 (add_executable):
  No SOURCES given to target: VulkanHppGenerator


CMake Generate step failed.  Build files cannot be regenerated correctly.'''
```

Thank you in advance to help myself pass this error,

Regards.

Azaretdodo.

**Comment by asuessenbach** [comment]
glslang is used as a submodule in the samples of this repo.
That is, you need to update the submodules for VulkanHpp, before you can run CMake on it.

**Comment by Azaretdodo** [comment]
Can I git clone by the hand the glslang fork?

Thank you in advance to agree or disagree,

Regards.


Azaretdodo.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Azaretdodo** [comment]
I went to git clone I am happening now an error I was pass before :

'''Cannot find source file : 

/home/dorianrosse/Vulkan-Hpp/glslang/SPIRV/GlslangToSpv.cpp

CMake error at CMakeLists.txt:175 (add_executable):

No SOURCES given to target: VulkanHppGenerator'''

Thank you in advance to pass this error,

Regards.


Azaretdodo.

**Comment by asuessenbach** [comment]
We've added some docu on how to build the VulkanHppGenerator, the samples, and the test. See #711.
