### ISSUE TITLE
Workflow for dynamic dispatch with multiple devices

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-Hpp#707]
To gain the small performance increase from loading device functions directly per-device, I think the workflow requires me to pass a dispatcher I've allocated/initialized myself (one per device) to every function call.
This is reasonable, but error-prone due to the default parameter value given to the dispatcher argument in every function call. It would be very easy to accidentally forget to pass the per-device dispatcher into a function call.

Could there be a mode where this default is disabled, so it's an error to not pass a dispatcher?
Or is there another workflow I should be looking at?
Thanks

**Comment by asuessenbach** [comment]
Interesting idea, indeed.
That would mean, all the create* and allocate* functions would not be allowed to have a default for the allocator argument. But I think that would be acceptable, you would have to provide that parameter anyways in order to provide the Dispatcher argument.
