### ISSUE TITLE
Loading equivalent extension functions when core one isn't found?

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-Hpp#708]
Would it be reasonable for the dynamic loader to try to load the equivalent extension function when the core function isn't found?
For example vkGetPhysicalDeviceImageFormatProperties2 and vkGetPhysicalDeviceImageFormatProperties2KHR. To avoid needing if statements to check if I'm using Vulkan 1.1, or using this via an extension in Vulkan 1.0, it would be nicer if the loader just tried the core first, and fell back to the extension version if the core one didn't exist. That way I can just program using the core function calls and avoid if statements everywhere.
Only for functions which are truly equivalent though.

**Comment by asuessenbach** [comment]
Nice idea.
That way, all your vulkan version and extension logic would be needed just at device creation time. Assuming, you're enabling the corresponding extension in case of a lower core version.

**Comment by mbechard** [comment]
Thanks. It seems like this is also what the Vulkan loader does, but if you are dealing with loader that is unaware of the newer core features (such linking with MoltenVK's binary directly), having the DynamicLoader be aware of it would be helpful.

**Comment by mbechard** [comment]
Thank you for your quick changes! Really appreciate it!
