### ISSUE TITLE
Get DebugReportObjectTypeEXT from Vulkan Object

### ISSUE THREAD

**Issue by W4RH4WK** [KhronosGroup/Vulkan-Hpp#713]
In my code-base I have a template function to give me the corresponding `DebugReportObjectTypeEXT` of a given Vulkan object. It would be great if the Vulkan-Hpp could provide this.

My ad hoc implementation looks like this:

```c++
template<typename T>
constexpr vk::DebugReportObjectTypeEXT getDebugReportObjectTypeEXT()
{
    if constexpr(false) {
    }

#define VULKAN_TYPE(_type) \
    else if constexpr(std::is_same_v<T, vk::_type>) { return vk::DebugReportObjectTypeEXT::e##_type; }
#include "raygun/utils/vulkan_types.def"

    else {
        return vk::DebugReportObjectTypeEXT::eUnknown;
    }
}
```

Where `vulkan_types.def` contains a list of Vulkan types.

```
VULKAN_TYPE(Instance)
VULKAN_TYPE(PhysicalDevice)
VULKAN_TYPE(Device)
...
```

Side note: This is also used to implement a type trait, which could also be a nice addition. Perhaps implemented independent of each other.

```c++
template<typename T>
struct is_vulkan_type {
    static constexpr bool value = getDebugReportObjectTypeEXT<T>() != vk::DebugReportObjectTypeEXT::eUnknown;
};

template<typename T>
constexpr bool is_vulkan_type_v = is_vulkan_type<T>::value;
```

**Comment by asuessenbach** [comment]
@W4RH4WK Regarding the `is_vulkan_type` type trait: I assume you would be interested in knowing if a type is a vulkan **handle** type, not any of the other vulkan types, like an enum class or a struct?

**Comment by W4RH4WK** [comment]
Yes, `is_vulkan_handle_v` would be a far better name.
