### ISSUE TITLE
std::tie for vk::ResultValue?

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-Hpp#714]
It seems that structured binding works well:
auto [result, pipeline] = device.createGraphicsPipelineUnique(...);

But is it possible to use std::tie? Something like:
vk::Result result;
vk::Pipeline pipeline;
std::tie(result, pipeline) = device.createGraphicsPipelineUnique(...);

Cannot get it work for some reason, unfortunately.

**Comment by asuessenbach** [comment]
I assume, you mean this:

```
    vk::Result         result;
    vk::UniquePipeline pipeline;
    std::tie( result, pipeline ) = device->createGraphicsPipelineUnique( nullptr, graphicsPipelineCreateInfo );
```
as this nicely compiles:
```
    vk::Result   result;
    vk::Pipeline pipeline;
    std::tie( result, pipeline ) = device->createGraphicsPipeline( nullptr, graphicsPipelineCreateInfo );
```

**Comment by pc-john** [comment]
Sorry for the typo. Exactly as you say, Unique objects seems to not work with std::tie. It would be very cool to have it work if I may have wishes...

**Comment by asuessenbach** [comment]
@pc-john I actually can't figure out how to make that conversion implicit.
Would you consider an explicit function call to be an acceptable solution to this issue?
```
    vk::Result         result;
    vk::UniquePipeline pipeline;
    std::tie( result, pipeline ) = device->createGraphicsPipelineUnique( nullptr, graphicsPipelineCreateInfo );.asTuple();
```

**Comment by pc-john** [comment]
I asked my colleague, c++ expert. I shall be back when I hear from him.

**Comment by pc-john** [comment]
I support the idea of .asTuple() .
Today, I sat with my colleague who is c++ expert but we did not find any solution. So, your proposed .asTuple() seems the best workaround.
