### ISSUE TITLE
Writing mocks for VulkanHPP Classes

### ISSUE THREAD

**Issue by axsaucedo** [KhronosGroup/Vulkan-Hpp#734]
Hello, I am currently looking for best practices to create mocks for the Vulkan HPP library to be able to test individual components of a Vulkan Compute framework I'm currently working on (https://github.com/axsaucedo/vulkan-kompute), and wanted to get your thoughts on what woudl be the best practice, or the most common approach to this, particularily around building mocks for the Vulkan classes. Currently some ways I have been able to identify how mocks could be written for vulkan classes are below.

The ideal approach would be if Vulkan HPP could come wtih parent interfaces that implemented the methods as virtual so they could be extended with mocks, however given that all the functions are configured to be templated in order to pass the Dispatch class I understand it would be harder to achieve. 

The current approach I started exploring is creating a separate mock classes that could be linked on the tests so these can be used instead during the tests themselves. This unfortunately would be virtually impossible as it would require re-defining all the classes that are used from the vulkan HPP classes.

Another option is to extend the current classes to expose the vulkan HPP classes as template arguments in the application, so they can be swapped at compile time, but this would be sub-optimal given it would require all classess to be templates (which would require all definitions in header file or limitations of template types with forward definitions), as well as add extra complexity for users having to define the template parameters (even if default parameters are provided as the vulkan hpp classes).

Do you have some insights on how people are currently approaching this with VulkanHPP? Thank you.

**Comment by asuessenbach** [comment]
It seems, there's nobody out there answering this.
Closing.
