### ISSUE TITLE
Renaming vk::Optional

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-Hpp#760]
vk::Optional shares the name with std::optional, but has different semantics, which can be confusing for people. Perhaps it could be renamed to vk::MaybeNull or similar (in a similar vein to gsl::not_null)?

**Comment by martty** [comment]
![image](https://user-images.githubusercontent.com/395730/94921546-d214bc80-04b8-11eb-83cd-7c8bb9ad1947.png)

see for example this very unhelpful fixit hint.

**Comment by asuessenbach** [comment]
We think, vk::Optional is a good name for what it's representing.
Agreed, that fixit hint is of no great help. But just including <optional> should clear that issue.
