### ISSUE TITLE
Vulkan-Hpp should have tags to match with other Vulkan repositories

### ISSUE THREAD

**Issue by timo-suoranta-varjo** [KhronosGroup/Vulkan-Hpp#769]
I am trying to build Vulkan-Hpp (and other parts of the Vulkan SDK) a bit like VKB does, as part of my CMake project since I need to debug validation layers.

I am running into:

```
[build] Scanning dependencies of target build_vulkan_hpp
[build] make[2]: *** No rule to make target '../subprojects/Vulkan-Docs/registry/vk.xml', needed by '../subprojects/Vulkan-Headers/include/vulkan/vulkan.hpp'.  Stop.
[build] make[1]: *** [CMakeFiles/Makefile2:2851: subprojects/Vulkan-Hpp/CMakeFiles/build_vulkan_hpp.dir/all] Error 2
```

This happens, because of this line in Vulkan-Hpp `CMakeLists.txt`

`file(TO_NATIVE_PATH ${VulkanRegistry_DIR}/registry/vk.xml vk_spec)`

Ideally Vulkan-Hpp would have tags that match tags used in other Vulkan repositories, so for example `v1.2.154`.

Which commit should I use for Vulkan-Hpp to match Vulkan SDK 1.154.0 ?

**Comment by asuessenbach** [comment]
For a match of Vulkan SDK 1.154.0, you should your #745.
From version 155 on, there will be tags to ease selection of the right version.

**Comment by timo-suoranta-varjo** [comment]
I hope that in addition to `VK_HEADER_VERSION_157` tag there would be `v1.2.157` tag, and also would be great if there was matching tag for SDK releases (such as `sdk-1.2.154.0`).
