### ISSUE TITLE
Runtime Issue In the Hpp header on Linux

### ISSUE THREAD

**Issue by Makogan** [KhronosGroup/Vulkan-Hpp#777]
Operating system: Arch linux, majaro distribution
Drivers: proprietary Nvidia, version 450.66
GPU: GTX 1070

Problem:
Code crashes on nvidia but not on amd with a cryptic error. Hacking the header to print out the problem makes it seem a requested layer is missing, however all requested layers are present on the system.

More details: 
https://stackoverflow.com/questions/64408440/creating-instance-in-vulkan-seems-to-be-missing-layer-but-layer-is-installed

I am not sure if the problem is on my end, with the hpp header or with the drivers. The error message itself could at least be improved to be less cryptic. I appreciate any help I can get.

**Comment by asuessenbach** [comment]
@Makogan Could you please verify the link you're providing? I get a page-not-found error.

**Comment by Makogan** [comment]
My bad, I must have picked the wrong question:
https://stackoverflow.com/questions/64407268/vulkan-instance-creation-fails?noredirect=1#comment113927528_64407268
