### ISSUE TITLE
vk.xml path inconsistency in CMakeLists.txt

### ISSUE THREAD

**Issue by timo-suoranta-varjo** [KhronosGroup/Vulkan-Hpp#793]
In `Vulkan-Hpp/CMakeLists.txt`, path to `vk.xml` in  has some inconsistency.
`VulkanRegistry_DIR` cannot point to Vulkan-Docs, because inside it `vk.xml` is inside `xml` directory.
Meanwhile, Vulkan-Hpp `CMakeLists.txt` expects `vk.xml` to be found from directory called `registry`.

One possible solution is to move `Vulkan-Headers/registry/vk.xml` to `Vulkan-Headers/registry/xml/vk.xml`.

IMHO it is not ideal that Vulkan-Headers keeps copy of registry from Vulkan-Docs. It would be better to simply use files from Vulkan-Docs directly.

**Comment by asuessenbach** [comment]
`VulkanRegistry_DIR` is supposed to point to `Vulkan-Headers/registry`, not to `Vulkan-Docs`
That said, we're currently using it wrong, expecting it would point to `Vulkan-Headers`, I will adjust it accordingly!

**Comment by timo-suoranta-varjo** [comment]
Presumably then `VulkanRegistry_DIR` can also point to `Vulkan-Docs/xml`?
Why `Vulkan-Headers` is used in the middle at all, why not use `Vulkan-Docs` directly?
