### ISSUE TITLE
Storing generated files in version control should be avoided

### ISSUE THREAD

**Issue by timo-suoranta-varjo** [KhronosGroup/Vulkan-Hpp#795]
Generated `vulkan.hpp` is stored in version control, and in two separate locations:

- `Vulkan-Hpp/vulkan/vulkan.hpp`
- `Vulkan-Headers/include/vulkan/vulkan.hpp`

It would be better not to store generated files at all in version control.

**Comment by asuessenbach** [comment]
There are two reasons why we're storing the generated vulkan.hpp:
1. The interested user can just get the header and use it, without the need to generate it.
2. It's easier to see differences resulting from a changed generator.
