### ISSUE TITLE
Travis-CI clang compiler errors

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Hpp#81]
Pulled the 1.0.40 version of vulkan.hpp into Vulkan-LoaderAndValidationLayers and continuous integration began failing with scads of the following errors:

```
In file included from /home/travis/build/KhronosGroup/Vulkan-LoaderAndValidationLayers/demos/cube.cpp:37:
/home/travis/build/KhronosGroup/Vulkan-LoaderAndValidationLayers/include/vulkan/vulkan.hpp:1095:19: error: 
      unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
    DeviceMemory( nullptr_t )
                  ^~~~~~~~~
                  std::nullptr_t
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8/bits/c++config.h:190:29: note: 
      'std::nullptr_t' declared here
  typedef decltype(nullptr)     nullptr_t;
```
                                ^

**Comment by karl-lunarg** [comment]
Is there any way the HPP team can set up a Travis-CI project to build and test this project?   It would generate the hpp file and then compile a set of source programs that use the hpp file.

This sort of test would have avoided the last couple of issues and make it a lot easier to continue including this project in the SDK.

Feel free to use the .travis.yml file from Vulkan-LoaderAndValidationLayers as a starting point.  If you rip out the Android part, it becomes pretty simple.  You already pull in Vulkan-Docs, so you have the Vulkan headers for use by the source programs that include the hpp file.

**Comment by mtavenrath** [comment]
@oddhack Can you help up setting up a Travis-CI project?

**Comment by karl-lunarg** [comment]
I'm not sure that @oddhack is the one to do this.

I've gone ahead and submitted #84 which contains a Travis CI file that you can put in this repo.  See the PR for more info and how to turn on Travis CI.

**Comment by mtavenrath** [comment]
libstdc++ is not fully compatible with clang and thus I've removed the clang build in the travis CI build. Closing.
