### ISSUE TITLE
Abstracting setDebugUtilsObjectNameEXT

### ISSUE THREAD

**Issue by kiroma** [KhronosGroup/Vulkan-Hpp#812]
Currently to fill out the `vk::DebugUtilsObjectNameInfoEXT` struct, the user is required to manually manually specify the ObjectType of the annotated object, and then reinterpret_cast the raw VkHandle to a uintptr_t and assign it to the objectHandle field.
It would be great to have an overload for the function that only takes in the object handle and the name to set for it.

**Comment by asuessenbach** [comment]
Agreed, that would be a valuable overload.
But I don't see any means how to determine that behaviour out of the source of truth for the VulkanHppGenerator, the vk.xml. That is, it would be a very special special handling for just that function.
And I really would like to avoid such special handlings.
So, I think, this is probably more a candidate for a local helper function in your own environment.
