### ISSUE TITLE
StructureChain const get overload compiliation failure

### ISSUE THREAD

**Issue by ImJustAskingDude** [KhronosGroup/Vulkan-Hpp#818]
Hey there,

I am using Vulkan 1.2.159, and vulkan.hpp that is bundled with that,

Problem: StructureChain.get throws a compliation error
Expected: StructureChain returns the requested type

Actual:
I am trying to run something like this:
```
const vk::InstanceCreateInfo _instanceCreateInfo;
const vk::StructureChain<CreateInfoType...> _structureChain;
// CreateInfoType... = { vk::InstanceCreateInfo, vk::DebugUtilsMessengerCreateInfoEXT }
// in constructor init list
_instanceCreateInfo(_structureChain.template get<vk::InstanceCreateInfo>())
```
this fails to compile, as the code in vulkan.hpp that gets executed is this:
```
template <typename T = typename std::tuple_element<0, std::tuple<ChainElements...>>::type, size_t Which = 0>
    T const & get() const VULKAN_HPP_NOEXCEPT
    {
      return std::get<ChainElementIndex<0, T, Which, void, ChainElements...>::value>( static_cast<std::tuple<ChainElements...>&>( *this ) );
    }
```
It is trying to static_cast a `const StructureChain` to a non-const `std::tuple`, or at least I think that is the problem.

The solution to be able to compile, is this change:

```
template <typename T = typename std::tuple_element<0, std::tuple<ChainElements...>>::type, size_t Which = 0>
    T const & get() const VULKAN_HPP_NOEXCEPT
    {
      return std::get<ChainElementIndex<0, T, Which, void, ChainElements...>::value>( static_cast<const std::tuple<ChainElements...>&>( *this ) );
    }
```

But I am not sure how that aligns with the whole project, or if it has any deep running consequences

Could anyone tell me, if adding `const` there is the right thing to do ?

Thanks

**Comment by asuessenbach** [comment]
You're right, there's a `const` missing.
Thanks for spotting this issue, it will be fixed immediately.

**Comment by ImJustAskingDude** [comment]
That's great, thank you!
