### ISSUE TITLE
Remove "specified without a corresponding VkDebugReportObjectTypeEXT enum value!" warnings

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#821]
The debug_report extension is deprecated and there is no intention to require new handle types to have a corresponding debug_report interaction, so this warning is not useful. @courtney-g confirmed this in internal Vulkan issue 2413.

**Comment by asuessenbach** [comment]
Thanks for that hint.
I will replace that warning with a similar check on VkObjectType values.
