### ISSUE TITLE
Consider making Flags<> usable as NTTP

### ISSUE THREAD

**Issue by cos-public** [KhronosGroup/Vulkan-Hpp#847]
Currently `Flags::m_mask` private data member prevents `Flags<>` and other structures containing `Flags<>` from being used as non-type template parameter like:

    template <vk::DescriptorSetLayoutBinding ... Bindings>
    struct descriptor_set_layout {
    ...
    };

The easiest way would be just to make `m_mask` public.

**Comment by asuessenbach** [comment]
We don't want to make m_mask public in general.
But for those who need that non-type template parameter functionality and weight it more than the security you got with the private m_mask, we're introducing a configuration flag VULKAN_HPP_FLAGS_MASK_TYPE_AS_PUBLIC to switch the access specifier for m_mask from private to public, allowing the use of Flags as non-type template parameters.
