### ISSUE TITLE
V40 doesn't match v40 vulkan.h: uses missing VkColorSpace enums.

### ISSUE THREAD

**Issue by msc-** [KhronosGroup/Vulkan-Hpp#85]
The latest vulkan.hpp, which is checking that vulkan.h is version 40, uses several VK_COLOR_SPACE*EXT enum values which are not in either v40 or v41 of vulkan.h available from https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/vulkan/vulkan.h. e.g. `VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT`.

**Comment by asuessenbach** [comment]
It seems, those VK_COLOR_SPACE*EXT values have been added to v39 (https://github.com/KhronosGroup/Vulkan-Docs/commit/ca4abe0d34ca8ed8410c65c177f8658da183576d) and are removed again in v41 (https://github.com/KhronosGroup/Vulkan-Docs/commit/e29a51b23181e5ab1e0b18f43d8462b586dddfc8).That is, they're available at v40.
I'll add a pull-request on a v41-build later today.
