### ISSUE TITLE
FTBFS v1.2.162

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#854]
When I tried to build tag `v1.2.162` I get an error (gcc, Linux => `-Werror`, `VULKAN_HPP_RUN_GENERATOR=TRUE`):
```
~/Projects/Vulkan-Hpp/VulkanHppGenerator.cpp: In member function ‘std::string VulkanHppGenerator::constructCommandResultGetTwoVectors(const string&, const VulkanHppGenerator::CommandData&, bool, const std::map<long unsigned int, long unsigned int>&) const’:
~/Projects/Vulkan-Hpp/VulkanHppGenerator.cpp:4094:8: error: variable ‘firstVectorParamIt’ set but not used [-Werror=unused-but-set-variable]
 4094 |   auto firstVectorParamIt = vectorParamIndices.begin();
      |        ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
It is better to prepend `auto firstVectorParamIt` by `[[maybe_unused]]` or to move it into the `#if !defined( NDEBUG )` block, where it is solely used. Which approach is preferable? I can prepare a pull request btw.

**Comment by asuessenbach** [comment]
I would prefer to have it moved into the debug-only block.
Thanks for spotting this issue!
Please, feel free to provide a pull request.
