### ISSUE TITLE
Registry format issue

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#856]
[There](https://github.com/KhronosGroup/Vulkan-Hpp/blob/dcc775eb5394da494f4d06f8efa99422f0c1beab/VulkanHppGenerator.cpp#L9339) is nothing to split. Format of the `attribute.second` is strictly `VK_STRUCTURE_TYPE_[A-Z_]+` atm.

**Comment by asuessenbach** [comment]
Currently, that's right.
