### ISSUE TITLE
Passing shader code to ShaderModuleCreateInfo using ArrayProxy errors in runtime

### ISSUE THREAD

**Issue by KestutisMa** [KhronosGroup/Vulkan-Hpp#857]
Why could this happen? 
Looks like passing _vertShaderCode_, using .size() and .data() works, while using ArrayProxy doesn't:
_vertShaderCode_ is std::vector<uint32_t>
Works:
```
device->createShaderModuleUnique(vk::ShaderModuleCreateInfo{ {}, vertShaderCode.size(), vertShaderCode.data()}); //  <<<==== WORKS
```

Doesnt work:
```
device->createShaderModuleUnique(vk::ShaderModuleCreateInfo{ {}, vertShaderCode}); // <<<==== resuts in error:
```

`validation layer: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x556d78754a68, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid instruction word count: 0`

**Comment by asuessenbach** [comment]
@KestutisMa That's strange! I would have expected, that your first approach, using .size() and .data() would have failed, while using the ArrayProxy would have worked.

The reason for this expectation: The codeSize in the ShaderModuleCreateInfo is supposed to be in byte, not in sizeof(uint32_t). The ArrayProxy-based constructor of ShaderModuleCreateInfo takes that into account, while your .size()/.data() approach does not. That size should be too small by a factor of 4.

Could you please verify your observations? Especially, whether that vertShaderCode for the ArrayProxy-approach is not empty?
In case you can confirm your observation, some more code showcasing the issue would be great.

**Comment by KestutisMa** [comment]
Yes, I verified. Program runs and draws correctly only using .size(). data()
_vertShaderCode_ is read with:
```
std::vector<uint32_t> readFile(const std::string &filename) {
  std::ifstream file(filename, std::ios::ate | std::ios::binary);

  if (!file.is_open()) {
    throw std::runtime_error("failed to open file!");
  }
  // start at and to get size, then go to begining and read all
  size_t fileSize = (size_t)file.tellg();
  std::vector<uint32_t> buffer(fileSize);
  file.seekg(0);
  file.read(reinterpret_cast<char *>(buffer.data()), fileSize);
  file.close();

  return buffer;
}
```

**Comment by asuessenbach** [comment]
@KestutisMa I see...
You're getting the size of the file by calling file.tellg() (by the way, aren't you missing to call file.seekg( 0, file.end ); to get to the end?)
That size is in byte, let's call it N.
Then you allocate a vector of N uint32_t (which has size 4 * N bytes!)
Then you read the N bytes into that vector, filling the first N/4 elements.
When you later on pass .size()/.data() of that vector into createShaderModuleUnique, you've got the correct size N. It doesn't matter that there is plenty of empty space after the first N bytes.
But when you pass the vector as an ArrayProxy into createShaderModuleUnique, it calculates a length of 4 * N  bytes for that shader, which does not fit to the data.
The actual error message seems to be a bit misleading, but I think, that's your issue here.

**Comment by KestutisMa** [comment]
Thank you @asuessenbach,  I understand now, .size() should be in Bytes but .data() in uint32_t, so it is not possible use ArrayProxy here.

> by the way, aren't you missing to call file.seekg( 0, file.end ) o get to the end?
no, it returns file size correctly, similar method is used in official vulkan examples

Also, when I pass ArrayProxy as described in 1st post (error), after program exits with layers error, gnome-shell (I am using Linux and Nvidia drivers) starts to be unresponsive, restart of gnome process solved problem. Could it be that some resources are not released after I exit program?

**Comment by asuessenbach** [comment]
@KestutisMa I'm sorry, but I think, you did not get the point.
ArrayProxy (and ArrayProxyNoTemporaries as well, to be exact) works very well, all the samples you can find in the samples directory here use that feature.
An ArrayProxy and an ArrayProxyNoTemporaries passes the complete array (the std::vector<uint32_t> here), not only the first quarter of it to the function and a structure, respectively.
But your readFile function returns a vector containing N uint32_t, holding 4N bytes, where just the first N are filled, and the other 3N bytes are left empty. Instead it should reaturn a vector with N/4 uint32_t, completely filled with the N bytes read.
