### ISSUE TITLE
Make StructureChain::isLinked public

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#858]
Currently it is hard to infer is particular element of the structure chain is linked or not.

    template<typename ...StructureTypes>
    void printStructureChain(const vk::StructureChain<StructureTypes...> & structureChain) const
    {
        (printStructure(structureChain.template get<StructureTypes>(), structureChain.template isLinked<StructureTypes>()), ...);
    }

**Comment by asuessenbach** [comment]
@tomilov The currently available and private function StructureChain::isLinked is a little helper function, supposed to be used internally only. Therefore, it's private and should be kept private.
But I think, you're asking for a function with the following signature, which would fit well to the public functions `unlink()` and `relink()`, right?
```
    template <typename ClassType, size_t Which = 0>
    bool isLinked() VULKAN_HPP_NOEXCEPT
```

**Comment by tomilov** [comment]
Yes. Exactly this signature would be most useful, I think.
