### ISSUE TITLE
vk::UniqueDebugUtilsMessengerEXT doesn't make sense in current form

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#869]
Prerequisites: `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=0`.
```
using UniqueDebugUtilsMessengerEXT = UniqueHandle<DebugUtilsMessengerEXT, VULKAN_HPP_DEFAULT_DISPATCHER_TYPE>;
```
Currently of no use, because symbols `vkCreateDebugUtilsMessengerEXT`/`vkDestroyDebugUtilsMessengerEXT` are not exported from `vulkan` DLL (due to they are coming from extension).

Current workaround is to define messenger as:
```
vk::UniqueHandle<vk::DebugUtilsMessengerEXT, vk::DispatchLoaderDynamic> debugUtilsMessenger;
```
and initialize it as follows:
```
vk::DispatchLoaderDynamic dld{*instance, vkGetInstanceProcAddr};
std::tie(result, debugUtilsMessenger) = instance->createDebugUtilsMessengerEXTUnique(debugUtilsMessengerCreateInfo, nullptr, dld).asTuple();
```

Possibly there are another problematic symbols.

**Comment by tomilov** [comment]
I think it better to redisign `UniqueHandle` to not require parametrization by `Dispatcher`. Currently it just need to accept and save `vkDestroy*` function, I think.

**Comment by dan5sch** [comment]
The chosen type for `UniqueDebugUtilsMessengerEXT` is usable, even when `VULKAN_HPP_DEFAULT_DISPATCHER_TYPE` is `vk::DispatchLoaderStatic`. See [samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp), where `vkCreateDebugUtilsMessengerEXT` and `vkDestroyDebugUtilsMessengerEXT`, which _are_ declared in `vulkan.h` by default, are given definitions in the `.cpp` file that dispatch to the locally loaded functions.

(I was coincidentally wrestling with function loading in Vulkan-Hpp yesterday and saw this issue.)

**Comment by tomilov** [comment]
I see. It hard to know this until someone read examples. Thanks.
