### ISSUE TITLE
BaseStructure

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#879]
Is it possible (and reasonable) to add following base for all the structures?
```cpp
struct BaseStructure
{
    StructureType sType = {};
    BaseStructure* pNext = nullptr;
};
```

**Comment by asuessenbach** [comment]
You might have noticed, that there already are a `BaseInStructure` and a `BaseOutStructure`.
But as all the structures in vulkan.hpp are 1-1 mappings of the underlying C-structs, they're not used as a base for any of the C++-structs.
Why do you ask?

**Comment by tomilov** [comment]
Yes, I saw `Base(In|Out)Structure`s.
All the structures in vulkan.hpp still remains 1-1 mappings of underlying C-structs in sense of layout compatibility if inheritance would be used. Not strict C++ layout compatibility in sense of _common initial sequence_, but in sense, that allows to not worry when you do `reinterpret_cast` from one to another.
I as because it would make vulkan.hpp is better arranged internally in some cases. Say, writing all the traversing functions in `StructureChain` will be `reinterpret_cast`-free (though not matters much).

**Comment by asuessenbach** [comment]
Agreed.
I'll have a look for that.

**Comment by asuessenbach** [comment]
Well, thinking about this issue again, I don't see any substantial gain for such a change.
Having the StructureChain functions slightly simpler to write does not really sound as a big win.
