### ISSUE TITLE
Default initialized structure members?

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-Hpp#892]
I am wondering why we now default-initialize all members in structures like vk::PhysicalDeviceFeatures, PhysicalDeviceVulkan11Features, InstanceCreateInfo, and hundreds of others. Vulkan.hpp boasts to have minimal overhead and this seems as wasting of cpu cycles in many cases.

If Vulkan driver is going to fill the structure like PhysicalDeviceFeatures, I do not need to initialize it at all. The driver will fill the structure with data. Other structures need to initialize only sType and pNext members. This is example of PhysicalDeviceVulkan11Features. Others need to be filled with values that are often different from the default values, like InstanceCreateInfo, etc.

I hope I understand this
```    void *                                    pNext                    = {};```
well when I expect it initializes pNext by nullptr, any ints by 0 and all other types by a kind of a default value. This includes small cpu overhead as it must write to the memory. It is usually less than 1KB, and usually bellow 100B, but anyway, why to waste cpu cycles on such low-level, low-overhead, high-performance api as vulkan.hpp? Would not there be a way around?

**Comment by loicmouton** [comment]
Hello, I'm quite new to vulkan but, as far as I know, default-initializing all members in such structures allow them to have an invariant that makes sense after the call to the constructor.
Without initializing all members, all data members with class type will still get their default constructor called but data members with non-class type (ie: primitive type) won't be initialized. This makes it hard to formulate an invariant and can be error prone as there is no way to tell which members are automatically initialized without looking at their types.
Again, I am quite new to vulkan so I might miss something, but I don't find it surprising to pay such cost to have more C++-idiomatic structures. Finally, I think Herb Sutter did talk about a proposal that might allow such optimization while maintaining an invariant ([link with timestamp](https://youtu.be/6lurOCdaj0Y?t=3115)), which makes me think we have no way to avoid this (without adding a macro for that very purpose of course).

**Comment by pc-john** [comment]
You are right that we will get invariant by initialization of all members. Actually, invariance is just opposite of what I would expect in the direction of performance. An example: I have 2MB array of vertex positions. I definitely do not want them to be default initialized in most of my cases. For instance, I am going to fill the array immediately by the data from the disk. Thus, default initialization and all the invariance is just waste of cpu time and pollution of caches by 2MB of data. I am speaking of 2MB but it can be 2GB. True that Vulkan structures are just tens or hundreds of bytes, so not a big deal. Anyway, why to waste performance on low-level API?

Concerning looking on data member types to know which shall be default-initialized for the purpose of invariance: AFAIK all standard Vulkan structures contain only trivial types, such as ints, bools, floats, array of chars. None of these has special constructor doing any initialization. It is just c api. If vulkan.hpp structures does it differently (not sure), it is again topic of this issue. Correct me anybody if I am wrong.

**Comment by asuessenbach** [comment]
As @pc-john  already mentioned, those structures are in the tens or hundreds of bytes, so probably not a real perf issue. But compared to the plain C-structures substantially more secure. And, in case you're already on C++20 and want to use designated initializers, the members of a struct need to be default initialized.
If someone comes up with a performance problem due to those default initializations, we might introduce something like VULKAN_HPP_NO_DEFAULT_INITIALIZATION or so for those who really care.

**Comment by pc-john** [comment]
These designated initializers are strong argument. Some union approach might workaround this, but no energy to think about it today :-) .

**Comment by pc-john** [comment]
Still rethinking this: Why we carry this "= {}" anyway? If we omit them in member initialization, we will allow the user to choose what he wants. If he uses designate initialization, these "= {}" will be generated by the compiler internally. What I read in the doc and saw in C++20 tutorials, these "= {}" are not necessary and compiler behaves like they would be there. And if the user chooses not to use designated initialization, he will get the structure constructed without overhead. So, it will be up to the user to choose what he wants.

Concerning security, I do not see any benefit here, apart that the driver itself would try to steal process data. Anyway, the driver has much more convenient ways to steal data because the user-space driver has access to the whole address space of the process, AFAIK. So, zeroing of the structure will not bring much. But I am not security expert.

**Comment by asuessenbach** [comment]
> So, zeroing of the structure will not bring much.
Sure, it does. It's the improved safety you get with initializing structure members. I just can't miss any and potentially have garbage there that accidentally looks like a valid value.

**Comment by pc-john** [comment]
Oh, you meant security with regard to using of non-initialized values. It is mistake of the programmer to not initialize what he has to initialize. Zeroing of memory simplifies the things for him largely, but does not solve the problem. It is still his responsibility to properly initialize his data structures as zero is not always valid value. At least the program will consistently fail or work as there is no non-determinism if we zero initialize. So, from this perspective, I agree that it brings more safety or security to programming.

I guess all was said. I am taking your decision of 3 days old post as the concluding one. Thanks for shedding more light on the reasoning behind this particular design decision.

**Comment by Calinou** [comment]
> If he uses designate initialization, these "= {}" will be generated by the compiler internally. What I read in the doc and saw in C++20 tutorials, these "= {}" are not necessary and compiler behaves like they would be there.

If that's the case, how does Vulkan-hpp differ from the Vulkan C API when it comes to using designated initializers from a C++20 compiler (other than `sType` being set automatically)? I was always confused by this and can't find much information on it, so apologies for asking here.

**Comment by loicmouton** [comment]
If I remember correctly, Vulkan-hpp provides a default value for its data member using default member initializers. So each data member, if not specified in the designated initializers will have its default value.
You can find some info about this here : [Aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers). In particular, you should look at the example in the section "Designated initializers".
