### ISSUE TITLE
Default constructor for raii-compliant handle wrapper classes 

### ISSUE THREAD

**Issue by loicmouton** [KhronosGroup/Vulkan-Hpp#893]
Hello!
While trying out the new _vulkan_raii.hpp_, I came across an issue: the _vk::raii::Instance_ has a deleted default constructor which makes some use cases impossible.
Namely, I cannot construct an empty _vk::raii::Instance_ then set the instance like I would with a _vk::UniqueHandle<vk::Instance, dispatch_t>_.
Several other raii types seem to be missing a default constructor, though I just took a quick look. As far as I know, there is no reason to prohibit such behavior and it greatly reduce the usefulness of the raii types.

**Comment by asuessenbach** [comment]
@loicmouton What use cases would you need that can't be supported with the deleted default constructors?
Why would you like to construct an empty `vk::raii::Instance`, and set the `vk::Instance` on it later on? Do you get the instance from some third party?

**Comment by loicmouton** [comment]
I would like to be able to create a class that contains handles which own instances of vulkan types such as vk::Instance and which do (almost) nothing on construction. Then, after construction, handles could be tested to see if they hold a value and handles could receive a new value. On destruction, every handle that has a value destroys it. I have been using UniqueHandle to do this and I hoped I could replace it with the types defined in _vulkan_raii.hpp_.
I noticed that, because they can be moved, the "raii-compliant handle wrapper classes" introduced in _vulkan_raii.hpp_ already have some kind of "default value": I'm talking about when their instances are in a "moved from" state. Because of this, the destructor must already handle this case.

**Comment by asuessenbach** [comment]
@loicmouton Instead of directly holding a vk::raii::Instance, your class should hold a smart pointer to that thing, like a std::unique_ptr<vk::raii::Instance>.

If some default-initialization without really creating the wrapped handle would be allowed (and some means to initalize it later on), every access to a member or function would need to be checked for a valid handle. Just because it is allowed to not have one.

**Comment by loicmouton** [comment]
Wouldn't that add an indirection that could be avoided?

It could be undefined behavior to do this (or that could be caught and launch an exception or raise an assert), like it is for raw pointers, std::optional, std::unique_ptr etc. The current implementation already does something like this regarding moved-from handle wrappers as they don't own an handle, and thus shouldn't be used like ones that do.

**Comment by pc-john** [comment]
Commenting a little late, anyway: Using constructions like std::unique_ptr<vk::raii::Instance> means extra memory allocation. It is known that huge amount of memory allocations is a difficulty and performance problem in some applications (f.ex. CAD applications). Thus, embedding the object inside parent object is the preferred way over using indirection of pointer, unique_ptr or, even worse, shared_ptr. Unless I really need this extra memory object for some objective reason, I prefer to built it into parent object and avoid all the drawbacks of other option.

**Comment by Endilll** [comment]
I'd like to reopen this, given that all RAII wrappers got constructors from `std::nullptr_t` years ago (in https://github.com/KhronosGroup/Vulkan-Hpp/commit/c3f32b8538433d5b1e680e9804fba5d6aba2bb6d and https://github.com/KhronosGroup/Vulkan-Hpp/commit/782c4aa46c61b415c048a2a8396b2fd1f5dce9aa), which I don't think are semantically different from default constructors.

> Having a RAII-compliant class that can start in a valid but undefined state is a contradiction.

It's worth pointing out that providing default constructors that behave the same as constructors from `std::nullptr_t` would bring RAII wrappers in line with `std::unique_ptr` and `std::shared_ptr`.

My personal pain point looks like the following:
```cpp
std::vector<std::array<vk::raii::DeviceMemory, 3>> v;
// what I want to write:
auto& planes1{v.emplace_back()};
// what I have to write today:
auto& planes2{v.emplace_back(std::array<vk::raii::DeviceMemory, 3>{nullptr, nullptr, nullptr})};
```

Maybe less of a use case, but something I can see users bump into, is refactoring (any?) Vulkan tutorial using RAII wrappers. For example, replacing data member `VkPhysicalDevice physicalDevice` with `vk::raii::PhysicalDevice physicalDevice` is not going to work — it has to be `vk::raii::PhysicalDevice physicalDevice{nullptr}`, which adds friction for no benefit.

**Comment by Zamundaaa** [comment]
> Having a RAII-compliant class that can start in a valid but undefined state is a contradiction.

All RAII classes I've seen that provide methods like `clear` or `reset` also have a default constructor that creates the object in the state it would reach with that method call.

Unless you also can't get the object in that same state through other commonly used means (like calling `clear()`, or moving the object), I don't think this really has any downsides?
