### ISSUE TITLE
Linker errors when using C++20 modules

### ISSUE THREAD

**Issue by ImTouchk** [KhronosGroup/Vulkan-Hpp#900]
```
module;
#include <vulkan/vulkan.hpp>
export module MyRenderer;

export class Renderer {
    public:
        Renderer() = default;
        ~Renderer() = default;

    private:
        vk::Instance m_instance;
    };
}
```
This throws hundreds of `unresolved external symbol` errors, and if I replace `vk::Instance` with `VkInstance` it works just fine.

Using a header file instead of a module header unit works fine.

Running on the latest version of MSVC on Windows.

**Comment by ImTouchk** [comment]
[VulkanHppIssue.zip](https://github.com/KhronosGroup/Vulkan-Hpp/files/6120978/VulkanHppIssue.zip)

**Comment by mtavenrath** [comment]
@ImTouchk 

It looks like C++ modules import all symbols used by (inline) member functions of a class once it gets instantiate which is different from the non-module behaviour where only functions actually being referenced are linked. vk::Instance uses some functions which are not statically exported by the Vulkan loader and thus we get a linker error for those symbols.

```
#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#include <vulkan/vulkan.hpp>
VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE
```

To solve the issue you have to use the dynamic dispatcher provided by Vulkan-Hpp which loads all functions dynamically. Take a look at the Readme how to use it.

Given that Macros are not visible outside of a module it might make be good to have a separate Vulkan-Hpp module like this (untested)

```
module;

#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#include <vulkan/vulkan.hpp>
VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE

export namespace vkm {
  using namespace ::vk;
}

export module Vulkan-Hpp;
```

This way Vulkan-Hpp would be compiled only once and could be used by multiple modules with the storage for the dispatcher being defined only once.

I haven't figured out if it's possible to export an existing namespace. Thus I renamed the namespace to vkm for this idea. I'm not sure if it makes sense to make vulkan-hpp export its namespace given that it could be configured in multiple ways.
