### ISSUE TITLE
issue with compiling vulkan example

### ISSUE THREAD

**Issue by Val999** [KhronosGroup/Vulkan-Hpp#901]
I am trying to compile some samples of vulkan code from vk_raytracing_tutorial_KHR with gcc
(https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR) but I constantly receive errors originating from the the use of appbase_vkpp.hpp included into the sample kit. Error #1 is  .../appbase_vkpp.hpp:266:35: error: ‘class vk::DispatchLoaderStatic’ has no member named ‘init’
  266 |     VULKAN_HPP_DEFAULT_DISPATCHER.init(vkGetInstanceProcAddr). I looked through the the file vulkan.hpp containing the class DispatchLoaderStatic and in fact this class has not init functions , which is called from the file  appbase_vkpp.hpp. I downloaded the most recent version of vulkan SDK suitable for ray tracing on in Ubuntu environment. So, failed to compile any sample of  vk_raytracing_tutorial_KHR. Does anybody know how to compile those sample codes?

**Comment by mklefrancois** [comment]
Hi @Val999,

The Cmake adds a define to use the Dynamic Loader otherwise it gives the error you are seeing.
```
add_definitions(-DVULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1)
```

Can you please verify that the define is set on your end?

**Comment by Val999** [comment]
Thanks for this advice. Now I have the other issue . I am using Ubuntu and GCC but when I compile those samples using cmake or just make I obtained the bin files in the directory bin_x64 with the extension exe which are not suitable for running neither my Ubuntu 20.10 nor surprisingly on Windows 10.

**Comment by Val999** [comment]
I confused some other RTX vulkan package with vk_raytracing_tutorial-KHR-master. I added the line 
#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1 at the beginning off main.cpp file in ray_tracing__simple sample. After this the error: ‘class vk::DispatchLoaderStatic’ has no member named ‘init’ has GONE!
But nevertheless during compilation  of ray_tracing__simple sample I obtain the following lots of other of errors:

/home/val/Desktop/vk_raytracing_tutorial_KHR-master/shared_sources/nvvk/appbase_vkpp.hpp: In member function ‘virtual void nvvk::AppBase::setup(const vk::Instance&, const vk::Device&, const vk::PhysicalDevice&, uint32_t)’:
/home/val/Desktop/vk_raytracing_tutorial_KHR-master/shared_sources/nvvk/appbase_vkpp.hpp:279:31: error: ‘PROJECT_NAME’ was not declared in this scope

/home/val/Desktop/vk_raytracing_tutorial_KHR-master/shared_sources/nvvk/appbase_vkpp.hpp: In member function ‘bool nvvk::AppBase::isMinimized(bool)’:/home/val/Desktop/vk_raytracing_tutorial_KHR-master/shared_sources/nvvk/appbase_vkpp.hpp:849:7: error: ‘usleep’ was not declared in this scope

main.cpp:118:7: error: ‘PROJECT_ABSDIRECTORY’ was not declared in this scope
main.cpp:119:28: error: expected ‘}’ before string constant
  119 |       PROJECT_ABSDIRECTORY "..",

  119 |       PROJECT_ABSDIRECTORY "..",
main.cpp:127:3: error: ‘contextInfo’ does not name a type
main.cpp:156:3: error: ‘vkctx’ does not name a type
main.cpp:168:73: error: ‘window’ was not declared in this scope
  168 |   const vk::SurfaceKHR surface = helloVk.getVkSurface(vkctx.m_instance, window);
main.cpp:171:3: error: ‘helloVk’ does not name a type
  171 |   helloVk.setup(vkctx.m_instance, vkctx.m_device, vkctx.m_physicalDevice,

main.cpp:310:20: error: expected constructor, destructor, or type conversion before ‘(’ token
  310 |   glfwDestroyWindow(window);


I tried to compiled with cmake --configure . and cmake --build. but I failed to build anythig due to the above mentioned errors.
Then I tried to compile with g++ -Wall -o "%e" "%f" -std=c++17 -O2 -lglfw -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi -I/home/val/Desktop/vk_raytracing_tutorial_KHR-master(1)/shared_sources/imgui/ -I/home/val/Desktop/vk_raytracing_tutorial_KHR-master/shared_sources/nvh/ -I/home/val/Desktop/vk_raytracing_tutorial_KHR-master/shared_sources/nvvk/   neither it did not help. Are you sure that the sample ray_tracing__simple sample can be compiled and run on Ubuntu ?

**Comment by Val999** [comment]
when I try to compile this simple sample with cmake -confugure . the error is following
CMake Error at CMakeLists.txt:20 (_add_project_definitions):
  Unknown CMake command "_add_project_definitions".
-- Configuring incomplete, errors occurred!
See also "/home/val/Desktop/vk_raytracing_tutorial_KHR-master/vk_raytracing_tutorial_KHR-master/ray_tracing__simple/CMakeFiles/CMakeOutput.log".

Than i tried  cmake --build . to get the error
gmake: *** No targets specified and no makefile found.  Stop.

**Comment by Val999** [comment]
in addition cmake included into vk_raytracing_tutorial_KHR-master requires some external function to compile shaders as one can see 
-- Processing Project vk_ray_tracing__before_KHR:
CMake Error at CMakeLists.txt:53 (_compile_GLSL):
  Unknown CMake command "_compile_GLSL".
-- Configuring incomplete, errors occurred!

**Comment by Val999** [comment]
finally after reinstalling everything on ubuntu 20.10  the recommended set of commands:
cd vk_raytracing_tutorial_KHR
mkdir build
cd build
cmake ..

gave the following bad result
[100%] Building CXX object ray_tracing__before/CMakeFiles/vk_ray_tracing__before_KHR.dir/home/val/shared_sources/imgui/imgui_impl_gl.cpp.o
[100%] Building CXX object ray_tracing__before/CMakeFiles/vk_ray_tracing__before_KHR.dir/home/val/shared_sources/imgui/imgui_impl_vk.cpp.o
[100%] Linking CXX executable /home/val/bin_x64/vk_ray_tracing__before_KHR.exe
/usr/bin/ld: CMakeFiles/vk_ray_tracing__before_KHR.dir/hello_vulkan.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [ray_tracing__before/CMakeFiles/vk_ray_tracing__before_KHR.dir/build.make:282: /home/val/bin_x64/vk_ray_tracing__before_KHR.exe] Error 1
make[2]: Leaving directory '/home/val/VVV/vk_raytracing_tutorial_KHR/build'
make[1]: *** [CMakeFiles/Makefile2:442: ray_tracing__before/CMakeFiles/vk_ray_tracing__before_KHR.dir/all] Error 2
make[1]: Leaving directory '/home/val/VVV/vk_raytracing_tutorial_KHR/build'
make: *** [Makefile:130: all] Error 2
val@val-HP-ZBook-17-G6:~/VVV/vk_raytracing_tutorial_KHR/build/ray_tracing__before$ ls
CMakeFiles  cmake_install.cmake  Makefile

**Comment by Val999** [comment]
I found a very similar compilation error on : https://stackoverflow.com/questions/56841870/how-to-fix-undefined-reference-to-symbol-dlcloseglibc-2-2-5-from-glad-c

usr/bin/ld: CMakeFiles/gltuto.dir/src/glad.c.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
It was recommended to add  libdl with CMAKE_DL_LIBS in target_link_libraries(gltuto PUBLIC glfw OpenGL::GL ${CMAKE_DL_LIBS}) of CMakeLists.txt.
I introduced the following change into this file like 
#--------------------------------------------------------------------------------------------------
# Linkage
#
target_link_libraries(${PROJNAME} ${PLATFORM_LIBRARIES} ${CMAKE_DL_LIBS} shared_sources)

But the outcome was the same, so what was wrong and how solve the tackle the  issue of make[2]: *** [ray_tracing__before/CMakeFiles/vk_ray_tracing__before_KHR.dir/build.make:282: /home/val/bin_x64/vk_ray_tracing__before_KHR.exe] Error 1? I have no clue why this error is connected with the windows file vk_ray_tracing__before_KHR.exe if I develop my software on ubuntu 20.10 platform?

**Comment by Val999** [comment]
Finally I have solved the problems with compilation of  vk_raytracing_tutorial_KHR-master samples on Ubuntu using cmake followed by make. In all CMakeFiles.txt I modified only one line: target_link_libraries(${PROJNAME} ${PLATFORM_LIBRARIES} ${CMAKE_DL_LIBS} shared_sources)  by adding  ${CMAKE_DL_LIBS}. All problems have gone and I can compile files of the raytracing tutorial. I only wonder why the all resulting executable files have EXE extension. Nevertheless they are perfectly executable on Ubuntu without any compatibility layer like Wine but can not be executed on Windows 10.

**Comment by mklefrancois** [comment]
Hi @Val999, your comments should go into the [vk_raytracing_tutorial_KHR](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR) project rather than here. This will allow someone in the team to inspect why your version of Ubuntu isn't recognize as a legitimate Linux platform and creates executables with the .exe extension. 

Normally, following the steps describe here is sufficient: https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/master/docs/setup.md

Please comment exactly the issue, the operating system details and what has been done to fix it. Since most of the samples under github/nvpro-samples are using the same framework, there is a big chance that all other samples will behave the same.
