### ISSUE TITLE
UniqueDebugReportCallbackEXT causes linker error

### ISSUE THREAD

**Issue by xMAC94x** [KhronosGroup/Vulkan-Hpp#91]
When using `UniqueDebugReportCallbackEXT` instead of `DebugReportCallbackEXT` i get two linker errors. one for Create and Destroy (i translated the error from german to english, so this might not be the exact Error String (marked _italic_):

../engine/libEngine.a(instance.cpp.o): _In function_ \`vk::Instance::createDebugReportCallbackEXT(vk::DebugReportCallbackCreateInfoEXT const&, vk::Optional<vk::AllocationCallbacks const>) const\':
~/VulkanSDK/1.0.42.0/x86_64/include/vulkan/vulkan.hpp:26901: _undefined reference to_\`vkCreateDebugReportCallbackEXT\'

../engine/libEngine.a(instance.cpp.o): _In function_ \`vk::Instance::destroyDebugReportCallbackEXT(vk::DebugReportCallbackEXT, vk::Optional<vk::AllocationCallbacks const>) const\':
~/VulkanSDK/1.0.42.0/x86_64/include/vulkan/vulkan.hpp:26920: _undefined reference to \`vkDestroyDebugReportCallbackEXT\'

The second error occurs when creating a variable holding a `uniqueDebugReportCallbackEXT` e.g.
```
class abc {
private:
  vk::UniqueDebugReportCallbackEXT callback_;
}
```

The first error occurs as soon as i try to access the `vk::Instance::createDebugReportCallbackEXTUnique` method

**Comment by mtavenrath** [comment]
Vulkan-Hpp assumes that there're implementations for all functions declared in vulkan.h. There's an extension loader available here which implements the logic for all extensions: https://github.com/KhronosGroup/Vulkan-Docs/tree/1.0/src/ext_loader
