### ISSUE TITLE
Multi-device dynamic dispatcher

### ISSUE THREAD

**Issue by loicmouton** [KhronosGroup/Vulkan-Hpp#918]
Hello! 
Unless I am mistaken, it seems that the default dynamic dispatcher is meant to be used with only one device. Because it also contains the adresses of the global and instance level functions, there is some data duplication when using multiple devices simultaneously as their respective dispatcher share these adresses.
I think creating global-level, instance-level and device-level dispatcher types would solve this and we could still have the default "one-device" dynamic dispatcher using public inheritance. The user could then create its own dispatchers for use in a multi-device application.
I can look into it and make a pull request but I would like to be sure I didn't get anything wrong first.

**Comment by asuessenbach** [comment]
> it seems that the default dynamic dispatcher is meant to be used with only one device.

Well, not exactly, but it's pretty close.
Actually, there are three ways to achieve multi-device support with vulkan.hpp:
**1. Simple:**
Just skip the (optional) third initialization step of the dynamic dispatcher; just initialize it with the vkGetInstanceProcAddr and the vk::Instance, but skip the intialization with the vk::Device. That way, your default dispatcher does not use device specific function pointers but uses the driver's dispatching capabilities to get to the correct device.
**2. Efficient**
Don't use the default dispatcher, but instantiate a specific dispatcher for each device. And then you have to pass the corresponding dispatcher as the last argument to every vk::-function. Efficient, but error prone.
**3. Very simple and efficient**
Well, actually, this is not available with vulkan.hpp, but with vulkan_raii.hpp, which is a newly created header on top of vulkan.hpp that gets generated in lock-step with vulkan.hpp in this repository. And it's not (yet) part of the Vulkan SDK.
That header provides raii-compliant wrapper classes for all the vulkan handle type. And it resolves the multi-device issue "automagically": You just instantiate your `vk::raii::Device`s, and you're done. Those classes hold the corresponding device-specific function pointers.
@loicmouton: If you think, your approach would add a valuable fourth approach, I'd be glad to get some more details about it. What would the user need to do, and how would your dispatcher`s approach resolve the multi-device issue?

**Comment by loicmouton** [comment]
Thanks for the detailed answer ! What I had in mind was something like this; using three new class types which act as dispatchers for only one specific level of functions each (respectively device-level, instance-level and global-level), roughly defined as follows, we could resolve the multi-device issue by giving more control to the user.
```
class DispatcherDeviceLoaderDynamic
{
public:
    void init(Device);
    void init(Instance);
    // only device-level functions
};

class DispatcherInstanceLoaderDynamic
{
public:
    void init(Instance);
    // only instance-level functions
};

class DispatcherGlobalLoaderDynamic;
{
public:
    void init(PFN_vkGetInstanceProcAddr);
    // only global-level functions
};
```
In a multi-device application, the user would start by initializing the global-level dispatcher, then they would create an instance from it and associate a instance-level dispatcher to it. Finally, for each device they create using the instance and its dispatcher they would have to have a corresponding device-level dispatcher.
With this, we would have a one-to-one relationship between the dispatcher and the entity that uses it, which is easy to wrap (we could imagine a class-type that owns both a device-level dispatcher and unique handle to a device).

Finally, it would still be possible to define a default dynamic dispatcher such as the current one. For example, we could have something like this:
```
class DispatchLoaderDynamic : public DispatcherGlobalLoaderDynamic,
                              public DispatcherInstanceLoaderDynamic,
                              public DispatcherDeviceLoaderDynamic
{
    // same as usual
    void init(PFN_vkGetInstanceProcAddr); 
    void init(Instance);
    void init(Device);
   // no function pointers here
};
```

**Comment by asuessenbach** [comment]
If I got that right, your approach would not resolve or simplify the multi-device handling. Just as it is with the current single Dispatcher class, you would need to hold one dispatcher object per device. And somehow provide it the function calls. You would just spare a few houndred bytes per device. (Note: which is a good thing (TM))
Besides that, you're describing nearly exactly what I'm working on for the wrapper classes in vulkan_raii.hpp.

**Comment by loicmouton** [comment]
Yes my main concern was the few bytes that we could save by using this method. It would also be a little closer to the "single responsibility principle" as the dispatchers would only have to worry about one level of functions.
Well in that case, if the dispatchers were added, you could probably have some use for them in the wrapper classes in vulkan_raii.hpp. 
Should I try to implement them then?
