### ISSUE TITLE
Hello World example

### ISSUE THREAD

**Issue by Swoorup** [KhronosGroup/Vulkan-Hpp#92]
It would be great to see, if there was any hello triangle example using Vulkan-Hpp

**Comment by realvictorprm** [comment]
I suggest porting the Triangle example of the vulkan tutorial.
The code [here](https://vulkan-tutorial.com/code/hello_triangle.cpp) should simply be ported to Vulkan-Hpp.
Vertex shader can be found [here ](https://vulkan-tutorial.com/code/shader_base.vert)and fragment shader [here](https://vulkan-tutorial.com/code/shader_base.frag).

If I have time maybe I'll do it.

**Comment by alaingalvan** [comment]
I ported the triangle example from @SaschaWillems's [Vulkan Examples](https://github.com/SaschaWillems/Vulkan) repo to Vulkan-Hpp, here's a repo with the code:
https://github.com/alaingalvan/raw-vulkan

And here's a blog post summarizing it:
https://alain.xyz/blog/raw-vulkan

**Comment by Swoorup** [comment]
Thats pretty awesome @alaingalvan .

Thank you so much for doing this. 
I'll be following your project.

**Comment by realvictorprm** [comment]
Nice @alaingalvan 👍 I think @Swoorup you can close this.

**Comment by SaschaWillems** [comment]
I did a single file example based off my triangle example some time ago too (windows, Linux, android) , you can find it at https://github.com/SaschaWillems/Vulkan_Test/blob/master/01_triangle/01_triangle.cpp

**Comment by realvictorprm** [comment]
Hm @SaschaWillems if you're here ... Are you planning to do more stuff for vulkanhpp? So far I know you like to dig into new stuff (yeah it isn't that new anymore).

**Comment by SaschaWillems** [comment]
> Hm @SaschaWillems if you're here ... Are you planning to do more examples for vulkanhpp?
Yes, I'd like to do some more examples using vulkanhpp in the future if time permits.

**Comment by jherico** [comment]
You might want to take a look at my fork here: https://github.com/jherico/Vulkan

I ported most of the examples to Vulkan-Hpp, although that was quite a while ago and I haven't tracked changes in the main repository yet.

**Comment by Swoorup** [comment]
Pretty awesome, thanks @jherico

**Comment by realvictorprm** [comment]
@Swoorup close it. Everything is provided. Maybe @asuessenbach  thinks about adding a reference to the examples. Would be very _nice_ !

**Comment by jherico** [comment]
There actually used to be one.

**Comment by Swoorup** [comment]
Thank you all, I like the responses so far. Would be great to link the examples to the Readme or something. 
Cheers!

**Comment by Swoorup** [comment]
I think the projects mentioned here, need to be added to readme or somewhere, it's almost impossible to find the projects mentioned
