### ISSUE TITLE
Proper clang-format package for Debian 10

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#922]
When I generate Vulkan-Headers, vulkan.hpp is still not getting formatted because the default version of clang-format with Debian 10 is 1:7.0 and you wanted 1.10 IIRC. If you can tell me where to get a trustworthy .deb of the desired version of clang-format for Debian 10 I'll use it, but otherwise the situation remains as it stands.

**Comment by asuessenbach** [comment]
I'm currently in the process of downgrading the requirements to clang-format 7. But it might take a bit longer, so probably for the next release, the situation has to remain as it stands.
