### ISSUE TITLE
non-explicit nullptr constructor causes ambiguity

### ISSUE THREAD

**Issue by wobakj** [KhronosGroup/Vulkan-Hpp#93]
This happens when using functions which can receive `VK_NULL_HANDLE` as arguments, like the `fence` argument of `vk::Queue::submit`. 
Due to the new constructors in SDK 1.0.42 taking `std::nullptr_t` as argument, g++6 reports an ambiguity error because `VK_NULL_HANDLE` can be the argument of both the c-struct- and the nullptr-constructor. This ambiguity makes it also impossible to initialize a wrapper class with the `VK_NULL_HANDLE` value. 
Making the nullptr-constructor explicit solves this issue but I am not sure if this would violate any rules of the wrapping.

**Comment by mtavenrath** [comment]
nullptr is the current substitute for VK_NULL_HNADLE, so there's no ambiguity when using it instead of VK_NULL_HANDLE. We're considering adding the API constants as requested in issue #138. With this change vk::NullHandle will be a nullptr and the ambiguity will be gone.
