### ISSUE TITLE
Add some sort of 'Invalid' enum entry to the scoped enumerations

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/Vulkan-Hpp#930]
It's often useful to be able to store a value in a scoped enumeration that shows the variable doesn't have a valid value/hasn't been set yet. The C enums for Vulkan have VK*_MAX_ENUM = 0x7FFFFFFF for each of their enums, which can be used for this purpose.
It would be useful if all of the scoped enums similarly has an 'eInvalid' or similar entry for this usage pattern. I guess 'eMaxEnum' may be the most consistent.

**Comment by asuessenbach** [comment]
@mbechard Those MAX_ENUMs are just part of the C-binding, not part of the vulkan spec. And they are just there to get a defined size for the enums. Besides that, they don't have any meaning for the corresponding enum.
If we would use that value (or, in fact, any other value) to have some defined INVALID_VALUE, we would get a problem in case that value collides with a valid value. That could easily happen with bitmasks.
That is, we will not introduce something like an INVALID_VALUE that's not defined by the vulkan spec.
You can easily introduce something like that in your own projects, by assigning some arbitrary value, but that would require some static_cast.

**Comment by Kasys** [comment]
You could also use an std::optional, which fits this usecase perfectly I think.

**Comment by mbechard** [comment]
Ok thanks, ya I'm currently assigning an arbitrary value using a cast, but it's just a little ugly with something strongly typed like a scoped enum. std::optional seems interesting, at the cost of a bit more memory. I'll look into that.
