### ISSUE TITLE
Implicit-cast operators on vk::ResultValue compilation error (as reported in issue #938)

### ISSUE THREAD

**Issue by rosasco-wk** [KhronosGroup/Vulkan-Hpp#942]
Hi Andreas,

The compilation problems as reported in issue #938 aren't all yet resolved.  If it works on your end, I'd prefer it if you would use the issues I file as authoritative in the repo instead of filing a separate issue and closing my filings in response to addressing the newly filed issue.  Also, it would be better if I could verify a fix before issues I've filed are closed.

Here are the compilation errors that remain using the same vk.xml attached to issue #938:

FAILED: obj/src/graphics/tests/benchmark/vkcopy.vkcopy.cc.o 
~/src/fuchsia/prebuilt/third_party/goma/linux-x64/gomacc  ../../prebuilt/third_party/clang/linux-x64/bin/clang++ -MD -MF obj/src/graphics/tests/benchmark/vkcopy.vkcopy.cc.o.d -DTOOLCHAIN_VERSION=pRlhGPqYQoY4vHqzFBmHYO_D41XXqHubR7bNFUaCHmEC -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DZX_ASSERT_LEVEL=2 -DFIDL_TRACE_LEVEL=0 -DFIDL_TRACE_LEVEL=0 -DVULKAN_HPP_ASSERT\(expr\)=do\ \{\}\ while\(0\) -DVULKAN_HPP_NO_EXCEPTIONS -DVK_USE_PLATFORM_FUCHSIA -DVULKAN_HPP_NO_NODISCARD_WARNINGS -DAPI_NAME=\"Vulkan\" -DUSE_UNSAFE_FILE_SEARCH=1 -DVK_USE_PLATFORM_FUCHSIA -DVULKAN_HPP_NO_NODISCARD_WARNINGS -I../.. -Igen -I../../sdk -Igen/sdk -I../../sdk/lib/fit/include -I../../sdk/lib/stdcompat/include -I../../zircon/system/ulib/fbl/include -I../../third_party/googletest/src/googletest/include -I../../third_party/Vulkan-Headers/include -I../../third_party/Vulkan-Loader/loader/generated -I../../third_party/Vulkan-Loader/loader -I../../third_party/Vulkan-Headers/include -I../../sdk/lib/fdio/include -I../../zircon/system/ulib/zx/include -Igen/include -I../../src/zircon/lib/zircon/include -I../../zircon/system/ulib/syslog/include -fcolor-diagnostics -fcrash-diagnostics-dir=clang-crashreports -fexperimental-new-pass-manager --sysroot=gen/zircon/public/sysroot/cpp --target=aarch64-unknown-fuchsia -ffile-compilation-dir=. -no-canonical-prefixes -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O0 -gdwarf-4 -g3 -Wall -Wextra -Wnewline-eof -Wconversion -Wno-unused-parameter -Wno-unknown-warning-option -Wno-sign-conversion -Wno-unknown-warning-option -Wno-c99-designator -Wno-int-in-bool-context -Wno-address-of-packed-member -Wno-range-loop-analysis -Wno-free-nonheap-object -fvisibility=hidden -Werror -Wno-error=deprecated-declarations -Wa,--fatal-warnings -ftrivial-auto-var-init=pattern -Wthread-safety -Wno-conversion -fvisibility-inlines-hidden -fexperimental-relative-c++-abi-vtables -std=c++17 -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-unknown-warning-option -Wno-suggest-override -fno-exceptions -fno-rtti -c ../../src/graphics/tests/benchmark/vkcopy.cc -o obj/src/graphics/tests/benchmark/vkcopy.vkcopy.cc.o
In file included from ../../src/graphics/tests/benchmark/vkcopy.cc:11:
In file included from ../../src/graphics/tests/common/utils.h:13:
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:111755:57: error: no matching constructor for initialization of 'typename ResultValueType<MemoryOpResultFUCHSIA>::type' (aka 'ResultValue<vk::MemoryOpResultFUCHSIA>')
  typename ResultValueType<MemoryOpResultFUCHSIA>::type opResult;
                                                        ^
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:19088:30: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
template <typename T> struct ResultValue {
                             ^
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:19088:30: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 0 were provided
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:19090:3: note: candidate constructor not viable: requires 2 arguments, but 0 were provided
  ResultValue(Result r, T &v) VULKAN_HPP_NOEXCEPT(VULKAN_HPP_NOEXCEPT(T(v)))
  ^
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:19098:3: note: candidate constructor not viable: requires 2 arguments, but 0 were provided
  ResultValue(Result r, T &&v)
  ^
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:111760:10: warning: 'operator vk::ResultValue<vk::MemoryOpResultFUCHSIA> &&' is deprecated: Implicit-cast operators on vk::ResultValue are deprecated. Explicitly access the value as member of ResultValue. [-Wdeprecated-declarations]
  return createResultValue(result, opResult,
         ^
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:19129:3: note: 'operator vk::ResultValue<vk::MemoryOpResultFUCHSIA> &&' has been explicitly marked deprecated here
  VULKAN_HPP_DEPRECATED(
  ^
../../third_party/Vulkan-Headers/include/vulkan/vulkan.hpp:197:38: note: expanded from macro 'VULKAN_HPP_DEPRECATED'
#define VULKAN_HPP_DEPRECATED(msg) [[deprecated(msg)]]
                                     ^
1 warning and 1 error generated.
[29860/46406] CXX obj/src/graphics/tests/common/vkcontext.test_vkcontext.cc.o

**Comment by asuessenbach** [comment]
@rosasco-wk Please sorry, that I missed the second part of the error log.
A fix for that issue is filed (#943).

**Comment by asuessenbach** [comment]
@rosasco-wk Has your issue been fixed?

**Comment by rosasco-wk** [comment]
Yes, fixed.  Thanks.
