### ISSUE TITLE
Extensions paired with the vk::WriteDescriptorSet enhanced constructor 

### ISSUE THREAD

**Issue by LeonBrands** [KhronosGroup/Vulkan-Hpp#945]
The enhanced constructor of vk::WriteDescriptorSet applies a check to make sure that at least imageInfo, bufferInfo, or texelBufferView is set:
```
if ( ( !imageInfo_.empty() + !bufferInfo_.empty() + !texelBufferView_.empty() ) != 1 )
{
  throw LogicError( VULKAN_HPP_NAMESPACE_STRING "::WriteDescriptorSet::WriteDescriptorSet: ( !imageInfo_.empty() + !bufferInfo_.empty() + !texelBufferView_.empty() ) != 1" );
}
```

But if i understand it correctly, it should allow all of them to be default/empty when the WriteDescriptorset is used with an extension in pNext (e.g. vk::WriteDescriptorSetAccelerationStructureKHR), so this check might not be correct. Unfortunately the constructor doesn't come with a pNext parameter built in, so the check can't simply check if pNext is assigned either.

**Comment by asuessenbach** [comment]
Thanks for spotting this issue. I'll relax the check to accept **up to one** non-empty array, instead of **exactly one**.
