### ISSUE TITLE
VulkanHppGenerator asserts when processing 1.0.46 Vulkan vk.xml version

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Hpp#95]
This header version extends the debug report enum type with `VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR_EXT `-- this triggers the assert in the strip() function:

`assert(strippedValue.substr(strippedValue.length() - postfix.length()) == postfix);`

**Comment by asuessenbach** [comment]
Resolved with pull request #96.
