### ISSUE TITLE
Release 176 missing

### ISSUE THREAD

**Issue by medakk** [KhronosGroup/Vulkan-Hpp#959]
I noticed that there was a PR for v1.2.176: #939 but no [corresponding release](https://github.com/KhronosGroup/Vulkan-Hpp/releases). I noticed because I just ran a system upgrade on Ubuntu 18.04 and it pulled in vulkan 1.2.176. Is this intentional, or an oversight?

Thanks for maintaining this project!

**Comment by asuessenbach** [comment]
Oops, sorry, that's just an oversight!
