### ISSUE TITLE
[vk::raii] consider to grant strong exception guarantee

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#962]
When (e.g.) `vk::raii::Buffer` is used as element in `std::vector` it is desired, that special move functions (c-tor and `operator=`) of `vk::raii::Buffer` would be `noexcept`. It is explained in the note in Exceptions part [here](https://en.cppreference.com/w/cpp/container/vector/push_back).

**Comment by asuessenbach** [comment]
Thanks for that hint. I'll adjust them.
