### ISSUE TITLE
Compilation errors between Debug and Release versions

### ISSUE THREAD

**Issue by akshit-sharma** [KhronosGroup/Vulkan-Hpp#964]
Sample code has some inconsistency when build with release versions as opposed to debug versions.
Example: debugUtilsMessenger variable is [not declared](https://github.com/KhronosGroup/Vulkan-Hpp/blob/c92c47c3a4713107110c915ce51a4b795eb518f2/samples/02_EnumerateDevices/02_EnumerateDevices.cpp#L42) in release version (as it is bounded by NDEBUG) but is [destroyed](https://github.com/KhronosGroup/Vulkan-Hpp/blob/c92c47c3a4713107110c915ce51a4b795eb518f2/samples/02_EnumerateDevices/02_EnumerateDevices.cpp#L52).
This will give an compilation error.

There is similar error in [utils.hpp](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/samples/utils/utils.hpp) and [utils.cpp](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/samples/utils/utils.cpp) also.
Definition of gatherLayers in [hpp](https://github.com/KhronosGroup/Vulkan-Hpp/blob/c92c47c3a4713107110c915ce51a4b795eb518f2/samples/utils/utils.hpp#L450) and [cpp](https://github.com/KhronosGroup/Vulkan-Hpp/blob/c92c47c3a4713107110c915ce51a4b795eb518f2/samples/utils/utils.cpp#L295), makes it seem layerProperties parameter is only required for debug version. If that is correct, then [calling the function](https://github.com/KhronosGroup/Vulkan-Hpp/blob/c92c47c3a4713107110c915ce51a4b795eb518f2/samples/utils/utils.cpp#L339) will fail for release version.

Are these behaviors supposed to be understood by users on their own for samples?

**Comment by asuessenbach** [comment]
Thanks for spotting these issues. Will fix them.
