### ISSUE TITLE
Would Vulkan-Hpp be impacted by removing 'pipeline' attributes from vk.xml?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#966]
The Vulkan WG is hoping to remove the 'pipeline' attributes from vk.xml, and the corresponding 'Pipeline Types' column from the specification. Would this impact your use of the XML? Easiest way to tell is probably by substituting the [attached proposed vk.xml](https://github.com/KhronosGroup/VK-GL-CTS/files/6536053/vk.zip) in your build and see if it makes a difference.

**Comment by oddhack** [comment]
Sorry, excessive title cut & paste.

**Comment by asuessenbach** [comment]
@oddhack No, removing the 'pipeline' attribute from vk.xml would not affect vulkan.hpp generation at all.
I could just remove one optional attribute from the attribute list of a command, which otherwise is completely ignored.

**Comment by oddhack** [comment]
Thanks!
