### ISSUE TITLE
Add .natvis file to improve debugging  

### ISSUE THREAD

**Issue by MythreyaK** [KhronosGroup/Vulkan-Hpp#989]
Debugger view for most of the things works fine, but flags and enums show up as numbers. It would be great if a natvis file was added to the SDK to visualize them. This would improve debugging experience a lot.

**Comment by asuessenbach** [comment]
Interesting idea!
Unfortunately, I'm not that fluent with .natvis files. Could you provide some sample how it would look like with flags?
And I think, enums are already displayed nicely in the debugger, aren't they?

**Comment by MythreyaK** [comment]
Enums, yes, flags, no. 

![image](https://user-images.githubusercontent.com/26112391/122255171-7fb2e900-ceeb-11eb-94f8-7c248a5de7dd.png)

![image](https://user-images.githubusercontent.com/26112391/122255360-a83ae300-ceeb-11eb-8e68-42c29ddfbbef.png)

I assume that with a natvis file, the masks would expand to the actual enum values. For example, in the above cases, I expect it to show something along the lines of `Graphics | Compute | Transfer | SparseBinding` and `eOpaque` respectively, if [this](https://devblogs.microsoft.com/cppblog/visual-studio-2008-enum-bit-flags-visualization/) blog article by MS is anything to go by.

**Comment by asuessenbach** [comment]
Well, it turned out to be not that complex. And it's not needed to generate such a .natvis file.
Getting the enum-display for the flags types needs just these few lines here:

```
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
  <Type Name="vk::Flags&lt;*&gt;">
    <DisplayString>[{($T1)m_mask}]</DisplayString>
  </Type>
</AutoVisualizer>
```

**Comment by MythreyaK** [comment]
Oh wow that's pretty simple! I should've gone through the documentation a bit more closely. 
Thanks!

**Comment by MythreyaK** [comment]
I'll close this since the issue is solved. Thanks for the help!
Not sure about including just this with the SDK
